.circleci/config.yml, docker/compose/ci/docker-compose.yml, docker/images/alpine/dev/Dockerfile, docker/images/dev/Dockerfile, env.d/ci
=> 👷(circle) move to a richie's container based CI

richie/js/components/courseGlimpse/courseGlimpse.spec.tsx, richie/js/components/courseGlimpse/courseGlimpse.tsx, richie/js/components/courseGlimpseContainer/courseGlimpseContainer.spec.tsx, richie/js/components/courseGlimpseContainer/courseGlimpseContainer.tsx, richie/js/components/courseGlimpseList/courseGlimpseList.spec.tsx, richie/js/components/courseGlimpseList/courseGlimpseList.tsx
Add a connected component around CourseGlimpse to receive the course and get the relevant organization from the state.
=> Get organization names from the state for course glimpses

richie/js/components/courseGlimpse/courseGlimpse.tsx, richie/js/components/courseGlimpseContainer/courseGlimpseContainer.tsx, richie/js/components/courseGlimpseListContainer/courseGlimpseListContainer.tsx, richie/js/components/searchFilterGroup/searchFilterGroup.spec.tsx, richie/js/components/searchFilterGroupContainer/searchFilterGroupContainer.spec.tsx, richie/js/components/searchFilterGroupContainer/searchFilterGroupContainer.tsx, richie/js/data/configureStore.ts, richie/js/data/course/reducer.spec.ts, richie/js/data/course/reducer.ts, richie/js/data/genericReducers/resourceById/resourceById.spec.ts, richie/js/data/genericSideEffects/getResourceList/getResourceList.ts, richie/js/data/organization/reducer.ts, richie/js/data/rootReducer.ts, richie/js/data/subject/reducer.ts, richie/js/index.tsx, richie/js/utils/types.ts, tsconfig.json
As we talked about @sampaccoud I updated `tsconfig.json` in order to enable strict mode. This of course required some changes to the code to still compile (and did catch some potential errors).
I could not find a good online resource about this so I wrote a blog post if anyone's interested: http://mbenadda.com/typescripts-strict-compiler-option/
Related to issue #90
=> Use typescript strict mode

package.json
The project's metadata in the `package.json` needed an update.
Updated:
* license
* author
* description
=> Update package.json description, license and author

package.json, yarn.lock
Routine greenkeeper dependency update.
=> ⬆️(package) update webpack-cli to version 3.0.6

package.json, yarn.lock
* update @types/react to version 16.3.18
* update karma to version 2.0.3
* update webpack-cli to version 3.0.8
Closes #222, #224, #225
=> ⬆️(package) upgrade front-end dependencies

.circleci/config.yml, README.md, package.json, yarn.lock
Greenkeeper was not satisfying to us as we did not find a way to schedule and squash commits on eg. a single PR per week.
We're therefore removing it and replacing it with a more promising alternative in Renovate.
- Remove greenkeeper (this PR)
- Enable Renovate (see #247)
=> 🔥(greenkeeper) remove greenkeeper from the project

richie/settings.py
CMS_PLACEHOLDER_CONF had ImagePlugin to indicate that we wanted user to upload an image. The name of the plugin for that is PicturePlugin. So i replaced all instance of ImagePlugin by PicturePlugin in the setting file.
I replaced all instance of ImagePlugin by PicturePlugin in the setting file.
=> Replaced ImagePlugin by PicturePlugin in setting file.

sandbox/static/css/main.css, src/richie/apps/persons/models.py, strings/src/richie-front/js/components/CourseGlimpse/CourseGlimpse.json, strings/src/richie-front/js/components/SearchSuggestField/SearchSuggestField.json, strings/src/richie-front/js/settings.json, strings/src/richie-front/js/utils/commonMessages.json, tests/apps/persons/test_person_plugin.py
Fix this issue: https://github.com/openfun/richie/issues/278
=> Fix person plugin by selecting only person pages

package.json, src/richie-front/js/bootstrap.ts, src/richie-front/js/components/CourseGlimpseContainer/CourseGlimpseContainer.spec.tsx, src/richie-front/js/components/CourseGlimpseListContainer/CourseGlimpseListContainer.spec.tsx, src/richie-front/js/components/CourseGlimpseListContainer/CourseGlimpseListContainer.tsx, src/richie-front/js/components/SearchFilterGroup/SearchFilterGroup.spec.tsx, src/richie-front/js/components/SearchFilterGroup/SearchFilterGroup.tsx, src/richie-front/js/components/SearchFilterGroupContainer/SearchFilterGroupContainer.spec.tsx, src/richie-front/js/components/SearchSuggestField/SearchSuggestField.spec.tsx, src/richie-front/js/components/SearchSuggestFieldContainer/SearchSuggestFieldContainer.tsx, src/richie-front/js/data/genericReducers/resourceById/resourceById.ts, src/richie-front/js/data/genericReducers/resourceList/resourceList.ts, src/richie-front/js/data/genericSideEffects/getResourceList/getResourceList.spec.ts, src/richie-front/js/data/genericSideEffects/getResourceList/getResourceList.ts, src/richie-front/js/integration_tests/filters.spec.tsx, src/richie-front/js/types/Course.ts, src/richie-front/js/types/api.ts, src/richie-front/js/utils/filters/computeNewFilterValue.spec.ts, src/richie-front/js/utils/filters/computeNewFilterValue.ts, src/richie-front/js/utils/filters/updateFilter.ts, src/richie-front/js/utils/searchSuggest/getSuggestionsSection.ts, src/richie-front/js/utils/searchSuggest/suggestionsFromSection.ts, webpack.config.js, yarn.lock
Just some routine maintenance, cleaning unused imports & removing an unused dependency.
What it says on the label
=> Clean unused imports & drop momentjs

sandbox/settings.py, src/richie-front/scss/_main.scss, src/richie/apps/courses/templates/courses/cms/_subject_detail.scss, src/richie/apps/courses/templates/courses/cms/course_detail.html, src/richie/apps/courses/templates/courses/cms/organization_detail.html, src/richie/apps/courses/templates/courses/cms/subject_detail.html, tests/apps/courses/test_templates_subject_detail.py
Copy organization detail style. Adapt copied template and style for subject detail. 
Adapt related tests.
To have a basic style for subject detail pages. #220 
Imitate what was done for organization detail. Adjust it to suit subject detail.
=> 💄(courses) subject detail: template and style

package.json, yarn.lock
=> ⬆️(dependencies) update npm dependencies

src/richie/apps/courses/models/course.py, src/richie/apps/courses/templates/courses/cms/_course_detail.scss, src/richie/apps/courses/templates/courses/cms/course_detail.html, tests/apps/courses/test_models_course_run.py, tests/apps/courses/test_templates_course_detail.py
Currently course run list is just simple list with no style and rude
look.
This add some style around course run, group date and format them to
"short date" display. Some tests have been fixed because course run
HTML has some changes in these tests.
=> 💄(layout) improve course run list look in course detail

src/richie-front/scss/_main.scss, src/richie-front/scss/mixins/_cards.scss, src/richie/apps/courses/templates/courses/cms/_course_detail.scss, src/richie/apps/courses/templates/courses/cms/course_detail.html, src/richie/apps/persons/templates/persons/cms/_person_detail.scss, src/richie/apps/persons/templates/persons/cms/person_detail.html, src/richie/apps/persons/templates/persons/plugins/_person_plugin.scss, src/richie/apps/persons/templates/persons/plugins/person.html, tests/apps/persons/test_cms_plugins_person.py
Current person contents does not have any real look styling.
This add some style around person plugin and plugin detail page.
Some tests have been fixed because course run HTML has some
changes in these tests.
=> 💄(layout) improve person plugin and detail look

src/richie/apps/persons/templates/persons/cms/_person_detail.scss, src/richie/apps/persons/templates/persons/plugins/_person_plugin.scss
Person cards from plugin and detail is not responsive enough,
on mobile screens the card horizontal mode does not fit well.
We just make the card on vertical mode starting on mobile screen
and switch to horizontal mode on large breakpoint.
=> 💄(layout) make person cards responsive

src/richie/apps/courses/templates/courses/cms/_course_detail.scss
Actually Course detail styles can not be piloted from settings.
This commit change Course detail stylesheet to use variable settings
for every relevant values (font size, margin, padding, colors,
etc..).
=> WIP:💄(course) move relevant course detail styles values to settings

src/richie-front/js/components/SearchFilter/SearchFilter.tsx, src/richie-front/js/components/SearchFilter/_SearchFilter.scss, src/richie-front/js/components/icons/CloseIcon.tsx, src/richie-front/js/components/icons/_CloseIcon.scss, src/richie-front/scss/_main.scss
Following #380, we have made some improvements to the active filter state. Part of #376.
Closes #380.
=> Improve SearchFiler active state

sandbox/settings.py, src/richie/apps/courses/templates/courses/cms/_course_detail.scss
=> ✨(sandbox) enable image as teaser

sandbox/settings.py, src/richie-front/scss/_main.scss, src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html, src/richie/apps/courses/templates/courses/plugins/_organization_plugin.scss
Add style sheet to organization plugin.
Minor fix to course_glimpse to retrieve main organization after course refactoring.
Allow only organization_plugin in organization course-detail section.
=> add style to organization plugin

src/richie-front/js/data/genericSideEffects/getResourceList/getResourceList.spec.ts, src/richie-front/js/data/genericSideEffects/getResourceList/getResourceList.ts
The `fetchList` function in the `getResourceList` saga, and its related tests,  were written with `.then` promise and the `done` utility.
Replace those with async/await to make them simpler and easier to understand.
=> Use async/await to simplify getResourceList

src/richie/apps/courses/templates/courses/plugins/_organization_plugin.scss
Added sass value to cap the logo image size when it's in the plugin.
Removed unused value.
=> 🐛(organization) organization plugin logo too big

src/richie/apps/courses/templates/courses/cms/fragment_organization_main_logo.html
Repair a problem when adding a new course page from scratch.
In the absence of an organization, don't try and show anything as the main organization logo.
=> 🐛(course) update fragment_organization_main_logo.html

sandbox/settings.py, src/frontend/scss/_main.scss, src/richie/apps/core/management/commands/create_demo_site.py, src/richie/apps/courses/templates/courses/cms/_organization_list.scss, src/richie/apps/courses/templates/courses/cms/organization_list.html
Page is currently just a raw list, it should have a better look
as vertical card list.
This add a stylesheet and a new template dedicated to
organization list. Close #371.
=> 💄(organization) improve Organization list look

src/richie/apps/courses/cms_toolbars.py, tests/apps/courses/test_admin_page_snapshot.py
By translating Richie to french, @2018D found a small bug that is fixed by first commit. This also showed up a bug in unit tests.
=> I18n issues

sandbox/settings.py, src/frontend/scss/_colors.scss, src/frontend/scss/_main.scss, src/frontend/scss/_variables.scss, src/frontend/scss/mixins/_hero.scss, src/richie/apps/core/management/commands/create_demo_site.py, src/richie/plugins/large_banner/templates/richie/large_banner/_hero-intro.scss, src/richie/plugins/large_banner/templates/richie/large_banner/hero-intro.html, src/richie/plugins/section/templates/richie/section/_highlighted_items.scss, src/richie/plugins/section/templates/richie/section/highlighted_items.html
Homepage has no real webdesign integration and is pretty
basic.
This commit improve Homepage layout with some stylesheets and
template, taking funmooc.fr as a reference.
This depends from #508 merge.
=> 💄(homepage) improve homepage layout

.circleci/config.yml, .dockerignore, CHANGELOG.md, Dockerfile, Makefile, bin/pylint, docker/compose/ci/mysql/docker-compose.yml, docker/compose/ci/postgresql/docker-compose.yml, docker/images/alpine/Dockerfile, docker/images/alpine/ci/Dockerfile, docker/images/alpine/dev/Dockerfile, docker/images/ci/Dockerfile, docker/images/dev/Dockerfile, setup.cfg, src/richie/apps/core/fields/multiselect.py
We recently stumbled upon a packaging issue that enlighten the fact that tests performed in the CI cannot detect those issues as the tested image ships project sources.
=> Improve docker images and the CI to detect packaging issues

src/frontend/js/components/SearchFiltersPane/_SearchFiltersPane.scss, src/richie/apps/courses/templates/courses/cms/_course_detail.scss
Some minor feedbacks have been reported on course detail layout.
This reduce space between rows and some column title from blue
to white on blue.
=> 💄(course) fix minor feedbacks for layout reported in #540

CHANGELOG.md, setup.cfg, src/frontend/package.json
- Enable parent/children filters in the filters pane in Search,
- Add a template filter to check if a placeholder is empty,
- Add a new "Assessment" section in the course page.
- Hide empty placeholders from the course public page,
- Simplify the page creation wizard by reducing possibilities and automating object relations based on the navigation context:
* ensure we are not creating duplicate slugs when creating a page,
* reduce number of fields on form to create a new course run (remove languages and resource_link) and add a checkbox to easily snapshot the course when creating the course run,
* automatically link courses with an organization when created from this organization's page,
* create nested categories automatically when visiting the parent category page,
* show button to …
=> 🔖(chore) bump release to 1.0.0-beta.5

.circleci/config.yml, CHANGELOG.md
We need to enforce a maximal line length in our changelog to ease our life while releasing/commiting changes with a simple copy/paste that passes the git linter.
=> 👷(circleci) add lint-changelog job

src/richie/apps/demo/defaults.py, src/richie/apps/demo/management/commands/create_demo_site.py
Now that the functionality is available, let's add some categories to persons on the demo site.
Add between 1 and 3 subjects to each person.
=> 🚸(demo) add categories to persons on the demo site

CHANGELOG.md, src/frontend/scss/_main.scss, src/frontend/scss/objects/_organization_glimpses.scss, src/frontend/scss/templates/courses/cms/_organization_list.scss, src/richie/apps/courses/templates/courses/cms/fragment_organization_glimpse.html, src/richie/apps/courses/templates/courses/cms/organization_list.html, src/richie/apps/courses/templates/courses/plugins/organization.html, tests/apps/courses/test_cms_plugins_organization.py, tests/apps/courses/test_templates_course_detail.py, tests/apps/courses/test_templates_course_run_detail.py
Organization was the last component which have same representation
in different template fragment.
This commit finish the fragments refactoring. It adds a new
organization glimpse template and use it in organization list and
organization plugin.
=> 💄(organization) add organization glimpse template

CHANGELOG.md, Makefile, docker-compose.yml
Recent changes in the Docker stack raised issues that needed to be addressed.
=> Fix docker environment

CHANGELOG.md, sandbox/settings.py, src/richie/apps/courses/settings/__init__.py, src/richie/apps/courses/settings/mixins.py
=> Improve settings on the sandbox

CHANGELOG.md, setup.cfg, src/frontend/package.json
This is the first stable release of Richie 🎉
=> 🔖(chore) bump release to 1.0.0

CHANGELOG.md, setup.cfg, src/frontend/package.json
- Add course effort and duration values to demo site.
- Replace first name, last name and person title by page title.
- Add missing translation when displaying effort and duration on the course.
=> 🔖(chore) bump release to 1.3.0

CHANGELOG.md, setup.cfg, src/frontend/package.json
- Improve the layout for the person details page.
- Improve label text for the child filter toggle in Search.
=> 🔖(chore) bump release to 1.4.1

CHANGELOG.md, src/frontend/scss/components/_header.scss
Padding should be spelled with two 'd' not three.
=> ✏️(scss) fix typo in variable name

CHANGELOG.md, setup.cfg, src/frontend/package.json
- Fixed typos in header-related SCSS variable names.
- Fix non-conformities in blogpost, category, organization & person glimpses.
- Fix lodash-es, handlebars vulnerabilities by upgrading versions.
=> 🔖(chore) bump version to 1.5.1

.circleci/config.yml, CHANGELOG.md, Makefile, setup.cfg, src/richie/apps/core/factories.py, src/richie/apps/core/helpers.py, src/richie/apps/courses/factories.py, src/richie/apps/courses/helpers.py, src/richie/apps/demo/management/commands/create_demo_site.py, src/richie/apps/demo/utils.py, tests/apps/core/test_helpers.py, tests/apps/courses/test_admin_page_snapshot.py
We want to lint our Python source code with [bandit](https://github.com/PyCQA/bandit).
- Add bandit as dev dependency
- Run bandit in the CI as a linter
- Add a make target to run bandit as a linter
- Fix or ignore warnings in order to get all green on all severity levels (low, medium and high)
=> 👷(linters) lint backend source code with bandit

CHANGELOG.md, setup.cfg, src/frontend/package.json
- Improve english date on course page,
- Improve course glimpse text formatting.
- Remove asserts and prepare codebase for activation of `bandit` linter.
=> 🔖(chore) bump version to 1.5.2

CHANGELOG.md, setup.cfg, src/frontend/package.json
Fixed
- Add woff2 in MANIFEST.in so new font is included in Python package.
=> 🔖(chore) bump version to 1.7.1

CHANGELOG.md, setup.cfg, src/frontend/package.json, src/richie/apps/core/templates/richie/base.html
=> Release 1.7.3 - Fix logo url in footer

CHANGELOG.md, setup.cfg, src/frontend/package.json
Added
- Show a "More options" button along with a modal to find more filter values
for each filter in the search filters pane in course search, only when there
are more values to be found.
Fixed
- Fix missing author name on blogpost detail pages because of an error in
the person plugin template.
- Fix search API endpoints for categories, organizations & persons.
=> 🔖(chore) bump version to 1.8.0

CHANGELOG.md, setup.cfg, src/frontend/package.json
- Allow overriding Richie's default settings in inheriting configurations
=> 🔖(chore) bump version to 1.8.3

CHANGELOG.md, UPGRADE.md
We need a place where all important instructions to upgrade the project are listed. 
We think an UPGRADE.md file at the root of the project, and following the same format as the CHANGELOG.md file, is a good way to make this information available to all.
=> 📝(project) add a file at the root of the project to document upgrades

CHANGELOG.md, setup.cfg, src/frontend/package.json
- Logo image location wrongly targetted in base.html new SEO tags.
=> 🔖(chore) bump version to 1.9.2

CHANGELOG.md, setup.cfg, src/frontend/package.json
Added
- Make stylesheet links overridable in the base template
=> 🔖(chore) bump version to 1.11.0

CHANGELOG.md, setup.cfg, src/frontend/package.json, website/package.json
- Create a documentation & marketing website for the project. It lives under the `docs` folder and is deployed to Github Pages.
- Fix an API request issue that was breaking the `<RootSearchSuggestField />` component.
=> 🔖(chore) bump version to 1.12.1

CHANGELOG.md, bin/lint-back-diff, src/richie/apps/courses/models/course.py, tests/apps/courses/test_models_course.py
The main organization method was broken since we inadvertently commented a line in the code. 
The real problem is that this was not pinpointed by a breaking test. I fixed the method and improved the related test to make sure that it fails when the ordering clause is commented.
Fixes https://github.com/openfun/richie/issues/902
=> 🐛(courses) fix main organization broken by a comment & a missing test

CHANGELOG.md, setup.cfg, src/frontend/package.json, website/package.json
Fixed
- Add missing migration dependency to avoid IntegrityError on live databases.
=> 🔖(chore) bump version to 1.14.1

CHANGELOG.md, setup.cfg, src/frontend/package.json, tests_e2e/package.json, website/package.json
- Allow CKEditor with minimal options on course format, prerequisites and
assessment sections.
=> 🔖(chore) bump version to 1.16.1

CHANGELOG.md, setup.cfg, src/frontend/package.json, tests_e2e/package.json, website/package.json
- Fixed an issue with Picture instances that did not contain an image.
=> 🔖 Release version to 1.16.2

.circleci/config.yml, CHANGELOG.md, UPGRADE.md, setup.cfg, src/frontend/package.json, tests_e2e/package.json, website/package.json
- Add new plugin "Glimpse" to include some basic content with some variant
form factor available.
- Add new plugin "NestedItem" to implement structured nestable and foldable
content items.
- Add Styleguide view only available on `/styleguide/` in debug mode.
- Add full favicon set to cover every usages (browser, mobile app, etc..).
- Major templates/css refactor to bring a complete new design for the demo.
- The `section_cadenced` and `section_list` templates from the section plugin.
=> 🔖(chore) bump version to 2.0.0-beta.0

CHANGELOG.md, MANIFEST.in, setup.cfg, src/frontend/package.json, tests_e2e/package.json, website/package.json
- Add missing favicon static files to MANIFEST.in
=> Fix missing favicon static files in python package

CHANGELOG.md, setup.cfg, src/frontend/package.json, src/richie/apps/demo/defaults.py, src/richie/apps/demo/management/commands/create_demo_site.py, src/richie/apps/demo/utils.py, tests/apps/demo/test_commands_create_demo_site.py, tests_e2e/package.json, website/package.json
- Allow defining custom image fixtures on demo site,
- Allow configuring a custom domain on demo site.
Fixes https://github.com/openfun/richie/issues/999
=> Allow customising domain and fixtures on demo site

CHANGELOG.md, setup.cfg, src/frontend/package.json, src/richie/apps/demo/utils.py, tests_e2e/package.json, website/package.json
- Custom fixtures directory setting should point to the "fixtures" directory
=> Custom fixtures directory setting should point to the "fixtures" directory

CHANGELOG.md, setup.cfg, src/frontend/package.json, tests_e2e/package.json, website/package.json
- Fix an issue where analyzing course search queries with irrelevant analyzers
caused very low relevance results in course search.
- New Program glimpse layout.
- A lot of minor fixes and changes in Sass sources.
=> 🔖(chore) bump version to 2.0.0-beta.5

CHANGELOG.md, setup.cfg, src/frontend/package.json, tests_e2e/package.json, website/package.json
- Allow glimpse plugin in course information placeholder
- Allow overriding the contact us button in the topbar
- Improve performance of Search frontend.
- Refine Large banner plugin layout for hero variant.
- First course glimpses on three columns on homepage.
- Fix glitch with "scaleX" usage on wave decoration on category and organization detail banner.
- Fix content vertical alignment for category glimpses in section tiles.
=> 🔖(chore) bump version to 2.0.0-beta.7

CHANGELOG.md, src/frontend/scss/components/templates/courses/cms/_course_detail.scss
Primary group contents in course detail could have incorrect vertical
rhythm (lacking of marging) when content is plain text (without
paragraph). Also these content font size was a little bit too small.
Here we just fix this minor issues in course detail Sass component.
=> 👌(layout) fix course detail vertical rhythm and font size

CHANGELOG.md, src/frontend/js/components/UserLogin/_styles.scss, src/frontend/scss/settings/_colors.scss
Login and logout CTA in header was less visible than the ones from mockups.
We just change a theme color and make them uppercase as from mockups.
=> 👌(layout) make login/logout CTA more visible

CHANGELOG.md, src/frontend/scss/components/_footer.scss, src/frontend/scss/settings/_colors.scss
Font color ratio from text in "body-mentions" element in footer was
too low.
This change the theme so font color has maximum ratio. Also fix a
minor issue with brand link taking too much width for nothing.
=> 👌(layout) improve accessibility on 'body-mentions'

CHANGELOG.md, src/richie/apps/core/templates/richie/base.html
We need a template block around footer slogan so projects can change
it or even disable it if needed.
This just update the base.html to put the slogan in a template block
"body_footer_slogan".
=> 👌(layout) add template block around footer slogan

CHANGELOG.md, setup.cfg, src/frontend/package.json, tests_e2e/package.json, website/package.json
- Add checkmark icon to course skills bullet lists.
- Change course detail content titles to neutral dark color.
- Customize CMS placeholder menu for more readability.
- Make login/logout CTA more visible.
- Add template block around footer slogan.
- Fix course detail vertical rhythm and font size.
- Fix accordion border line.
- Fix basic block element alignment in section.
- Include the SVG icons sprite in `base.html` instead of loading it as external content so it can support usage with CDNs.
- Add grid constraint on person 'main_content' placeholder content.
- Make course glimpse category cartouche less "aggressive".
- Improve accessibility on 'body-mentions'
=> 🔖(chore) bump version to 2.0.0-beta.8

CHANGELOG.md, setup.cfg, src/frontend/package.json, tests_e2e/package.json, website/package.json
- Add oauth2 and OIDC authentication backends for SSO with Open edX
- Add an icon to the 'login' button.
- Add icons in course glimpse footer & next to organization name.
- Add new variant "quote" to glimpse plugin.
- Improve search error message layout
- Make larger thumbnail for course and blogpost glimpses.
- Lowered down global 'h1' and 'h2' font size and added new 'extra-font-size' variable with previous h1 value.
- Adjust title size 'large_banner' variants.
- Fix accordion button 'nested-item__title' alignment to the left.
- Another attempt to definitively fix the glitch with wave decoration and Chrome zoom/unzoom.
- Add a little bit of space between banner and title on organization and category detail.
- Fix header menus align/position between breakpoint 'md' end and 'lg' start.
- …
=> 🔖(chore) bump version to 2.0.0-beta.9

CHANGELOG.md, src/richie/apps/courses/cms_plugins.py, src/richie/apps/courses/settings/__init__.py
The support team reported some minor configuration issues.
- Allow one simple text plugin as person page main content
- Allow glimpse plugins in course page information placeholder
- Revert to long plugin names in side toolbar placeholder plugin list
=> Minor settings adjustments

CHANGELOG.md, setup.cfg, src/frontend/package.json, tests_e2e/package.json, website/package.json
- Add LMS connection (back and front) to handle enrollment on course runs
- Add LMS backend with enrollment methods for Open edX
- Allow any format for course run urls
- Stop synchronizing user permission fields on oauth: `is_staff` and `is_superuser`
- Add default image for empty person portrait
- Add default images for empty organization logo and banner
- Add translation context to course and course run detail page section titles
- Authentication urls should not be i18n
- Reorder sections on the course run detail page to mirror course detail page
=> 🔖(chore) bump version to 2.0.0-beta.12

docs/docker-development.md, docs/native-installation.md, website/versioned_docs/version-1.12/docker-development.md
To bootstrap properly richie, I read the doc provided and I found little mistakes.
=> ✏️ (docs) fix misspelling

docs/docker-development.md
On unix systems, Elasticsearch requires some tweaking to run. New comers always ask how to make the change permanent.
Add instructions to the documentation.
=> 📝(docs) add instructions to make elasticsearch system tweak permanent

CHANGELOG.md, src/frontend/scss/components/templates/courses/cms/_program_list.scss, src/frontend/scss/objects/_program_glimpses.scss, src/richie/apps/courses/settings/__init__.py, src/richie/apps/courses/templates/courses/cms/program_list.html, src/richie/apps/demo/management/commands/create_demo_site.py
We want to allow creating content on the programs list page.
We also need to be more lax and allow the default CKEditor configuration for all main content placeholders.
=> Text on program list page and ckeditor on home

CHANGELOG.md, src/richie/apps/courses/templates/courses/cms/fragment_course_run.html, tests/apps/courses/test_templates_course_detail.py
update fragment_course_run template to match new css class.
replace course-detail__run-cta in fragment_course_run template by course-run-enrollment__cta
=> 💄(course) replace course-detail__run-cta 

CHANGELOG.md, setup.cfg, src/frontend/package.json, tests_e2e/package.json, website/package.json
- Hide unpublished pages from public version of organizations list page
- Improve sanitizing of input text on CKEditor plugin
- Replace course-detail__run-cta in fragment_course_run template by course-run-enrollment__cta
=> 🔖(chore) bump version to 2.0.0-beta.16

.circleci/config.yml, src/frontend/webpack.config.js
Since webpack 5, env variables declaration in cli has changed and it breaks ts build from richie-site-factory.
So we add a ci job to check that building richie in dependent mode works
Related issue: #1168
=> 🐛 (webpack 5) update config file

CHANGELOG.md, src/frontend/scss/components/templates/richie/section/_section.scss, src/frontend/scss/settings/_colors.scss, src/richie/apps/courses/settings/__init__.py, src/richie/plugins/section/cms_plugins.py, src/richie/plugins/section/forms.py, src/richie/plugins/section/templates/richie/section/section.html
We would like to emphase some content in section title.
=> ✨(SectionPlugin) title field is now editable with ckeditor

CHANGELOG.md, setup.cfg, src/frontend/package.json, src/richie/apps/courses/admin.py, tests_e2e/package.json, website/package.json
- Fix maincontent placeholder on person detail page when empty
=> Release 2.0.0 beta.20

CHANGELOG.md, src/frontend/scss/components/_footer.scss
In `body-footer_items` we cannot have lot of columns.
=> 💄(footer) save space in links menu

CHANGELOG.md, src/richie/apps/courses/settings/__init__.py
`program_body` placeholder accepted all kind of plugins. It has been asked to restrict this placeholder to accept only a CKEditorPlugin`.
=> ♻️(program_detail) allow only one ckeditor to program_body placeholder

CHANGELOG.md, src/richie/apps/courses/templates/courses/cms/organization_detail.html
Image srcset was misconfigured. 
Sizes attributes was set to `300px` so the smallest resolution size was always selected.
So poor quality image was displayed especially on large screen.
On a non retina screen
On a non retina screen
=> 🐛(organizations) image srcset was misconfigured

UPGRADE.md
Since Richie owns its error template, we have to explain how to use them.
=> 📝(UPGRADE) add explanation to use custom error views

CHANGELOG.md, src/richie/apps/search/forms.py
Arrow version 1.0 introduces some breaking changes https://github.com/arrow-py/arrow/issues/832
Replace .timestamp property by .int_timestamp
=> 🚑(deps) Update arrow usage for version 1.0

CHANGELOG.md, src/frontend/js/components/CourseRunEnrollment/index.spec.tsx, src/frontend/js/components/CourseRunEnrollment/index.tsx, src/frontend/js/components/LanguageSelector/index.spec.tsx, src/frontend/js/components/LanguageSelector/index.tsx, src/frontend/js/components/LtiConsumer/index.spec.tsx, src/frontend/js/components/LtiConsumer/index.tsx, src/frontend/js/components/Root/index.spec.tsx, src/frontend/js/components/Root/index.tsx, src/frontend/js/components/RootSearchSuggestField/index.spec.tsx, src/frontend/js/components/RootSearchSuggestField/index.tsx, src/frontend/js/components/Search/index.spec.tsx, src/frontend/js/components/Search/index.tsx, src/frontend/js/components/SearchSuggestField/index.spec.tsx, src/frontend/js/components/SearchSuggestField/index.tsx, src/frontend/js/components/UserLogin/index.spec.tsx, src/frontend/js/components/UserLogin/index.tsx
As frontend widgets aims to grow, we need to optimize js chunks to load them only where they are needed.
=> ⚡️(frontend) lazy load react widgets

CHANGELOG.md, src/richie/apps/search/forms.py, src/richie/apps/search/indexers/courses.py, tests/apps/search/test_forms_search_courses.py, tests/apps/search/test_indexers_courses.py, tests/apps/search/test_query_courses.py, tests/apps/search/test_query_courses_edge_cases.py, tests/apps/search/test_viewsets_courses.py
The course introduction is an important piece of text on which we should search.
Also, we want to share the course introduction on the API to be able to build glimpses with more information than the
present card.
Add course introduction text to the course search index and to the displayed fields on the search API.
=> ✨(search) add introduction text to search index and API

tests/apps/search/test_indexers_courses.py
When a course is unpublished in one language, but it has related objects that are still published in this language, should or shouldn't we use this language's content for the related objects when building the course glimpse? For the moment it does.
This choice is controversial and I had to write these tests to fully understand it. So I propose to commit them to keep this memory.
Note: We could argue in the future that a course glimpse should be built with content only in the same language and not with "as few fallback languages as possible, using available content in each language".
=> ✅(search) clarify languages used on course unpublished in a language

src/richie/apps/core/context_processors.py, src/richie/apps/core/templates/richie/base.html, src/richie/apps/core/templatetags/full_static_tags.py, src/richie/apps/courses/models/course.py, src/richie/apps/courses/templates/courses/cms/course_detail.html, tests/apps/core/test_cache.py, tests/apps/core/test_templates_richie_homepage.py, tests/apps/core/test_templatetags_full_static_tags.py, tests/apps/courses/test_templates_course_detail_opengraph.py, tests/apps/courses/test_templates_course_detail_rendering.py
Change course cover image using 1200x630 size and if the course don't have a cover show the site logo.
Also add the og:image:width and og:image:height for sharing performance.
=> 🔍️(SEO) fix og image meta

CHANGELOG.md, sandbox/urls.py, src/richie/apps/core/templates/richie/robots.html, tests/apps/core/test_robots.py
Add sitemap.xml to robots.txt, so it's no longer need to register the sitemap.xml URL to each crawler administration panel
=> 🔍️(SEO) add sitemap to robots

CHANGELOG.md, docs/web-analytics.md, sandbox/settings.py, src/richie/apps/core/context_processors.py, src/richie/apps/core/templates/richie/base.html, src/richie/apps/core/templates/richie/web_analytics.html, src/richie/apps/courses/models/organization.py, tests/apps/core/test_web_analytics.py, tests/apps/courses/test_models_organization.py
Optionally add Google Analytics to Richie.
Including Google Analytics custom dimensions that make it possible to create better custom reports.
on docs/google-analytics.md I've added a documentation how to enabled it on an existing richie site.
=> Add Google Analytics using Google Tag manager script.

UPGRADE.md
We forgot to add instructions about new css imports and rules.
Add missing instructions to `UPGRADE.md` file.
=> 📝(upgrade) add missing instructions on css for upgrade to 2.10.x

website/pages/en/index.js
Edited language for minor grammar issues, clarity, and consistency
Came across Richie while looking for e-learning and LMS projects open to contributions. The website is very clean and well-designed. I am a UX writer and happy to help clarify language for end-users. Thus, I've edited the written content on the homepage to hopefully help people who find and want to use Richie in English.
- Fix minor grammatical errors
- Fix passive voice (when appropriate)
- Language focused on potential users
- Some jargon was simplified, as website states Richie can be used by non-software engineers
=> Edited homepage language

.circleci/config.yml, CHANGELOG.md, docker-compose.yml
=> ⬆️(mysql) upgrade mysql to version 8

CHANGELOG.md, docs/web-analytics.md, src/frontend/js/data/useCourseEnrollment/index.ts, src/frontend/js/types/WebAnalytics.ts, src/frontend/js/types/commonDataProps.ts, src/frontend/js/types/web-analytics/google_analytics.d.ts, src/frontend/js/types/web-analytics/google_tag_manager.d.ts, src/frontend/js/utils/api/web-analytics/base.ts, src/frontend/js/utils/api/web-analytics/google_analytics.spec.ts, src/frontend/js/utils/api/web-analytics/google_analytics.ts, src/frontend/js/utils/api/web-analytics/google_tag_manager.spec.ts, src/frontend/js/utils/api/web-analytics/google_tag_manager.ts, src/frontend/js/utils/api/web-analytics/index.ts, src/frontend/js/utils/api/web-analytics/no_provider.spec.ts, src/frontend/js/utils/api/web-analytics/unknown_provider.spec.ts, src/frontend/js/utils/test/factories.ts, src/richie/apps/core/context_processors.py, src/richie/apps/core/templates/richie/web_analytics.html, tests/apps/core/test_pages.py, tests/apps/core/test_web_analytics.py
Differentiate between Google Analytics and Google Tag Manager js code has different Web Analytics providers.
Send web analytics event when an user enrolls to a course using the LMS enrollment api.
=> ✨(web_analytics) improve web analytics

CHANGELOG.md, src/frontend/scss/_main.scss, src/frontend/scss/components/templates/richie/_multiple-columns.scss, src/frontend/scss/objects/_person_glimpses.scss, src/frontend/scss/tools/_rem.scss, src/richie/apps/core/templates/richie/multiple_columns.html, src/richie/apps/core/templates/richie/three_columns_33.html, src/richie/apps/core/templates/richie/two_columns_25_75.html, src/richie/apps/core/templates/richie/two_columns_50.html, src/richie/apps/core/templates/richie/two_columns_75_25.html, src/richie/apps/courses/settings/__init__.py, tests/apps/courses/test_cms_views.py, tests/apps/courses/test_settings_mixins.py
Users have expressed a need to create some page with multiple columns with various
widths.
This adds new templates for various columns variants:
And some CSS to adjust column contents to fit their column width.
This is a work in progress, published sooner to allow some reviews before continuing since it involves a lot of CSS adjustments.
There is a huge plugin variance and plugins layouts have been almost exclusively to be in 100% container width, without adjustments a lot of plugins looks ugly or are even broken (with contents overflowing other contents, etc..).
Also, i started this branch with a minor Sass fix about deprecation warning for division operator with recent Sass implementation from Dart Sass. It has been done in a first distinct commit.
Some screenshot will illustrate the …
=> 💄 Add new column layout templates

CHANGELOG.md, UPGRADE.md, src/frontend/scss/colors/_theme.scss, src/frontend/scss/components/templates/courses/cms/_course_detail.scss
Add theme variable to change checkmark color.
On NAU we don't use the `indianred3` color, so we have detected that is not easy to change the check mark color when using a list on the field _What you will learn_ on the course page.
With this change, when we change the new theme variable `checkmark-list-decoration-color` to `blue`:
=> 💄(theme) add checkmark color variable

CHANGELOG.md, src/frontend/js/components/SaleTunnelStepPayment/index.spec.tsx, src/frontend/js/components/SaleTunnelStepPayment/index.tsx
In one test, random values could create some conflict so we refactor this test
to prevent this random conflict.
Resolve #1677
=> ✅(frontend) fix erratic failure

CHANGELOG.md, UPGRADE.md, src/frontend/js/components/AddressesManagement/AddressForm.tsx, src/frontend/js/components/AddressesManagement/_styles.scss, src/frontend/js/components/AddressesManagement/index.tsx, src/frontend/js/components/PaymentButton/index.tsx, src/frontend/js/components/RegisteredAddress/_styles.scss, src/frontend/js/components/RegisteredAddress/index.tsx, src/frontend/js/components/SaleTunnel/_styles.scss, src/frontend/js/components/SaleTunnelStepPayment/index.tsx, src/frontend/js/components/SaleTunnelStepResume/index.tsx, src/frontend/js/components/SaleTunnelStepValidation/index.tsx, src/frontend/scss/_main.scss, src/frontend/scss/colors/_theme.scss, src/frontend/scss/tools/_buttons.scss, src/frontend/scss/tools/_colors.scss
Previously, it was pretty hard to customize theme within sale tunnel, and it
could lead to poor result across our sites. Now, we are able to customize
button style within sale tunnel.
=> 💄(frontend) improve sale tunnel overriding

renovate.json
There was a typo within the renovate json file.
Resolve #1481
=> 🐛(renovate) fix renovate configuration

CHANGELOG.md, sandbox/urls.py, src/frontend/js/components/DashBoard/index.spec.tsx, src/frontend/js/components/DashBoard/index.tsx, src/frontend/js/components/Root/index.tsx, src/richie/apps/core/templates/richie/dashboard.html, tests/apps/core/test_templates_richie_dashboard.py
Add a simple Dashboard that will show dashboard of users
=> ✨ (richie) Add a dashBoard

CHANGELOG.md, setup.cfg
Add pip requests package for open edx lms backend.
Closes #1768
=> ➕(requests) add requests package

CHANGELOG.md, cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/backend/{{cookiecutter.site}}/settings.py, sandbox/settings.py, src/richie/apps/core/context_processors.py, src/richie/apps/core/templates/richie/base.html, tests/apps/core/test_templates_dns_prefetch.py
Add dns prefetch and optionally preconnect to media cdn
=> ⚡️(dns) add dns prefetch for media cdn

CHANGELOG.md, src/frontend/.storybook/main.js, src/frontend/.storybook/preview-body.html, src/frontend/.storybook/preview.js, src/frontend/.storybook/preview.tsx, src/frontend/js/components/Banner/index.stories.tsx, src/frontend/js/components/Form/CheckboxField.stories.tsx, src/frontend/js/components/Form/Field.stories.tsx, src/frontend/js/components/Form/RadioField.stories.tsx, src/frontend/js/components/Form/SelectField.stories.tsx, src/frontend/js/components/Form/TextAreaField.stories.tsx, src/frontend/js/components/Form/TextField.stories.tsx, src/frontend/js/components/Icon/index.stories.tsx, src/frontend/js/components/Modal/index.stories.tsx
The goal is to increase the coverage of the recently installed Storybook.
Components to create stories for: 
- `components/Banner`
- `components/Icon`
- `components/Form/Inputs/*`
- `components/Modal`
=> 🧑‍💻(frontend) add components to storybook

CHANGELOG.md, src/frontend/js/components/Form/Field.stories.tsx, src/frontend/scss/colors/_theme.scss, src/frontend/scss/objects/_form.scss
Add a differentiable style to disabled inputs.
=> 🧑‍💻(frontend) add style to disabled inputs

src/frontend/.storybook/main.js, src/frontend/.storybook/preview-head.html, src/frontend/package.json, src/frontend/webpack.config.js, src/frontend/yarn.lock
=> Fix various storybook little issues

src/frontend/js/components/DashboardAddressesManagement/DashboardCreateAddress.spec.tsx, src/frontend/js/components/DashboardAddressesManagement/DashboardEditAddress.spec.tsx, src/frontend/js/components/DashboardAddressesManagement/index.spec.tsx, src/frontend/js/hooks/useAddresses.ts, src/frontend/js/hooks/useAddressesManagement.tsx, src/frontend/js/hooks/useCreditCardsManagement.tsx
=> 🌐(frontend) fix various translations

.github/ISSUE_TEMPLATE/Bug_report.md
When want to open an issue for a problem we encountered it is weird to first ask about the expected behavior before even describing the problem. I never know what to write and end-up changing the questions.
First ask about the but, then about what was expected.
=> 🧑‍💻(github) improve bug report issue template

CHANGELOG.md, sandbox/settings.py, src/frontend/js/components/AddressesManagement/index.spec.tsx, src/frontend/js/components/CourseProductCertificateItem/index.spec.tsx, src/frontend/js/components/CourseProductCourseRuns/index.spec.tsx, src/frontend/js/components/CourseProductsList/index.spec.tsx, src/frontend/js/components/Dashboard/index.spec.tsx, src/frontend/js/components/DashboardAddressesManagement/DashboardCreateAddress.spec.tsx, src/frontend/js/components/DashboardAddressesManagement/DashboardEditAddress.spec.tsx, src/frontend/js/components/DashboardAddressesManagement/index.spec.tsx, src/frontend/js/components/DashboardCreditCardsManagement/DashboardEditCreditCard.spec.tsx, src/frontend/js/components/DashboardCreditCardsManagement/index.spec.tsx, src/frontend/js/components/PaymentButton/index.spec.tsx, src/frontend/js/components/SaleTunnel/index.spec.tsx, src/frontend/js/components/SaleTunnelStepPayment/index.spec.tsx, src/frontend/js/data/SessionProvider/JoanieSessionProvider.spec.tsx, src/frontend/js/data/useCourseEnrollment/index.spec.tsx, src/frontend/js/hooks/useCreditCards/index.spec.tsx, src/frontend/js/settings.ts, src/frontend/js/utils/api/joanie.ts
Recently, we versionned Joanie api endpoint. So we have to update joanie api interface to dialog with new endpoints.
=> ♻️(frontend) use versionned Joanie API routes

CHANGELOG.md, UPGRADE.md, docs/joanie-connection.md
We do not update joanie-connection.md documentation page since we rename the setting from `JOANIE` to `JOANIE_BACKEND`. Furthermore, we add new settings and the purpose of each of them was not explained.
=> 📝(doc) update joanie-connection documentation

src/frontend/js/components/SaleTunnel/index.spec.tsx, src/frontend/js/components/SaleTunnel/index.tsx
If a product has no target courses we need to prevent him from buying it.
=> 🐛(frontend) disable payment button if a product has no courses

CHANGELOG.md, Dockerfile, Makefile
Add Makefile entry to acces postgresql docker in cli using: `make psql`
=> Add make dbshell cmd to access database in cli

src/frontend/js/hooks/useEnroll/index.spec.tsx
one act warning and some unmocked requests
Keep warning free tests
=> ✅(frontend) clear warning from useEnroll test

CHANGELOG.md, src/frontend/js/components/CourseProductCourseRuns/EnrolledCourseRun.tsx, src/frontend/js/components/CourseProductCourseRuns/_styles.scss, src/frontend/js/components/CourseProductCourseRuns/index.spec.tsx, src/frontend/js/components/CourseProductItem/CourseRunItem.tsx, src/frontend/js/components/CourseRunEnrollment/index.tsx, src/frontend/js/components/CourseRunUnenrollmentButton/_styles.scss, src/frontend/js/components/CourseRunUnenrollmentButton/index.spec.tsx, src/frontend/js/components/CourseRunUnenrollmentButton/index.tsx, src/frontend/js/utils/relativeDate.ts, src/frontend/js/utils/useDateRelative.tsx, src/frontend/scss/components/_index.scss
On the CourseProductItem component, when the user is enrolled to a course but the related course run is not yet opened, a button "Access to cours" is displayed to access to the course that is weird.
Instead to display the access button, we should display a message that mention that the course starts in <RELATIVE_DATE_TIME>.
=> ✨(frontend) EnrolledCourseRun button displayed when course is not yet opened

CHANGELOG.md, src/frontend/js/components/Button/index.tsx, src/frontend/js/components/CourseAddToWishlist/_styles.scss, src/frontend/js/components/CourseAddToWishlist/index.login.spec.tsx, src/frontend/js/components/CourseAddToWishlist/index.logout.spec.tsx, src/frontend/js/components/CourseAddToWishlist/index.tsx, src/frontend/js/components/Root/index.tsx, src/frontend/js/components/Spinner/index.tsx, src/frontend/js/hooks/useResources/useResourcesRoot.ts, src/frontend/js/hooks/useUserWishlistCourses/index.spec.tsx, src/frontend/js/hooks/useUserWishlistCourses/index.ts, src/frontend/js/types/Joanie.ts, src/frontend/js/utils/api/joanie.ts, src/frontend/js/utils/test/factories.ts, src/frontend/scss/components/_index.scss, src/richie/apps/courses/templates/courses/cms/course_detail.html
add button to add a course to user wishlist
Add a button on course detail page when no runs are available
=> ✨(frontend) user course wishlist

CHANGELOG.md, src/frontend/js/components/DashboardCourses/_styles.scss, src/frontend/js/components/DashboardCourses/index.spec.tsx, src/frontend/js/components/DashboardCourses/index.tsx, src/frontend/js/components/DashboardItem/Enrollment/DashboardItemEnrollment.tsx, src/frontend/js/components/DashboardItem/_styles.scss, src/frontend/js/components/DashboardItem/index.stories.tsx, src/frontend/js/components/DashboardItem/index.tsx, src/frontend/js/components/PaginateCourseSearch/index.tsx, src/frontend/js/components/Pagination/index.spec.tsx, src/frontend/js/components/Pagination/index.tsx, src/frontend/js/hooks/useEnrollments.ts, src/frontend/js/hooks/useResources/index.spec.tsx, src/frontend/js/hooks/useResources/useResourcesRoot.ts, src/frontend/js/types/Joanie.ts, src/frontend/js/utils/routers/dashboard/useDashboardRouter/index.tsx, src/frontend/js/utils/test/expectSpinner.ts, src/frontend/js/utils/test/factories.ts
=> ✨(frontend) create pagination for enrollments

CHANGELOG.md, src/frontend/js/widgets/CourseProductItem/components/CourseProductCourseRuns/_styles.scss
We recently rework form styles and it introduces a layout issue on CourseProductItem.
=> 💄(frontend) fix layout issue on CourseProductItem

CHANGELOG.md, src/richie/apps/courses/templates/courses/cms/course_detail.html, src/richie/apps/courses/templates/courses/cms/organization_detail.html
Fix the image sizes in the `srcset` to allow for better resolution.
Fix the organization page banner not correctly cropping the image.
The current definitions for the image don't allow a good quality image to be displayed.
The sole purpose of this PR is to adjust the image resolution, so it doesn't display really low quality images.
=> 🩹(courses) fix image sizes for course cover

src/frontend/js/components/AddressesManagement/index.tsx, src/frontend/js/components/CourseGlimpse/CourseGlimpseFooter.tsx, src/frontend/js/components/CourseGlimpse/index.tsx, src/frontend/js/components/Icon/index.spec.tsx, src/frontend/js/components/Icon/index.stories.tsx, src/frontend/js/components/Icon/index.tsx, src/frontend/js/components/Modal/index.tsx, src/frontend/js/components/SearchInput/index.tsx, src/frontend/js/pages/DashboardAddressesManagement/index.tsx, src/frontend/js/pages/DashboardCreditCardsManagement/DashboardCreditCardBox.tsx, src/frontend/js/widgets/CourseProductItem/components/CourseProductCourseRuns/CourseRunList.tsx, src/frontend/js/widgets/CourseProductItem/components/CourseProductCourseRuns/EnrollableCourseRunList.tsx, src/frontend/js/widgets/CourseProductItem/components/SaleTunnel/index.tsx, src/frontend/js/widgets/CourseProductItem/components/SaleTunnelStepPayment/index.tsx, src/frontend/js/widgets/CourseProductItem/components/StepBreadcrumb/index.spec.tsx, src/frontend/js/widgets/CourseProductItem/hooks/useStepManager/index.ts, src/frontend/js/widgets/CourseProductItem/index.tsx, src/frontend/js/widgets/Dashboard/components/DashboardBreadcrumbs/index.tsx, src/frontend/js/widgets/Dashboard/components/DashboardCard/index.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Certificate/index.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/DashboardItemCourseEnrolling.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.tsx, src/frontend/js/widgets/Search/components/FiltersPaneCloseButton.tsx, src/frontend/js/widgets/UserLogin/components/UserMenu/MobileUserMenu.tsx, src/frontend/js/widgets/UserLogin/index.tsx
We need to have a visualisation of existing icons on richie.
Simple story with all existing icon for richie.
=> 🎨(frontend) icon in storybook

src/frontend/js/hooks/useUnionResource/index.spec.tsx, src/frontend/js/hooks/useUnionResource/index.ts, src/frontend/js/hooks/useUnionResource/utils/fetchEntities.ts, src/frontend/js/hooks/useUnionResource/utils/fetchEntity.ts, src/frontend/js/hooks/useUnionResource/utils/hasIntegrity.spec.ts, src/frontend/js/hooks/useUnionResource/utils/hasIntegrity.ts, src/frontend/js/hooks/useUnionResource/utils/log.ts, src/frontend/js/hooks/useUnionResource/utils/syncIntegrityCount.ts, src/frontend/js/pages/DashboardCourses/index.spec.tsx, src/frontend/js/pages/DashboardCourses/index.tsx, src/frontend/js/pages/DashboardCourses/useOrdersEnrollments.tsx, src/frontend/js/settings.ts
Use a generic code to merge entities from two different endpoints
=> ♻️(frontend)generice use union resourse

src/frontend/scss/objects/_dashboard.scss
on merge of:
commit bd2ca45664765e9893d33b97e5ec4af46bd5d0cb
✨(frontend) add page teacher dashboard training
a visual bug aprear on the new training page.
Before: 
After:
=> 💄(frontend) Fix dashboard title small and large

CHANGELOG.md, src/frontend/js/api/joanie.spec.ts, src/frontend/js/api/joanie.ts, src/frontend/js/types/Joanie.ts, src/frontend/js/utils/errors/HttpError.ts, src/frontend/js/utils/test/factories/joanie.ts, src/frontend/js/widgets/CourseProductItem/components/PaymentButton/index.tsx, src/frontend/js/widgets/CourseProductItem/components/PurchaseButton/index.spec.tsx, src/frontend/js/widgets/CourseProductItem/components/PurchaseButton/index.tsx
Product should not be available for sell when it has no remaining order left.
=> ✨(frontend) Prevent to purchase a product

CHANGELOG.md, src/frontend/js/components/CourseGlimpse/index.spec.tsx, src/frontend/js/components/CourseGlimpse/index.tsx, src/frontend/js/components/CourseGlimpse/utils.ts, src/frontend/js/components/TeacherDashboardCourseList/index.spec.tsx, src/frontend/js/hooks/useCourseProductUnion/index.spec.tsx, src/frontend/js/hooks/useCourseProductUnion/index.ts, src/frontend/js/pages/TeacherCoursesDashboardLoader/index.spec.tsx, src/frontend/js/types/Joanie.ts, src/frontend/js/utils/test/factories/joanie.ts
To improve performance, we had to change what's CourseProductRelation
endpoint return.
Therefor we need to refactor this endpoint usage in our frontend.
=> ♻️(frontend) refactor CourseProductRelation types

src/frontend/js/api/joanie.ts, src/frontend/js/components/PaymentButton/components/PaymentInterfaces/PayplugLightbox.tsx, src/frontend/js/components/PaymentButton/index.spec.tsx, src/frontend/js/components/PaymentButton/index.tsx, src/frontend/js/contexts/OrderContext/index.tsx, src/frontend/js/hooks/useOrders.ts, src/frontend/js/types/Joanie.ts, src/frontend/js/widgets/Dashboard/components/DashboardItem/DashboardItemCourseEnrolling.spec.tsx, src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.spec.tsx, src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.tsx
With the new payment tunnel, the ordering logic has changed.We need to reflect this in API types, requests and frontend.
=> ✨(frontend) refactor sale tunnel 

CHANGELOG.md, src/frontend/js/widgets/SyllabusCourseRunsList/components/SyllabusCourseRun/index.tsx, src/frontend/js/widgets/SyllabusCourseRunsList/index.spec.tsx
opened course run show '...' when date is empty
Help fix issue #2063
Verify if value is empty before displaying it
=> 🐛(courserun) fix empty date on opened course run

src/frontend/package.json, src/frontend/yarn.lock
=> ⬆️(deps) bump cunningham

src/frontend/js/api/joanie.spec.ts, src/frontend/js/api/joanie.ts
We create a function to handle url build that was repeat over and over.
=> ♻️(frontend) api.joanie: add buildApiUrl

CHANGELOG.md, src/frontend/js/api/joanie.ts, src/frontend/js/hooks/useContacts/index.tsx, src/frontend/js/pages/TeacherDashboardContractsLoader/ContractFilters/index.tsx, src/frontend/js/pages/TeacherDashboardContractsLoader/TeacherDashboardContracts/index.spec.tsx, src/frontend/js/pages/TeacherDashboardContractsLoader/TeacherDashboardContracts/index.tsx, src/frontend/js/pages/TeacherDashboardContractsLoader/TeacherDashboardCourseContractsLoader/index.spec.tsx, src/frontend/js/pages/TeacherDashboardContractsLoader/TeacherDashboardCourseContractsLoader/index.tsx, src/frontend/js/pages/TeacherDashboardContractsLoader/TeacherDashboardOrganizationContractsLoader/index.spec.tsx, src/frontend/js/pages/TeacherDashboardContractsLoader/TeacherDashboardOrganizationContractsLoader/index.tsx, src/frontend/js/pages/TeacherDashboardContractsLoader/index.ts, src/frontend/js/pages/TeacherDashboardContractsLoader/styles.scss, src/frontend/js/settings.ts, src/frontend/js/types/Joanie.ts, src/frontend/js/utils/test/factories/joanie.ts, src/frontend/js/widgets/Dashboard/components/DashboardLayout/_styles.scss, src/frontend/js/widgets/Dashboard/components/TeacherDashboardCourseSidebar/index.spec.tsx, src/frontend/js/widgets/Dashboard/components/TeacherDashboardCourseSidebar/index.tsx, src/frontend/js/widgets/Dashboard/components/TeacherDashboardCourseSidebar/utils.ts, src/frontend/js/widgets/Dashboard/components/TeacherDashboardOrganizationSidebar/index.tsx, src/frontend/js/widgets/Dashboard/utils/teacherRouteMessages.tsx, src/frontend/js/widgets/Dashboard/utils/teacherRoutes.tsx, src/frontend/mocks/handlers.ts, src/frontend/mocks/handlers/contracts.ts, src/frontend/scss/components/_index.scss
:warning: This PR is rebased on https://github.com/openfun/richie/pull/2091, do not review the first commit about bulk renames.
Add a page for organizations to signe they contracts, see issue: https://github.com/openfun/richie/issues/2075
=> ✨(frontend) add page organization download contracts

CHANGELOG.md, src/frontend/js/components/PurchaseButton/index.spec.tsx, src/frontend/js/components/PurchaseButton/index.tsx, src/frontend/js/components/SaleTunnel/components/SaleTunnelStepValidation/CourseRunsList.tsx, src/frontend/js/components/SaleTunnel/components/SaleTunnelStepValidation/_styles.scss, src/frontend/js/components/SaleTunnel/components/SaleTunnelStepValidation/index.spec.tsx, src/frontend/js/components/SaleTunnel/components/SaleTunnelStepValidation/index.tsx, src/frontend/js/components/SaleTunnel/index.tsx, src/frontend/js/types/Joanie.ts, src/frontend/js/utils/test/factories/joanie.ts, src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/DashboardItemEnrollment.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.spec.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.tsx
We need to improve the sale tunnel for certificate product. There need :
=> ✨(frontend) improve SaleTunnel validation step

CHANGELOG.md, src/frontend/js/pages/TeacherDashboardCoursesLoader/index.spec.tsx, src/frontend/js/widgets/Dashboard/components/DashboardLayout/_styles.scss, src/frontend/js/widgets/Dashboard/components/DashboardSidebar/_styles.scss, src/frontend/js/widgets/Dashboard/components/DashboardSidebar/components/NavigationSelect.tsx, src/frontend/js/widgets/Dashboard/components/DashboardSidebar/index.tsx, src/frontend/js/widgets/Dashboard/components/TeacherDashboardCourseSidebar/index.spec.tsx, src/frontend/js/widgets/Dashboard/components/TeacherDashboardProfileSidebar/index.spec.tsx, src/frontend/scss/objects/_course_glimpses.scss
Our mobile version of the dashboard needed some improvments
See https://github.com/openfun/richie/issues/2097
This PR fix: 
* Sidebar right margin
* Sidebar navigation select
=> 📱(frontend) fix mobile dashboard layout

CHANGELOG.md, src/frontend/js/hooks/useProductOrder/index.spec.tsx, src/frontend/js/hooks/useProductOrder/index.tsx, src/frontend/js/types/Joanie.ts, src/frontend/js/utils/test/factories/joanie.ts, src/frontend/js/widgets/Dashboard/components/DashboardItem/CertificateStatus/index.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/DashboardItemEnrollment.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.spec.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/stories.mock.ts, src/frontend/js/widgets/Dashboard/components/DashboardItem/utils/order.ts, src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.spec.tsx
New development about product certificate have been merge to joanie.
Theses updated includes breaking change in richie that need to be fixed:
* Order's listing must use enrollment instead of course in order to choose which footer display (buy, wait, download)
=> ✨(frontend) Fix product certificate listing

CHANGELOG.md, src/frontend/js/components/PurchaseButton/index.spec.tsx, src/frontend/js/components/PurchaseButton/index.tsx
Improve original string to aid with translation.
As I was doing translations over Crowdin, I found these 2 strings on `PurchaseButton` that were really hard to translate to portuguese, due their punctuation. I propose some changes to aid future translations, including the one I'm taking care of.
=> 🌐(translations) improve base strings

src/frontend/js/contexts/SessionContext/JoanieSessionProvider.tsx
In some cases we opening a new tab we had the following error:
It is not occurring all the time, that's because a race condition is occurring. 
Since the migration to ReactQuery v5 we had to remove `onSuccess` callback in favor of `useEffect` to set the `sessionStorage.setItem(RICHIE_USER_TOKEN, user?.access_token!);`. 
But this resulted to turning `enabled==true` the `useSession` queries BEFORE calling `useEffect` inside `JoanieSessionProvider`, then calling session queries via `fetchWithJWT` that tries to retrieve the `RICHIE_USER_TOKEN` from the session which is not set yet, and sometimes ( race condition ) setting an undefined Bearer token.
Remove the use of `useEffect` and synchronize directly the session.
It a bit what react query contributors advice us to do: …
=> 🐛(frontend) fix react query cache race condition causing 401

CHANGELOG.md, src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/ContractFrame/index.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrderContract.spec.tsx, src/frontend/js/widgets/Dashboard/components/DashboardOrderLoader/index.tsx
Fix typo on the DashboardOrderLoader component to improve translation.
=> 🌐(fix) fix typo on DashboardOrderLoader

src/frontend/js/components/PaymentButton/index.spec.tsx, src/frontend/js/hooks/useOrders.ts, src/frontend/js/hooks/useProductOrder/index.spec.tsx, src/frontend/js/hooks/useProductOrder/index.tsx, src/frontend/js/pages/DashboardCourses/index.spec.tsx, src/frontend/js/pages/DashboardCourses/index.tsx, src/frontend/js/types/Joanie.ts, src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.spec.tsx, src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.stories.tsx
All joanie's filters now use descriptive suffix like: _id, _code, _title, etc
=> 👽️(frontend) update filter types

src/frontend/js/api/lms/joanie.ts, src/frontend/js/components/PaymentButton/index.tsx, src/frontend/js/components/PurchaseButton/index.spec.tsx, src/frontend/js/components/PurchaseButton/index.tsx, src/frontend/js/components/SaleTunnel/components/SaleTunnelStepValidation/index.spec.tsx, src/frontend/js/components/SaleTunnel/components/SaleTunnelStepValidation/index.tsx, src/frontend/js/components/SaleTunnel/context.tsx, src/frontend/js/components/SaleTunnel/index.tsx, src/frontend/js/types/Joanie.ts, src/frontend/js/utils/test/factories/joanie.ts, src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/DashboardItemEnrollment.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.tsx, src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunEnrollment/index.joanie.spec.tsx
Each bug is fixed in its own commit.
=> 🐛(frontend) fix multiple product certificate bugs

src/frontend/js/components/SaleTunnel/components/SaleTunnelStepValidation/index.tsx
=> 🐛(frontend) remove debug residue

src/frontend/js/components/PaymentButton/index.spec.tsx, src/frontend/js/components/PaymentButton/index.tsx, src/frontend/js/components/PurchaseButton/index.spec.tsx, src/frontend/js/components/PurchaseButton/index.tsx, src/frontend/js/components/SaleTunnel/components/SaleTunnelStepValidation/index.spec.tsx, src/frontend/js/components/SaleTunnel/context.tsx, src/frontend/js/components/SaleTunnel/index.tsx, src/frontend/js/hooks/useProductOrder/index.tsx, src/frontend/js/types/Joanie.ts, src/frontend/js/utils/test/factories/joanie.ts, src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/DashboardItemEnrollment.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.spec.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.tsx, src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/CourseProductItemFooter/index.tsx, src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.tsx
Buying product certificate doesn't work, we need to fix it.
=> 🐛(frontend) retrieve product certificate order

src/frontend/js/components/ContractStatus/index.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/Contract/index.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/ContractFrame/index.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrderContract.spec.tsx
Feature PR: https://github.com/openfun/richie/pull/2096
=> ♻️(frontend) contract page cleanup

src/frontend/js/components/ContractFrame/index.sign.spec.tsx, src/frontend/js/components/ContractFrame/index.tsx, src/frontend/js/components/ContractStatus/index.tsx, src/frontend/js/components/DownloadContractButton/index.spec.tsx, src/frontend/js/components/SignContractButton/index.omniscientOrders.spec.tsx, src/frontend/js/components/SignContractButton/index.spec.tsx, src/frontend/js/components/SignContractButton/index.tsx, src/frontend/js/pages/TeacherDashboardContractsLoader/TeacherDashboardContracts/index.tsx, src/frontend/js/types/Joanie.ts, src/frontend/js/utils/test/factories/joanie.ts, src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrderContract.spec.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrderContract.useUnionResource.cache.spec.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderStateMessage/index.spec.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/utils/order.ts
Contract are signed twice, once by the studdent then once by a
organization owner.
Here we update our Contract type
=> 🏷️(frontend) update Contract

src/frontend/js/types/Joanie.ts, src/frontend/js/utils/StringHelper/index.spec.tsx, src/frontend/js/utils/StringHelper/index.ts, src/frontend/js/widgets/Dashboard/components/DashboardAvatar/_styles.scss, src/frontend/js/widgets/Dashboard/components/DashboardAvatar/index.spec.tsx, src/frontend/js/widgets/Dashboard/components/DashboardAvatar/index.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/index.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/stories.mock.ts, src/frontend/js/widgets/Dashboard/components/DashboardSidebar/_styles.scss, src/frontend/js/widgets/Dashboard/components/DashboardSidebar/index.tsx, src/frontend/js/widgets/Dashboard/components/TeacherDashboardOrganizationSidebar/index.tsx, src/frontend/js/widgets/Dashboard/components/TeacherDashboardProfileSidebar/components/OrganizationLinks/_styles.scss, src/frontend/js/widgets/Dashboard/components/TeacherDashboardProfileSidebar/components/OrganizationLinks/index.spec.tsx, src/frontend/js/widgets/Dashboard/components/TeacherDashboardProfileSidebar/components/OrganizationLinks/index.tsx
Fix several layout issues on Dashboard Teacher views
| Before | After |
|<img width="350" alt="avatar-abbr-before" src="https://github.com/openfun/richie/assets/9265241/61c7b1b4-c547-4e3a-9d5d-7e8535ef0d99">|<img width="350" alt="avatar-abbr-after" src="https://github.com/openfun/richie/assets/9265241/7e7d8fa4-89ef-44be-ab36-d791fe66dc84">|
|<img width="350" alt="orga-links-before" src="https://github.com/openfun/richie/assets/9265241/3e479a2f-f388-44e3-92e3-b02f529ae794">|<img width="350" alt="orga-links-after" src="https://github.com/openfun/richie/assets/9265241/495b963d-d563-4064-b1b0-4ec52d5624c0">|
|<img width="350" alt="orga-view-abbr-before" src="https://github.com/openfun/richie/assets/9265241/d0eca24c-85f4-4fee-8261-9df91e6c5a61">|<img width="350" …
=> ✨(frontend) add abbreviate method to StringHelper

src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.stories.tsx
issue: https://github.com/openfun/richie/issues/2196
This story was broken since course product item retrieve a courseProductRelation instead of a product.
There three more stories with different order states: PENDING, SUBMITED, VALIDATED
=> 🧑‍💻(frontend) fix CourseProductItem stories

src/frontend/js/components/TeacherDashboardCourseList/_styles.scss, src/frontend/js/components/TeacherDashboardCourseList/index.tsx, src/frontend/js/pages/TeacherDashboardCourseLoader/CourseRunList/index.spec.tsx, src/frontend/js/pages/TeacherDashboardCourseLoader/CourseRunList/utils.tsx, src/frontend/js/pages/TeacherDashboardTraining/index.spec.tsx, src/frontend/js/widgets/Dashboard/components/DashboardLayout/_styles.scss, src/frontend/js/widgets/Dashboard/components/DashboardSidebar/_styles.scss, src/frontend/js/widgets/Dashboard/components/TeacherDashboardCourseSidebar/index.spec.tsx, src/frontend/js/widgets/Dashboard/components/TeacherDashboardCourseSidebar/index.tsx, src/frontend/js/widgets/Dashboard/components/TeacherDashboardProfileSidebar/components/OrganizationLinks/_styles.scss, src/frontend/scss/colors/_theme.scss, src/frontend/scss/components/_content.scss
Little relifts and fixes of some dashboard ui
|<img width="350" alt="after-10" src="https://github.com/openfun/richie/assets/9265241/68511c35-e30e-4d22-98f4-204c6947317f">|<img width="350" alt="before-10" src="https://github.com/openfun/richie/assets/9265241/f12f69c6-463f-4a1b-a192-f0d6858a75e7">|
|<img width="350" alt="after-30" src="https://github.com/openfun/richie/assets/9265241/5a67e2e0-f360-41db-b5ac-a233d981e935">|<img width="350" alt="before-30" src="https://github.com/openfun/richie/assets/9265241/59c86c3a-b658-4383-a516-b595b6848a6b">|
|<img width="600" alt="after-20" src="https://github.com/openfun/richie/assets/9265241/0f181e52-c89c-4d9b-a0ea-9979f38150ca"><img width="600" alt="after-21" …
=> 💄(frontend) little relifts and fixes of some dashboard ui

src/frontend/.storybook/preview.tsx, src/frontend/js/components/AddressesManagement/AddressForm/index.stories.tsx, src/frontend/js/pages/DashboardAddressesManagement/DashboardCreateAddress.stories.tsx, src/frontend/js/pages/DashboardAddressesManagement/DashboardEditAddress.stories.tsx, src/frontend/js/pages/DashboardAddressesManagement/index.stories.tsx, src/frontend/js/widgets/Dashboard/components/TeacherDashboardOrganizationSidebar/index.stories.tsx
Since cunnigham is used, most of our stories were broken because CunninghamProvider was missing.
=> 🧑‍💻(frontend) fix storybook

.gitignore, src/frontend/js/api/lms/dummy.ts, src/frontend/js/settings.dev.dist.ts, src/frontend/js/settings.ts
We've to change dev user during development and it's common to forget about it on commit.
To avoid redundant task of switching dev user on each new branch, we moved this choice in an ignored file `settings.dev.ts`
* copy `settings.dev.dist.ts` as `settings.dev.ts`
* choose your user in `settings.dev.ts`
* enjoy
=> 🧑‍💻(frontend) ignore dev user selection

src/frontend/js/settings.dev.dist.ts, src/frontend/js/settings.ts
I break this dev settings logic by fixing default import on previous commit.
It result on a infinite spinner when trying to login.
=> 🐛(frontend) fix dev settings loading

CHANGELOG.md
I realized that one of previously added entry was in the wrong section.
=> 📝(changelog) fix changelog

CHANGELOG.md, src/frontend/js/components/ContractStatus/index.spec.tsx, src/frontend/js/components/ContractStatus/index.tsx
Fix typo in ContractStatus component
=> ✏️(front) fix typo in ContractStatus component

src/frontend/js/api/joanie.ts, src/frontend/js/components/DownloadContractButton/index.spec.tsx, src/frontend/js/components/DownloadContractButton/index.tsx, src/frontend/js/hooks/useContractArchive/index.download.spec.tsx, src/frontend/js/hooks/useContractArchive/index.ts, src/frontend/js/hooks/useDownloadCertificate/index.spec.tsx, src/frontend/js/hooks/useDownloadCertificate/index.tsx, src/frontend/js/utils/download.ts, src/frontend/js/widgets/Dashboard/components/DashboardItem/Certificate/index.spec.tsx, src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/components/CourseProductCertificateItem/index.spec.tsx
We had the same code at three different places. It's a easy pick to
normalize this browser download feature.
=> ♻️(frontend) normalize download file feature

src/frontend/jest/setup.ts, src/frontend/js/components/ContractFrame/AbstractContractFrame.spec.tsx, src/frontend/js/components/DjangoCMSTemplate/index.spec.tsx, src/frontend/js/components/Modal/index.spec.tsx, src/frontend/js/components/PurchaseButton/index.spec.tsx, src/frontend/js/components/SaleTunnel/index.spec.tsx, src/frontend/js/components/SignContractButton/index.omniscientOrders.spec.tsx, src/frontend/js/components/SignContractButton/index.spec.tsx, src/frontend/js/pages/DashboardContracts/index.spec.tsx, src/frontend/js/pages/DashboardOrderLayout/index.spec.tsx, src/frontend/js/pages/TeacherDashboardContractsLayout/TeacherDashboardContracts/index.spec.tsx, src/frontend/js/pages/TeacherDashboardContractsLayout/components/ContractActionsBar/index.spec.tsx, src/frontend/js/pages/TeacherDashboardContractsLayout/components/SignOrganizationContractButton/index.spec.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Contract/index.spec.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.spec.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.spec.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrderContract.spec.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrderContract.useUnionResource.cache.spec.tsx, src/frontend/js/widgets/Search/components/SearchFilterGroup/index.spec.tsx, src/frontend/js/widgets/Search/components/SearchFilterGroupModal/index.spec.tsx, src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.spec.tsx
Our modal needs a div with a specific id to be render. This test configuration is better now in a global configuration than repeted everywhere.
=> 🧑‍💻(frontend) jest/setup: create modal div

src/frontend/js/utils/test/wrappers/JoanieAppWrapper.tsx
router props weren't correctly given to RouterWrapper
=> 🐛(frontend) fix test wrapper props

.gitignore, src/frontend/js/api/lms/dummy.ts, src/frontend/js/settings.dev.dist.ts, src/frontend/js/settings/index.ts, src/frontend/js/settings/settings.dev.dist.ts, src/frontend/js/settings/settings.prod.ts, src/frontend/js/settings/settings.test.ts
All settings may be changeable in development without interfering with
production settings.
=> 🧑‍💻(frontend) Split settings file

src/frontend/js/hooks/useUnionResource/index.spec.tsx, src/frontend/js/hooks/useUnionResource/index.ts
rebased on https://github.com/openfun/richie/pull/2308
fix a bug where when stack.length === 0, invalidate the query will not refetch.
=> 🐛(frontend) useUnionResource refetch on invalidate

src/frontend/js/hooks/useUnionResource/index.ts
=> ✏️(frontend) typo

CHANGELOG.md, src/frontend/js/api/joanie.ts, src/frontend/js/types/Joanie.ts, src/frontend/js/utils/CertificateHelper/index.spec.ts, src/frontend/js/utils/CertificateHelper/index.ts, src/frontend/js/utils/test/factories/joanie.ts, src/frontend/js/widgets/Dashboard/components/DashboardItem/Certificate/index.spec.tsx, src/frontend/js/widgets/Dashboard/components/DashboardItem/Certificate/index.tsx
Some certificate can be linked to an enrollment. Currently we do not manage
those cases so an error is displayed when we meet this use case.
=> 🐛(frontend) manage certificate linked to enrollment

CHANGELOG.md, src/richie/apps/courses/factories.py, src/richie/apps/courses/settings/__init__.py, src/richie/apps/courses/templates/courses/cms/course_detail.html, tests/apps/courses/test_templates_course_detail_rdfa.py, tests/apps/courses/test_templates_course_detail_rendering.py
Course now have accessibility and required equipment sections.
resolve #2087
=> ✨(backend) add course sections

CHANGELOG.md, src/frontend/js/hooks/useContractArchive/index.ts, src/frontend/js/pages/TeacherDashboardContractsLayout/components/BulkDownloadContractButton/index.spec.tsx, src/frontend/js/pages/TeacherDashboardContractsLayout/components/BulkDownloadContractButton/index.timer.spec.tsx, src/frontend/js/pages/TeacherDashboardContractsLayout/components/BulkDownloadContractButton/index.tsx, src/frontend/js/pages/TeacherDashboardContractsLayout/components/ContractActionsBar/index.spec.tsx, src/frontend/js/pages/TeacherDashboardContractsLayout/components/ContractActionsBar/index.tsx, src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useCheckContractArchiveExists/index.spec.tsx, src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useCheckContractArchiveExists/index.tsx, src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useDownloadContractArchive/contractArchiveLocalStorage.spec.ts, src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useDownloadContractArchive/contractArchiveLocalStorage.ts, src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useDownloadContractArchive/index.spec.tsx, src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useDownloadContractArchive/index.tsx, src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useHasContractToDownload/index.tsx, src/frontend/js/types/Joanie.ts, src/frontend/js/widgets/Dashboard/components/TeacherDashboardCourseSidebar/index.spec.tsx, src/frontend/js/widgets/Dashboard/utils/teacherDashboardPaths.tsx, src/frontend/js/widgets/Dashboard/utils/teacherRoutes.tsx
joanie is now able to generate contracts archive for given organization
and courseProductRelation ids.
Here we implemente this feature on the course details pages
=> ✨(frontend) Allow download of training contracts

CHANGELOG.md, src/frontend/js/api/lms/dummy.ts, src/frontend/js/api/lms/openedx-fonzie.ts, src/frontend/js/components/Form/Form/index.tsx, src/frontend/js/components/Form/utils.ts, src/frontend/js/components/OpenEdxFullNameForm/index.stories.tsx, src/frontend/js/components/OpenEdxFullNameForm/index.tsx, src/frontend/js/components/SaleTunnel/components/SaleTunnelStepPayment/_styles.scss, src/frontend/js/components/SaleTunnel/components/SaleTunnelStepPayment/index.spec.tsx, src/frontend/js/components/SaleTunnel/components/SaleTunnelStepPayment/index.tsx, src/frontend/js/components/SaleTunnel/index.stories.tsx, src/frontend/js/hooks/useOpenEdxProfile/index.ts, src/frontend/js/hooks/useOpenEdxProfile/utils/index.spec.ts, src/frontend/js/hooks/useOpenEdxProfile/utils/index.ts, src/frontend/js/pages/DashboardCreditCardsManagement/DashboardEditCreditCard.spec.tsx, src/frontend/js/pages/DashboardOpenEdxProfile/index.spec.tsx, src/frontend/js/pages/DashboardOpenEdxProfile/index.stories.tsx, src/frontend/js/pages/DashboardOpenEdxProfile/index.tsx, src/frontend/js/types/api.ts, src/frontend/scss/colors/_theme.scss, src/frontend/scss/objects/_form.scss
add a story for the sale tunnel. It make it easy to update it.
BEFORE
=====
AFTER
=> ✨(frontend) add fullname form in saletunnel 

src/frontend/jest/setup.ts, src/frontend/js/components/PurchaseButton/index.spec.tsx, src/frontend/js/components/SaleTunnel/index.spec.tsx, src/frontend/js/pages/DashboardAddressesManagement/DashboardCreateAddress.spec.tsx, src/frontend/js/pages/DashboardAddressesManagement/DashboardEditAddress.spec.tsx, src/frontend/js/pages/TeacherDashboardOrganizationCourseLoader/index.spec.tsx, src/frontend/js/pages/TeacherDashboardTraining/index.spec.tsx, src/frontend/js/utils/test/expectUrlMatchLocationDisplayed.ts, src/frontend/js/widgets/Dashboard/index.spec.tsx
Some test have unmached api calls and do not throw errors. This can lead to fake positive tests
=> 🧑‍💻(frontend) throw error on unmatched calls

CHANGELOG.md, src/frontend/js/pages/DashboardCertificates/components/CertificateList/index.tsx, src/frontend/js/pages/DashboardCertificates/index.spec.tsx, src/frontend/js/pages/DashboardCertificates/index.tsx, src/frontend/js/settings/settings.prod.ts
note: rebased on #2370 
On certificate page, we don't want user that only have regular
certificate to see an empty "attestation certificate" tab.
=> ✨(frontend) conditionaly show attestation tab

src/frontend/js/components/AddressesManagement/index.spec.tsx
Currently a frontend test often fails as it exceeds the default 5000ms timeout. This test contains lot of async user interactions so we increase the timeout delay for this given test.
https://app.circleci.com/pipelines/github/openfun/richie/10247/workflows/8601f877-4e41-4989-b51a-b862a20982f1/jobs/238418
=> ✅(frontend) fix timeout tests

CHANGELOG.md, src/frontend/js/components/OpenEdxFullNameForm/index.tsx, src/frontend/js/components/PurchaseButton/index.tsx, src/frontend/js/hooks/useDateFormat/index.spec.tsx, src/frontend/js/hooks/useDateFormat/index.tsx, src/frontend/js/utils/UserHelper/index.spec.ts, src/frontend/js/utils/UserHelper/index.ts, src/frontend/js/widgets/SyllabusCourseRunsList/components/SyllabusCourseRun/index.tsx
Bunch of fixes : 
- useDateFormat did not return empty string with null values
- PurchaseButton instantiated a hook conditionnaly
- Make UserHelper manages OpenEdxProfile object to extract name
=> 🐛(frontend) bunch of fixes

src/frontend/js/components/ContractFrame/AbstractContractFrame.spec.tsx, src/frontend/js/components/PaymentScheduleGrid/index.tsx, src/frontend/js/components/SaleTunnel/SaleTunnelInformation/index.tsx
A title was not localized. We fix that.
=> 🌐(frontend) add missing localized title

.circleci/config.yml
Setup circle ci test reporting.
=> ⚗️(circleci) test to setup tests report

.circleci/config.yml, cookiecutter/{{cookiecutter.organization}}-richie-site-factory/.circleci/src/jobs/@backend.yml, cookiecutter/{{cookiecutter.organization}}-richie-site-factory/docker-compose.yml, docker-compose-postgresql.yml, tests/apps/courses/test_models_licence.py, tests/plugins/large_banner/test_cms_plugins.py, tests/plugins/nesteditem/test_cms_plugins.py
We want to upgrade our Postgres version to 16.4
This PR update the CI and compose to match the expected version.
=> ⬆️(backend) update postgres to version 16.4

CHANGELOG.md, cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/requirements/base.txt, cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/frontend/package.json
Fix building site from cookie cutter:
```
ERROR [app collector 2/3] RUN python manage.py collectstatic --noinput
```
fix #2610
=> 🐛(cookiecutter): fix building site

CHANGELOG.md, src/frontend/js/widgets/SyllabusCourseRunsList/components/SyllabusCourseRun/index.tsx, src/frontend/js/widgets/SyllabusCourseRunsList/components/SyllabusCourseRunCompacted/index.tsx, src/frontend/js/widgets/SyllabusCourseRunsList/index.spec.tsx
We want to display the certificate and normal discount price for syllabus course run
Here's the proposed design for the component.
=> Display certificate and normal discount price for Syllabus Course Run
