openfun/richie

richie/settings.py

The lack of this setting constant and the default french language of our project
probably results in a edge case conflict where ironicaly `safe_translation_getter`
fails to choose language to translate

Add missing Django-parler setting

---

richie/js/data/genericReducers/resourceById/actions.ts
richie/js/data/genericReducers/resourceById/resourceById.spec.ts
richie/js/data/genericReducers/resourceById/resourceById.ts
richie/js/data/genericSideEffects/getResourceList/getResourceList.spec.ts
richie/js/data/genericSideEffects/getResourceList/getResourceList.ts

We encountered performance issues when putting hundreds of RESOURCE_ADD actions at once. Sidestep the issue by adding an action that can add multiple sibling resources at once.

Batch resourceById adds through a list action

---

apps/search/tests/test_viewsets_course.py
apps/search/viewsets/course.py
richie/js/components/courseGlimpseListContainer/courseGlimpseListContainer.spec.tsx
richie/js/components/searchFilter/searchFilter.spec.tsx
richie/js/components/searchFilter/searchFilter.tsx
richie/js/components/searchFilterGroup/searchFilterGroup.spec.tsx
richie/js/components/searchFilterGroup/searchFilterGroup.tsx
richie/js/components/searchFilterGroupContainer/searchFilterGroupContainer.spec.tsx
richie/js/components/searchFilterGroupContainer/searchFilterGroupContainer.tsx
richie/js/data/genericReducers/resourceList/resourceList.spec.ts
richie/js/data/genericReducers/resourceList/resourceList.ts
richie/js/data/genericSideEffects/getResourceList/actions.ts
richie/js/data/genericSideEffects/getResourceList/getResourceList.ts
richie/js/types/FilterDefinition.ts
richie/js/types/api.ts

Simply take the orgs & subjects from facets we received from the server and display them along with the proper count (if available) in the left sidebar.
NB: this required a slight API change to avoid overcomplicating things on the client side.

Display facet results in filter pane

---

apps/search/tests/test_viewsets_course.py
apps/search/viewsets/course.py

A call on `/api/v1.0/course?organizations=345` should filter courses to keep those that belong to organization 345.
-> `CourseListForm` should provide the value as `[ '345' ]`
The call filters courses that belong to organizations 3, 4 and 5.
-> `CourseListForm` provides the value as `'345'`
This was due to the way we sidestepped the magic list-eating behavior of QueryValueDict: we patched the values on the form after initializing it with an object that contains values taken from QueryValueDict with `v[0] if len(v) == 1 else v`.
Our own code replaces lists of 1 element with the element when the list is one element long. That is the expected behavior, *except* for `organizations` and `subjects`.
Patching them after the the form is initialized is too late: the form data is already set and …

Fix an issue on org & subject filters on course search

---

richie/settings.py

To run Richie in various environments for various clients on OpenShift, we need to be able the add flexibility in some settings, particularly the `ALLOWED_HOSTS` setting.
We decided to get the `ALLOWED_HOST` value from the environment, because it's easily manageable thanks to Ansible & OpenShift.

Update configurations to run Richie on OpenShift

---

.circleci/config.yml

* The hub job was broken since it wasn't docker loading the development
images archive.
* Debian images development cache was not targetting the good directory.
This had no consequences except increasing the cache size.

💚(circle) fix dev images cache & hub job

---

richie/js/components/searchFilter/searchFilter.tsx

The SearchFilter component's prop type signature was named SearchFilterContainerProps instead of SearchFilterProps by mistake.
Simply rename it.

🐛(front) fix SearchFilter component prop typing naming

---

richie/js/components/courseGlimpseListContainer/courseGlimpseListContainer.spec.tsx
richie/js/components/searchFilterGroupContainer/searchFilterGroupContainer.spec.tsx
richie/js/data/genericReducers/resourceList/resourceList.spec.ts
richie/js/data/genericReducers/resourceList/resourceList.ts
richie/js/data/genericSideEffects/getResourceList/actions.ts
richie/js/settings.d.ts
richie/js/settings.json
richie/js/types/api.ts

As we're not caching list responses anymore, we don't need the query key. On the other hand, we do need the current params to modify them as users interact with the filters.
Set defaults and clean up APIListCommonRequestParams.
It makes more sense to have them specified and then use Partial<> when we accept incomplete subsets.

Clean up resource list params in reducer

---

docker/files/usr/local/etc/gunicorn/richie.py

Current gunicorn configuration hides every log gunicorn might be able to stream. It would be helpful to be make them readable from OpenShift.
Refactor gunicorn configuration file to:
* decrease the log level to `INFO`
* redirect error logs to `stderr`
* redirect access logs to `stdout`
For a logging with Docker reference, see: https://docs.docker.com/config/containers/logging/

🔧(gunicorn) redirect logs to stdout

---

apps/search/tests/test_viewsets_courses.py
apps/search/viewsets/courses.py

The "terms" query does not support multiple different keys on the same query. This is not documented but the issue arose when we attempted it on our live ES instance.
We received a 500 error on the API (400 error from ES) when attempting to filter on orgs & subjects at the same time.
Use a "bool" query that allows us to combine multiple queries (and therefore 2 or more "terms" queries) into one.
It's also structurally cleaner as it allows us to express our constraints as arrays of invididual constraints
with a filter/ranking/necessity marker.
Docs: https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-bool-query.html

🐛(search) fix subjects+organizations terms queries in the same query

---

richie/js/bootstrap.ts
richie/js/components/courseGlimpseContainer/courseGlimpseContainer.spec.tsx
richie/js/components/courseGlimpseListContainer/courseGlimpseListContainer.spec.tsx
richie/js/components/searchFilter/searchFilter.spec.tsx
richie/js/components/searchFilter/searchFilter.tsx
richie/js/components/searchFilterGroup/searchFilterGroup.spec.tsx
richie/js/components/searchFilterGroup/searchFilterGroup.tsx
richie/js/components/searchFilterGroupContainer/computeNewFilterValue.spec.ts
richie/js/components/searchFilterGroupContainer/computeNewFilterValue.ts
richie/js/components/searchFilterGroupContainer/getFilterFromState.spec.ts
richie/js/components/searchFilterGroupContainer/getFilterFromState.ts
richie/js/components/searchFilterGroupContainer/searchFilterGroupContainer.spec.tsx
richie/js/components/searchFilterGroupContainer/searchFilterGroupContainer.tsx
richie/js/data/filterDefinitions/initialState.ts
richie/js/data/filterDefinitions/reducer.ts
richie/js/data/rootReducer.ts

This is the most basic form of the expected functionality for our frontend: let users pick a filter in the left sidebar, add it to the current search and get new, relevant search results. 
Build handlers for filter adding and removal in `SearchFilterGroupContainer` as it is the place where all the actionable information is gathered.
We then pass down the handlers through to `SearchFilter` which just uses them as click handlers and passes its own value back upstream.
Note: removal functionality was not included in the UI as this PR was already complicated enough as it is — and it would required us first to manage to show the active filters so they can be deactivated.
The same goes for facet management, which is separate logic: adding/removing should work the same no matter the actual …

Update the filters and trigger a request when the user clicks on a filter

---

richie/js/components/searchFilter/searchFilter.spec.tsx
richie/js/components/searchFilter/searchFilter.tsx
richie/js/components/searchFilterGroup/searchFilterGroup.spec.tsx
richie/js/components/searchFilterGroup/searchFilterGroup.tsx
richie/js/components/searchFilterGroupContainer/computeNewFilterValue.spec.ts
richie/js/components/searchFilterGroupContainer/computeNewFilterValue.ts
richie/js/components/searchFilterGroupContainer/searchFilterGroupContainer.spec.tsx
richie/js/components/searchFilterGroupContainer/searchFilterGroupContainer.tsx
richie/js/data/genericReducers/resourceList/resourceList.ts
richie/js/data/genericSideEffects/getResourceList/actions.ts
richie/js/data/genericSideEffects/pushHistoryState/actions.ts

Until now active filters were indistinguishable from inactive filters. There was no way to remove them either (apart from editing the URL).

List active filters to let users remove them

---

apps/search/tests/test_viewsets_courses.py
apps/search/viewsets/courses.py

We were having an issue where counts on facets were not what we expected, as counts for eg. the organizations facets were only including courses that matched the current organizations filter.
This made the facet counts pretty much useless for us.
We can instead facet on everything and use a specific filter for each aggregation, that reproduces the main query but omits the current dimension. See [a simple example](https://blog.madewithlove.be/post/faceted-search-using-elasticsearch/) for this pattern.

🐛(search) do not apply dimension D's filter when faceting on it

---

requirements/base.txt

This library was forgotten when removing Aldryn Newsblog

➖(requirements)Remove phonenumbers dependecy

---

richie/js/components/searchFilterGroup/searchFilterGroup.spec.tsx
richie/js/components/searchFilterGroup/searchFilterGroup.tsx
richie/js/data/filterDefinitions/reducer.ts
richie/js/settings.d.ts
richie/js/types/filters.ts
richie/js/utils/filters/getFilterFromState.spec.ts
richie/js/utils/filters/getFilterFromState.ts

As we worked on implementing autosuggest, we felt the need to improve some typings

Improve some typings for autosuggest

---

richie/js/utils/indirection/location.ts

Some native APIs can be hard to test, especially when they cannot be mocked or when they're used through assignment rather than by calling methods.
Add an almost transparent layer of indirection to make testing them a breeze.

Add an indirection layer for access to window.location

---

richie/js/utils/errors/handle.ts

We need some error handler to call from our code instead of throwing and calling it a day; that's especially true for async function where it's easy to leave failures uncaught.
Simply add a module with a `handle` export that logs errors to the console so we can start calling it. More comprehensive content such as reporting will be added later on as we work on #112 .

Add a generic error handler shell

---

apps/search/forms.py
apps/search/tests/test_viewsets_courses.py
apps/search/tests/test_viewsets_organizations.py
apps/search/tests/test_viewsets_subjects.py
apps/search/viewsets/courses.py
apps/search/viewsets/organizations.py
apps/search/viewsets/subjects.py

Courses use "match" as the param name for searches, whereas Subjects & Organizations use "name". This is unintuitive in the client-side as it would force us to maintain a list matching those param names to model names.
Change those so everyone uses "match".

Use "match" as the params name for basic searches

---

.circleci/config.yml

Every greenkeeper PR's CI fails while trying to install project dependencies as the `yarn.lock` file does not match dependencies listed in the `package.json` file.
Only install Greenkeeper-lockfile if it is not already installed. Previous implementation using `yarn add` was updating this dependency (and the lockfile), this was not intended as the resulting lockfile did not match the PR new `package.json` file.
Once the yarn.lock file has been updated by greenkeeper, we need to save this new version in the job's workspace to restore it during the installation job. Using the `--frozen-lockfile` option of `yarn install` ensures that our new lockfile is properly correlated with dependencies definition in the `package.json` file.

🐛(circle) fix yarn.lock file update

---

richie/js/components/SearchFilterGroup/SearchFilterGroup.spec.tsx
richie/js/components/SearchFilterGroup/SearchFilterGroup.tsx
richie/js/components/SearchFilterGroupContainer/SearchFilterGroupContainer.spec.tsx
richie/js/components/SearchFilterGroupContainer/SearchFilterGroupContainer.tsx
richie/js/integration_tests/filters.spec.tsx
richie/js/utils/filters/getActiveFilterValues.spec.ts
richie/js/utils/filters/getActiveFilterValues.ts

We used to handle both active filters and facets together, which caused us to display useless counts next to active filters, and more importantly to *not* display active filters that were not part of the facets.
Handling them separately helps us solve both these issues and also gets rid of some awkward code in `SearchFilterGroup`.
Pass active filter values separately from `SearchFilterGroupContainer`.

Rework active filters without facets

---

.circleci/config.yml
.gitlint
gitlint/gitlint_emoji.py

We want the commit history to be beautiful and normalized.

Add gitlint to enforce format of commit messages

---

.circleci/config.yml

Most of the time, the `lockfile-front` CI job refuses to update the `yarn.lock` file, but sometimes it works. When the `yarn.lock` file is not updated, the front-end workflow fails as we install dependencies using a frozen lockfile (it cannot be updated and dependencies listed in `package.json` should match those listed in the `yarn.lock` file).
As mentionned in `greenkeeper-lockfile` documentation [1], the `lockfile-front` job SHOULD be the FIRST job to run. I misunderstood this rule and thought that the first job of the front-end workflow would be sufficient. This was a mistake: as we have multiple parallel workflows, all other workflows' first job SHOULD require the `lockfile-front` job to ensure that it will always be the first job to run.
[1] …

🐛(circle) force lockfile-front as the first job

---

.gitlint

Pyup and Greenkeeper bots git commit title does not comply with our imposed pattern :cry: thus blocking each PR that the bot makes.
We choose to add a `git-lint` rule to ignore the linting of these commits to be able to reformat them using the "squash and merge" strategy while merging the PR.

💚(gitlint) ignore bots git message lint

---

gitlint/gitlint_emoji.py

Message displayed to when git commit message title did not match regexp could let
user think colon (":") was part of required format

🚸(gitlint) Improve UC1 error message

---

README.md

The isort linter was added to CircleCI lately but the github issue related to this was missing this documentation step to be completed.
Add mention about isort in readme under the "checking your code" section.
Closes https://github.com/openfun/richie/issues/139

Add mention about isort in readme

---

apps/courses/templates/courses/cms/_organization_detail.scss
apps/courses/templates/courses/cms/organization_detail.html
apps/courses/tests/test_templates_organization_detail.py
richie/static/scss/_main.scss
richie/static/scss/_variables.scss

The template for the organization detail view existed but did not include any CSS. 
Do some mobile-first layout work and add some basic styling so the default version of the website without any style override can be shown or used as an example directly.
Part 1/2 of work towards #228.
Part 2 will be to reuse `CourseGlimpse` component styles to have a proper list of related courses as shown in #228 — it just expanded the scope of this PR a little too much.

💄(courses) lay out & style the organization detail view

---

richie/settings.py

The js/css files are the result of a build done by webpack. Each time they are updated, browsers will get an outdated version from cache on the webserver or CDN which are difficult to invalidate.
By appending as querystring a unique identifier calculated on the content of the file we make sure browsers always get the updated version.
Use Django's `ManifestStaticFilesStorage` to collect static files (only in production settings).

Add cache invalidation mechanism for js/css files

---

sandbox/settings.py

Recent changes in the project tree moved indexers path, and we did not report new paths to the sandbox's `ES_INDEXES` setting.

🐛(settings) fix ES_INDEXES paths

---

setup.cfg

During Richie's packaging, we removed requirements files in favor of a setup.cfg configuration. During this step, pyup contraints on dependencies have been dropped.
As pyup seems to support `setup.cfg` format, let's try to use the same syntax as for requirements, _e.g._ `... # pyup: <2.0` (this is an undocumented feature).

📌(pyup) restore dependency contraints

---

.babelrc.js
package.json
src/richie-front/js/components/CourseGlimpse/CourseGlimpse.spec.tsx
src/richie-front/js/components/CourseGlimpse/CourseGlimpse.tsx
src/richie-front/js/components/SearchFilter/SearchFilter.spec.tsx
src/richie-front/js/components/SearchFilter/SearchFilter.tsx
src/richie-front/js/components/SearchFilterGroup/SearchFilterGroup.spec.tsx
src/richie-front/js/components/SearchFilterGroup/SearchFilterGroup.tsx
src/richie-front/js/components/SearchFilterGroupContainer/SearchFilterGroupContainer.spec.tsx
src/richie-front/js/components/SearchSuggestField/SearchSuggestField.spec.tsx
src/richie-front/js/components/SearchSuggestField/SearchSuggestField.tsx
src/richie-front/js/components/SearchSuggestFieldContainer/SearchSuggestFieldContainer.spec.tsx
src/richie-front/js/index.tsx
src/richie-front/js/integration_tests/filters.spec.tsx
src/richie-front/js/settings.ts
src/richie-front/js/types/filters.ts
src/richie-front/js/types/searchSuggest.ts
src/richie-front/js/utils/commonMessages.ts
src/richie-front/js/utils/filters/getFilterFromState.spec.ts
src/richie-front/js/utils/filters/updateFilter.spec.ts
src/richie-front/js/utils/searchSuggest/getSuggestionsSection.ts
src/richie-front/js/utils/searchSuggest/getSuggestionsSections.spec.ts
src/richie-front/js/utils/searchSuggest/suggestionsFromSection.spec.ts
tsconfig.json
yarn.lock

This is step 3 & 4 of #89. We need to manage strings inside the JS app and to collect them for translation.

Manage translations through react-intl

---

Makefile
README.md
bin/_config.sh
bin/entrypoint
bin/exec
bin/pylint
bin/pytest
bin/run
docs/docker_development.md

While running Richie locally for development, we use to mount local volumes to running containers. As containers may create files, those last may have inappropriate permissions depending on the user running in the container (_e.g._ root). 
To avoid permission issues we need to map local user with the running container user:

Fix docker user for development

---

Makefile

When starting to work on the project (or after a `git clean`), if the `data` directory does not exist, it is created by `docker-compose` and belongs to the `root` user; leading to permission issues while trying to collect statics or upload media.

🐳(compose) fix permissions for data directory

---

.circleci/config.yml
docker/compose/ci/docker-compose.yml
docker/compose/test/docker-compose.yml
docker/images/dev/Dockerfile

As discussed in #279, running tests in the container using the root user may hide potential issues of the application (e.g. permission-related issues). We need to make our test suite more reliable and trustworthy by running the test suite using a non-privileged user.
Fix #282

🐳(user) use an un-privileged user in tests

---

src/richie/apps/persons/templates/persons/plugins/person.html
src/richie/apps/persons/tests/test_person_plugin.py

Due to Page extension relation, Person plugin template does not reach
commonly the Person resume attribute value so it is not marked as safe
content, leading to escaped HTML.
This little fix just add the `|safe` filter to the resume variable
usage.

🐛(person) fix Person plugin template escaped html

---

src/richie/apps/core/models.py
src/richie/apps/courses/cms_wizards.py
src/richie/apps/courses/models.py
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/organization_detail.html
src/richie/apps/courses/templates/courses/cms/subject_detail.html
tests/apps/courses/test_models_course.py
tests/apps/courses/test_models_organization.py
tests/apps/courses/test_models_subject.py
tests/apps/persons/test_person_plugin.py

Many to many relations between page extenions are copied when a page is published. We end up with links between draft and published versions of the page extension but the draft version should serve as the reference. I added tests to evidence the bug and then fixed it.
TODO: improving tests on the html generated by our templates will be done in https://github.com/openfun/richie/pull/288

Fix getting linked page extensions via many-to-many

---

.babelrc.js
.circleci/config.yml
.gitignore
Dockerfile
Makefile
i18n/scripts/upload.js
package.json
src/richie-front/js/settings.ts
yarn.lock

Generate a POT file from our strings and upload strings to our SaaS translation manager.
🚫 install & configure the Crowdin CLI tool (abandoned because it introduced a dependency to java in the project and that's not something we're ready for)
Note: penultimate step towards #89

Upload frontend strings to crowdin

---

Makefile
src/richie/apps/core/models.py
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/organization_detail.html
src/richie/apps/courses/templates/courses/cms/organization_fragment.html
src/richie/apps/courses/templates/courses/cms/subject_detail.html
tests/apps/courses/test_templates_course_detail.py
tests/apps/courses/test_templates_organization_detail.py
tests/apps/courses/test_templates_subject_detail.py
tests/apps/persons/test_person_plugin.py

When checking if a page is published, we were just checking the existence of a public version of the page. It turns out that pages can be published and later unpublished... so the public version of a page may exist but not be in a "published" status. 
Furthermore, the publication of a page is handled language by language.

Fix checking if page extension is published

---

sandbox/settings.py
src/richie/apps/search/exceptions.py
src/richie/apps/search/index_manager.py
src/richie/apps/search/indexers/courses.py
src/richie/apps/search/indexers/organizations.py
src/richie/apps/search/indexers/subjects.py
src/richie/apps/search/utils/es_indices.py
src/richie/apps/search/viewsets/courses.py
src/richie/apps/search/viewsets/organizations.py
src/richie/apps/search/viewsets/subjects.py
tests/apps/search/test_index_manager.py
tests/apps/search/test_indexers_courses.py
tests/apps/search/test_indexers_organizations.py
tests/apps/search/test_indexers_subjects.py
tests/apps/search/test_viewsets_organizations.py
tests/apps/search/test_viewsets_subjects.py

As we were working on #292, we noticed some necessary improvements we should undertake before getting to the heart of the matter.

Prepare to implement default filters on the api

---

.circleci/config.yml

If the current working directory that hosts the workspace with richie's dist packages is not mounted in the container that needs to push them to PyPI, the PyPI job fails.
Mount the working directory in `/app` and work with CircleCI user ID to upload build packages to PyPI.

🐛(pypi) fix package upload from the CI

---

.circleci/config.yml
tests/apps/courses/test_templates_subject_detail.py
tests/apps/search/test_indexers_courses.py
tests/apps/search/test_indexers_subjects.py
tests/apps/search/test_viewsets_organizations.py
tests/apps/search/test_viewsets_subjects.py

A recent commit reactivated linting on the tests directory but only in the Makefile. I forgot to reactivate it in the CI configuration so we had discrepancies between what the CI and what our locale linting were saying.

🐛(circleci) fix linting of tests directory

---

env.d/development

There was an issue with logs for the app container (from django) being delayed, which slowed down some development tasks. This was due to python buffering its console output.
Disable python console buffering through the relevant environment variable.

Improve logging in the app container

---

Makefile
docker/images/dev/Dockerfile

When starting the development stack using the `docker-compose up` command, compose uses the image default `USER` to run defined command (_e.g._ `10000` in the "dev" Dockerfile). Hence the Django development server runs using this user ID. This is an issue when developing with local volumes mounted in this container, because, the server may want to create new files in these volumes and unfortunately the running user (with UID `10000`) has no permission to write in the aforementioned volumes.
Fix #305

🐛(docker) use local user ID in the dev image

---

src/richie/apps/search/defaults.py
src/richie/apps/search/forms.py
src/richie/apps/search/indexers/courses.py
src/richie/apps/search/viewsets/courses.py
tests/apps/search/test_indexers_courses.py
tests/apps/search/test_viewsets_courses.py

We need to implement some default filters for development in the sandbox and to enable providers to quickly have an up-and-running search experience when they start working with Richie.
We wanted these default filters to be easy to extend/replace without having to re-do or copy/pasta the whole query building logic which can be daunting for people unfamiliar with ES.
Provide a way to add filters through settings (and some useful defaults for them) by specifying key/value pairs along with form fields to validate them and actual ES query fragments to use them.
Note: we still have some work to complete this PR:
Closes #292.
Follows #302 & #307.

Implement custom+default filters on the api

---

setup.cfg

Django 1.11.14 has a security issue: https://docs.djangoproject.com/en/2.1/releases/1.11.15
and pyup.io/safety-ci will not let us merge any PR until requirements are fixed

⬆️(django) upgrade Django to 1.11.15

---

package.json

`tslint` was not running on `.tsx` files, which constitute most of our project. 
No errors had slipped through thanks to editor support but this actually fixes tslint enforcement on the CI side.

Fix tslint linter path glob

---

tslint.json

`tslint` recently changed the default (or added a default) for property names in objects. This clashes with the standard way to write JS and with what prettier is enforcing.
We also want to keep the rules consistent between our projects. See [the related PR in marsha](https://github.com/openfun/marsha/pull/38).
Change it to only allow quotes when they are strictly necessary.
Also remove the one-line rule for if/else clauses, which makes no sense when writing branching logic with comments that can't be coerced easily into a switch.

🔧(tslint) update tslint rules for prettier & style consistency

---

Makefile
package.json

Right now we don't have easy-to-use commands to run prettier in write mode on the codebase (the CI just runs it in list-different mode).
Add a "yarn prettier" command that can be run directly by end-users with local installs of yarn & dependencies, and a corresponding lint-front-prettier in Makefile to enable users to run the same
from the container.

Add package.json/makefile commands to run prettier

---

src/richie/apps/core/management/commands/create_demo_site.py
src/richie/apps/courses/factories.py
tests/apps/courses/test_factories_course_run.py
tests/apps/courses/test_models_course_glimpse_date.py

On the demo site, all course runs were created in the future. We want to have course runs in different states: some open, and some future, past, open or closed for enrollment, etc.
I chose the option to loosen the factory and had to fix a few tests as a consequence.

Diversify course runs on the demo site

---

src/richie/apps/courses/templates/courses/cms/_course_detail.scss
src/richie/apps/courses/templates/courses/cms/course_detail.html

Course detail teaser take full width and takes too much place.
Also there is some responsive issues.
Teaser video has been moved to aside column, title placed in main
column, responsive issues has been fixed and some minor color
adjustment on content rows.

💄(layout) push course teaser to aside column and fix responsive

---

src/richie/apps/core/factories.py
src/richie/apps/core/management/commands/create_demo_site.py
src/richie/apps/courses/factories.py

When Licence has been created, their logo image was left to the
'FilerImageFactory' which generate a simple plain color and dummy
image.
Licence factory has been changed to use a new Subfactory for image
file to randomly select a licence logo from fixtures.

🐛(licence) fill Licence with a sample image from fixtures

---

src/richie-front/scss/_main.scss
src/richie-front/scss/_variables.scss
src/richie/apps/courses/templates/courses/cms/_course_detail.scss
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/plugins/_licence_plugin.scss
src/richie/apps/courses/templates/courses/plugins/licence_plugin.html
tests/apps/courses/test_licence_plugin.py

Licence plugin from course detail did not have any styles. Also
teaser container from course detail take too much width.
This commit improves licence plugin look with some styles and
revised HTML structure in templates. Also course detail teaser
container include some padding.

💄(layout) improve licence plugin look and course detail teaser

---

src/richie/apps/courses/templates/courses/cms/_course_detail.scss
src/richie/apps/courses/templates/courses/cms/course_detail.html
tests/apps/courses/test_templates_course_detail.py

Actually subjects in Course detail is just a simple list of subject
item.
This commit change course detail template and styles so the subject
now look like tiny badges under Course title. Tests has been update
to match against template changes.

💄(layout) style course subject to look as badges

---

src/richie-front/js/components/SearchFilterGroupContainer/SearchFilterGroupContainer.spec.tsx
src/richie-front/js/components/SearchSuggestField/SearchSuggestField.spec.tsx
src/richie-front/js/components/SearchSuggestFieldContainer/SearchSuggestFieldContainer.spec.tsx
src/richie-front/js/integration_tests/filters.spec.tsx
src/richie-front/js/utils/filters/updateFilter.spec.ts
src/richie-front/js/utils/searchSuggest/getSuggestionsSections.spec.ts

Using "import * as {name}" and then patching {name} with a spy is practical but it is not spec compliant. For example, it did not work in our previous karma + jasmine environment with babel 7.
Just use jest mocks instead, which are more explicit and do work out of the box.

Use jest mocks instead of "import * as" patches

---

src/richie-front/js/utils/filters/getActiveFilterValues.spec.ts
src/richie-front/js/utils/filters/getActiveFilterValues.ts
src/richie-front/js/utils/filters/getFilterFromState.spec.ts
src/richie-front/js/utils/filters/getFilterFromState.ts

deal with a point in #376 
> The filters are not implemented nor the facets displayed for other dimensions than organizations & subjects. They are available on the backend and just need to be plugged in here.

Search missing facets

---

src/richie-front/js/utils/filters/getActiveFilterValues.ts
src/richie-front/js/utils/filters/getFilterFromState.ts
src/richie-front/js/utils/filters/isResourceBasedFilterGroupName.ts

we don't want to hardcode filter name anymore. This PR creates a type
guard to  detect if the filter name is a resource or hardcoded one.
In PR #384 @mbenadda suggests to stop harcoding filter name in each switch statement. 
create a type guard allowing us to detect if the filter name is a `resource` or `hardcoded` one.

♻️ (front) create a type guard to check machine name in search filters

---

.pylintrc
src/richie/apps/courses/factories.py
src/richie/apps/courses/models/subject.py
src/richie/apps/courses/templates/courses/cms/subject_detail.html
tests/apps/courses/test_models_subject.py
tests/apps/courses/test_templates_organization_detail.py
tests/apps/courses/test_templates_subject_detail.py

This is a port to the organization detail page of what is done in PR https://github.com/openfun/richie/pull/397 for subjects ie display the related courses as course glimpse on the page.

Add course glimpses on the subject detail page

---

src/richie-front/js/utils/filters/getFilterFromState.spec.ts
src/richie-front/js/utils/filters/getFilterFromState.ts

When we're using facet counts to display a resource-based filter, we're only showing the top 10 available values in the list. (We'll be adding a UI element to filter using other values).
When there are no facet counts, we're displaying all possible values. This is not ideal as it might make the UI jitter on load & looks bad / makes it seem like there is a bug when we really are missing the facets.
Sample 10 random values from the full list in this case.

Limit resource-based filters to 10 displayed suggestions

---

src/richie-front/js/components/SearchSuggestField/SearchSuggestField.spec.tsx
src/richie-front/js/components/SearchSuggestField/SearchSuggestField.tsx
src/richie-front/js/components/SearchSuggestFieldContainer/SearchSuggestFieldContainer.spec.tsx
src/richie-front/js/components/SearchSuggestFieldContainer/SearchSuggestFieldContainer.tsx
src/richie-front/js/types/searchSuggest.ts
src/richie-front/js/utils/searchSuggest/getSuggestionsSection.ts
src/richie-front/js/utils/searchSuggest/suggestionHumanName.ts
src/richie-front/js/utils/searchSuggest/suggestionsFromSection.spec.ts
src/richie-front/js/utils/searchSuggest/suggestionsFromSection.ts

The course search bar in the courses page only offers suggestion for courses of resource-based filters. We also intend to support full-text search through both course title, metadata & syllabus.

Handle full text search

---

src/richie/apps/search/indexers/courses.py
src/richie/apps/search/indexers/organizations.py
src/richie/apps/search/indexers/subjects.py
src/richie/apps/search/utils/viewsets.py
src/richie/apps/search/viewsets/courses.py
src/richie/apps/search/viewsets/organizations.py
src/richie/apps/search/viewsets/subjects.py
tests/apps/search/test_indexers_courses.py
tests/apps/search/test_indexers_organizations.py
tests/apps/search/test_indexers_subjects.py
tests/apps/search/test_viewsets_courses.py

We generally want to promote code reuse throughout Richie. Here, we're trying to apply this idea to consumers of our indexers, and ViewSets in particular.
As we were working on adding new endpoints for autocompletion to our ViewSets, we realized the functionality would be the same for all of our resources.
However, we encountered two issues that prevented us from just using a Mixin to share this code:
- indexers had different names for ES to API object formatted method. 
- there was no way for our Mixins to access the indexers.

Enable code reuse in viewsets

---

sandbox/settings.py
src/richie/apps/search/indexers/courses.py
src/richie/apps/search/indexers/organizations.py
src/richie/apps/search/indexers/subjects.py
src/richie/apps/search/utils/es_indices.py
src/richie/apps/search/utils/indexers.py
src/richie/apps/search/utils/viewsets.py
src/richie/apps/search/viewsets/courses.py
src/richie/apps/search/viewsets/organizations.py
src/richie/apps/search/viewsets/subjects.py
tests/apps/search/test_index_manager.py
tests/apps/search/test_indexers_courses.py
tests/apps/search/test_indexers_organizations.py
tests/apps/search/test_indexers_subjects.py
tests/apps/search/test_utils_indexers.py
tests/apps/search/test_utils_viewsets.py

We're providing autocompletion functionality on the frontend. If we use the full-text search with standard/language analyzers, this gets us weird results.
We can get better results using ElasticSearch's builtin completion type. 
Use a separate endpoint to handle those requests separately from our general search endpoints.
Notes:
- to get the most predictable results, we had to enrich the data we  index in the completion fields;
- we used a Mixin to add the new autocomplete endpoints as it's basically the same code for all resources.

Open autocomplete endpoints

---

src/richie-front/js/data/genericSideEffects/getResourceList/getResourceList.ts
src/richie-front/js/data/rootReducer.ts
src/richie-front/js/settings.ts
src/richie-front/js/utils/searchSuggest/getSuggestionsSection.ts
src/richie-front/js/utils/searchSuggest/getSuggestionsSections.spec.ts

We opened autocomplete endpoints specifically to have better suggestion results in search boxes with the autosuggest UI.
Autocomplete as a functionality needs to be very easy to understand for users. They need to see at a glance why so or so result is being suggested.

Use autocomplete endpoints in main search autosuggest

---

src/richie/apps/courses/admin.py
src/richie/apps/courses/cms_toolbars.py
src/richie/apps/courses/factories.py
src/richie/apps/courses/models/organization.py
src/richie/apps/courses/models/subject.py
src/richie/apps/courses/templates/courses/cms/_course_detail.scss
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/course_run_detail.html
src/richie/apps/persons/tests/utils.py
tests/apps/courses/test_admin_page_snapshot.py
tests/apps/courses/test_cms_toolbars.py
tests/apps/courses/test_models_organization.py
tests/apps/courses/test_models_subject.py
tests/apps/persons/test_cms_toolbars.py

In previous commits, we re-engineered courses to accomodate snapshots (copies of a course in a given version that is placed as a child of the course). We now need to make it easy to generate the snapshot of a course.
If a course has course runs, the course runs should be moved as course runs of the new snapshot so that we keep track of the state of the course at the time these course runs were created.
While working on this, I encountered bugs for which I also propose fixes:
:point_right: add a unique sequence to the organization code.
:point_right: add a query filter to exclude snapshots and a test to secure this behavior.
Screenshot of the toolbar item visible on a course page:

Add a toolbar item to easily snapshot a course page

---

Dockerfile
docker/images/alpine/Dockerfile
package.json
setup.cfg
yarn.lock

Builds were broken on `master` due to two things:
- `flatmap-stream` versions were depublished due to a malicious code injection
- `pylint-django` was not compatible with a new version of `astroid`
The `flatmap-stream` issue also revealed us our Dockerfiles were pulling incorrect versions of dependencies.

Pin npm deps in dockerfiles

---

Makefile

Temporary files generated by the python packaging suite (egg-related), can lead to unexpected behavior during the bootstrap phase.
I've experimented this during the development Docker image build: no development dependencies definition were found (due to an old `setup.cfg` file version stored in an egg).

🔧(utils) add clean makefile rule

---

Dockerfile
docker/images/alpine/Dockerfile

When we've refactored the project tree, we forgot to fix the path to our WSGI configuration to run `gunicorn`.
We choose to change to the `sandbox` directory before running `gunicorn` to prevent PYTHONPATH-related issues (e.g. to import settings). Another strategy would have been to change the `WORKDIR`, but it also means that this would break our development images building, and it would be disturbing to default to the sandbox directory instead of the project's root.

🐛(docker) fix default command

---

Dockerfile
docker/images/alpine/Dockerfile
docker/images/alpine/dev/Dockerfile
docker/images/dev/Dockerfile

`python:3.6` base Docker image is bundled with a rather old release of pip (`9.0.3` vs `19.0.1` at the time of writing), leading to warnings during the build. 
Using the latest release of pip ensures that we benefit from latest performance improvements of the package manager.

⚡️(docker) upgrade pip to its latest release

---

src/richie-front/js/components/CourseGlimpse/CourseGlimpse.spec.tsx
src/richie-front/js/components/CourseGlimpse/CourseGlimpse.tsx
src/richie-front/js/components/SearchSuggestField/SearchSuggestField.spec.tsx
src/richie-front/js/components/SearchSuggestField/SearchSuggestField.tsx

We could not link to the courses / course runs from the course glimpses in seach before actual courses from the models were indexed in elasticsearch.
Ditto for the courses in suggestions.
Now that we have a real index, we can trivially add those links by using the new `absolute_url` field on Courses.
~NB: rebased on #450~

Add link to course run on search glimpses

---

src/richie/apps/courses/models/course.py
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/course_run_detail.html
src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html
src/richie/apps/search/indexers/courses.py
tests/apps/courses/test_models_course_glimpse_date.py
tests/apps/courses/test_models_course_run.py
tests/apps/courses/test_templates_course_detail.py
tests/apps/courses/test_templates_course_run_detail.py
tests/apps/search/test_indexers_courses.py

We need to harmonize the course glimpse displayed in search results with the course glimpse displayed elsewhere in the CMS. The first step to do this is to make the course run state available in the search API document.
* replace the `glimpse info` dictionary by a `CourseState` namedtuple,
* simplify state computation and make it coherent between the course state and the course run state, by computing the course state directly from the state of its course runs,
* allow computing the course run state directly from dates (ie without a course run instance) so that we can use this method also with Elasticsearch results,

Add course run state to the search API document

---

src/richie-front/js/components/SearchSuggestField/SearchSuggestField.spec.tsx
src/richie-front/js/components/SearchSuggestField/SearchSuggestField.tsx
src/richie-front/js/components/SearchSuggestFieldContainer/SearchSuggestFieldContainer.spec.tsx
src/richie-front/js/components/SearchSuggestFieldContainer/SearchSuggestFieldContainer.tsx
src/richie-front/js/utils/indirection/getSearchParam.ts

We were adding filters (such as facets or related resources) to the URL and history, but not full text search queries. They were only added to the URL when eg. a filter forced an update.
We also noticed the UI was no picking up the "query" param from the URL. We then added a call in the `<SearchSuggestField />` constructor to get it to initialize its state.
Finally, we needed to add a way for users to easily remove the full text query.
Closes #453.

Improve full text search experience

---

sandbox/settings.py

We used to take demo data from the fun-mooc API to populate our search index.
Now that we populate the index with real data from the models, we do not need these API endpoints in our settings anymore.

🔥(settings) remove dead demo settings

---

.circleci/config.yml
CHANGELOG.md
package.json
setup.cfg

This release indicates our intention to release richie 1.0.
Here are the core features that enabled us to reach this milestone:
- index the courses, organizations & subjects (now categories) in  ElasticSearch from the DjangoCMS models;
- create course snapshots to keep a history of the versions of a course Page throughout its various course runs;
- add full text search queries to the course Search;
- handle facet counts for all our filters in course Search;
- develop plugins for all essential parts: courses, organizations, categories, people, licences...
As we prepare to release, here are some improvements and fixes still ahead of us:
- allow nesting of categories, to let users customize "meta" categories and build their own subtrees;
- finish integrating the missing pages and improve the …

🔖(chore) bump release to 1.0.0-beta.0

---

.circleci/config.yml

We want to automatically deploy the master branch to our staging environment :tada: 
For this, we first need to keep a Docker image up-to-date with the master branch.
Modify the CircleCI configuration to also push Docker images to DockerHub for each build on the `master` branch and tags them `master` and `alpine-master`.
We also propose to stop publishing development images to DockerHub as they are only used locally by developpers.

Build docker image on master

---

CHANGELOG.md
src/richie/plugins/simple_text_ckeditor/forms.py
src/richie/plugins/simple_text_ckeditor/models.py

The `simple_text_ckeditor` plugin is not distributed as a python package, only templates are part of the packaged plugin.
```
$ touch src/richie/plugins/simple_text_ckeditor/__init__.py
```

🐛(package) fix simple_text_ckeditor plugin discoverability

---

CHANGELOG.md
package.json
setup.cfg

- Publish a `master` tagged docker image to DockerHub. It is supposed to reflect
the `master` branch state.
- The simple_text_ckeditor plugin was not discovered as a python module and thus
not distributed with Richie's python package.
- The organization logo maximal size is now restrained to its container size.
- We no longer publish development images to DockerHub as they appear useless.

🔖(chore) bump release to 1.0.0-beta.1

---

src/richie/apps/search/defaults.py
src/richie/apps/search/forms.py
src/richie/apps/search/indexers/courses.py
src/richie/apps/search/viewsets/courses.py
tests/apps/search/test_indexers_courses.py
tests/apps/search/test_viewsets_courses.py

We first implemented the languages filter as a hardcoded filter with predefined choices in `defaults.py`.
This was not perfect as it prevented us from using all the possible language choices from `settings.ALL_LANGUAGES`.
Instead, we can use a simple "terms" in ElasticSearch and treat the field exactly like we already do categories and organizations. 
The new `FILTERS_DYNAMIC` name also reflects the fact that it's not just resources.

♻️(search) refactor languages into a dynamic filter

---

src/richie/apps/courses/factories.py
tests/apps/courses/test_models_course_glimpse_date.py

The CourseRunFactory was randomly randomly failing to instantiate because random dates were picked incoherently.
I was using `toordinal` for datetimes. In fact, `toordinal` represents dates...
Using timestamps is more appropriate. I made sure that picking random datetimes was never incoherent any more and ran the tests in loop for several hours to try it out.

🐛(courserun) fix randomly failing tests linked to course run datetimes

---

src/richie/apps/core/helpers.py
src/richie/apps/core/management/commands/create_demo_site.py
src/richie/apps/courses/cms_wizards.py
src/richie/apps/courses/helpers.py
src/richie/apps/courses/models/category.py
src/richie/apps/courses/models/course.py
src/richie/apps/search/indexers/categories.py
src/richie/apps/search/indexers/courses.py
src/richie/apps/search/indexers/organizations.py
tests/apps/courses/test_cms_plugins_category.py
tests/apps/courses/test_helpers.py
tests/apps/courses/test_models_category.py
tests/apps/courses/test_models_course.py
tests/apps/search/test_indexers_categories.py
tests/apps/search/test_indexers_courses.py
tests/apps/search/test_indexers_organizations.py
tests/apps/search/test_viewsets_categories.py

We want to allow building category taxonomies in the CMS:
- multiple types of categories e.g. `Subject` versus `Level`
- nested categories e.g. `subject / maths / algebra` versus `level / expert`
We propose to use the DjangoCMS page tree to build the taxonomy. Everything is already there to do it... so we just had to:
Some side clean-up was made in the process:

Allow building category trees

---

src/richie/apps/search/indexers/courses.py
tests/apps/search/test_indexers_courses.py

We need to be able to surface courses with organization X or category Y when a user does a full-text search for X or Y.
Currently, this does not happen if X and/or Y do not appear in the syllabus or title of the course.

Surface courses with categories/organizations even in full-text searches

---

src/richie/apps/persons/models.py
tests/apps/persons/test_models_person.py

"get_full_name" method expected "person_title" was allways filled
although this field is not required resulting in an AttributeError
on page which display full name (at least the course detail).
Method has been fixed to support empty "person_title" and a test
has been modified to check this case.

🐛(person) fix Person.get_full_name when person_title is empty

---

src/richie/apps/search/defaults.py
src/richie/apps/search/indexers/courses.py
src/richie/apps/search/utils/filter_definitions.py
src/richie/apps/search/viewsets/courses.py
tests/apps/search/test_indexers_courses.py
tests/apps/search/test_utils_filter_definitions.py
tests/apps/search/test_viewsets_courses.py

Work on points 2, 3 & 4 of #476.
Generating the filters on the server-side, instead of reconstructing them from their disparate sources in the frontend, will help us scale them better with our needs.
Notably, it will be helpful when we reflect the category taxonomy in our search filters.
We decided to implement a series of `FilterDefinition` classes that manage the way filters interact with ElasticSearch, from ES query & aggs building to their consumption and the output of complete filter definitions.
Those are intended as defaults that can be removed, replaced or modified through settings.
The rest of #476 will be tackled in subsequent PRs, as we felt this one was large enough as it is, and it does not contain any breaking change.

Filter definitions

---

src/richie/apps/core/fields/multiselect.py

Automated test was sending this warning:
RemovedInDjango30Warning: Remove the context parameter from
MultiSelectField.from_db_value().
Support for it will be removed in Django 3.0
Edit MultiSelectField.from_db_value() to remove context parameter

🚨(core) remove warning concerning context in from_db_value

---

src/frontend/package.json

CircleCI job recently included prettier task on Sass sources
but it was not reflected on 'package.json' so this was not
effective on 'make lint-front'.
'package.json' has been modified to include new rules about Sass
sources so it is ready now to match to CircleCI job constraint.

🔧(project) update 'package.json' for sass rules with prettier

---

sandbox/settings.py
sandbox/templates/djangocms_link/button-caesura/link.html
src/richie/plugins/section/templates/richie/section/_highlighted_items.scss

Sections allowed every available plugins for inclusion while we
want to restrict available plugin to a little set. Also, Sections
need capacity to have a button link like "Read more".
This commits add placeholder plugins rules on homepage main
placeholder to only enable CoursePlugin, OrganizationPlugin,
CategoryPlugin and LinkPlugin inside a SectionPlugin. Also there is
a new template for LinkPlugin to correctly style a link include in
section.

💄(homepage) add homepage plugin constraints and enable LinkPlugin

---

sandbox/settings.py
sandbox/templates/richie/_single-column.scss
sandbox/templates/richie/single-column.html
src/frontend/scss/_main.scss

Currently there is only a "full width" page where content takes the
full width which is a little rude to make simple page like Annexes.
We need to add a new simple template which only include a single
column structure with a little vertical padding so we have a nicer
render for simple pages.

💄(project) add new template for a simple single column page

---

sandbox/settings.py
src/richie/apps/core/management/commands/create_demo_site.py
src/richie/plugins/section/templates/richie/section/_highlighted_items.scss
src/richie/plugins/section/templates/richie/section/highlighted_items.html

Homepage misses a "Persons" section like for Organizations, Courses,
etc..
This add some new styles on highlight section to correctly include
PersonPlugin and "create_demo_site" has been changed to include some
PersonPlugin in a section on homepage. 
Also include a little fix on "create_demo_site" that did not published again 
homepage after adding section and plugins.

💄(homepage) enable PersonPlugin on homepage sections

---

sandbox/settings.py

We stated about available plugins on single column template which
should not have every plugins enabled because some are useless and
some other duplicate features with other plugins.
This commit updates the main placeholder configuration for single
column template so we have a limited accurate set of available
plugins such as:
* TextPlugin (the default one from DjangoCMS) is disabled in profit
to our "CKEditorPlugin";
* GoogleMapPlugin is disabled because it's not really useful for
richie cases;
* PicturePlugin (Image) is disabled because CKEditor already allow
to include an image;
* Plugins for Courses, Organizations, Person and Category are only
allowed inside a SectionPlugin so they are correctly aligned;
* Link is only allowed inside a SectionPlugin to display them as a
Button with …

🔧(single-column) proper placeholder config for single column template

---

sandbox/settings.py
sandbox/templates/cms/plugins/text.html
sandbox/templates/djangocms_link/button-caesura/link.html
sandbox/templates/djangocms_video/full-width/video_player.html
sandbox/templates/richie/_single-column.scss
sandbox/templates/richie/single-column.html
src/frontend/scss/_main.scss
src/frontend/scss/components/_content.scss
src/richie/plugins/section/templates/richie/section/_highlighted_items.scss

Single column template allow a dozen of plugins but without any
proper layout, this is not really pretty.
This commit adds some styles around these plugins for single column
template so it have a nicer basic layout.

💄(single-column) add proper basic layout for available plugins 

---

CHANGELOG.md
setup.cfg
src/frontend/package.json

- Improved Docker image: now it does not ship with the project sources but only with runtime-required requirements (_i.e._ the sandbox and richie's package installed globally).
- Richie templates now live in core instead of sandbox.
- Reorganize the search frontend to support nested filters.
- The CI now effectively tests packaging issues.
- The `apps.core.fields` module is no longer missing from Richie's package.
- Fixed the `bin/pylint` script to work with the default database engine (PostgreSQL)
- Fixed `rebuild` & `bootstrap` Makefile rules

🔖(chore) bump release to 1.0.0-beta.3

---

CHANGELOG.md
sandbox/settings.py

The `collectstatic` management command is broken.

🐛(sandbox) remove STATICFILES_DIRS setting

---

src/richie/apps/courses/factories.py

Previous commit #535 has renamed cover fixture files but filenames has
not been updated to the new names. It didn't have any impact on
tests so it didn't triggered any error but it leads to
"create_demo_site" to fail.
This commit just fix "courses.factories.VIDEO_SAMPLE_LINKS" to fit
to the new names. I promise this fix has been correctly tested from
tests and "create_demo_site" so there will be no "fix fix" to
happen.

🐛(course) fix cover fixture for course factory

---

src/richie/apps/search/defaults.py
tests/apps/search/test_query_courses.py
tests/apps/search/test_viewsets_courses.py

Availability filter possiblities are not compatible between each other and should be selected independantly. 
Define the `availability` filter as a "drilldown".

🐛(courses) define availability as a drilldown filter

---

src/richie/apps/search/indexers/courses.py
tests/apps/search/test_indexers_courses.py

We forgot to exclude snapshots so they were getting indexed along side their parent course.

🐛(search) exclude snapshots from the courses index

---

src/frontend/package.json

Currently watch-sass does not see when a Sass source from an app is
changed and so it does not perform a new build. This would fix and
close #499 
Fix only add `--watch` arguments to nodemon command to define every
directory to watch instead of default behavior to watch only current
directory.

🐛(project) fix watch-sass for sources out of frontend directory

---

sandbox/settings.py
src/richie/apps/core/fields/multiselect.py

Translate languages used for course run through multiselect field.
They were untranslated up till now.
Make the values used in setting translatable.
Fix the multiselect field to return lower string values only after translation is done.

🌐(courses) translate course run language

---

src/richie/apps/core/management/commands/create_demo_site.py
src/richie/apps/courses/models/course.py
src/richie/apps/search/__init__.py
src/richie/apps/search/apps.py
src/richie/apps/search/index_manager.py
src/richie/apps/search/indexers/categories.py
src/richie/apps/search/indexers/courses.py
src/richie/apps/search/indexers/organizations.py
src/richie/apps/search/signals.py
tests/apps/courses/test_models_course.py
tests/apps/courses/test_models_course_run.py
tests/apps/search/test_index_manager.py
tests/apps/search/test_signals.py

Elasticsearch indices are created and populated via a management command. 
Up to now, any modification to the pages that was done after running this command were not reflected in the search indices.

Update Elasticsearch indices when a modification is published

---

docker-compose.yml
docker/compose/ci/mysql/docker-compose.yml
docker/compose/ci/postgresql/docker-compose.yml
docker/compose/development/mysql/docker-compose.yml
docker/compose/test/mysql/docker-compose.yml
docker/compose/test/postgresql/docker-compose.yml
src/richie/apps/core/factories.py
src/richie/apps/core/management/commands/create_demo_site.py
src/richie/apps/courses/factories.py
src/richie/apps/courses/helpers.py
src/richie/apps/search/defaults.py
src/richie/apps/search/filter_definitions/base.py
src/richie/apps/search/filter_definitions/courses.py
src/richie/apps/search/filter_definitions/mixins.py
src/richie/apps/search/forms.py
src/richie/apps/search/indexers/categories.py
src/richie/apps/search/indexers/courses.py
src/richie/apps/search/indexers/organizations.py
src/richie/apps/search/signals.py
src/richie/apps/search/viewsets/courses.py
tests/apps/search/test_filter_definitions.py
tests/apps/search/test_forms_search_courses.py
tests/apps/search/test_forms_search_items.py
tests/apps/search/test_indexers_categories.py
tests/apps/search/test_indexers_courses.py
tests/apps/search/test_indexers_organizations.py
tests/apps/search/test_query_courses.py
tests/apps/search/test_signals.py
tests/apps/search/test_viewsets_courses.py

For the moment, the category filter includes all categories. But since categories are now a taxonomy, we want to be able to declare several filter blocks that each target a specific part of the category taxonomy.
We also need to be able to render the taxonomy with its nested parents and children.

Allow nested categories and categories split on several filters

---

src/richie/apps/search/filter_definitions/courses.py
tests/apps/search/test_filter_definitions.py
tests/apps/search/test_query_courses.py

The include regex on indexable filters was cached on the first execution, whatever the result. 
In cases where the setting was set before the page was created and published, it could cause the method to cache the empty regex. In this case, we had to restart the app (on all pods in case of scaled deployments) for the include regex to be updated and for the filters to show correctly.
The solution applied here is to cache the result only when the page pointed by the setting is found. Until then, the cache is not set and we keep looking for the page.

🐛(search) improve caching of include regex on indexable filters

---

src/richie/apps/courses/models/category.py
src/richie/apps/courses/models/course.py
src/richie/apps/courses/models/organization.py
tests/apps/courses/test_cms_plugins_category.py
tests/apps/courses/test_cms_plugins_course.py
tests/apps/courses/test_cms_plugins_organization.py

Make sure there's only one version of each category found by category plugin
Fix issue #506 
Add an extra filter

🐛(category) fix duplicate category

---

README.md

The demo site is now available on https://richie.education so we should showcase it. 
Exclusive reference to Open edX does not make sense as Richie is completely agnostic of the LMS used below it.

📝(readme) add link to demo site, remove exclusive reference to Open edX

---

src/richie/apps/search/filter_definitions/courses.py
src/richie/apps/search/filter_definitions/mixins.py
tests/apps/search/test_filter_definitions.py
tests/apps/search/test_query_courses.py
tests/apps/search/test_query_courses_edge_cases.py

On indexable filters that are using a terms aggregation with a limit of 10 facet results, we could end up with a selected filter value not being included in the top 10 facets. Since the frontend now relies on the query result to display the filter boxes, the selected facet was not visible on the site anymore and could not be unselected...
Fixes https://github.com/openfun/richie/issues/504
We fix this problem by forcing specific facetting on the selected filter values. We choose to merge them with the facets returned by the terms aggregation. 
Note that it can lead to more than 10 facets but we think this allows keeping a significant number of new available choices.

🐛(search) make sure selected filter values are included in the result

---

sandbox/settings.py
src/richie/apps/core/context_processors.py
src/richie/apps/core/templates/richie/base.html

We need to reach current site object (from Django Site framework)
from every templates and so we will be able to use site name or
domain from templates.
This commit add and enable a new template context processor in
settings.

✨(project) add new context processor to add Site values in templates

---

src/richie/apps/courses/templates/courses/cms/category_detail.html
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/course_run_detail.html
src/richie/apps/courses/templates/courses/cms/organization_detail.html

Our support team reported that having 3 titles is confusing for teachers/marketers editing the page in frontend. Also, it is very rare that you will need to modify the html title and menu title specifically...
I propose to reduce to the main `title` field. For power users, it is still possible to edit the other titles via the "page settings" menu item...

🚸(courses) simplify page title frontend editing

---

sandbox/settings.py
src/richie/apps/courses/cms_plugins.py
src/richie/plugins/large_banner/cms_plugins.py
src/richie/plugins/plain_text/cms_plugins.py
src/richie/plugins/section/cms_plugins.py
src/richie/plugins/simple_text_ckeditor/cms_plugins.py

We were using the name FUN for the plugin group but it should be Richie as FUN is now just one of the websites we will build with Richie.
Rename `FUN_PLUGIN_GROUP` setting to `RICHIE_PLUGIN_GROUP`.

🎨(project) rename plugin group to richie

---

sandbox/settings.py

When we added the blog post plugin, we forgot to add it as a possible option on the home page.

🔧(blog) allow adding blog post plugins on the home page

---

Makefile

In the makefile when we want to use an other task we call it using the MAKE environment variable. When it's a prerequisite we should instead use rules dependencies
Refactor makefile and use prequisite tasks when possible.

Standardize the Makefile

---

Makefile

Rule "lint-back" call the rule "int-back-flake8" instead of
"lint-back-flake8" and so fail about unexisting rule.
This fix the typo so the "lint-back" is fully working again.

🐛(project) fix typo about 'lint-back-flake8' in Makefile

---

.circleci/config.yml

In the i18n PR I changed the path where the code is checkout and also the working directory. Doing this I break how the `node_modules` path is stored in cache.

refactor paths for frontend tasks in circleci

---

Makefile
src/richie/apps/core/management/commands/create_demo_site.py
src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
src/richie/apps/courses/templates/courses/cms/person_detail.html
tests/apps/core/test_commands_create_demo_site.py

It was not possible to edit the title of the blog post and person pages as easily as on the other types of pages.

Improve frontend editing for person and blog

---

MANIFEST.in

Some extensions were missing in MANIFEST.in file. Without them it is not
possible anymore to run collecstatic command.

🐛(manifest) add missing extensions in MANIFEST.in file

---

src/richie/apps/core/templates/menu/language_menu.html

We want to display the human name of the language in the current language on the `title` attribute of the links used to switch language.
Display the human name of the target language on each link.

🐛(i18n) display human languages on link title of language picker

---

sandbox/settings.py
src/frontend/scss/_main.scss
src/frontend/scss/elements/_images.scss
src/frontend/scss/templates/richie/section/_section.scss
src/richie/static/richie/css/ckeditor.css

Some configuration is missing to allow controlling the positioning
of images and image element (img and figure) behaviors are not
correct.
Related to issue #567
Here we add some basic image element styles so image have correct
basic behaviors on its alignments and with its container. Also we
disable some useless CKEditor features and fixed alignment buttons.
Note than since CKEditor edit render have its own CSS file to
customize render and since we need to use it to fix text alignment,
we forced its addition to the repository in richie static directory.

💄(layout) improve styling images and CKEditor usage

---

Dockerfile
docker/images/alpine/Dockerfile
docker/images/alpine/ci/Dockerfile
docker/images/alpine/dev/Dockerfile
setup.cfg

Richie is supposed to be distributed as a django third-party application, we needed to separate direct dependencies from runtime dependencies (sandbox).
Also, pinning direct dependencies for the app is not a good idea since we do not need to force a particular release when it's not required. This will ease the app installation by avoiding unresolvable dependencies.
Finally secondary dependencies should not be listed nor pinned as their constraints should be declared in primary dependencies' package.
Fixes #257, #259

📦(dependencies) refactor app/sandbox dependencies

---

.circleci/config.yml
src/frontend/scss/_main.scss
src/frontend/scss/_variables.scss

When using `richie-education` package as a library to build upon, having relative imports breaks derivated builds compilation. 
Since `node_modules` is in the `SASS_PATH`, we should derive dependency imports from this location.

🐛(frontend) fix scss relative imports

---

Dockerfile
src/frontend/package.json

The Dockerfile at root project is used to build the production image. We
should build the frontend application in production mode.

🐳(front) build frontend in production mode

---

src/richie/apps/search/defaults.py
tests/apps/search/test_query_courses_edge_cases.py

The section titles on the search page are not translating properly with gettext. 
You can see it on:
https://richie.education/fr/cours/?limit=999&offset=0
and this screenshot from my localhost:
Using ugettext_lazy instead fixes the problem.

🌐(search) replace gettext by ugettext_lazy in the defaults file

---

CHANGELOG.md
setup.cfg
src/frontend/package.json

- Add i18n tooling to export strings to Crowdin, retrieve and compile translations, for the  frontend and the backend. All translations are committed inside the project,
- Add links to switch language from the menu,
- Add social network badges in the footer, on course pages and on blog posts,
- Make categories configurable via the CMS, multi-dimensional and nested,
- Add blog post pages in a section called `News`,
- Update Elasticsearch indexes each time a page is modified and published,
- Improve fulltext search to match partial words,
- Add end-to-end tests for the search functionality to secure behavior.
- Make site look generic and deploy it to https://richie.education,
- Build frontend in production mode,
- Upgrade to Python 3.7,
- Switch to indexing courses instead of course runs,
- …

🔖(chore) bump release to 1.0.0-beta.4

---

.circleci/config.yml

We need a way to remind us to update the project's `CHANGELOG` when we submitting a PR.
One may believe that this is another annoying task, but the experience we had with Arnold's repository shows that it drastically speeds up the release cycle since almost everything has already been prepared upfront.
You may have noticed that this job **is not required** to merge a PR since the `CHANGELOG` does not have to be updated for every submitted changes.

👷(circleci) add check CHANGELOG job

---

CHANGELOG.md
src/frontend/babel.config.js
src/frontend/js/index.tsx
src/frontend/package.json
src/frontend/tsconfig.json
src/frontend/webpack.config.js
src/frontend/yarn.lock

I'm not confident with what I made in my [PR managing i18n](https://github.com/openfun/richie/pull/566) and I don't know if we can really rely with this kind of dynamic require.
So I look for an other solution using dynamic import in a more "typescript" way.
There are maybe negative points here :warning:  :
- the build now have lot of files and not only one `index.js`. This is because the build import every possible file "importable" and react-intl as a lot of `locale-data` files.
- I have switch the module resolution use in the typescript config, so I don't really know with which browser our code will work now, I found nothing about this in the documentation, but with babel maybe we have no compatibility regression.

Refactor dynamic import in frontend application

---

CHANGELOG.md
Dockerfile

Now that we've packaged the frontend application, we no longer require to copy the whole repository sources to compile the frontend.

🐳(frontend) improve build

---

src/frontend/scss/_main.scss
src/frontend/scss/mixins/_empty.scss
src/frontend/scss/templates/courses/cms/_blogpost_detail.scss
src/frontend/scss/templates/courses/cms/_category_detail.scss
src/frontend/scss/templates/courses/cms/_course_detail.scss
src/frontend/scss/templates/courses/cms/_organization_detail.scss
src/frontend/scss/templates/courses/cms/_organization_list.scss
src/frontend/scss/templates/courses/cms/_person_detail.scss
src/frontend/scss/templates/courses/plugins/_category_plugin.scss
src/frontend/scss/templates/courses/plugins/_organization_plugin.scss
src/frontend/scss/templates/richie/section/_section.scss
src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
src/richie/apps/courses/templates/courses/cms/category_detail.html
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/fragment_course_content.html
src/richie/apps/courses/templates/courses/cms/fragment_organization_main_logo.html
src/richie/apps/courses/templates/courses/cms/organization_detail.html
src/richie/apps/courses/templates/courses/cms/organization_list.html
src/richie/apps/courses/templates/courses/cms/person_detail.html
src/richie/apps/courses/templates/courses/plugins/organization.html

Empty pages must look good. More importantly, it should be obvious
how to fill them.
This is related to #542
This commit add some styles for media placeholders which don't have
any content, making them more consistent visually and without
perturbing layout. It cover categories, courses, blogposts,
organizations and persons.

💄(layout) improve how empty pages look

---

src/frontend/js/index.tsx
src/frontend/webpack.config.js

public path of splitted files in generated bundle by webpack is missing so the current url is used as a prefix and chunk are never loaded.
There is an other bug, the value returned by dynamic import was not the one expected. It returns an
object having only getters to lazy load what was imported. addLocaleData
function was excepting an array so we have to rebuild it by
extracting all the value of the returned object.
Description...

Fix webpack publicpath

---

CHANGELOG.md
src/frontend/js/components/SearchFilterGroup/SearchFilterGroup.spec.tsx
src/frontend/js/components/SearchFilterGroup/SearchFilterGroup.tsx
src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.spec.tsx
src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.tsx
src/frontend/js/types/filters.ts

The existing implementation of parent & children filters in the frontend expected filter values to have a "children" value that directly contained their own children values.
We decided to go another way with standard formatted paths that give us many benefits in terms of search but needed a different implementation in the frontend as parent filters need to fetch their children when the user requests them.
This also improves scalability.
Update the frontend to use the paths & make the appropriate requests.
WIP: missing tests
Fixes https://github.com/openfun/richie/issues/582

✨(search) implement parent & children filters in the frontend

---

CHANGELOG.md
sandbox/settings.py
src/richie/apps/core/management/commands/create_demo_site.py
src/richie/apps/courses/admin.py
src/richie/apps/courses/cms_wizards.py
src/richie/apps/courses/helpers.py
src/richie/apps/courses/models/__init__.py
src/richie/apps/courses/templates/courses/cms/course_run_detail.html
src/richie/apps/courses/templates/courses/cms/fragment_course_content.html
src/richie/apps/courses/templatetags/extra_tags.py
src/richie/apps/search/indexers/courses.py
src/richie/apps/search/indexers/organizations.py
tests/apps/courses/test_admin_page_snapshot.py
tests/apps/courses/test_cms_wizards_blogpost.py
tests/apps/courses/test_cms_wizards_category.py
tests/apps/courses/test_cms_wizards_course.py
tests/apps/courses/test_cms_wizards_course_run.py
tests/apps/courses/test_cms_wizards_organization.py
tests/apps/courses/test_cms_wizards_person.py
tests/apps/search/test_indexers_courses.py

Our support team gave a lot of feedback last week. The main point was that, because the page creation wizard proposes to create any type of page from anywhere on the site, they ended-up with wrong pages at the wrong place... They also felt that it was making things unnecessarily complicated to understand.
The idea of this PR is to make page creation contextual ie take into account the position on the site from which a page is created to:
- customize what buttons are shown or hidden on the page creation wizard,
- automatically place pages in the CMS tree or create plugins.
More precisely:
Other related improvements made on the basis of their feedback:
Fixes https://github.com/openfun/richie/issues/607
Fixes https://github.com/openfun/richie/issues/573

Simplify page creation

---

setup.cfg

During our latest refactoring of dependencies management, we thought unpinning direct dependencies would be enough for `pyup` to ignore them. We were wrong.

🔧(pyup) ignore direct dependencies pinning

---

CHANGELOG.md
src/frontend/js/components/SearchFilterGroup/SearchFilterGroup.spec.tsx
src/frontend/js/components/SearchFilterValueLeaf/SearchFilterValueLeaf.spec.tsx
src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.spec.tsx
src/frontend/js/components/SearchFiltersPane/SearchFiltersPane.spec.tsx
src/frontend/js/components/SearchSuggestField/SearchSuggestField.spec.tsx
src/frontend/js/components/SearchSuggestField/SearchSuggestField.tsx
src/frontend/js/data/useFilterValue/useFilterValue.spec.tsx
src/frontend/js/types/filters.ts

Selecting a category in the autocomplete suggestions caused the app to crash. This was due to a mismatch between the filters object, that contained definitions for meta-categories, and the autocomplete code, which was looking for a "category" definition.
This can be fixed by adding the path to filter definitions and searching in the filters object for a definition that matches the beginning of the filter we're attempting to add.
Closes #582

Fix category selection from autocomplete

---

.circleci/config.yml
.dockerignore
CHANGELOG.md
Dockerfile
setup.cfg

We've detected multiple issues related to static files packaging (Docker + Python):
- `ckeditor.css` file is missing in the Docker image
- `statics` & `locale` contents are not distributed with the python package

Fix statics in docker and package builds

---

.circleci/config.yml

We (I mean I :grin:) forgot that CircleCI Docker images use a non-privileged user, so we need to perform a local twine install and invoke this local script.

🐛(circleci) fix PyPI package upload job

---

CHANGELOG.md
sandbox/settings.py
src/frontend/scss/objects/_blogpost_glimpses.scss
src/frontend/scss/objects/_course_glimpses.scss
src/frontend/scss/objects/_person_glimpses.scss
src/frontend/scss/templates/courses/cms/_person_detail.scss
src/frontend/scss/templates/courses/plugins/_category_plugin.scss
src/richie/apps/courses/factories.py
src/richie/apps/courses/models/category.py
src/richie/apps/courses/models/organization.py
src/richie/apps/courses/templates/courses/cms/blogpost_list.html
src/richie/apps/courses/templates/courses/cms/category_detail.html
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/fragment_blogpost_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_organization_main_logo.html
src/richie/apps/courses/templates/courses/cms/fragment_person_glimpse.html
src/richie/apps/courses/templates/courses/cms/organization_detail.html
src/richie/apps/courses/templates/courses/cms/person_detail.html
src/richie/apps/courses/templates/courses/cms/person_list.html
src/richie/apps/courses/templates/courses/plugins/blogpost.html
src/richie/apps/courses/templates/courses/plugins/person.html
src/richie/apps/search/signals.py
tests/apps/courses/test_cms_plugins_person.py
tests/apps/courses/test_models_category.py
tests/apps/courses/test_models_organization.py
tests/apps/courses/test_templates_person_detail.py

We want to allow tagging a person with categories.
While doing this PR I found a bug that allowed plugins added to a draft page to be displayed on the public page so I fixed it everywhere:
- on the category page:
- on the organization page:

Add categories to a person

---

CHANGELOG.md
src/frontend/js/components/CourseGlimpse/CourseGlimpse.spec.tsx
src/frontend/js/components/CourseGlimpse/CourseGlimpse.tsx
src/frontend/js/components/CourseGlimpseList/CourseGlimpseList.tsx
src/frontend/js/types/Course.ts
src/frontend/scss/objects/_course_glimpses.scss
src/richie/apps/search/indexers/courses.py
tests/apps/search/test_indexers_courses.py
tests/apps/search/test_query_courses.py
tests/apps/search/test_query_courses_edge_cases.py
tests/apps/search/test_viewsets_courses.py

Course glimpses in the search results were missing elements and cases when compared to the ones in the CMS.
Bring them up-to-speed:

Update course glimpse to match template in CMS

---

src/richie/apps/courses/cms_wizards.py
src/richie/apps/courses/templates/courses/cms/fragment_organization_main_logo.html
tests/apps/courses/test_cms_wizards_person.py
tests/apps/courses/test_templates_course_detail.py

Our support department reported 2 small glitches:
- The link on the main organization logo was broken,
- The person title field should not be required when creating a new person page.

Fix minor glitches

---

CHANGELOG.md
setup.cfg
src/frontend/package.json

- Allow tagging persons with categories,
- A "Clear x active filters" button in the search filters pane lets the user remove all active filters with one click
- Add template and styling for persons list page,
- Add template and styling for categories list page,
- Add sub categories in category detail page.
- Show CTAs to Enroll on course glimpses in Search.
- Make the `RICHIE_ES_HOST` configurable in the sandbox
- Harmonize how cards look on the site (grey border and white background),
- Move all the code related to the demo site to its own application,
- Activating a filter that is a parent or child of a current active filter removes this active relative. This makes the experience of adding those relative filters more intuitive,
- Simplify Richie settings and provide defaults for those …

🔖(chore) bump release to 1.0.0-beta.6

---

.circleci/config.yml

The build-docker* jobs are using CircleCI docker layers caching feature. At first, I thought that the images will also get restored in future jobs, but this is not the case; only layers are cached. 
In order to properly tag and publish build images, we need to rebuild them first (using cached layers). I expect that no new layer will be created and it should be blazing fast.
I've also made improvements to:

Fix ci hub job

---

CHANGELOG.md
src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.spec.tsx
src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.tsx
src/frontend/scss/objects/_search-filter-value.scss

Active parent filters in the search filters pane were displayed with 2 borders due to a mistake in the styles (as most styles are common between parent self filters & leaf filters).
We updated the CSS to fix this glitch and reorganized & added comments to the `.scss` file to make it more explicit where the two uses for these styles need to be handled with special care.

🐛(search) fix a display glitch in active parent filters

---

CHANGELOG.md
setup.cfg
src/frontend/package.json

Changed
- Update French and Canadian French `.po` files with the latest translations.
Fixed
- Fix broken `hub` job in CI publishing the Docker image,
- Fix a display glitch with parent filters when active.

🔖(chore) bump release to 1.0.0-beta.7

---

CHANGELOG.md
src/richie/apps/courses/models/organization.py
src/richie/apps/courses/models/person.py
src/richie/apps/courses/templates/courses/cms/organization_detail.html
tests/apps/courses/test_models_organization.py
tests/apps/courses/test_templates_blogpost_detail.py
tests/apps/courses/test_templates_category_detail.py
tests/apps/courses/test_templates_organization_detail.py
tests/apps/courses/test_templates_person_detail.py

Persons are indirectly related to an organization via the course teams in which they participate. We want to display these related persons on the organization detail page.

✨(organizations) show related persons on the organization detail page

---

CHANGELOG.md
src/richie/apps/courses/models/category.py
src/richie/apps/courses/models/person.py
src/richie/apps/courses/templates/courses/cms/person_detail.html
src/richie/apps/intial/fun_universities.csv
tests/apps/courses/test_models_person.py
tests/apps/courses/test_templates_person_detail.py

We want to show more information on the person detail page : blog posts s.he authored, courses to which s.he participated...

Show related pages on person detail page

---

CHANGELOG.md
sandbox/settings.py
src/frontend/scss/objects/_organization_glimpses.scss
src/richie/apps/courses/factories.py
src/richie/apps/courses/models/organization.py
src/richie/apps/courses/templates/courses/cms/fragment_organization_glimpse.html
src/richie/apps/courses/templates/courses/cms/person_detail.html
tests/apps/courses/test_models_organization.py
tests/apps/courses/test_templates_organization_detail.py
tests/apps/courses/test_templates_person_detail.py

Last week, we displayed the link between a person and an organization via their presence on a course. The problem is that a course is linked to several organizations and several persons and we are not able to differentiate which persons belong to which organization.

♻️(persons) link persons to organizations

---

CHANGELOG.md
src/frontend/js/components/SearchSuggestField/SearchSuggestField.spec.tsx
src/frontend/js/components/SearchSuggestField/SearchSuggestField.tsx
src/frontend/js/types/searchSuggest.ts
src/frontend/js/utils/searchSuggest/getSuggestionsSection.ts
src/frontend/js/utils/searchSuggest/suggestionsFromSection.ts

Instead of offering autocomplete-based suggestions, we can offer users a more intuitive and faster experience by directly querying the search index itself with their query as they are typing.
This is what we're enabling here. We can simply rely on our existing change handler for the input, the only differences being checking for the change method to only run a search when it comes from the user (not when they eg. hover a suggestion), and debouncing these requests to avoid overloading the server.
Closes #483 (by making it irrelevant).

Live search when the user is typing

---

CHANGELOG.md
src/frontend/js/components/SearchFilterValueLeaf/SearchFilterValueLeaf.spec.tsx
src/frontend/js/components/SearchFilterValueLeaf/SearchFilterValueLeaf.tsx
src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.spec.tsx
src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.tsx
src/frontend/js/components/SearchFiltersPane/SearchFiltersPane.spec.tsx
src/frontend/js/components/SearchFiltersPane/SearchFiltersPane.tsx
src/frontend/js/components/SearchFiltersPane/_SearchFiltersPane.scss
src/frontend/scss/objects/_search-filter-value.scss
src/richie/apps/search/defaults.py
src/richie/apps/search/filter_definitions/base.py
src/richie/apps/search/filter_definitions/mixins.py
tests/apps/search/test_query_courses.py

The number of facets displayed varies each time a new filter or query is applied because we only display facets that have some results. 
In order to prevent this annoying effect, we can display all facets and disable those that have zero results.
Fixes https://github.com/openfun/richie/issues/663

🚸(search) prevent search filters from jumping around

---

CHANGELOG.md
src/frontend/js/components/CourseGlimpseList/CourseGlimpseList.spec.tsx
src/frontend/js/components/CourseGlimpseList/CourseGlimpseList.tsx
src/frontend/js/components/Search/Search.tsx
src/frontend/scss/objects/_course_glimpses.scss

We want to show the number of results a given combination of a text query (or none) and search filters returns.
We can simply show it at the top of the search results, and repeat it at the bottom if the list is long enough to warrant it.
Closes #455

Show results count in course search

---

CHANGELOG.md
src/frontend/scss/objects/_organization_glimpses.scss
src/richie/apps/demo/defaults.py
src/richie/apps/demo/management/commands/create_demo_site.py

Now that we can link persons to a set of organizations, we should demonstrate it on the demo site.
Randomly assign organizations to each person.
I paid attention to keep course teams coherent ie the persons in a course team should be linked to one of the organizations that linked to the course.
Fixes https://github.com/openfun/richie/issues/456

Link persons to organizations in demo site

---

CHANGELOG.md
setup.cfg
src/frontend/package.json

Added
- Link persons to a random set of organizations in the demo site,
- Add organizations to a person via plugins on the person detail page,
- Show related persons on the organization detail page,
- On a person detail page, show courses to which s.he participated and
blogposts s.he authored,
- Show results count in the course search results list.
Changed
- Search as the user types in the course search field. This replaces
autosuggest in course names with a full index search,
- Prevent search filters from jumping around by displaying facets with zero
results as disabled and always reserving the space for the "Clear filters"
button,
- Improve demo dataset by assigning each person to an organization,
- Use checkboxes to enable/disable filters in search page,
- Improve autosuggest tests to …

🔖(chore) bump release to 1.0.0-beta.8

---

CHANGELOG.md
src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.spec.tsx
src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.tsx
src/frontend/js/data/useCourseSearchParams/computeNewFilterValue.ts
src/frontend/js/data/useCourseSearchParams/useCourseSearchParams.spec.tsx
src/frontend/js/utils/mptt/index.spec.ts
src/frontend/js/utils/mptt/index.ts

We had two separate issues that ended up being related to incorrect handling of MPTT paths in the frontend:
- The `language` filter was behaving as a drilldown filter even though is was marked as `is_drilldown: false` in API responses.
- Parent filter values, when opened, would only show a maximum of 5 children filter values.
We made more fleshed out `utils` to handle MPTT paths, solving both issues.

Fix two issues related to incorrect handling of MPTT paths

---

CHANGELOG.md
src/richie/apps/search/indexers/courses.py
tests/apps/search/test_indexers_courses.py

This bug was identified in the Sentry dashboard of our https://richie.education demo site.
If a course with no organization is indexed in Elasticsearch (which should not happen if moderation is correctly done), the serializer breaks because it expects at least one organization to be declared
on the course. 
Even if this is not a desired situation, the code should not break if it happens.
I propose to set the highlighted organization to `null` in its serialized form if the course has no organization.
I added a test to surface the bug and secure the fix.

🐛(search) fix course indexer when no related organization

---

CHANGELOG.md
Makefile

While developing Riche, the project's `Makefile` became quite big and messy. It was time to invest some efforts to make it more readable / homogeneous.
We've updated the project's `Makefile` with the following statements in mind:
1. Every variable should be defined in the _ad hoc_ **VARIABLES** section with a relevant subsection
2. Every new rule should be defined in the _ad hoc_ **RULES** section with a relevant subsection depending on the targeted service
3. Rules should be sorted alphabetically within their section
4. When a rule has multiple dependencies, you should:
- duplicate the rule name to add the help string (if required)
- write one dependency per line to increase readability and diffs
5. `.PHONY` rule statement should be written after the corresponding rule
I am open to other …

🔧(project) improve Makefile readability

---

CHANGELOG.md
sandbox/settings.py
src/richie/apps/courses/templates/courses/cms/fragment_course_content.html

Our support team requested some cosmetic changes on the course page.

Re-order placeholders on course page and force most of them to plain text

---

CHANGELOG.md
src/richie/apps/courses/cms_wizards.py
tests/apps/courses/test_cms_wizards_blogpost.py
tests/apps/courses/test_cms_wizards_category.py
tests/apps/courses/test_cms_wizards_course.py
tests/apps/courses/test_cms_wizards_course_run.py
tests/apps/courses/test_cms_wizards_organization.py
tests/apps/courses/test_cms_wizards_person.py

The form field used for the slug, on the page creation wizards, was missing a validator. The form was accepting invalid slugs and the code later crashed with a 500 error.
I added a validator to the slug form field and wrote tests to secure this feature on all the page creation wizards that are depending on this code.

🐛(courses) return error for invalid slugs on page creation

---

CHANGELOG.md
sandbox/settings.py
src/frontend/scss/objects/_person_glimpses.scss
src/richie/apps/core/helpers.py
src/richie/apps/courses/cms_wizards.py
src/richie/apps/courses/defaults.py
src/richie/apps/courses/factories.py
src/richie/apps/courses/management/commands/richie_init.py
src/richie/apps/courses/models/__init__.py
src/richie/apps/courses/models/blog.py
src/richie/apps/courses/models/category.py
src/richie/apps/courses/models/course.py
src/richie/apps/courses/models/organization.py
src/richie/apps/courses/models/person.py
src/richie/apps/courses/templates/courses/cms/fragment_person_glimpse.html
src/richie/apps/courses/templates/courses/cms/person_detail.html
src/richie/apps/demo/defaults.py
src/richie/apps/demo/helpers.py
src/richie/apps/demo/management/commands/create_demo_site.py
tests/apps/courses/test_cms_plugins_person.py
tests/apps/courses/test_cms_wizards_blogpost.py
tests/apps/courses/test_cms_wizards_category.py
tests/apps/courses/test_cms_wizards_course.py
tests/apps/courses/test_cms_wizards_course_run.py
tests/apps/courses/test_cms_wizards_organization.py
tests/apps/courses/test_cms_wizards_person.py
tests/apps/courses/test_factories_person.py
tests/apps/courses/test_templates_person_detail.py

We had a management command to create full demo sites. But all Richie need to have required pages under which the different objects will be created (courses, organizations, persons, blog posts...). We need a command line to create only these required pages.
I refactored the management command that creates a demo site and added a new command line to create just the site structure. I placed it in the `courses` app because all sites need it.

Add command to initialize site structure

---

src/richie/apps/core/helpers.py
src/richie/apps/demo/defaults.py
src/richie/apps/demo/management/commands/create_demo_site.py
tests/apps/demo/test_commands_create_demo_site.py

PR https://github.com/openfun/richie/pull/693 broke the `create_demo_site` management command. 
It's not the first time we break this command because it is not tested. This is historical because it takes too long to run.
I fixed the command and added a test to secure it, bringing it down to 4-5 seconds by mocking the number of objects that are created. It's still too long but at least we can be sure the command works.

🐛(demo) fix and test the create_demo_site management command

---

CHANGELOG.md
src/richie/apps/courses/models/course.py
src/richie/apps/search/description.apib
src/richie/apps/search/forms.py
src/richie/apps/search/indexers/__init__.py
src/richie/apps/search/indexers/categories.py
src/richie/apps/search/indexers/courses.py
src/richie/apps/search/indexers/organizations.py
src/richie/apps/search/indexers/persons.py
src/richie/apps/search/urls.py
src/richie/apps/search/viewsets/persons.py
tests/apps/courses/test_models_course.py
tests/apps/search/test_autocomplete_persons.py
tests/apps/search/test_forms_search_courses.py
tests/apps/search/test_forms_search_items.py
tests/apps/search/test_index_manager.py
tests/apps/search/test_indexers_courses.py
tests/apps/search/test_indexers_persons.py
tests/apps/search/test_query_courses.py
tests/apps/search/test_viewsets_persons.py

We want users to be able to find courses by persons (in the UI) and to find persons themselves through the API (for now).
Handles boxes 1 and 3 from #664

Index persons themselves & on courses

---

CHANGELOG.md
src/richie/apps/core/factories.py
src/richie/apps/core/helpers.py
src/richie/apps/courses/factories.py
src/richie/apps/demo/management/commands/create_demo_site.py
tests/apps/core/test_helpers.py
tests/apps/courses/test_cms_plugins_blogpost.py
tests/apps/courses/test_models_category.py
tests/apps/courses/test_models_organization.py
tests/apps/courses/test_models_person.py
tests/apps/demo/test_helpers.py
tests/apps/search/test_templates_search.py

The helpers.py file in richie.core is used in production and is depending on the `factory` third party lib.
The dependency to `factory` is because of two functions:
- the `create_text_plugin` function is actually only used in tests, let's move it to `factories.py`,
- the `create_i18n_page` function was using faker to generate random   title when the title was not passed. Let's make title a required field and let the page extension factories generate a random title if they need one (this will soon be refactored to make use of our new `PageFactory`).

♻️(core) remove dependency to `factory` in production

---

CHANGELOG.md
src/richie/apps/core/defaults.py
src/richie/apps/courses/cms_wizards.py
src/richie/apps/courses/defaults.py
src/richie/apps/courses/models/course.py
tests/apps/courses/test_cms_wizards_course_run.py

This PR fixes a few bugs following feedback on 1.0.0-beta.9
* If the exact site language is not found in `ALL_LANGUAGES`, look for a language with the same generic language code,
* if a matching language is still not found, raise a configuration error at application startup.

Fix feedback on 1.0.0-beta.9

---

setup.cfg

Generating the demo site requires factory boy. Up to now it was added to the final image by our deployment tool. We have stopped building a custom image for Richie. 
We can add factory boy in the image as it is only going to be used for demo.

⬆️((demo) add factory boy as dependency to the sandbox for demo

---

CHANGELOG.md
src/richie/apps/core/helpers.py
tests/apps/core/test_helpers.py

When deploying Richie, we need to run management commands in jobs. We need those jobs to be idempotent. The recently introduced `richie_init` management command is not.

⚡️(helpers) make recursive_page_creation idempotent

---

CHANGELOG.md
src/richie/apps/courses/templatetags/extra_tags.py
tests/apps/courses/test_templatetags_extra_tags_block_plugin.py

The blockplugin template tag was broken in edit mode.

🐛(courses) fix the blockplugin template tag in edit mode

---

CHANGELOG.md
src/richie/apps/core/helpers.py
tests/apps/core/test_helpers.py

The `richie_init` command was overriding existing home pages if they did not have a `reverse_id` set to `home`.
Also, the `recursive_page_creation` helper was not site aware so when calling it on multiple sites, the pages with the same name were retrieved for the wrong site.

🚸(init) respect existing home page and multiple sites on init command

---

.circleci/config.yml

The idea was to not test code that did not pass linters. We are reconsidering this because:
- it is interesting to get a full feedback on linting and tests,
- the `lint-back` job takes more than 2 minutes that will be saved on build time,
- we don't think this will overload CircleCI with current resources.
In the CircleCI configuration file, remove dependency on the `lint-back` job for the `test-postgresql` and `test-back-mysql` jobs.

⚡️(circleci) speed up CI by removing depending on linting for tests

---

sandbox/settings.py

The `X_FRAME_OPTIONS` setting should be set to `SAMEORIGIN` to allow DjangoCMS admin frames display; this requires to ignore a system check.

🔧(sandbox) make X_FRAME_OPTIONS setting configurable

---

CHANGELOG.md
src/richie/apps/courses/defaults.py
tests/apps/courses/test_cms_wizards_course.py
tests/apps/courses/test_cms_wizards_organization.py

The `PagePermission` model is actually a 2-headed snake... it can act as a permission if `can_view` is False but acts as a view restriction if `can_view` is True.
Said differently, the purpose of the `can_view` flag is not to define that some staff users have the right to view the page... its purpose is to define who can view the page on the frontend.
What we want here is a permission on admin pages for our staff users so `can_view` should be False.

🐛(permissions) fix page permissions that were making pages private

---

CHANGELOG.md
setup.cfg
src/frontend/package.json

- Fix page permissions that ended-up being considered as view restrictions
making all organization and course pages private.

🔖(chore) bump release to 1.0.1

---

CHANGELOG.md
src/richie/apps/courses/cms_wizards.py
src/richie/apps/courses/settings/__init__.py
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/fragment_blogpost_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html
tests/apps/courses/test_cms_plugins_blogpost.py
tests/apps/courses/test_cms_plugins_course.py
tests/apps/courses/test_cms_wizards_blogpost.py
tests/apps/courses/test_cms_wizards_category.py
tests/apps/courses/test_cms_wizards_course.py
tests/apps/courses/test_cms_wizards_course_run.py
tests/apps/courses/test_cms_wizards_organization.py
tests/apps/courses/test_cms_wizards_person.py
tests/apps/courses/test_templates_person_detail.py

The improvements and fixes proposed here follow feedback by our support team.

Support feedback Week 23

---

CHANGELOG.md
setup.cfg
src/frontend/package.json

- Allow only formatted texts or images in course complementary information,
- Simplify why permissions are required to create Richie extension pages,
- Show course creation wizard only on organization pages.
- Fix giving permissions on a course filer folder to its organization admins.

🔖(chore) bump release to 1.1.0

---

CHANGELOG.md
src/richie/apps/courses/settings/__init__.py

In ff1282e we modified the image size on course glimpses but we forgot to modify the thumbnail definition for the image used on the search page.

🚸(search) harmonize glimpse image size on search page

---

CHANGELOG.md
setup.cfg
src/frontend/package.json

- Add field on course to record effort (e.g 5 hours/day) and duration
(e.g 4 weeks).
- Add a new plugin to easily create HTML sitemaps.
- Fix thumbnail definition for the image glimpse used on the search page.

🔖(chore) bump release to 1.2.0

---

CHANGELOG.md
src/richie/apps/core/fields/duration.py
src/richie/apps/courses/factories.py
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/plugins/html_sitemap/migrations/0001_initial.py
src/richie/plugins/html_sitemap/models.py
tests/apps/courses/test_models_course.py

We recently added on the course page the effort and duration fields. We forgot to fill them up in our demo site.
- generate random values for the effort and duration fields on the course factory,
- fix i18n when displaying these fields on the course detail view.

Add effort and duration to demo site

---

CHANGELOG.md
src/frontend/scss/objects/_organization_glimpses.scss
src/frontend/scss/templates/courses/cms/_course_detail.scss
src/frontend/scss/templates/courses/cms/_organization_detail.scss
src/richie/apps/courses/templates/courses/cms/fragment_organization_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_organization_main_logo.html
src/richie/apps/courses/templates/courses/cms/organization_detail.html
tests/apps/courses/test_cms_plugins_organization.py
tests/apps/courses/test_templates_course_detail.py

Organization logos & banners were cropped. This was not the expected outcome for logos. We decided to use a rectangular format for organization logos, and a thinner format for organization banners.
Update the CSS on all uses of organization logos to enforce our aspect ratio without ever cropping the images.
We also had to update srcsets with sizes to fit our expected sizes, and related styles and markup around organization logos.

💄(organizations) rework organization images

---

CHANGELOG.md
setup.cfg
src/frontend/package.json

- Add a catchphrase on top of the course detail view.
- Allow configuring max length and CKeditor on specific placeholders for text
plugins, and propose default configurations using this new feature.
- Improve handling of organization-related images to prevent unwanted cropping
of organization logos.
- Change the person bio to a plain text plugin.

🔖(chore) bump release to 1.4.0

---

CHANGELOG.md
src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.spec.tsx
src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.tsx

The child filter toggle in the course search was deemed compliant, but the label for the toggle is not very explicit, especially for a screen reader user that cannot see its context.
Instead of "Show child filters", we can have it say "Show more filters for Subject X", which is way more explcit. Ditto for the other toggle position.

Improve label for child filter toggle

---

CHANGELOG.md
src/frontend/scss/templates/courses/cms/_course_detail.scss
src/frontend/scss/templates/courses/cms/_person_detail.scss
src/richie/apps/courses/templates/courses/cms/person_detail.html
tests/apps/courses/test_templates_person_detail.py

Person details pages used the maincontent placeholder inside the person card. This is not appropriate as it results in a broken layout.
We put it outside of the person card and took this opportunity to improve the layout of the person card in the person detailed page.
We fixed a display glitch with videos in course detail pages.

Fix person detail maincontent

---

CHANGELOG.md
src/richie/apps/courses/models/course.py
tests/apps/courses/test_models_course.py

On the course model we have getters to retrieve persons, categories and organizations related to a course. 
They were not filtered by language so it was mixing up results between languages. This was especially buggy when retrieving the main organization.
I added a filter on the language to the 3 concerned getters on the course model: `get_organizations`, `get_categories` and `get_persons`.

🐛(courses) fix getting objects related to a course via plugins

---

src/frontend/scss/templates/courses/cms/_course_detail.scss

We recently fixed a display glitch in embedded video elements in course details pages. Our fix broke layout for YouTube videos.
Add back the height we removed as a `min-height` so both embedded videos and YouTube videos are displayed correctly.

🐛(courses) fix display glitch with youtube video iframe

---

CHANGELOG.md
src/richie/apps/courses/settings/__init__.py
src/richie/apps/courses/templates/courses/cms/fragment_course_content.html
src/richie/plugins/simple_text_ckeditor/cms_plugins.py
tests/plugins/simple_text_ckeditor/test_cms_plugins.py

We want to add a placeholder to describe what the student will learn by completing a course.
Description...
- Fix the plugin configuration specific to a placeholder,
- Add a new placeholder to the course detail page `course_skills`.

Add a section "What you will learn" to the course page

---

CHANGELOG.md
src/frontend/js/components/SearchSuggestField/SearchSuggestField.spec.tsx
src/frontend/js/components/SearchSuggestField/SearchSuggestField.tsx

As the user inputs text into the autocomplete search bar, it is used for our search-as-you-type interface, and also send to the API to compute suggestions.
When a user selects a suggestion, we need to remove the query added to params by search-as-you-type because the text entered by the user was already "consumed" by the action to select the suggestion.
Not doing this was causing inconsistent UI state and broken search results.
Clear the text query when the user selects a suggestion.

Don't keep stale user input when a suggestion is selected

---

CHANGELOG.md
setup.cfg
src/frontend/package.json

- Add a section "What you will learn" to the course page.
- Fix language confusion when getting objects that are related to a course via a plugin (organizations, categories and persons),
- Use empty image alt text & no link title text for course glimpses to comply with accessibility standards (existing alts & titles were redundant).
- Fix an issue that caused inconsistent UI and broken search results when selecting a suggestion in course search.

Bump version to 1.5.0

---

CHANGELOG.md
src/frontend/yarn.lock

Fix GitHub warning for vulnerability in lodash.

⬆️(lockfile) update lodash to v4.17.13+ [SECURITY]

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html

Fulfills request "Date formating on english pages #569". Have english date go from "12/15/2019" to "Dec. 15, 2019" format.
Course glimpse is the only glimpse using "title" formatting. User feedback made us realize that.
Fixes #569

Course date l10n and course glimpse formatting

---

src/richie/apps/search/defaults.py
src/richie/apps/search/filter_definitions/courses.py
src/richie/apps/search/filter_definitions/mixins.py
tests/apps/search/test_query_courses_facet_limits.py

By default, ElasticSearch returns the 10 top terms when making an aggregations call on top terms. This fit us pretty well when we just show the top values by default.
However, it's not enough when we run a search for a specific number of facet counts: we want the client to be able to request all the facets they need and get them (within reasonable bounds).
We added settings to manage these values (default and max facet limits), and wrote some tests for this behavior.

Add settings for facet limits

---

CHANGELOG.md
src/richie/apps/courses/cms_wizards.py
src/richie/apps/courses/factories.py
src/richie/apps/courses/models/course.py
src/richie/apps/courses/models/organization.py
src/richie/apps/courses/models/role.py
src/richie/apps/demo/management/commands/create_demo_site.py
tests/apps/courses/test_cms_wizards_course.py
tests/apps/courses/test_models_course.py
tests/apps/courses/test_models_organization.py
tests/apps/courses/test_models_page_role.py

The roles and permissions (Django models, DjangoCMS pages and Django Filer folders) were created by page creation wizards.
We also need to create them in the demo site and when adding a page programmatically (e.g automatic imports).
I propose to factorize in the models the code that creates roles and permissions, so that it can easily be called from anywhere in the code base.
As a first use case, I added roles and permissions in the demo site.

Refactor roles and permissions to add them to the demo site

---

CHANGELOG.md
setup.cfg
src/frontend/package.json

- Configure roles and permissions in the demo site.
- Factorize the code creating roles & permissions for organizations & courses,
- Display an icon on the course glimpse (the first among the course's icons),
- Add icons to the course detail page via a constrained placeholder,
- Add an icon to the category detail page via a constrained placeholder,
- Add icon image to the category search index,
- Add icon image to the course search index.
- Fix `get_placeholder_plugins` template tag when the placeholder is missing,
- Stop limiting course getters to specific placeholder names on all objects.

🔖(chore) bump version to 1.6.0

---

CHANGELOG.md
src/frontend/js/components/Search/Search.tsx
src/frontend/js/components/Search/_Search.scss
src/frontend/js/index.tsx
src/frontend/scss/templates/search/_search.scss
src/richie/apps/search/templates/search/search.html
tests/apps/search/test_templates_search.py

Currently the Django template is responsible for displaying the page title on the search results, like on any other page. This is good in that it allows this title to be managed in the CMS. However, it is
troublesome in terms of page structure as we want to handle the search filters pane more cleanly.
To keep the title in the CMS while improving our page structure, we decided to pass the page title to the React frontend via a data attribute in the Django template. This lets us cleanly insert it in the relevant place in our markup.
In our opinion, this is a better compromise than hardcoding it in React (as we lose CMS management of the title, which should not happen if we can avoid it), or adding hacks to the CSS which can be more harmful in the longer term.

Move the search template title into react

---

CHANGELOG.md
setup.cfg
src/frontend/package.json

- Move the page title in Search so it can be placed correctly in the page structure.
- Use the "Exo 2" font throughout Richie.

🔖(chore) bump version to 1.6.1

---

src/frontend/js/components/CourseGlimpse/CourseGlimpse.spec.tsx
src/frontend/js/components/CourseGlimpseList/CourseGlimpseList.spec.tsx
src/frontend/js/components/SearchFilterGroup/SearchFilterGroup.spec.tsx
src/frontend/js/components/SearchFilterValueLeaf/SearchFilterValueLeaf.spec.tsx
src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.spec.tsx
src/frontend/js/components/SearchFiltersPane/SearchFiltersPane.spec.tsx
src/frontend/js/components/SearchSuggestField/SearchSuggestField.spec.tsx
src/frontend/js/data/useCourseSearch/useCourseSearch.spec.tsx
src/frontend/js/data/useCourseSearchParams/useCourseSearchParams.spec.tsx
src/frontend/js/data/useFilterValue/useFilterValue.spec.tsx

`testing-library` now automatically performs cleanup in `afterEach`, which means our manual `cleanup` calls are entirely useless.
We mocked `console.error` in our tests to remove non-actionable `act` warnings from React when state updates were triggered by async functions.
We updated to React 16.9, which includes `async act`.

Remove testing library cleanup

---

CHANGELOG.md
src/frontend/js/components/CourseGlimpseList/CourseGlimpseList.spec.tsx
src/frontend/js/components/CourseGlimpseList/CourseGlimpseList.tsx
src/frontend/js/components/PaginateCourseSearch/_PaginateCourseSearch.scss
src/frontend/js/components/PaginateCourseSearch/index.spec.tsx
src/frontend/js/components/PaginateCourseSearch/index.tsx
src/frontend/js/components/Search/Search.tsx
src/frontend/js/components/SearchFiltersPane/SearchFiltersPane.tsx
src/frontend/js/data/useCourseSearchParams/useCourseSearchParams.spec.tsx
src/frontend/js/data/useCourseSearchParams/useCourseSearchParams.ts
src/frontend/js/settings.ts
src/frontend/js/types/api.ts
src/frontend/js/utils/indirection/window.ts
src/frontend/scss/_main.scss
src/frontend/scss/_utils.scss

On large richie instances, there can be hundreds of courses available to display. As the default view of the search page is non-filtered, the page could be slow to load with hundreds of courses to load from the API and display in complex glimpses with their cover images.
We can paginate the view down to a useful level (say, 20 courses by default) which keeps the page reasonably long and deals with performance issues.
Closes #754

Paginate course search

---

CHANGELOG.md
src/richie/apps/search/index_manager.py
src/richie/apps/search/indexers/categories.py
src/richie/apps/search/indexers/courses.py
src/richie/apps/search/indexers/organizations.py
src/richie/apps/search/indexers/persons.py
src/richie/apps/search/text_indexing.py
tests/apps/search/test_autocomplete_categories.py
tests/apps/search/test_autocomplete_courses.py
tests/apps/search/test_autocomplete_organizations.py
tests/apps/search/test_autocomplete_persons.py

Autosuggestion API endpoints treat accented characters as different from the non-accented versions of the same characters.
This is technically correct but is not intuitive for users who want to see the results they expect regardless of accents.
Create a custom analyzer that folds accented characters into their ascii version and use that for all our completion fields in our object mappings.
Closes #419.

✨(search) make autosuggestion diacritics insensitive

---

CHANGELOG.md
src/frontend/scss/templates/courses/cms/_course_detail.scss
src/frontend/scss/templates/courses/plugins/_category_plugin.scss
src/richie/apps/courses/factories.py
src/richie/apps/courses/settings/__init__.py
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/plugins/category_plugin.html
src/richie/apps/demo/defaults.py
src/richie/apps/demo/helpers.py
tests/apps/courses/test_factories_category.py
tests/apps/courses/test_templates_blogpost_detail.py
tests/apps/courses/test_templates_course_detail.py
tests/apps/courses/test_templates_course_run_detail.py
tests/apps/courses/test_templates_person_detail.py

In [v1.6.0](https://github.com/openfun/richie/releases/tag/v1.6.0) (PR https://github.com/openfun/richie/pull/758), we added a new separate placeholder to attach category icons to a course. With this design, it was not possible to add an icon to the course detail view without making it appear on its glimpse. 
In order to allow this use case, we refactored categories to display as icons when they have an image, regardless of the placeholder to which they are added on the course page.
The first category in the `course_icons` placeholder is still displayed on the glimpse but it is now possible to add icons to the course detail view via the old `course_categories` placeholder so that they don't appear on the glimpse.

✨(courses) allow icons to display on course detail and not on glimpse

---

CHANGELOG.md
setup.cfg
src/frontend/package.json

- Paginate the course search results view.
- Add a CSS class to move content offscreen so it's only available for users of assistive technologies.
- Allow category icons to be displayed on course detail and not on glimpse.
- Autosuggestion endpoints are diacritics insensitive.

Bump version to 1.7.0

---

MANIFEST.in

Commit edac2ac added a new woff2 font but it was not included in the Python package because woff2 was missing from the MANIFEST.in file.
Add *woff2 to [MANIFEST.in](https://github.com/openfun/richie/blob/master/MANIFEST.in)

🐛(project) add woff2 in manifest for newly added font

---

CHANGELOG.md
src/frontend/js/components/SearchFilterGroup/SearchFilterGroup.spec.tsx
src/frontend/js/components/SearchFilterGroup/SearchFilterGroup.tsx
src/frontend/js/components/SearchFilterGroupModal/_SearchFilterGroupModal.scss
src/frontend/js/components/SearchFilterGroupModal/index.spec.tsx
src/frontend/js/components/SearchFilterGroupModal/index.tsx
src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.spec.tsx
src/frontend/js/components/SearchFilterValueParent/SearchFilterValueParent.tsx
src/frontend/js/types/Category.ts
src/frontend/js/types/Course.ts
src/frontend/js/types/Organization.ts
src/frontend/js/types/Resource.ts
src/frontend/js/types/Suggestion.ts
src/frontend/package.json
src/frontend/scss/_main.scss
src/frontend/scss/objects/_search-filter-value.scss
src/frontend/yarn.lock
src/richie/apps/core/templates/richie/base.html
src/richie/apps/search/forms.py
src/richie/apps/search/indexers/categories.py
tests/apps/search/test_forms_search_items.py
tests/apps/search/test_query_categories.py
tests/apps/search/test_query_organizations.py
tests/apps/search/test_query_persons.py
tests/apps/search/test_viewsets_categories.py

In the search filters pane, we display the top N (by default 10) values for each filter, ordered by facet count. It makes sense to show the values with the most matching courses more prominently, but users might want to filter by other values, especially on Richie instances that host a large number of courses.
Add a button on said search filters that opens a modal with a search field that is specialized to that filter.
This will let users easily add any value for a given filter through a full-text search.

Scale facet filters

---

CHANGELOG.md
src/richie/apps/core/templates/richie/base.html

In Release 1.7.2, the footer logo is pointing to a file that does not exist which raises a 500 error in production when using the manifest static files storage backend.
Cherry pick commits 90b7328 and e1dc722 to master.

🐛(project) fix logo url in footer

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/plugins/person.html
tests/apps/courses/test_templates_blogpost_detail.py

The person plugin, when used through its tag form, contained an error where `get_tile` was called instead `get_title`.
It was also called on the person object (which has no such method) instead of the related page (which does, and has the person's name as its title).
We simply fixed the error and added tests to make sure it works from now on.

Fix a template error in the person plugin

---

CHANGELOG.md
src/frontend/js/components/SearchFilterGroupModal/index.spec.tsx
src/frontend/js/components/SearchFilterGroupModal/index.tsx

The "more options" modal for filter values in the search filters pane incorrectly made the assumption that all searchable filters were based on MPTT paths and built a regexp accordingly.
That is not the case: in our own sandbox environment, persons are not using those paths and the "more options" for persons modal is broken. 
We can simplify the regexp to make it work with every filter.

Fix "more options" modal for non-mptt-paths based filters

---

CHANGELOG.md
src/frontend/js/components/SearchFilterGroupModal/_SearchFilterGroupModal.scss
src/frontend/js/components/SearchFilterGroupModal/index.spec.tsx
src/frontend/js/components/SearchFilterGroupModal/index.tsx

The "More options" modal for filter values was making request to the server as soon as the user started to type, and immediately showed a cryptic error message as it received an error for the server, because textual search only works in our API endpoints with 3 characters or more.
Stop sending useless API requests when users input 1 or 2 characters and show a helpful message in the modal instead.

Improve error messages in the "more options" modal in filters

---

src/richie/apps/demo/defaults.py

We're using demo content to showcase richie's feature set as best we can.
In this instance, we want to make a better demo for the "More options" modal on filters, and for course pagination.
Increase the number or courses & organizations included in the demo site by default.

Increase courses & organizations numbers on demo site

---

src/richie/apps/courses/templates/courses/cms/blogpost_detail.html

The string shown in the blogpost detail template when a blogpost does not have an author - "No author yet." - should not have a period at the end as it is displayed between two dashes.
Just remove the period from the string in the template.

Improve a string in the blogpost detail template

---

CHANGELOG.md
src/frontend/js/components/PaginateCourseSearch/_PaginateCourseSearch.scss
src/frontend/js/components/PaginateCourseSearch/index.tsx

Our pagination as implemented in course search had two flaws:
- low contrast difference between the currently active page button and other pages;
- small clickable zone, only clicks on the page number itself triggered a page change, not clicks on the button itself.
We made the clickable area encompass the whole page button, and used a reverse color scheme for the active page to make it more obvious for all users (and avoid a WCAG non-conformity for low contrast).

Improve pagination UX in course search

---

CHANGELOG.md
src/frontend/yarn.lock

Regenerate the lockfile to ensure only versions > 2.0.1 (safe versions) of the `set-value` npm package are used.

🔒(dependencies) bump set-value to > 2.0.1

---

CHANGELOG.md
src/frontend/js/components/PaginateCourseSearch/index.spec.tsx
src/frontend/js/components/PaginateCourseSearch/index.tsx

Visible pagination does not contain a lot of strings, but we have a few more strings for accessibility helpers that provide context along with the page numbers.
We previously attempted to do this "smartly" through the HTML structure of our interpolated strings. This is not ideal as it works for english and some other languages, but fails for other languages with a different grammar.
Also, we forgot a bunch of strings, which resulted in hardcoded english in our template.
Use a more straightforward structure for our JSX and put all content in strings, repeating it instead of concatenating them.

Improve and complete strings in pagination

---

CHANGELOG.md
setup.cfg
src/frontend/js/translations/fr_CA.po
src/frontend/js/translations/fr_FR.po
src/frontend/package.json
src/richie/locale/fr_CA/LC_MESSAGES/django.po
src/richie/locale/fr_FR/LC_MESSAGES/django.po

- Fix "More options" modal for searchable filter values not based on MPTT paths (eg. "Person" in the sandbox environment).
- Improve pagination UX by increasing contrast between the active page number and others, and making button clickable areas larger.
- Stop making failed API requests and instead show a helpful error message in the "More options" modal for filter values when the user inputs their first 1 or 2 characters.
- Improve pagination strings for localization.
- Update the mixin-deep and set-value packages to safe versions.

Release 1.8.1

---

CHANGELOG.md
src/richie/apps/courses/settings/mixins.py
tests/apps/courses/test_settings_mixins.py

We were setting default values on the configuration mix instance. As a result it could not be overriden by class attributes on a configuration class inheriting from this mixin. 
We should set values on the configuration mixin as class attributes.

🐛(settings) allow overriding default settings defined in Richie's mixin

---

CHANGELOG.md
src/frontend/scss/_main.scss
src/frontend/scss/objects/_breadcrumbs.scss
src/richie/apps/core/templates/menu/breadcrumb_item.html
src/richie/apps/core/templates/richie/base.html
src/richie/apps/core/templates/richie/homepage.html
src/richie/apps/courses/templates/courses/cms/blogpost_list.html
src/richie/apps/courses/templates/courses/cms/category_list.html
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/organization_list.html
src/richie/apps/courses/templates/courses/cms/person_list.html
src/richie/apps/search/templates/search/search.html

Pages missed breadcrumbs which is a penalty for ergonomy, since we have more
than two page levels.
Here we add breadcrumbs as a common element from base template skeleton in
its own template block so on default it is enabled everywhere. However we do
not want to show it on homepage and first level page which are already
visually active in header menu, so we disable breadcrumbs block from all
page listing templates.
This does not involve any new tests since we stand on basical feature from
Django templates and DjangoCMS.

✨(layout) add breadcrumbs on top of page details

---

src/frontend/js/common/searchFields/getSuggestionsSection.spec.ts
src/frontend/js/common/searchFields/getSuggestionsSection.ts
src/frontend/js/common/searchFields/index.tsx
src/frontend/js/components/RootSearchSuggestField/index.spec.tsx
src/frontend/js/components/RootSearchSuggestField/index.tsx
src/frontend/js/components/SearchSuggestField/SearchSuggestField.tsx
src/frontend/js/index.tsx
src/frontend/js/types/Suggestion.ts
src/richie/apps/search/indexers/courses.py
tests/apps/search/test_indexers_courses.py

Reuse parts of what we built for <SearchSuggestField /> to make <RootSearchSuggestField />, a React-powered course search field that can live anywhere in Richie, independently from <Search />.
Since most of its features are pretty different from those in the original <SearchSuggestField />, we found it preferable to create a new component, and try to reuse as much of the actual logic as possible.

Add a standalone search field component

---

.circleci/config.yml
CHANGELOG.md

The circle-ci job uploading translations on crowdin is failing since few
days because there is an issue with the tar version used in our crowdin
image. We think it's a circle-ci regression, they remove the fallback on
their tools to use the good tar commad. We decided to add tar in our
crowdin image and to use it in our upload-i18n-strings job.

⬆️ (circle) upgrade crowdin image version

---

CHANGELOG.md
src/richie/apps/core/templates/richie/base.html
src/richie/apps/core/templates/richie/fullwidth.html
src/richie/apps/core/templates/richie/homepage.html
src/richie/apps/core/templates/richie/single_column.html
src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
src/richie/apps/courses/templates/courses/cms/category_detail.html
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/course_run_detail.html
src/richie/apps/courses/templates/courses/cms/organization_detail.html
src/richie/apps/courses/templates/courses/cms/person_detail.html
src/richie/apps/courses/templates/courses/cms/program_detail.html

There is currently no meta tags in pages, which is an issue for SEO.
This is related to #568.
Here we add and define meta tags as meaningfully as possible for home and detail pages. To do so we add new dedicated blocks in the base template with some basic information then page templates can fill
or override them to define relevant meta information.

🔍(SEO) configure meta and opengraph tags

---

CHANGELOG.md
setup.cfg
src/frontend/package.json

- Add a React-powered course search field that can live anywhere in Richie.
- Add breadcrumbs element on all pages but the listing ones.
- Add a new page type for programs as a collection of courses.
- New dependency "dj-pagination" to enable pagination on blogpost list
and person list.
- Add basic SEO tags with some more relevant ones in page details.
- Refactor course search field to make it reusable.
- Upgrade crowdin image used in circle-ci to version 2.0.31 including
tar command.
- Translate login/signup on header.

🔖(chore) bump version to 1.9.0

---

src/richie/apps/core/templates/richie/base.html

The logo image location was modified but the SEO tag PR was opened before this and still had the old path. This error only appears after deployment because it is caused by the use of the Manifest
static storage backend.
Fix logo image location in base.html template.
Note: We should add tests in our CI to identify this type of issues earlier. I'm going to open an issue.

🐛(static) fix logo location that breaks static finder

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/fragment_course_content.html
tests/apps/courses/test_templates_course_detail.py

The placeholders for organizations and teams was different from the rest.
This older structure prevented you from adding plugins into them if you
did not already have one in it since they aren't in the template if you don't already have something.
This fixes it by using the template structure used for the other placeholders that work.

🐛(template) update fragment_course_content

---

CHANGELOG.md
src/frontend/scss/components/_footer.scss
src/richie/apps/core/templates/menu/footer_menu.html
src/richie/apps/core/templates/richie/base.html

It has been required that footer main menu should be able to display a second
level menu if there is one.
This commit changed footer_menu.html template to enable to list direct
children of first level items. Note that this only display well if all first
level items have children, else it could seem a little bit empty.

💄(layout) enable submenu in footer main menu

---

CHANGELOG.md
setup.cfg
src/frontend/package.json

- Add plugin to embed organizations by their category on any page,
- Display related organizations on category detail page,
- Add a variant option for organization glimpse,
- Allow tagging organizations with categories,
- Allow second level children in footer menu.
- When displaying objects related to a category, include objects related to
the categories' descendants,
- When displaying related objects on a category, respect page tree ordering,
- The filters pane in course search is now a sliding drawer on mobile,
- Use SVG icons instead of an icon font.
- Fix add plugin to team and organization on fragment_course_content template
when they are empty.
- Anti-pattern in factories to create related objects from the targeted page.

🔖(chore) bump version to 1.10.0

---

CHANGELOG.md
UPGRADE.md
src/richie/apps/core/templates/richie/base.html
src/richie/apps/core/templates/richie/fullwidth.html
src/richie/apps/core/templates/richie/homepage.html
src/richie/apps/core/templates/richie/single_column.html
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/course_run_detail.html
src/richie/apps/courses/templates/courses/cms/fragment_course_content.html
src/richie/apps/search/templates/search/search.html
tests/apps/courses/test_templates_course_detail.py

The projects using richie as a dependency should be able to override a precise portion of the course detail view without having to override the whole template.
This will ease maintenance on such projects.
While working on this PR I had the chance to rename `course-detail__aside__run` selector to `course-detail__aside__runs` in `course_detail.html` template to reflect the fact that there are many course runs.

Wrap course detail sections in blocks

---

CHANGELOG.md
src/frontend/js/components/PaginateCourseSearch/index.tsx

There was an issue with the HTML tags used for pagination. For some reason, `<ul>` is an invalid tag for `role="navigation"`.
We just added an empty `<nav>` around our `<ul>` navigation with the `aria-labelledby` pointing to it.
This solves an issue screen readers would have encountered seeing the pagination as a navigational element.

♿️(search) fix frontend pagination accessibility issue

---

CHANGELOG.md
sandbox/settings.py
tests/sandbox/test_settings.py

The DRF API calls were responding with a 403 status code for anonymous users, and were working for authenticated users. This was due to a Basic Auth fallback option in the default configuration of DRF's authentication backends.
For an anonymous user:
- The first authentication backend in the list of DRF's default backends (Django session authentication) does not try to authenticate because it does not see any cookie,
- The second backend (Basic Authentication) tries to authenticate because it sees an Authentication header. But this header is coming from the Nginx htaccess (and is not known by Django), so the authentication fails with a 403.
Removing the Basic Authentication backend allows anonymous users to be really considered as anonymous in Django.
- Remove Basic Auth fallback option …

🐛(sandbox) make API calls work behind an htaccess

---

.circleci/config.yml

A new `mysql:5.6` Docker image was published that broke our CI because our fun user was not allowed to create a database anymore. It is necessary because tests run on a specific database called `test_richie` that it creates if it is missing. 
Making sure the database is already created in the container when it starts fixes the bug.
I also changed the name of the database for Posgresql so that it doesn't need to create another one either...
I did not include a changelog because there is no change on Richie, only this repository's CI.

👷(circleci) fix test-back-mysql following mysql image upgrade

---

src/frontend/scss/templates/courses/cms/_course_detail.scss
src/richie/apps/courses/templates/courses/cms/course_detail.html

The course runs block appearence was bugged. It's fixed with these
modifications. 
Update .scss to reflect the change from  `course-detail__aside__run' to `course-detail__aside__runs` and move a </div> that was included in the course runs block by error.

🐛(templates) fix bug in course detail

---

CHANGELOG.md
sandbox/settings.py
src/richie/apps/core/templates/djangocms_video/default/video_player.html
src/richie/apps/core/templates/richie/base.html
src/richie/apps/core/templates/richie/pagination.html
src/richie/apps/core/templates/social-networks/blogpost-badges.html
src/richie/apps/core/templates/social-networks/course-badges.html
src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
src/richie/apps/courses/templates/courses/cms/category_detail.html
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/fragment_blogpost_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_category_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_organization_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_organization_main_logo.html
src/richie/apps/courses/templates/courses/cms/fragment_person_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_program_glimpse.html
src/richie/apps/courses/templates/courses/cms/organization_detail.html
src/richie/apps/courses/templates/courses/cms/person_detail.html
src/richie/apps/courses/templates/courses/cms/program_detail.html
src/richie/apps/courses/templates/courses/plugins/category_plugin.html
src/richie/plugins/large_banner/templates/richie/large_banner/hero-intro.html
src/richie/plugins/large_banner/templates/richie/large_banner/large_banner.html
src/richie/plugins/section/templates/richie/section/section_cadenced.html
src/richie/plugins/simple_picture/templates/richie/simple_picture/picture.html
src/richie/static/richie/README.md
tests/apps/courses/test_templates_course_detail.py

Issue #825 has reported some warnings and errors from HTML validator in almost all pages which should be resolved for sanity.
This pull request will fix every reported warnings and errors from issue except the one about missing `lang` attribute which has already been fixed in a previous commit about SEO.

👌(layout) fix HTML validation warnings and errors

---

CHANGELOG.md
setup.cfg
src/frontend/package.json

- Add a variant option for course glimpses.
- Richie dependents can now run their own frontend build and override
components through command line arguments and a dedicated settings file.
- Rename {% block title %} to {% block head_title %} to avoid collision with
H1 title,
- Wrap each section of the course detail template in a block to allow partial
overrides,
- Rename `course-detail__aside__run` selector to `course-detail__aside__runs`
in `course_detail.html` template to better reflect its content.
- HTML validation warnings and errors,
- In the sandbox, make API calls work behind an htaccess by removing Basic
Auth fallback,
- Adding person/organization plugins to a new blank course,
- Remove multiple "h1" tags on homepage, section template will always have a
default level title of 2. …

🔖(chore) bump version to 1.12.0

---

.circleci/config.yml

Automated deployment to gh-pages in the CI fails because it runs with HTTPS and therefore hangs on an HTTP password prompt instead of using the git user token we generated for funmoocbot.
The `USE_SSH` environment variable should force it to use ssh to push to github and get rid of this password prompt.

Fix documentation build on the CI

---

.circleci/config.yml

This reverts commit 225ea8822e6c3b6b5387bc7759e1b1cf46da7f8f.
The change to the deployment command was unnecessary as the issues we were encountering were caused by an invalid token (which was not understood as such by us).
We can just revert them and everything works as intended with a valid token.

🐛(website) fix documentation build [REVERT]

---

CHANGELOG.md
src/frontend/js/components/RootSearchSuggestField/index.spec.tsx
src/frontend/js/components/RootSearchSuggestField/index.tsx

To initialize itself and know which filters can be used for autocompletion, <RootSearchSuggestField /> waits for valid user input and makes a request on the course search endpoint with a `"filters"` scope.
This request was failing due to incorrect case on the `scope`, which needs to be `"filters"` instead of `"FILTERS"`, and an incorrect value for `limit`, which can't be 0 even though we're not expecting
any actual search results.
Change the request parameters and update the tests to reflect this.

🐛(frontend) fix a 400 Bad Request issue in <RootSearchSuggestField />

---

CHANGELOG.md
src/richie/apps/search/viewsets/categories.py
tests/apps/search/test_viewsets_categories.py
tests/apps/search/test_viewsets_courses.py
tests/apps/search/test_viewsets_organizations.py
tests/apps/search/test_viewsets_persons.py

The categories ViewSet sits on a catchall url so it can receive requests for any "kind" of category in an intuitive way. This has a drawback though: unexpected requests might end up in our categories
routes.
We simply want to make sure those are handled properly and return eg. 404 errors, and do not raise 500s or return any unwanted data.

Handle unexpected calls on categories catchall API routes

---

docs/django-react-interop.md

We recently added a <UserLogin /> component, built in React, to enable users to log in/sign up to Richie or log out if they're already in.
We did not add the related documentation in the Django-React interop docs. This corrects that oversight.

📝(frontend) document the <UserLogin /> component

---

docs/building-the-frontend.md
website/sidebars.json

Dependents can run their own build for CSS & JS to theme, modify or extend Richie. This was mostly not documented, be it in the repository or in the NPM package that we publish to facilitate it.
We wrote some docs to help users figure out own to run it. They also explain the settings for the JS build.
Note: this does not explain how to actually use the files when they are built, as I don't know how to do that 😅
Someone more qualified proabably needs to step in to complete this introduction

📝(website) document the frontend build for dependents

---

CHANGELOG.md
src/richie/apps/courses/admin.py
src/richie/apps/search/cms_toolbars.py
src/richie/apps/search/models.py
src/richie/apps/search/urls.py
src/richie/apps/search/views.py
tests/apps/core/utils.py
tests/apps/courses/test_admin_page_snapshot.py
tests/apps/courses/test_cms_toolbars.py
tests/apps/search/test_cms_toolbars.py
tests/apps/search/test_views_bootstrap_elasticsearch.py

In some cases, staff user want to regenerate the search index from scratch.
We propose to trigger it via an Ajax menu item in the toolbar. Only staff users who were granted the
specific permission to manage the Elasticsearch index can do it.
We do it synchronously for the moment because:
- it should take less than 30 seconds,
- only authorized users can do it and it's rare,
- we want to avoid introducing a dependency to Celery or other asynchronous tasks handlers.

Add toolbar menu item to regenerate the Elasticsearch index

---

src/frontend/js/components/Search/index.spec.tsx

The <Search /> component was producing act-related warnings because some of our tests were making http requests and never explicitly waiting for them, resulting in the responses being handled (and state modified) at an undefined time.
Simply adding `await wait()` after rendering makes the test explicitly wait for resolution and wrap that in an `act()` call (that's what RTL's `wait()` does), and gets rid of the warnings.

♻️(frontend) remove act warnings in <Search />

---

src/richie/apps/core/templates/richie/base.html

The logo link in the footer used an empty alt text on the image, which is the only content for the link. This is incorrect as there is no text at all on the link for accessibility tech users.
We can just add `{{ SITE.name }}` like on the logo in the header.
Part of our effort on #888

Fix logo link in base footer

---

CHANGELOG.md
src/richie/apps/search/filter_definitions/base.py
src/richie/apps/search/filter_definitions/courses.py
src/richie/apps/search/urls.py
src/richie/apps/search/views.py
tests/apps/search/test_cms_toolbars.py
tests/apps/search/test_query_courses.py
tests/apps/search/test_query_courses_facets.py
tests/apps/search/test_views_bootstrap_elasticsearch.py
tests/apps/search/test_views_filter_definitions.py
tests/apps/search/test_viewsets_courses.py

We're refactoring our course search to make it more modular. One key part of this is to allow components to use search/autosuggest based on filters without making full course search requests first.
While doing this, we noticed a missing trailing slack on the `bootstrap-elasticsearch` API url, and decided to add it.

Add an API endpoint to get static search filter definitions

---

CHANGELOG.md
UPGRADE.md
src/richie/apps/core/templates/menu/language_menu.html
src/richie/apps/core/templates/richie/base.html
tests/apps/core/test_language_chooser.py

The language chooser was showing languages even when they were marked as "not public" in the settings.
- Remove the template tag that gets languages for the language chooser and rely on the languages variable already prepared by the language chooser template tag. It respects the public status of languages.
- Refactor the language chooser menu to include the `<ul>` tag so we can avoid having an empty `<ul>` on sites that have only one public language.

Fix language chooser

---

CHANGELOG.md
src/frontend/js/common/searchFields/index.tsx
src/frontend/js/components/RootSearchSuggestField/index.spec.tsx
src/frontend/js/components/RootSearchSuggestField/index.tsx
src/frontend/js/components/Search/index.tsx
src/frontend/js/components/SearchFilterGroup/index.spec.tsx
src/frontend/js/components/SearchFilterGroup/index.tsx
src/frontend/js/components/SearchFilterGroupModal/index.spec.tsx
src/frontend/js/components/SearchFilterGroupModal/index.tsx
src/frontend/js/components/SearchFilterValueLeaf/index.spec.tsx
src/frontend/js/components/SearchFilterValueLeaf/index.tsx
src/frontend/js/components/SearchFilterValueParent/index.spec.tsx
src/frontend/js/components/SearchFilterValueParent/index.tsx
src/frontend/js/components/SearchFiltersPane/index.spec.tsx
src/frontend/js/components/SearchSuggestField/index.spec.tsx
src/frontend/js/components/SearchSuggestField/index.tsx
src/frontend/js/data/useFilterValue/index.spec.tsx
src/frontend/js/data/useFilterValue/index.ts
src/frontend/js/data/useStaticFilters/index.spec.tsx
src/frontend/js/data/useStaticFilters/index.tsx
src/frontend/js/types/api.ts
src/frontend/js/types/filters.ts

We want to unplug `<SearchSuggestField />` from `<Search />` so we can extract it and put it somewhere else on the page. Then, they can interact through the URL query string.
One key dependency between `<SearchSuggestField />` and the rest of `<Search />` is that `<SearchSuggestField />` needs the filter definitions to configure itself.
This can be solved, and we can improve `<RootSearchSuggestField />` in the process, by using our new `filter-definitions` API endpoint to directly get static filter definitions from those components.

Refactor search for modularity

---

Makefile
bin/_config.sh
bin/lint-back-diff

The backend linters have become very slow, especially pylint. When working on a branch, we don't need to lint the whole project, but only what has changed. 
The idea of this command is to run the linters only on the files pointed by a `git diff --name-only master HEAD`.

✨(project) add a command to lint only what has changed since master

---

CHANGELOG.md
src/richie/apps/courses/migrations/0010_auto_footer_to_static_placeholder.py

The data migration that moves any existing footer to the new static placeholder was running before the schema migration on the section plugin allowed null titles. This was resulting in IntegrityErrors. We did not see this error in development because the database migrations were run separately. We did not see it in the CI either because migrations run on an empty database.
Add a dependency on the data migration that moves the footer so that it is run after the schema migration on the section plugin.

🐛(courses) add migrate dependency to update section b4 creating footer

---

UPGRADE.md

When addding user authentication on the top right of all pages, we forgot to add critical upgrade instructions. If these steps are not taken care off, all pages on the site will raise a 500 error.
Add upgrade instructions retrospectively.

📝(upgrade) add missing instructions for user related urls and settings

---

src/frontend/js/index.tsx

Richie's frontend operates on the assumption that en-US is the default language and is contained in the default messages as opposed to localization files that are lazily loaded for other languages.
We don't want to add a special case that does not import() an l10n file for en-US because we don't want to prevent Richie users from creating their own and loading it.
Therefore, we decided to load it if it's there, but not report an error that is in the default and most common case, just the app working as intended.
Closes #913

🌐(frontend) do not report errors related to en-US l10n files

---

CHANGELOG.md
bin/lint-back-diff
src/richie/apps/core/factories.py
src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
src/richie/apps/courses/templates/courses/cms/blogpost_list.html
src/richie/apps/courses/templates/courses/cms/fragment_blogpost_glimpse.html
tests/apps/courses/test_cms_plugins_blogpost.py
tests/apps/courses/test_templates_blogpost_detail.py
tests/apps/courses/test_templates_blogpost_list.py
tests/plugins/html_sitemap/test_cms_plugins.py

The date displayed on blog posts was their date of creation. DjangoCMS has a publication date feature that allows setting a date of publication and a date of end of publication for a page.
We would like to display the date of publication instead of the date of creation. 
The publication dates should be respected on the news page by hiding blog posts unless the current date is in the publication window configured for its page. 
While working on this feautre, I bumped into 2 small bugs that I fixed:

Display publication date on blogpost

---

CHANGELOG.md
bin/lint-back-diff
src/frontend/scss/templates/courses/cms/_course_detail.scss
src/richie/apps/courses/models/course.py
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/fragment_course_run.html
src/richie/apps/courses/templates/courses/cms/fragment_course_runs_list.html
tests/apps/courses/test_models_course_run.py
tests/apps/courses/test_models_course_state.py
tests/apps/courses/test_templates_course_detail.py
tests/apps/search/test_query_courses.py

Segment course runs according to status on published course detail page. Show less details for ongoing and archived course run. Sections with no course run are not shown. The draft page segments the runs but shows everything.
Separate the course runs according to their state.
- open sub and running
- open/will open sub and upcoming
- closed sub and upcoming/running (less details)
- archived (less details)
- to be scheduled (not shown unless on draft)
The draft page segments the runs but shows everything.
Fixes #574

💄(courses) segment course runs on published course detail page

---

src/frontend/yarn.lock

GitHub pushed a security advisory for one of our transitive dependencies. 
We can fix it by regenerating the lockfile, which will pick up a new version of the relevant dependency.

Regenerate yarn.lock to fix security advisory

---

CHANGELOG.md
setup.cfg

Django 3.0 is out but not supported yet by DjangoCMS so we need to make sure we stay on Django 2.x versions.
Add a requirement "Django<3.0" in backend dependencies.

📌(backend) pin Django to less than 3.0

---

CHANGELOG.md
src/frontend/babel.config.js
src/frontend/js/index.tsx
src/frontend/js/types/libs/mdn-polyfills/index.d.ts
src/frontend/js/types/libs/whatwg-fetch/index.d.ts
src/frontend/package.json
src/frontend/webpack.config.js
src/frontend/yarn.lock
src/richie/apps/core/templates/richie/base.html

Richie is not IE11 ready. One of the major parts that did not work with outdated browsers was the JS, which needed to be built specifically to support it.

Update our JS to support IE11 and old browsers

---

CHANGELOG.md
src/richie/apps/courses/settings/__init__.py

We want to allow minimal formatting on these 3 sections. The plain text did not allow line breaks.

🔧(courses) allow CKEditor on course format, prerequisite and assessment

---

CHANGELOG.md
src/richie/apps/search/indexers/courses.py
src/richie/plugins/simple_picture/helpers.py
tests/apps/search/test_indexers_courses.py
tests/plugins/simple_picture/test_helpers.py

Our simple plugin's `get_picture_info()` helper operated on the assumption that an Picture has a picture attribute, with a FileImage.
Depending on how actual users use the back-office, it is possible to create Picture instances that are missing this. This caused the helper to raise an error and crash the ES index generation.
We added a test to reproduce this issue and solved it by simply bailing out at the top if there is no image as `get_picture_info()` has pretty much nothing to return then.

🐛 Fix an issue with get_picture_info when there is no image

---

CHANGELOG.md
src/richie/apps/search/apps.py
src/richie/apps/search/index_manager.py
src/richie/apps/search/management/commands/bootstrap_elasticsearch.py
src/richie/apps/search/models.py
src/richie/apps/search/signals.py
tests/apps/search/test_autocomplete_categories.py
tests/apps/search/test_autocomplete_courses.py
tests/apps/search/test_autocomplete_organizations.py
tests/apps/search/test_autocomplete_persons.py
tests/apps/search/test_commands_bootstrap_elasticsearch.py
tests/apps/search/test_index_manager.py
tests/apps/search/test_partial_mappings.py
tests/apps/search/test_query_categories.py
tests/apps/search/test_query_courses.py
tests/apps/search/test_query_courses_edge_cases.py
tests/apps/search/test_query_courses_facets.py
tests/apps/search/test_query_organizations.py
tests/apps/search/test_query_persons.py
tests/apps/search/test_signals.py

Fixes #939.
In some instances, Richie can end up with an ElasticSearch that contains broken indices, with each index's expected alias as an index name. This can happen for example if the signals that are tasked with updating courses, organizations, etc. are happening in a state where the `bootstrap_elasticsearch` command was not run.
ES then implicitly creates the index for the object we're trying to update.
This caused `bootstrap_elasticsearch` to fail when attempting to create an alias with the same name as an existing index.
We replaced two heavily mocked tests with an entirely non-mocked one that should cover the same code surface with more confidence.
We also touched up on the code in the index_manager module, eg. fixing a small bug we encountered and replacing format calls with f …

🐛 Fix invalid alias name bug during `regenerate_indexes`

---

CHANGELOG.md
src/frontend/js/components/Root/index.spec.tsx
src/frontend/js/components/Root/index.tsx
src/frontend/js/components/Search/_styles.scss
src/frontend/js/components/Search/index.spec.tsx
src/frontend/js/components/Search/index.tsx

Our main `<Search />` component was previously simply ignoring errors, instead just keeping the loading spinner. This is far from ideal as users are left wondering what is happening.
We just added a case in our component to display an error message when the API search request on courses fails.
We also took this opportunity to fix a small mishap with `__richie_frontend_context__` handling.
Closes #938.

🥅 Improve error handling in <Search /> component

---

CHANGELOG.md
src/richie/apps/search/indexers/courses.py
tests/apps/search/test_indexers_courses.py
tests/apps/search/test_query_courses.py
tests/apps/search/test_viewsets_courses.py

Fixes #950.
Indexation in ElasticSearch used the order of courses as returned by the `course.get_organizations()` method to get the main organization for the course. This worked with a past implementation of this method but does not work with the current implementation, that does not order the organizations by placeholder position.
The correct method to use to determine the main organization is `course.get_main_organization`. 
Update the courses indexer helpers that put and retrieve objects to and from the index to make sure they get the expected organization as highlighted organization.

🐛 Make sure the correct org is highlighted on courses in Search

---

CHANGELOG.md
UPGRADE.md
sandbox/settings.py
src/richie/apps/search/defaults.py
src/richie/apps/search/index_manager.py
src/richie/apps/search/indexers/categories.py
src/richie/apps/search/indexers/courses.py
src/richie/apps/search/indexers/organizations.py
src/richie/apps/search/indexers/persons.py
tests/apps/search/test_index_manager.py
tests/apps/search/test_viewsets_categories.py
tests/apps/search/test_viewsets_courses.py
tests/apps/search/test_viewsets_organizations.py
tests/apps/search/test_viewsets_persons.py

ElasticSearch index names are hardcoded in their respective indexers.
There is a `richie_` prefix that should prevent conflicts with other applications running on the same ElasticSearch instance, but that still prevents more than one instance of Richie to run on the same ElasticSearch, as indices would share names.
We can make this changeable through the settings and an environment variable, using `richie_`as a default so it's not a breaking change for existing users.
Closes #940.
Note: rebased on #941 to avoid pointless conflicts as it affects the same files.

🔧 Variabilize ES index names through settings

---

CHANGELOG.md
src/richie/apps/courses/models/blog.py
tests/apps/courses/test_models_blogpost.py

We want to display, in the side column of the blogpost detail page, a list of related blogposts. 
I propose to add a method to retrieve the list of blogposts that share at least one category with the current blogpost.

✨(blogposts) add method on blogpost model to retrieve related blogposts

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/course_run_detail.html
src/richie/apps/courses/templates/courses/cms/fragment_course_run_breadcrumb.html
tests/apps/courses/test_templates_course_run_detail.py

Is an answer to issue #415 where we need a way to return to the course-run-detail page from the course run page including from snapshoted course run.
create a special breadcrumb layout for course run pages to
take into account snapshots.

💄(layout) unique breadcrumb layout for course run page

---

CHANGELOG.md
src/richie/apps/courses/models/course.py
tests/apps/courses/test_models_course.py
tests/apps/courses/test_models_organization.py

When manipulating organizations and courses programmatically, it was possible to unintentionally generate duplicate permissions. We should prevent that.
This issue does not affect creating organizations and courses via the DjangoCMS wizards.

🐛(permissions) prevent creating duplicate permissions programmatically

---

CHANGELOG.md
src/richie/apps/core/models.py
src/richie/apps/courses/cms_plugins.py
src/richie/apps/courses/models/blog.py
src/richie/apps/courses/models/category.py
src/richie/apps/courses/models/course.py
src/richie/apps/courses/models/organization.py
src/richie/apps/courses/models/person.py
src/richie/apps/courses/models/program.py

The name and description of plugins below a placeholder in the side toolbar was not helpful. 
We should display the page title preceded by an indication of the type of the plugin that should be as short as possible to leave as much space  as possible for the page title.  Hence the use abbreviations.

🚸(toolbar) improve plugin description displayed in side toolbar

---

UPGRADE.md
sandbox/settings.py
src/richie/apps/core/context_processors.py

Since the latest release the frontend context processor was added.  It constitutes a breaking change because this context processor is required.
I propose to group all context variables under one single existing context processor so that projects using richie don't need to add multiple context processors to their project just for richie when they are in fact all required.

♻️(core) remove context processor that was added since latest release

---

CHANGELOG.md
src/frontend/js/components/SearchSuggestField/index.spec.tsx
src/frontend/js/components/SearchSuggestField/index.tsx

Course search had an issue where filters were lost in some cases when the user typed in a full-text search. This was due to the use of a ref in the <SearchSuggestField /> component which resulted in an outdated function with an old closure being used.
Remove the ref which as a premature attempt at optimization.
We had some issues when trying to build tests to show this issue was resolved. We had to refactor the tests to handle history mocking differently and stop mocking our own History providing hook,
mocking only the browser's interface.

🐛Fix an issue with full-text search in course search

---

CHANGELOG.md
src/frontend/js/components/SearchFiltersPane/_styles.scss
src/frontend/js/components/SearchSuggestField/index.spec.tsx
src/frontend/js/components/SearchSuggestField/index.tsx

Richie's search engine has a "Clear active filters" link that removes all current filters from the search, including full-text search.
Until now however, it did not clear the actual text in the input field, it only removed the query from the search.
The <SearchSuggestField /> component has no way to know another component did a "FILTER_RESET" or changed the query.
Instead of adding costly plumbing for this, we decided <SearchSuggestField /> can instead just 
clear its own value when it notices the previous courseSearchParams had a query and the incoming ones have not.
We just have to use a ref to keep courseSearchParams N-1 around and do the comparison.
We also added a test to ensure this fixed behavior persists through future changes.
Fixes #978.

🐛 Empty the search input field when the filters are cleared

---

CHANGELOG.md
src/frontend/js/components/SearchSuggestField/index.spec.tsx
src/frontend/js/components/SearchSuggestField/index.tsx

Our full-text search API endpoint only accepts strings of 3 characters or more. This does not include white space. For instance, "ric" is a valid search query, but "ri " is not.
This was not reflected in our frontend check, which just looked at the string length.
We just have to trim the string before doing this check to ensure the query is valid. Also add a test for this behavior.

🐛 Fix an issue with whitespace in short search strings

---

UPGRADE.md

We forgot to update UPGRADE.md when releasing v1.16 and v1.17.
Group upgrade instructions under 1.16.x and 1.17.x titles.

📝(upgrade) add missing release markers to UPGRADE.md

---

CHANGELOG.md
src/frontend/scss/objects/_course_glimpses.scss

Since we recently remove course glimpse footer possibility to have a
"call to action" button, it is useless to keep footer date on two lines.
This commit fix the CSS so the footer date always fit on a single line.

👌(course) enforce course glimpse to be on single line

---

CHANGELOG.md
src/richie/plugins/section/migrations/0005_migrate_sectionlist_to_nesteditem.py

Migration "0005_migrate_sectionlist_to_nesteditem" has been done
planning to migrate section with deprecated template to a nesteditem
which was finally canceled, but there is still a dependency to
nesteditem initial migration that will cause trouble on migration on 
existing database.
We just remove the dependancy that should fix the issue without any change.

🐛(section) remove useless dependency to nesteditem migration

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
src/richie/apps/courses/templates/courses/cms/course_detail.html

In different projects using Richie, we need to override parts of the blog post detail page.
Add blocks around each part of the blogpost detail page to make it easier to override it.
Part of https://github.com/openfun/richie/issues/769

🎨(blogposts) add blocks to each part of the blogpost detail template

---

CHANGELOG.md
src/richie/apps/search/defaults.py
src/richie/apps/search/forms.py
tests/apps/search/test_forms_search_courses.py
tests/apps/search/test_forms_search_items.py
tests/apps/search/test_viewsets_categories.py
tests/apps/search/test_viewsets_organizations.py
tests/apps/search/test_viewsets_persons.py

Each field defines its own default search analyzer in its mapping (or defaults to the content analyzer if a specific search query analyzer is not defined). This is appropriate in principle but it
breaks down when we attempt to do multilingual searches: search queries are then analyzed using the field's analyzer or search analyzer, which might be in the wrong language, and give terrible results for the search query.
To prevent this from happening, we decided to enforce an analyzer at query time. If we can find an appropriate analyzer, it can then be used before searching even in indices in other languages.
To best find this appropriate analyzer, we let the frontend client pass us a preferred query language, which it can determine by guessing and offering guesses to the user to help them, …

✨ Improve query analyzer language selection

---

CHANGELOG.md
src/frontend/js/components/PaginateCourseSearch/index.spec.tsx
src/frontend/js/components/PaginateCourseSearch/index.tsx
src/frontend/js/components/RootSearchSuggestField/index.spec.tsx
src/frontend/js/components/Search/index.spec.tsx
src/frontend/js/components/Search/index.tsx
src/frontend/js/components/SearchFilterGroup/index.spec.tsx
src/frontend/js/components/SearchFilterGroupModal/index.spec.tsx
src/frontend/js/components/SearchFilterGroupModal/index.tsx
src/frontend/js/components/SearchFilterValueLeaf/index.spec.tsx
src/frontend/js/components/SearchFilterValueParent/index.spec.tsx
src/frontend/js/components/SearchFilterValueParent/index.tsx
src/frontend/js/components/SearchFiltersPane/index.spec.tsx
src/frontend/js/components/SearchFiltersPane/index.tsx
src/frontend/js/components/SearchSuggestField/index.spec.tsx
src/frontend/js/components/SearchSuggestField/index.tsx
src/frontend/js/data/useCourseSearchParams/computeNewFilterValue.ts
src/frontend/js/data/useCourseSearchParams/index.spec.tsx
src/frontend/js/data/useCourseSearchParams/index.ts
src/frontend/js/data/useFilterValue/index.spec.tsx
src/frontend/js/data/useFilterValue/index.ts
src/frontend/js/data/useHistory/index.spec.tsx
src/frontend/js/data/useHistory/index.ts
src/frontend/js/settings.ts

Fixes #998.
A bug was introduced that prevented course search from scrolling to the top on page change in course search.
In addition to fixing that bug, we decided to experiment (as mentioned in #998) with scrolling to the top when the user interacts with filters in the filters pane.
To make all of that work smoothly, we made some changes around course search params & actions:

Scroll to top in course search on most user actions

---

CHANGELOG.md
setup.cfg
src/frontend/package.json
tests_e2e/package.json
website/package.json

- New integration for nested items and glimpse plugins
- Add glimpse plugins to the course information placeholder on demo site
- Refactor nested items to simplify them
- Remove the "suggested by" sentence from course detail view
- Allow removing the contact us button in a theme
- Center organizations on course detail view
- Scroll course search to top when the user interacts with the filters pane.
- Increase default course search results number from 20 to 21.
- Invert course description and introduction blocks

🔖(chore) bump version to 2.0.0-beta.6

---

CHANGELOG.md
src/richie/apps/core/templates/richie/base.html

We want to make it easier to override the `contact us` button in the topbar.
Wrap the `contact us` button in a template block.

✨(core) allow customizing topbar contact button

---

CHANGELOG.md
src/frontend/js/components/CourseGlimpse/index.tsx
src/frontend/js/components/Root/index.tsx
src/frontend/js/components/SearchFilterValueLeaf/index.tsx
src/frontend/js/components/SearchSuggestField/index.spec.tsx
src/frontend/js/data/useCourseSearchParams/index.spec.tsx
src/frontend/js/data/useHistory/index.spec.tsx
src/frontend/js/data/useHistory/index.tsx

We were noticing some performance issues with Richie's Search. We were able to find a lot of pointless renders by using the React profiler.
We went through the lowest hanging fruits:
- memoize `<CourseGlimpse />` and `<SearchFilterValueLeaf />`, which are the two most common components in our app and are easy to skip
- stop re-rendering `<Root />`, which is very expensive and we never really need to re-render anyway

⚡️Improve <Search> performance

---

CHANGELOG.md
src/richie/apps/courses/settings/__init__.py

Glimpse plugins were added for use in the course information placeholder
they should be allowed by default in this placeholder.
Add `GlimpsePlugin` in `course_information` placeholder in default Richie settings.

🔧(courses) allow glimpse plugin in course information

---

CHANGELOG.md
src/frontend/scss/components/templates/richie/large_banner/_large_banner.scss
src/frontend/scss/settings/_colors.scss
src/richie/apps/demo/defaults.py
src/richie/plugins/large_banner/forms.py
src/richie/plugins/large_banner/templates/richie/large_banner/hero-intro.html

We need to fit a little bit more closer to the mockups for the hero
variant.
Title field is not used anymore from this variant template. We
expect the title to be add in content and apply a classname
"hero-intro__title" instead. We level up the CKEditor config for
large_banner plugin so now we can add title elements and edit HTML.
Finally, added some CSS changes, added
alternative color for strong element in title and pushed content
near to the top and search bar near to the bottom.

💄(plugins) large_banner hero variant refinement

---

CHANGELOG.md
src/frontend/scss/components/templates/courses/cms/_homepage.scss
src/richie/apps/demo/defaults.py

According to homepage mockup, the first three course glimpses should
be on three columns, then following glimpses should return to the
basic 4 columns behavior.
This commit update the "home_courses" number from demo to 7 objects
and added special homepage modifier for first three course glimpses
to be on three columns.

💄(homepage) first course glimpses on three columns on homepage

---

CHANGELOG.md
src/frontend/scss/components/templates/courses/cms/_category_detail.scss
src/frontend/scss/components/templates/courses/cms/_organization_detail.scss

There is a bug with CSS transform "scaleX(-1)" (to horizontally flip
an element) when browser view is zoomed. This is visible only on
category and organization details banner, the wave decoration is
displaced for one pixel and so does not cover completely the
background image.
Since this is a bug with from every browser we are not able to patch
it directly. So we just removed the scaleX usage and wave go back to
the original direction as everywhere else.

👌(layout) fix glitch with "scaleX" usage on wave decoration

---

.circleci/config.yml

The richie docker image for demo is now built with all our other sites at: https://github.com/openfun/richie-site-factory.

🔥(circleci) remove publication to Docker hub

---

CHANGELOG.md
src/frontend/scss/components/templates/richie/section/_section.scss

Vertical alignment was not really correct for content in category
glimpses in section tiles.
This commit just fix this behavior in Section Sass source so content
is aligned to the top.

👌(section) fix alignment for category glimpses in section tiles

---

CHANGELOG.md
src/frontend/scss/settings/_colors.scss

From mockup, content titles in course detail should be a neutral dark
color except for the "plan" accordion which still in primary color.
This commit just change the color from theme, other richie projects
will have to update it also in their own theme if needed.

👌(layout) change course detail content titles to neutral dark color

---

CHANGELOG.md
src/frontend/scss/components/templates/courses/cms/_course_detail.scss
src/frontend/scss/settings/_colors.scss
src/richie/apps/core/static/richie/images/components/checkmark.svg

From mockups, bullet lists in "course_skills" placeholder from course
details have a specific layout with colored checkmark instead of
disc. This was missing from integration.
This commit add a checkmark image file, some CSS specific to course
skills content and a new property "checkmark-list-decoration" in
theme group "course-detail".

👌(layout) add checkmark icon to course skills bullet lists

---

CHANGELOG.md
src/frontend/scss/components/templates/courses/cms/_course_detail.scss
src/frontend/scss/components/templates/richie/nesteditem/_nesteditem.scss
src/richie/apps/core/templates/richie/base.html

Accordion left border which make the path between item dots was
ending too far compared to mockup. This was due to CSS techniques
and HTML structure.
This commit just fix this with additional line in accordion
Javascript code to add an attribute on item so we can match
something in CSS and avoid border line to continue after the dot
when not opened. Also this adjust some margin on checkmark list from
previous commit 5d3b383.

👌(layout) fix accordion border line

---

CHANGELOG.md
src/frontend/scss/_main.scss
src/frontend/scss/trumps/_cms.scss

CMS page placeholders menu put the plugin name and plugin object
title on the same line to save vertical space at the cost
of readability. It comes quickly to unreadable plugin labels and
leaded to shortenize plugin names that was not intuitive.
This commit hack the CMS placeholder menu CSS to change this
behavior to stacked plugin name and object title on their own line.
With some adjustments to preserve some vertical space it free some
horizontal space so the plugin name can display a long name and
object title can be longer and more accurate.

👌(layout) customize CMS placeholder menu for more readability

---

CHANGELOG.md
src/frontend/scss/components/templates/richie/section/_section.scss

Recently Section plugin has been allowed to include simple text and
image in its content items on course_information placeholder. This
new configuration was not correctly integrated and so direct block
element (paragraph, list, images, etc..) was incorrectly
horizontally centered.
This commit fix the behavior for direct block element in section
contents in its Sass component.

👌(section) fix basic block element alignment in section

---

CHANGELOG.md
src/frontend/scss/objects/_course_glimpses.scss

In course glimpses, category cartouche have too much padding and font is in
bold, opposed to mockup which was mocking a less bigger cartouche without
bolded font.
Here we just fix these minor issue in course glimpse Sass.
A screenshot for sample (left for this PR display and right for current invalid layout):

👌(course) make course glimpse category cartouche less "aggressive"

---

CHANGELOG.md
Makefile
sandbox/settings.py
sandbox/urls.py
setup.cfg
src/richie/apps/core/backends.py

We want to connect richie with Open edX.The first step is to allow SSO connections between the two projects.
This is a port of the work done by @jmaupetit in our site factory repository: https://github.com/openfun/richie-site-factory/pull/26.
We use [python social auth](https://github.com/python-social-auth/social-app-django) and provide 2 backends for edX: oauth2 and OIDC. Which backend you should use, depends on the version of Open edX you are running.

✨(core) add social authentication backends for Open edX

---

CHANGELOG.md
src/frontend/scss/components/_content.scss
src/frontend/scss/components/_header.scss
src/frontend/scss/components/templates/courses/cms/_category_detail.scss
src/frontend/scss/components/templates/courses/cms/_organization_detail.scss
src/frontend/scss/components/templates/richie/large_banner/_large_banner.scss
src/frontend/scss/components/templates/richie/nesteditem/_nesteditem.scss
src/frontend/scss/objects/_breadcrumbs.scss
src/frontend/scss/settings/_variables.scss

Page detail main title is too big, this especially obvious when text
is longer than four words. 
Also since working on recent refinements and fixes, some minor issues have been found with some responsive behaviors.
This commit fix these issues (only Sass sources have been changed
without changes on theme):
- Lowered down global 'h1' and 'h2' font size and added new
'extra-font-size' variable with previous h1 value.
- Adjust title size 'large_banner' variants.
- Fix accordion button 'nested-item__title' alignment to the left.
- Another attempt to definitively fix the glitch with wave decoration
and Chrome zoom/unzoom.
- Add a little bit of space between banner and title on organization
and category detail.
- Fix header menus align/position between breakpoint 'md' end and
'lg' start.
- Fix …

👌(layout) lower page detail title and other minor issues

---

CHANGELOG.md
src/frontend/scss/components/_footer.scss
src/frontend/scss/components/templates/richie/nesteditem/_nesteditem.scss

When implemented, nesteditem list variant has been done only to cover
the specific behavior for footer menu which is a horizontal menu. But
finally this variant is expected to act like a common bullet list and
horizontal menu is reserved only for footer.
This commit just fix this behavior without any layout change, just
the horizontal menu keep working in footer and other list variant
usage elsewhere act like a common bullet list like in course plan.

💄(nesteditem) fix nesteditem list variant to act like a basic list

---

CHANGELOG.md
src/frontend/js/components/SearchSuggestField/index.spec.tsx
src/frontend/js/components/SearchSuggestField/index.tsx

When we added tracking of the last dispatched action(s) to our state setup, we refactored <SearchSuggestField /> to use that to determine when to empty itself in reaction to "filterReset" actions, instead of the previous approach of guessing based on a comparison between current values and values during the previous render.
However, we did not take into account that leaving the check in the body of the component, it would be executed on each render and prevent any value from being entered after a "filterReset" action was issued.
We can solve it by placing the check & clear in a useEffect that only runs when the last dispatched actions change. This way it will react to incoming action by checking if it needs to empty itself, but not even run the check if there is no new action and the user …

🐛 Fix the broken course search field after filters are reset

---

docker-compose.yml

During development, it is generally useful to enable live-debugging in the running container. By default, docker/compose prevents us from attaching to the debugger.
Enabling these two settings simply allows `docker attach` to connect to eg. the live python debugger and should not have any side-effects anywhere else as this docker-compose config is only used in development.

🔨 Enable live-debugging in app container

---

CHANGELOG.md
src/frontend/js/components/Spinner/_styles.scss
src/frontend/js/components/Spinner/index.tsx
src/frontend/scss/_main.scss

Merge spinner related fixes from #1034.
As we worked on course run enrollments, we fixed `<Spinner />` and made some improvements. We're proposing to merge them here as #1034 is now not intended to be merged (or at least not for a while).

🐛 Fix spinner styles & improve a11y

---

src/frontend/jest.config.js
src/frontend/js/components/CourseGlimpse/index.spec.tsx
src/frontend/js/components/CourseGlimpseList/index.spec.tsx
src/frontend/js/components/PaginateCourseSearch/index.spec.tsx
src/frontend/js/components/RootSearchSuggestField/index.spec.tsx
src/frontend/js/components/Search/index.spec.tsx
src/frontend/js/components/SearchFilterGroup/index.spec.tsx
src/frontend/js/components/SearchFilterGroupModal/index.spec.tsx
src/frontend/js/components/SearchFilterValueLeaf/index.spec.tsx
src/frontend/js/components/SearchFilterValueParent/index.spec.tsx
src/frontend/js/components/SearchFiltersPane/index.spec.tsx
src/frontend/js/components/SearchSuggestField/index.spec.tsx
src/frontend/js/components/UserLogin/index.spec.tsx
src/frontend/js/data/getResourceList/index.spec.ts
src/frontend/js/data/useStaticFilters/index.spec.tsx
src/frontend/js/utils/tests/Deferred.tsx

`testing-library` has evolved quite a bit since we started writing our tests using it. Some of our stuff is now triggering deprecation warnings. 
We went through the codebase to remove warnings and keep things up to date.
Note: we could also replace render destructuring with the use of `screen.getBy*` methods but this is a larger task as it's also an opportunity to add testing based on accessible roles and names, which we'll be doing separately later on.

Upgrade testing library practices

---

.circleci/config.yml
CHANGELOG.md
docker-compose.yml
sandbox/settings.py
setup.cfg
src/richie/apps/core/cache.py
tests/apps/core/test_cache.py

We want to enable Django caching features in production and use Redis (with Sentinel support) as a cache backend.
Use [django-redis](https://github.com/jazzband/django-redis) library and add support for Redis Sentinel with a [custom client class](https://github.com/lamoda/django-sentinel).

✨(core) add a plugin for django-redis that supports Redis Sentinel

---

CHANGELOG.md
sandbox/settings.py

We want to be able to configure django cache settings with environment variables.

✨(sandbox) allow to configure cache settings with environment variables

---

bin/pytest
docker-compose.yml

The `make test-back` command fails randomly with the following errors : 
- `No master found for mymaster`
- `Error 111 connecting to x.x.x.x:6379. Connection refused.`
This happens for the following reasons:
- when containers are restarted by `docker-compose`, their IP change 
- the `redis-sentinel` container is persisting the redis master IP across restarts
As a result, sentinel sometimes try to monitor the wrong container (i.e. postgresql) as the redis master and constantly fail.

🐛(docker) fix inconsistent sentinel state when running tests

---

CHANGELOG.md
setup.cfg
src/frontend/package.json
tests_e2e/package.json
website/package.json

There is a typo in python dev dependencies. As a result, we were
unable to upload the release 2.0.0-beta.10 to PyPI.

🐛(dependencies) fix typo in python dev dependencies

---

CHANGELOG.md
src/frontend/js/components/CourseRunEnrollment/index.spec.tsx
src/frontend/js/components/CourseRunEnrollment/index.tsx
src/richie/apps/core/templates/richie/base.html
src/richie/apps/courses/templates/courses/cms/fragment_course_run.html
tests/apps/courses/test_templates_course_detail.py

For anynomous users, the enroll button was disabled and a help text
displayed to inform the user to sign up or log in first. We change with
an active button which send the user to the log in page. The user is
redirected to the course page once connected.

♻️(courses) change CTA button for anonymous users

---

CHANGELOG.md
src/richie/apps/courses/settings/__init__.py

There is a limit on the number of characters that this placeholder can receive, which only makes sense if the number of plugins is
also limited to one.
Limit number of text plugins to 1 in the course description placeholder.

🔧(cms) limit number of plugin in course description to one

---

CHANGELOG.md
sandbox/settings.py
src/richie/apps/core/backends.py

in richie.core.backends module we want to configure EDX_USER_PROFILE_TO_DJANGO
setting. We try to pick it in django.conf.settings and fallback to a
default value if not configured.

✨(back) allow to configure EDX_USER_PROFILE_TO_DJANGO setting

---

CHANGELOG.md
src/frontend/js/components/Search/index.spec.tsx
src/frontend/js/components/Search/index.tsx
src/frontend/js/data/useCourseSearchParams/index.spec.tsx
src/frontend/js/data/useCourseSearchParams/index.ts

Currently, on the course search page, when user filters courses, UI scrolls to top directly on filter change. But in some case (e.g: if the network is slow), new courses has not been yet retrieved and it causes flickering that may be disappointing for the user.
Related to #1103

🚸(Search) scroll after course fetching

---

CHANGELOG.md
src/richie/apps/core/backends.py

When EDX_USER_PROFILE_TO_DJANGO is adding in the settings but without
default value, its value will be an empty dict. To avoid this we change
how default value is set.

🐛(back) fix how EDX_USER_PROFILE_TO_DJANGO default value is set

---

CHANGELOG.md
src/frontend/scss/components/_footer.scss
src/frontend/scss/components/_header.scss

When the language selector is displayed in the footer/header, it must adapt to its surroundings by using appropriate colors. (otherwise it might appear black on black, or white on white). This mostly goes for the text, which appears directly on the background of the footer/header.
To achieve this, we can use variables from sass theming when defining language selector colors. This is only used for the button which is integrated into its parent element. The dropdown itself has its own background.

🐛 Use variables for language selector colors

---

src/richie/apps/core/templates/richie/base.html

The "powered by" mention was pointing to the github repository, which is only good for developpers.
Point to the https://richie.education site.

👽(project) point powered by to https://richie.education

---

src/frontend/scss/components/_footer.scss
src/frontend/scss/objects/_selector.scss

The language selector arrow in the footer has not the good color.
`.language-selector` was renamed into `.selector` and Footer styles had not been updated accordingly.

💄(frontend) fix selector arrow color in footer

---

README.md

Now that we have added OpenEdX to our [demo site](https://demo.richie.education), the login is done via SSO on OpenEdX. On the LMS, the login is the email address.
Update login instructions in the README.

📝(readme) update demo login instructions after adding OpenEdX SSO

---

CHANGELOG.md
src/richie/apps/demo/defaults.py
src/richie/apps/demo/management/commands/create_demo_site.py
tests/apps/demo/test_commands_create_demo_site.py

Some customizations that we make in themed sites using richie (cf https://github.com/openfun/richie-site-factory) are breaking the demo site. It makes it difficult to work on such sites in development if we can't generate a demo site.

Demo site: allow removing licences placeholders and customizing pages info

---

docs/frontend-overrides.md
src/frontend/.eslintrc.json
src/frontend/js/index.tsx
src/frontend/package.json
src/frontend/webpack.config.js
src/frontend/yarn.lock
src/richie/apps/core/templates/richie/base.html
website/sidebars.json

As we worked on some of our Richie sites, we notice the dependent builds were broken, and some documentation was missing for frontend overrides.

Enable frontend overrides

---

CHANGELOG.md
src/frontend/jest.config.js
src/frontend/js/utils/errors/handle.spec.ts
src/frontend/js/utils/errors/handle.ts
tests/apps/core/test_pages.py

The path to get context from __richie_frontend_context__ was wrong so context variable was always undefined. In this way, Sentry was never initialize.

🐛 (frontend) handle error invalid configuration

---

CHANGELOG.md
src/frontend/scss/components/_footer.scss
src/richie/apps/core/templates/richie/base.html

The copyright notice is something specific to each site. Let's not propose anything in richie templates but just a template block to
add it if necessary.

🔥(core) remove copyright notice from footer in base template

---

CHANGELOG.md
sandbox/settings.py
src/richie/apps/core/cache.py
tests/apps/core/test_cache.py

By default, DjangoCMS sends cached responses with a `Cache-control: max-age` value reflecting the server cache TTL.
The thing is : the server side cache entry get invalidated each time a user publishes new content to the site, but we cannot invalidate our client browser cache entries. That's why we want to set a long TTL on the server side, but a much lower TTL on the browser cache.

✨(back) add LimitBrowserCacheTTLHeaders middleware

---

.circleci/config.yml

Docker will start a rate limit on pulling images on docker hub. This rate
limit is based on the IP used for anonymous users, this is the CircleCI IP
that will be used so the rate limit will be reached quickly. If the image pull
is made with a connected user, the rate limit becomes a per-user rate so we
should not reach it once connected.

♻️(ci) stop pulling images anonymously

---

CHANGELOG.md
src/richie/plugins/simple_text_ckeditor/forms.py
src/richie/plugins/simple_text_ckeditor/validators.py
tests/plugins/simple_text_ckeditor/test_forms.py
tests/plugins/simple_text_ckeditor/test_validators.py

CKEditor is submitting text with web entities (e.g. `&eacute;` for `é`) and potentially exotic characters. Our support team complained that the count of the max number of characters was wrong. 
This commit fixes it by normalizing and unescaping input strings. We do it for counting and also before saving it to database.

🚸(plugins) improve sanitizing of input text on CKEditor plugin

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/blogpost_list.html
src/richie/apps/courses/templates/courses/cms/organization_list.html
tests/apps/courses/test_templates_organization_list.py

Unpublished organizations were showing on the public version of the organizations list page. We should only show them to staff users.

🐛(organizations) fix organizations list page hiding unpublished

---

CHANGELOG.md
src/frontend/scss/components/_footer.scss
src/richie/apps/core/templates/richie/base.html
src/richie/apps/courses/settings/__init__.py
src/richie/apps/demo/defaults.py
src/richie/apps/demo/management/commands/create_demo_site.py

Footer menu items stretchs according to space available on a row which broke
layout if there was few elements on a row.

💄(footer) avoid stretching of footer menu items

---

CHANGELOG.md
src/richie/apps/courses/lms/__init__.py
tests/apps/courses/lms/test_lms_select.py

When a new course run page is created, a blank course run object is created.
But the course run page used has_connected_lms to check if the course run has an
associated known LMS. However the course run is blank, has_connected_lms crashes
because it send None value to LMSHandler.

 🚑(LMSHandler) select_lms returns None if url is blank

---

CHANGELOG.md
src/frontend/js/index.tsx
src/richie/apps/core/templates/richie/base.html

In edit mode, when user saves a modification, the new content is hot replaced
but js scripts are not reinitiliazed. In our case, as we use React, all React
components are not rendered after a content modification in Edit mode.
To solve this issue, Django-CMS provides an event "cms-content-refresh".
https://docs.django-cms.org/en/latest/topics/frontend-integration.html

🐛(frontend) refresh js on cms-content-refresh

---

setup.cfg

Since upgrade of Django CMS to 3.8 and Django 3, we have a log of warnings
during backend tests that pollutes ci stacktrace.
There are two available options: 
First we can use `filterwarnings` to ignore all warnings coming from another packages than richie or tests.
```
filterwarnings = 
ignore:::(?!(tests|richie))
```
On the other hand we can use `--disable-warnings`. In this case, Pytest does not ignore warnings, instead it just does not display details of them in the stacktrace. But If you read the tests resume, you see the number of warnings catched. And locally you can run make test-back and see all details.

✅(pytest) ignore warnings from 3rd party library

---

CHANGELOG.md
setup.cfg
src/frontend/js/components/Spinner/_styles.scss
src/frontend/package.json
src/frontend/scss/objects/_selector.scss
src/frontend/scss/settings/_colors.scss
src/frontend/yarn.lock
src/richie/apps/core/templates/richie/base.html
tests_e2e/package.json
website/package.json

- JS comments was at the wrong place and I didn't catch up this mistake.
- The new sass compiler watch mode is not really powerful and crashes when there is a lot of files to watch.
- Selector and Spinner must use their own color palettes to be customizable on Richie Site Factory.

🔖(patch) bump version to 2.0.0-beta.19

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/person_detail.html
tests/apps/courses/test_templates_person_detail.py

We did not include the "maincontent" placeholder in the page when it was empty, even for staff users. As a result the placeholder
was not functional in the plugin side bar.
Add a condition to add the `mainbody` placedholder in the draft person detail page for staff users, even if the placeholder is empty.

🐛(persons) allow adding plugins to main content when empty

---

CHANGELOG.md
src/frontend/js/components/PaginateCourseSearch/index.tsx

PaginateCourseSearch placeholder used a wrong class name so this element was not styled correctly.

🐛 (frontend) fix layout of PaginateCourseSearch placeholder

---

CHANGELOG.md
env.d/development/dev
env.d/development/dev-ssl
sandbox/settings.py
src/richie/apps/courses/lms/__init__.py
src/richie/apps/demo/management/commands/create_demo_site.py
tests/apps/courses/lms/test_lms_select.py
tests/apps/courses/test_templatetags_extra_tags_has_connected_lms.py

Enrollment widget can fail to enroll if course run resource_link is malformed.

🐛(LMSHandler) check resource_link matches lms COURSE_REGEX

---

CHANGELOG.md
setup.cfg
src/frontend/package.json
tests_e2e/package.json
website/package.json

- Add a frontend API Implementation for OpenEdX Dogwood/Eucalyptus
- Add a new variant "Badge" to glimpse plugin
- Improve the layout of the footer to save space
- Allow ProgramPlugin in SectionPlugin on Homepage
- Allow only one CKEditorPlugin to program_body placeholder
- Fix an issue about PaginateSearchCourse layout
- Prevent enrollment failure if course run's resource_link does not match the
course regexp

🔖(chore) bump version to 2.0.0-beta.21

---

Dockerfile

We submited a fix to djangocms-admin-style project but it is still pending review.
So to enable fix now, we could use our forked version of this package.

📌(djangocms-admin-style) use a forked version waiting next release

---

CHANGELOG.md
setup.cfg
src/frontend/package.json
tests_e2e/package.json
website/package.json

- Refactor course runs to not be CMS pages anymore
- Stop indexing snapshots on signal update
- Fix object names plurals in admin

🔖(chore) bump version to 2.0.0-beta.22

---

CHANGELOG.md
src/richie/apps/courses/admin.py
src/richie/apps/courses/helpers.py
tests/apps/courses/test_admin_course_run.py
tests/apps/courses/test_admin_form_course_run.py

The permissions course run admin pages are only classical django admin model level permissions because CourseRun is now a simple model. We need to limit permissions according to the course page to which a course run is linked.

🔒(courses) add permissions to course run admin

---

CHANGELOG.md
src/richie/apps/courses/factories.py
src/richie/apps/demo/management/commands/create_demo_site.py

The command generating the demo site was failing when "fr" was declared as the primary language.
We were unvoluntarily hardcoding the fact that "fr" was the secondary language.

🐛(demo) fix generate demo site when default language is set to "fr"

---

CHANGELOG.md
src/frontend/js/index.tsx

When intl-relativetimeformat polyfill must be applied, the locale module was
not found. In fact when locale is composed of a languageCode identical
to its countryCode, intl-relativetimeformat locale filename is only languageCode
i.e: if locale is fr-FR related locale filename is fr.js
if locale is fr-CA related locale filename is fr-CA.js

🐛(frontend) fix intlrelativeformat polyfill

---

CHANGELOG.md
sandbox/settings.py

When used in settings file where they are defined, properties ENVIRONMENT and RELEASE
return the property object signature not the value they should return elsewhere.

🐛(settings) sentry dsn is misconfigured

---

CHANGELOG.md
src/frontend/js/components/CourseRunEnrollment/index.spec.tsx
src/frontend/js/components/CourseRunEnrollment/index.tsx
src/richie/apps/courses/templates/courses/cms/fragment_course_run.html
src/richie/apps/courses/templatetags/extra_tags.py
tests/apps/courses/test_templates_course_detail.py
tests/apps/courses/test_templatetags_extra_tags_course_enrollment_widget_props.py

CourseRunEnrollment widget retrieves course run information by making a request to richie course-run api. It is useless as we could pass directly these information through `data-props` attribute.

♻️(CourseRunEnrollment) pass course run data from data-props

---

CHANGELOG.md
src/richie/apps/core/templates/richie/styleguide/index.html
src/richie/apps/core/templates/social-networks/blogpost-badges.html
src/richie/apps/core/templates/social-networks/course-badges.html
src/richie/apps/core/templates/social-networks/footer-badges.html
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html
src/richie/plugins/glimpse/templates/richie/glimpse/glimpse.html
tests/apps/courses/test_cms_plugins_course.py

Since SVG 2, `xlink:href` attribute has been replaced by `href`.
http://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/xlink:href

♻️(templates) remove use of deprecated xlink:href attribute

---

docker-compose.yml

For ouath2 we already allowed richie's development stack to access openedx-docker's development stack. For course runs synchronizations, it is the contrary: openedx-docker's development tack needs to be able
to call richie's course synchronization web hook on the development stack.
Connect nginx in the `lms_outside` network so it can be accessed from outside its docker-compose project with the `richie` host.

✨(development) allow connections from openedx-docker development stack

---

CHANGELOG.md
src/frontend/js/components/PaginateCourseSearch/index.spec.tsx
src/frontend/js/components/PaginateCourseSearch/index.tsx

Pagination course truncate page number where there are too much element to show. But in some case, truncation is not relevant. 
E.g:
Before if we had 5 pages, pagination looked like this:
`Page 1 2 3 ... 5`
Showing the fourth page number is more relevant is this case.

🚸(PaginateCourseSearch) do not truncate pagination if it is not relevant

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/fragment_course_runs_list.html
tests/apps/courses/test_templates_course_detail.py

The template code that was taking care of displaying the course run details with or without a title, was broken in french because the translation included a comma where it shouldn't. It turns out that the implementation is a git too "smart" and thus fragile. 
We refactor it to use a good old "if" clause.

🐛(courses) fix displaying course runs in list on course detail page

---

CHANGELOG.md
src/frontend/scss/components/_subheader.scss
src/richie/apps/courses/admin.py
src/richie/apps/courses/templates/courses/cms/course_detail.html
tests/apps/courses/test_templates_course_detail.py

It was not straightforward to go through the "course settings..." menu item to edit a course code. 
Since this is an important and uniquely defining information about the course, we propose to display it on the
detail page and allow frontend editing.
Fixes https://github.com/openfun/richie/issues/1249

✨(courses) display code on course detail page with frontend editing

---

CHANGELOG.md
src/frontend/scss/components/templates/courses/cms/_course_detail.scss
src/frontend/scss/components/templates/richie/section/_section.scss
src/richie/apps/courses/models/course.py
src/richie/apps/courses/settings/__init__.py
src/richie/apps/courses/templates/courses/cms/course_detail.html
tests/apps/courses/test_models_course.py
tests/apps/courses/test_settings_mixins.py
tests/apps/courses/test_templates_course_detail.py

Courses can be linked on a program detail page. In this case, it is interesting to link the related programs on the page. 
I adapted what had been done to list related courses on an organization detail page.
closes https://github.com/openfun/richie/issues/1237

✨(courses) display related programs on course detail page

---

CHANGELOG.md
Makefile
src/richie/apps/courses/factories.py
src/richie/apps/courses/settings/__init__.py
src/richie/apps/demo/management/commands/create_demo_site.py
tests/apps/courses/test_factories_person.py

Some person pages are in fact collectives. In this case, we want to include thumbnails of the persons in this collective.
Allow the person plugin on the person detail page.
closes https://github.com/openfun/richie/issues/1239

✨(persons) allow linking person plugins on a person's page

---

CHANGELOG.md
src/richie/plugins/glimpse/cms_plugins.py
src/richie/plugins/glimpse/defaults.py
src/richie/plugins/glimpse/templates/richie/glimpse/glimpse.html
src/richie/plugins/glimpse/templates/richie/glimpse/glimpse_person.html
src/richie/plugins/glimpse/templates/richie/glimpse/glimpse_quote.html
tests/plugins/glimpse/test_cms_plugins.py

We want to be able to refer to a person without having to create a person page. 
The glimpse plugin is perfect for this because it has the required fields: avatar, name, bio and link.
I chose to make the glimpse plugin generate the exact same markup as the person glimpse so that the css is entirely shared.
closes https://github.com/openfun/richie/issues/1255

✨(plugins) add a "person" variant to the glimpse plugin

---

CHANGELOG.md
src/richie/plugins/html_sitemap/cms_plugins.py
tests/plugins/html_sitemap/test_cms_plugins.py

Fix HTMLSiteMap plugin when placed in a static placeholder
This is not the preferred use case but it can nevertheless be done and
should not raise a 500 error 😱
Get page from context instead of poking the placeholder (static placeholders are not linked to any page).

🐛(plugins) fix HTMLSiteMap plugin when placed in a static placeholder

---

CHANGELOG.md
src/richie/apps/courses/admin.py
tests/apps/courses/test_admin_course_run.py

In our implementation, we excluded public course runs from the admin queryset. The problem is that, when a user who does not have sufficient permissions, tries to edit a course run, DjangoCMS opens the public version instead of the draft version. Our filtering thus results in a redirect to the admin home page. This is disturbing when we would like to see a permission error.
I proposed to stop filtering course runs in the query.
I noticed that the view list shows all course runs and cannot be secured because DjangoCMS permissions are hard to translate to a query. I think displaying all course runs to any staff users is not a problem if we show them only the `id` field. Of course, the change and delete actions are still subject to further object permissions.

Display 403 error when editing a course run without permission

---

CHANGELOG.md
src/richie/plugins/html_sitemap/cms_plugins.py
tests/plugins/html_sitemap/test_cms_plugins.py

HTMLSiteMap plugin use current_page context property to know if this page is a draft. If this property is not defined in the context, an exception is raised and we got a 500 error.

🐛(cms_plugins) fix HTMLSiteMap plugin when current_page is not defined

---

.circleci/config.yml

People which submit PR through a fork see ci job `docker-build` failed. For security reason, we don't share our CI environment variables with forked PR. This cause an issue on `docker login` because credential variables are not exposed.

💚(ci) fix docker login run with forks

---

CHANGELOG.md
src/frontend/js/components/CourseRunEnrollment/index.spec.tsx
src/frontend/js/utils/api/lms/index.spec.ts
src/frontend/js/utils/api/lms/openedx-hawthorn.spec.ts

When frontend tests are run, as console.error and console.warning are displayed, developer can think that some tests are failing.
Capture console.error and console.warning on concerned tests, and assert they have been called.
Only test displaying errors has been modified for now, but if the approach is ok, remaining test has to be updated as well.
fixes https://github.com/openfun/richie/issues/1263

🚸(frontend) hide console error in tests outputs

---

CHANGELOG.md
UPGRADE.md
sandbox/settings.py
src/frontend/js/components/CourseRunEnrollment/index.spec.tsx
src/frontend/js/components/CourseRunEnrollment/index.tsx
src/frontend/js/components/UserLogin/index.spec.tsx
src/frontend/js/components/UserLogin/index.tsx
src/frontend/js/components/UserMenu/DesktopUserMenu.tsx
src/frontend/js/components/UserMenu/MobileUserMenu.tsx
src/frontend/js/components/UserMenu/index.spec.tsx
src/frontend/js/types/User.ts
src/frontend/js/types/index.ts
src/frontend/js/utils/test/factories.ts
src/richie/apps/core/context_processors.py
src/richie/apps/courses/templatetags/extra_tags.py
tests/apps/core/test_authentication_delegation.py
tests/apps/courses/test_templatetags_extra_tags_course_enrollment_widget_props.py

In openedx, when we try to start a course which is not open yet, we might get a 500 error. The "go to course" button is not displayed in this case, and has been replaced with a dashboard link.
Also, as discussed, profile_urls in settings are stored in a list, which we need to loop on to find a particular url
New prop attributes have been added to CourseRunEnrollment component with a message indicating when the course will start and a dashboard link.
If the message is defined we display the button.
A key has been added to each url in profile_urls settings.
fixes #1260

🐛(frontend) replace "go to course" button with dashboard link for unstarted lms courses and add keys to profile_url settings

---

CHANGELOG.md
src/frontend/js/components/RootSearchSuggestField/index.spec.tsx
src/frontend/js/components/RootSearchSuggestField/index.tsx

When user select a course entry in the autosuggest menu, it should be redirect to the course page and not the search view. As `hasHighlightedSuggestion` state was not set correctly, that was not work.

🐛(frontend) fix autosuggest to redirect directly on course page

---

CHANGELOG.md
setup.cfg

django-treebeard 4.5 release seems introduce a breaking change that leads to
several issues from django-cms concerning PK management. Waiting to identify
the origin of this issue, we pinned django-treebeard to 4.4.

🚑(dependency) pin django-treebeard to 4.4

---

CHANGELOG.md
src/frontend/js/components/CourseRunEnrollment/index.tsx
src/frontend/js/types/Course.ts
src/frontend/js/types/index.ts
src/richie/apps/courses/models/course.py
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/search/forms.py
src/richie/apps/search/indexers/courses.py
tests/apps/courses/test_models_course_run.py
tests/apps/courses/test_models_course_state.py
tests/apps/courses/test_templates_course_detail.py
tests/apps/search/test_query_courses.py

In our catalog, we have the case of archived courses (with past dates) that are still open for enrollment.
This case is used for courses that are not followed by a teachers team but just left open for consultation.
We propose a new course state for these courses: `ARCHIVED_OPEN`
Courses in this state should be well positioned in results:
- just after "future course open for enrollment"
- before "future courses not yet open for enrollment".

✨(courses) add "archived open" state for course runs

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/blogpost_list.html
src/richie/apps/courses/templatetags/extra_tags.py
tests/apps/courses/test_templatetags_extra_tags_order_by.py

We were sorting blog posts as per the page tree to allow drag-and-drop reordering.
However, the DjangoCMS page tree does not scale to a big number of pages and we deactivated digging into blog post pages via the admin on some of our sites.
As a result we needed to find a better way to order blog posts.
The publication date seems like the best ordering criteria for blog posts. It can be changed via the toolbar on a given blog post.

✨(blogposts) order blog posts by reverse publication date on list view

---

CHANGELOG.md
UPGRADE.md
sandbox/settings.py
src/richie/apps/courses/api.py
src/richie/apps/courses/lms/edx.py
tests/apps/courses/test_api_course_run_sync_edx.py

In some case, we would like to protect some fields from update when course run synchronization hook is called.

✨(back) add protected fields to lms backends

---

CHANGELOG.md
sandbox/settings.py
src/richie/apps/search/defaults.py
src/richie/apps/search/forms.py
src/richie/apps/search/indexers/courses.py
src/richie/apps/search/viewsets/courses.py
tests/apps/search/test_autocomplete_courses.py
tests/apps/search/test_forms_search_courses.py
tests/apps/search/test_query_courses.py
tests/apps/search/test_query_courses_edge_cases.py
tests/apps/search/test_query_courses_facets.py
tests/apps/search/test_viewsets_courses.py

Sorting was only taking into account the state of a course's course runs. Now that we have opened enrollment for much more courses (archived yet open), we need to take into account the pertinence score of the fulltext search to try to improve the search experience.
I propose to replace the custom `sorting` script (that was overriding the relevance "_score") by a `score_script` which combines with it.
A weight is associated with each course run state to give it more or less importance. It is adjustable as a setting to fine-tune the search experience depending on real data.

✨(search) take into account search fulltext search score for sorting

---

CHANGELOG.md
src/richie/apps/courses/settings/__init__.py
src/richie/apps/courses/templates/courses/cms/course_detail.html
tests/apps/courses/test_templates_course_detail.py

Display the glimpse used in course_cover if no video in course_teaser is defined, and remove the possibility to add a SimplePicturePlugin plugin to course_teaser placeholder.
SimplePicturePlugin in course_teaser placeholder has been removed.
If no video is present in course_teaser placeholder, image from course_cover placeholder is used instead.
#1297

✨(course_teaser) display cover image by befault

---

CHANGELOG.md
src/frontend/scss/objects/_react-autosuggest.scss

On Firefox, user cannot select text in search input.
A `user-select: none` rule was applied to the search input that makes text
unselectable only on Firefox.
#1302

💄(frontend) fix text selection on search input on firefox

---

CHANGELOG.md
src/richie/apps/courses/models/course.py
src/richie/apps/courses/templates/courses/cms/course_detail.html
tests/apps/courses/test_models_course.py

On one of our sites, we want to display the first open course run in the top header of the course syllabus, and only the remaining ones in the side column.
This will is done via overridding template blocks in [richie site factory](https://github.com/openfun/richie-site-factory) and we will need to call the method "get_course_runs_dict" several times in the template.
This method being very costly, it is a good idea to first make sure that it is cached on the instance: make it a cached property.

⚡️(courses) cache getting course runs dict from the course models

---

CHANGELOG.md
env.d/development/common
src/richie/plugins/lti_consumer/cms_plugins.py
src/richie/plugins/lti_consumer/defaults.py
src/richie/plugins/lti_consumer/factories.py
src/richie/plugins/lti_consumer/forms.py
src/richie/plugins/lti_consumer/models.py
src/richie/plugins/lti_consumer/static/lti_consumer/js/change_form.js
tests/plugins/lti_consumer/test_cms_plugins.py
tests/plugins/lti_consumer/test_factories.py
tests/plugins/lti_consumer/test_forms.py
tests/plugins/lti_consumer/test_models.py

We experienced 3 bugs when trying to run the new LTI consumer plugin in production:
- The edit mode was not passed properly and made the signature wrong
- The "oauth_consumer_key" and "shared_secret" fields on the plugin were not taken into account
- The plugin was raising 500 errors when we tried to update it after creation
I improved the tests to fill the gaps and cover these cases.

🐛(plugins) fix LTI consumer plugin

---

UPGRADE.md

This upgrade instruction was forgotten and we missed it when upgrading our sites to use the new LTI consumer plugin.
Add the missing instruction to the `UPGRADE.md` file.

📝(upgrade) add instruction about the LTI consumer plugin stylesheet

---

CHANGELOG.md
src/frontend/js/components/LtiConsumer/index.tsx

When iframeResizer was enabled, it enforced iframe content width and leads to layout issue on small screens.
Furthermore, option to allow fullscreen was missing.

🐛(frontend) fix lti consumer issues

---

CHANGELOG.md
src/richie/apps/courses/models/course.py
tests/apps/courses/test_models_course.py

When effort unit was hour and pace was under an hour, computation was wrong.

🐛(course) fix pace computation

---

CHANGELOG.md
src/frontend/scss/objects/_program_glimpses.scss
src/richie/apps/courses/templates/courses/cms/fragment_program_glimpse.html

The date displayed on the glimpse was the "creation_date" which is useless. 
The support team requested that it be removed.
Remove program glimpse footer with creation date.

🚸(programs) remove date on program glimpse

---

CHANGELOG.md
UPGRADE.md
sandbox/urls.py
src/frontend/js/components/LtiConsumer/_styles.scss
src/frontend/js/components/LtiConsumer/index.spec.tsx
src/frontend/js/components/LtiConsumer/index.tsx
src/frontend/js/types/LtiConsumer.ts
src/richie/plugins/lti_consumer/api.py
src/richie/plugins/lti_consumer/cms_plugins.py
src/richie/plugins/lti_consumer/models.py
src/richie/plugins/lti_consumer/templates/richie/lti_consumer/lti_consumer.html
src/richie/plugins/lti_consumer/urls.py
src/richie/plugins/urls.py
tests/plugins/lti_consumer/test_api.py
tests/plugins/lti_consumer/test_cms_plugins.py

When the page is cached, LTI Consumer plugin embedded could contain stale oauth parameters that cause authentication failure to the LTI service. To keep a relevant cache duration on our CMS pages, we decided to retrieve the LTI Consumer context through an API endpoint.

🐛(lti_consumer) retrieve context through an api endpoint

---

CHANGELOG.md
src/frontend/js/components/SearchFilterGroupModal/_styles.scss
src/frontend/js/components/SearchFilterGroupModal/index.tsx

There were several issues on `<SearchFilterGroupModal />`, which we're fixing here:
- placeholder and label for the search input were not localized;
- close button created a double border as it overlapped with a list item;
- positioning for the close button was broken in Safari;
- document body kept scrolling even as the modal was opened.
For Safari I moved the scrolling container to the list of items as opposed to the whole modal. I also had to inject the Safari "hack" directly into the DOM as sass does not recognize it as valid CSS.
There's also another issue which I did not address: color contrast for the placeholder is not accessible. There's the same problem on the main search menu. I think both should be addressed together, I was not sure how we want to fix this (white input …

🐛(frontend) fix quality issues with <SearchFilterGroupModal />

---

CHANGELOG.md
src/frontend/js/components/Search/index.spec.tsx
src/frontend/js/components/Search/index.tsx
src/frontend/scss/components/_subheader.scss
src/frontend/scss/components/templates/search/_search.scss

1. The button to open/close filter pane did not (dis)appear on window resize
2. There was quality issues on the search filter pane on handheld devices

🐛(Search) fix filter pane quality issues on handheld devices

---

CHANGELOG.md
src/richie/apps/core/models.py
src/richie/apps/courses/models/blog.py
tests/apps/courses/test_models_blogpost.py

The `get_related_blogposts` method on the blogpost model does not take into account language fallbacks.
Refactor the `get_related_blogposts` method on the blogpost model to take into account language fallbacks.
Write a test to secure this behavior.

✨(blogposts) add language fallback to get_related_blogposts

---

CHANGELOG.md
src/richie/apps/core/templates/richie/base.html

initializeAccordions used js `toggleAttribute` methods which [is not supported on old browsers](https://caniuse.com/?search=toggleAttribute). Sentry reports us that several users still use old browser versions. As accordions are not usable for this user, we have to fix it by using supported methods.
https://sentry.io/organizations/gip-fun-mooc/issues/2337198788/events/5a4bfa3cb94048b287982d58c4e985a1/events/?environment=production&project=1454000

🐛(base) fix initializeAccordions compatibility issue

---

CHANGELOG.md
src/richie/apps/search/filter_definitions/courses.py
src/richie/apps/search/indexers/categories.py
src/richie/apps/search/indexers/courses.py
src/richie/apps/search/indexers/organizations.py
src/richie/apps/search/indexers/persons.py
tests/apps/search/test_query_categories.py
tests/apps/search/test_query_courses_edge_cases.py
tests/apps/search/test_query_organizations.py
tests/apps/search/test_query_persons.py
tests/apps/search/test_viewsets_categories.py
tests/apps/search/test_viewsets_courses.py
tests/apps/search/test_viewsets_organizations.py
tests/apps/search/test_viewsets_persons.py

A course should not get indexed with no titles, but if it does, querying the API should not raise a 500 error.
- Fix source fields definition to include the `title` field even if it's an empty dict.

🐛(search) avoid KeyError when a course is indexed with no titles

---

CHANGELOG.md
src/richie/plugins/lti_consumer/api.py
tests/plugins/lti_consumer/test_api.py

Previously, API endpoint to get lti context was cached for 9.5 minutes which was too long.
So some users can retrieve a stale context.

🚑(LTIConsumer) fix lti context cache duration

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/program_detail.html
tests/apps/courses/test_templates_program_detail.py

To be able to present programs that won't have or doesn't yet have courses
ready to be presented.
Add an if statement to check for course presence

💄(program) make related courses optional for program page

---

docker-compose.yml
docker/files/etc/nginx/conf.d/default.conf

Joanie, Richie and OpenEdX have to run over the same network. But both Richie and Joanie have a service called `app`. From Richie, `nginx` create a reverse proxy resolving urls with the domain `app`. If Joanie is run before Richie, the nginx service use the Joanie app service. To avoid this issue, we could add a network alias to the richie `app` service.
Related to https://github.com/openfun/joanie/pull/26

🔧(docker) use a custom name for the app service on default network

---

src/frontend/js/components/SearchFilterValueParent/index.spec.tsx
src/frontend/js/data/useCourseSearch/index.spec.tsx
src/frontend/js/utils/types.ts

Since @types/jest 24.9.0, `MockedFunction` type is available. So we can remove our own type JestMockOf and use the official MockedFunction type.

🔥(frontend) remove JestMockOf

---

renovate.json
setup.cfg

Following renovate configuration update, instead of ignore dependencies listed in
`excludePackageNames`, Renovate creates a dedicated PR for each of these dependencies.
So to renovate really ignores update of these dependencies we have to create
a dedicated packageRule
Furthermore with this syntax, it's easier to create a generic preset for all our repositories.

🔧(renovate) fix ignored python dependencies

---

CHANGELOG.md
src/richie/apps/core/templates/richie/base.html
src/richie/apps/core/templates/richie/hreflang.html
tests/apps/core/test_pages.py

I noticed that our pages where appearing twice in Google's search results, once per language. The good news is our SEO as skyrocketed, the bad news is we have duplicate content.
This is a well known problem solved by adding `hreflang` metas to all pages.

🔍️(i18n) add "hreflang" meta to avoid duplicates in search engines

---

CHANGELOG.md
src/frontend/js/components/LtiConsumer/index.spec.tsx
src/frontend/js/components/LtiConsumer/index.tsx
src/frontend/js/data/useSession/index.tsx

We would like to monitor which watch marsha video on Richie. In order to achieve this, we pass the username of the logged in user through the LTI context.

✨(frontend) send username to lti consumer if he/she login

---

renovate.json

In order to homegenize dependency management, we created a global  renovate preset which is in charge to upgrade js and python dependencies on our repositories. So on Richie, we have to update our renovate configuration to use
this new preset.

🔧(renovate) use openfun preset

---

CHANGELOG.md
src/richie/plugins/lti_consumer/api.py
tests/plugins/lti_consumer/test_api.py
tests/plugins/lti_consumer/test_models.py

We noticed that when a Marsha LTI consumer plugin is created, all editors on the site can update it regardless of the permissions they have to update this specific page and plugin.
We were granting the LTI `instructor` role as soon as edit mode was on. 
We propose to check plugin update permissions before granting this role and add tests to secure it.

🐛(lti_consumer) fix permissions granting institutor role more carefully

---

CHANGELOG.md
README.md
docs/api/course-run-synchronization-api.md
docs/displaying-connection-status.md
docs/lms-backends.md
docs/lms-connection.md
docs/quick-start.md
docs/synchronizing-course-runs.md
docs/tls-connection.md
sandbox/settings.py
website/versioned_docs/version-2.0.0/lms-connection.md
website/versioned_docs/version-2.0.1/lms-connection.md
website/versioned_docs/version-2.5.0/lms-connection.md

The documentation on how to connect Richie and OpenEdX was only targetting the development environment and many users requested a more complete documentation on how Richie can be connected to OpenEdX in production.
I tried to structure my explanations in 4 separate features:
- Displaying the OpenEdX connection status and user profile information in Richie,
- Enrolling to a course run on OpenEdX without leaving Richie,
- Synchronizing course runs automatically in the Richie catalog each time they are modified in OpenEdX,
- Joanie, enrollment management on steroids.
To view the documentation site as it will look after this PR, pull the branch, `cd` into the `website` directory and run:
```bash
yarn start
```
Then head over to the documentation site on `localhost:3000` and select the …

📝(richie) add documentation to connect Richie with OpenEdX

---

CHANGELOG.md
src/frontend/js/components/LtiConsumer/_styles.scss
src/frontend/scss/components/_subheader.scss

On Safari, when user launches course teaser in fullscreen mode some DOM elements
appear on the top of the video. It was due to a bug with Safari related to the
animation fill mode applied to the teaser container.
Also on Safari, a second layout bug has been found. An offset was applied to the iframe container when its content loaded.

🐛(frontend) fix fullscreen layout on safari

---

CHANGELOG.md
renovate.json
setup.cfg

[DjangoCMS 3.9.0](https://github.com/django-cms/django-cms/releases/tag/3.9.0) was released on June 29, 2021. We want to upgrade Richie to this version of DjangoCMS.

⬆️(cms) upgrade DjangoCMS to version 3.9.0 and Django to version 3.2.6

---

CHANGELOG.md
src/richie/apps/courses/models/course.py
src/richie/apps/search/indexers/courses.py
tests/apps/courses/test_models_course.py
tests/apps/search/test_indexers_categories.py
tests/apps/search/test_indexers_courses.py
tests/apps/search/test_indexers_organizations.py
tests/apps/search/test_indexers_persons.py

Unpublished categories were not indexed in the "categories" index but they were listed in the course document of the
"courses" index.
Fixes #704

🐛(search) fix indexing unpublished categories

---

CHANGELOG.md
src/richie/apps/courses/models/blog.py
tests/apps/courses/test_models_blogpost.py

When displaying related blogposts on a blogpost's detail page, we were sorting by the related blogposts' "path" (same order as in  the pages tree).
We were waiting for user feedback which requested to sort them by their publication date (the latest coming first).
Sort related blogposts by their publication date and add a test to secure this behavior.

✨(blogposts) sort related blog posts by their publication date

---

CHANGELOG.md
src/richie/apps/search/text_indexing.py
tests/apps/search/test_partial_mappings.py
tests/apps/search/test_query_courses_edge_cases.py

We noticed that courses with the word "`électricité`" could not be found with a search query lacking accents: "`electricite`".
The problem was due to a wrong ordering of filters. We were stemming before doing the ascii folding. As a result:
- "`électricité`" was indexed as "`electr`"
- searching "`électricité`" was analyzed as "`electr`" => result found :smiley: 
- searching "`electricite`" was analylzed as "`electricit`" => result not found :thinking: 
I changed the order of the char filters in our custom analyzers and added tests to secure the fix.
Fixes https://github.com/openfun/richie/issues/1347

🐛(search) fix search bug due to wrong ordering of char filters

---

CHANGELOG.md
src/richie/apps/search/forms.py
tests/apps/search/test_forms_search_courses.py
tests/apps/search/test_query_courses_edge_cases.py

When the query we type matches the title of a course that is not open, it may appear after some open courses with titles that don't match as good. 
Users expect to see the titles that match their query first.

🧐(search) boost title field for a better search experience

---

CHANGELOG.md
src/richie/apps/courses/settings/__init__.py

The default size limit for a blogpost excerpt was a bit short.
Bump the default limit to 240 characters.

🚸(blogposts) increase excerpt size limit to 240 characters

---

CHANGELOG.md
src/richie/apps/core/models.py
tests/apps/courses/test_models_category.py
tests/apps/courses/test_models_course.py
tests/apps/courses/test_models_organization.py
tests/apps/courses/test_models_person.py

When getting related objects on a public page, we excluded related objects that were not published but forgot to exclude objects that had been published and later unpublished.

🐛(courses) hide unpublished pages from related objects on public page

---

CHANGELOG.md
src/frontend/scss/components/templates/courses/cms/_blogpost_detail.scss

On blogpost pages, an apparently useless override on the section styles was breaking the flow.
As a result, adding several glimpses in a section was displaying them on several lines.

🐛(blogposts) fix section on blogpost detail page

---

CHANGELOG.md
src/richie/apps/search/apps.py
src/richie/apps/search/indexers/courses.py
src/richie/apps/search/signals.py
tests/apps/search/test_index_manager.py
tests/apps/search/test_indexers_courses.py
tests/apps/search/test_signals.py

When a page was published in a new version, we were updating it in our search indices, but we forgot to do the same upon unpublishing a page in a language
As a result, some hidden pages were remaining in the search engine until the next complete reindexation.

🐛(search) delete object from search indices when a page is unpublished

---

src/richie/apps/core/templates/richie/base.html

Adding a `topbar_branding` block allows us to easily switch and change properties on the site logo `<img>`. In specific cases, it allows users to place inline svg logos.

Add a topbar branding block to easily switch logos and images

---

src/richie/apps/search/filter_definitions/courses.py
tests/apps/search/test_query_courses_i18n.py

During our migration to ES7, we introduced a bug that was not directly caused by ES7, but by code changes we made during the migration. We naively used the result of a dict's `.keys()` method like it was a list, however it is not a list nor can it be serialized to one. Instead we needed to just spread the dict to get a list of its keys.
This was not caught by our tests as the place where the bug occurs was mocked out in all of our tests. We added a new test suite that does not mock out this part so we can avoid regressions with this code in the future.

Fix facet localization bug after ES7 migration

---

CHANGELOG.md
src/richie/apps/courses/api.py
tests/apps/courses/test_api_course_run_sync_edx.py

We mixed up both error codes:
- if there is no token, the user is anonymous and is not allowed to access the resource => 403
- if the token is invalid, the user can't be authenticated => 401
Reverse error codes and update tests.

🐛(courses) reverse 401 and 403 errors in course run sync webhook

---

.circleci/config.yml

Docusaurus-publish checks if it is running on a Pull Request by looking at the relevant environment variables as provided by
Circle CI. However, one of those is deprecated and we suspect it contains an incorrect value, where Docusaurus concludes it is running on a PR when it is actually just running on master.
Hopefully this will be solved in a later version of Docusaurus, and/or Circle CI will provide correct values in their environment variables.
In the meantime, since we manage when we deploy our docs on our own (by only running the job on master), we can just use FORCE_DEPLOY to disregard the check and always deploy when our CI deployment job is running.

🐛(docs) work around broken check for docs deployments

---

.circleci/config.yml

Docusaurus only deploys the website if the `CI_PULL_REQUEST` and `CIRCLE_PULL_REQUEST` environment variables are both null. This is apparently not the case anymore in CircleCI on a build of the master branch.
We have to force it on the command. We can not force deployment with the `FORCE_DEPLOY` environment
variable because it was not released in Docusaurus v1.

🐛(website) force deploy Docusaurus website

---

.circleci/config.yml

We previously used false as a value to force deployments of our docs regardless of the (incorrect) values provided by the
Circle CI environment. 
As environment variables are always strings, "false" is actually a truthy value. Use an empty string instead to we do provide a falsy value.

🐛(website) use falsy IS_PULL_REQUEST values to force docs to deploy

---

src/richie/apps/search/defaults.py
src/richie/apps/search/filter_definitions/base.py
src/richie/apps/search/filter_definitions/courses.py
tests/apps/search/test_query_courses_facets.py
tests/apps/search/test_query_courses_i18n.py

Facet counts (aggregations) in the filters on course searches had different logics applied to them for ordering depending on the kind of filter definition.
We rationalized the way facets are ordered to be either "conf", "count" then "alphabetical" or "alphabetical" then "count" so we always have a consistent expected ordering of results. It also makes it way easier to write tests as there is only one correct ordering.

✨(search) improve aggregations ordering on filters

---

CHANGELOG.md
src/richie/apps/core/templates/richie/hreflang.html
tests/apps/core/test_pages.py
tests/apps/courses/test_templates_course_detail_rdfa.py

Fix the href value of alternate meta, so we could have a better SEO.
Related with issue #1393 
Executed the suggestion change of @sveetch and fixed the tests.

🔍️(seo) fix alternate meta href value

---

CHANGELOG.md
src/richie/apps/search/templates/search/search.html

The favicon and open graph metas weren't being added to the search page.

🐛(search) fix search template meta block

---

CHANGELOG.md
sandbox/settings.py
src/richie/apps/search/elasticsearch.py
tests/apps/search/test_elasticsearch_compat_layer.py

Retrieve the elasticsearch server version on initialization could creates bug in contexts where elasticsearch host is not accessible. e.g: during a docker build if we run a manage command, an elasticsearch client is initiliazed and build
failed due to a ConnectionError. So a workaround is to lazily retrieve the elasticsearch version the first time we need to know the version then reuse the value.

🐛(search) lazily retrieve es version

---

CHANGELOG.md
sandbox/settings.py
src/richie/apps/search/defaults.py
src/richie/apps/search/filter_definitions/__init__.py
src/richie/apps/search/filter_definitions/courses.py
tests/apps/search/test_filter_definitions.py
tests/apps/search/test_query_courses.py
tests/apps/search/test_query_courses_edge_cases.py
tests/apps/search/test_query_courses_facets.py

Task n°2 for #1415 
Filters based on the IndexableMPTTFilterDefinition, which are filters defined by a base page and for which a hierarchy of pages indexed in ES is the list of available filters, were using a regex filter that required the MPTT path of said filters to be used as IDs and indexed on courses.
We replaced the regexp with a (cached) database call to directly provide a list of children instead of an MPTT based regex. This will enable us to link filters with courses through proper IDs as filters do not rely on MPTT paths in their definition.

♻️(search) stop relying on MPTT paths to define search filters

---

CHANGELOG.md
UPGRADE.md
src/frontend/scss/components/_subheader.scss
src/frontend/scss/settings/_variables.scss

Previously, we used `$r-course-aside` variable to define both the course content aside column width and  the subheader aside column width. But in some use case, we want to define this variable to null to make `course__content` in full width. But we do not want this behavior for the `subheader` block. So we decided to use a dedicated variable to set the subheader aside column width.

💄(subheader) use a dedicated variable to set aside column width

---

CHANGELOG.md
src/richie/apps/courses/models/course.py
tests/apps/courses/test_models_course.py

While computing the "pt_effort" string for schema.org's [timeRequired field](https://schema.org/timeRequired) on the course, we forgot to handle the case when the effort field is not set.

🐛(courses) fix "pt_effort" string computation when effort is not set

---

UPGRADE.md

We forgot to add an instruction about the new `robots.txt` path.
Add instruction:
```python
path(
"robots.txt",
TemplateView.as_view(
template_name="richie/robots.html", content_type="text/plain"
),
)
```

📝(UPGRADE) add missing instruction from 2.7.x to 2.8.x

---

CHANGELOG.md
src/frontend/js/common/searchFields/getSuggestionsSection.spec.ts
src/frontend/js/common/searchFields/getSuggestionsSection.ts
src/frontend/js/utils/errors/handle.ts
src/frontend/package.json
src/richie/apps/search/utils/viewsets.py
src/richie/apps/search/viewsets/categories.py
tests/apps/search/test_autocomplete_categories.py
tests/apps/search/test_autocomplete_courses.py
tests/apps/search/test_autocomplete_organizations.py
tests/apps/search/test_autocomplete_persons.py

Per #1349.
We have been seeing `KeyError` 500 errors on the API, caused by autocomplete calls without a `query`. As far as we can tell from the code, this should not be possible.
Still, the API should not throw up a 500 in this case, but should handle the error and return a 400 with an explanation. This should also help us better understand how the frontend ends up making those broken requests.
- Handle autocomplete errors gracefully on the API
- Improve error handling in the frontend so we can find out the reason for broken requests later on

(search) Manage Keyerror on autocomplete requests

---

CHANGELOG.md
src/richie/apps/search/signals.py
tests/apps/search/test_signals.py

When a page is moved in the MPTT tree, it can change the paths of an unbounded number of other pages linked to the same kind of objects. Right now, paths are only used for categories.
Therefore, when a category is moved in the page tree, we need to re-index all categories, as we do not know which pages may be impacted by the move.
Note: although there still is a `page_moved` signal (https://github.com/django-cms/django-cms/blob/f622008b471e664249b72db6dec528d4d8bd4255/cms/signals/__init__.py#L16), it is not called anywhere as it was intentionally removed (https://github.com/django-cms/django-cms/issues/6356).
The approach we propose relies on an internal tool, but thanks to our unit test, we should be warned if/when it is broken by Django CMS.

✨(search) update ES indices when a page is moved

---

CHANGELOG.md
src/frontend/js/components/UserMenu/DesktopUserMenu.tsx
src/frontend/js/components/UserMenu/index.spec.tsx
src/frontend/scss/objects/_selector.scss

In DesktopUserMenu, when user clicked on logout button, the action was trigger twice. First through the `onClick` handler then second from the downshift `onSelectedItemChange` handler used for accessibility purpose.

🐛(frontend) do not call logout twice

---

src/frontend/js/common/searchFields/index.tsx
src/frontend/js/components/SearchSuggestField/index.spec.tsx
src/richie/apps/search/indexers/categories.py
tests/apps/search/test_autocomplete_categories.py
tests/apps/search/test_indexers_categories.py

As a result of an oversight in our latest Search refactor, we broke the addition of autocompleted filters to the current course search params.
This was due to not having the correct "kind" on categories, them having "categories" instead of eg. "subjects" or "levels". There was a fallback relying on MPTT paths as IDs, which we recently removed.
We updated autocompleted categories to have the correct kind and removed the now unnecessary fallback.
NB: no changelog as the commits that broke this are not yet part of a release.

♻️(search) fix autocomplete filters in Search

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/course_detail.html
tests/apps/courses/test_templates_course_detail_rendering.py

Fixes #1520 
Change course page template so when there isn't a content or participation licenses the course page don't show the block that asks to insert that information on view mode.

✨(courses) make licenses on course page optional

---

CHANGELOG.md
src/frontend/scss/components/templates/courses/cms/_course_detail.scss
src/frontend/scss/settings/_colors.scss
src/frontend/scss/tools/_utils.scss
src/richie/apps/core/context_processors.py
src/richie/apps/core/templates/richie/base.html
src/richie/apps/courses/defaults.py
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/fragment_course_runs_list.html
tests/apps/courses/test_templates_course_detail_rendering.py

Limit the number of archived course runs displayed by default on a course detail page.
The additional runs can be viewed by clicking on `View more` link.
Then after clicking on _View more_ link it would show all the rest of the archived course runs.
#1497

✨(courses) optional limit max archived course runs

---

CHANGELOG.md
src/richie/apps/core/cache.py
tests/apps/core/test_cache.py

Remove error message related with cache when any test fails.
When any test fails locally, any test shows this annoying error. 
This pull request removes that message.
```
-------------------------------------------------------------------------------------------- Captured log call --------------------------------------------------------------------------------------------
ERROR    richie.apps.core.cache:cache.py:163 int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

🩹(tests) remove error message when a test fails

---

setup.cfg

We added redis-python to our dependencies to be able to control the version we run: it's a transitive dependency of django-redis, and versions >=4 <4.0.2 broke Richie. Now that the latest version 4.0.2 is not broken anymore, we can remove it from our dependencies and leave it to django-redis.

➖(backend) remove redis-python from dependencies

---

CHANGELOG.md
src/richie/apps/core/context_processors.py
tests/apps/courses/test_templates_course_detail_opengraph.py

Fix og:image when using S3Boto3Storage.
Fixes #1510

🐛(opengraph) fix og:image

---

CHANGELOG.md
UPGRADE.md
src/frontend/js/components/Spinner/_styles.scss
src/frontend/js/components/Spinner/index.tsx
src/frontend/scss/settings/_colors.scss

Spinner component now accepts a theme property.
Right now, this property can set to `light` otherwise it should be undefined.

💄(frontend) add theme modifier to spinner

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/blogpost_detail.html

The size definitions in srcset and actual generated image sizes for blog post images did not fit the actual layout of blogposts in Richie. 
Update the srcset & sizes for blogpost images so they fit the intended layout.
Fixes #1424

🐛(blog) fix blogpost image sizes

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
src/richie/apps/courses/templates/courses/cms/category_detail.html
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/fragment_blogpost_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_category_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_organization_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_organization_main_logo.html
src/richie/apps/courses/templates/courses/cms/fragment_person_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_program_glimpse.html
src/richie/apps/courses/templates/courses/cms/organization_detail.html
src/richie/apps/courses/templates/courses/cms/person_detail.html
src/richie/apps/courses/templates/courses/cms/program_detail.html
src/richie/apps/courses/templates/courses/plugins/licence_plugin.html
src/richie/plugins/glimpse/templates/richie/glimpse/glimpse.html
src/richie/plugins/glimpse/templates/richie/glimpse/glimpse_person.html
src/richie/plugins/glimpse/templates/richie/glimpse/glimpse_quote.html
src/richie/plugins/large_banner/templates/richie/large_banner/hero-intro.html
src/richie/plugins/large_banner/templates/richie/large_banner/large_banner.html
tests/apps/courses/test_templates_course_detail_rdfa.py

Easy thumbnails converts images to jpg when there is no transparency, but keeps png otherwise. We can't prevent users from uploading images with transparency in places where it is not desired but we can remove
it when generating thumbnails so that the image can be converted to jpg and thus be much smaller.
Force the `replace_alpha` in all thumbnails template tags to get rid of transparency and make sure images are converted to jpg and thus compressed to a much smaller size.

⚡️(templates) remove image transparency when not necessary so that thumbnails are converted to jpeg

---

CHANGELOG.md
src/richie/apps/core/templates/richie/base.html
src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
src/richie/apps/courses/templates/courses/cms/category_detail.html
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/organization_detail.html
src/richie/apps/courses/templates/courses/cms/person_detail.html
src/richie/apps/courses/templates/courses/cms/program_detail.html
src/richie/apps/courses/templatetags/extra_tags.py
tests/apps/courses/test_templates_blogpost_detail.py
tests/apps/courses/test_templates_category_detail.py
tests/apps/courses/test_templates_course_detail_rendering.py
tests/apps/courses/test_templates_organization_detail.py
tests/apps/courses/test_templates_person_detail.py
tests/apps/courses/test_templates_program_detail.py

Add a default value for the HTML header meta description. 
The default value depends on the page template:
* if course defaults to course introduction
* if blog defaults to blog excerpt
* if category defaults to description
* if person defaults to bio
* if program defaults to excerpt 
Closes #1355

✨(seo) add default value for meta description

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
src/richie/apps/courses/templates/courses/cms/category_detail.html
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/organization_detail.html
src/richie/apps/courses/templates/courses/cms/person_detail.html
src/richie/apps/courses/templates/courses/cms/program_detail.html
tests/apps/courses/test_templates_blogpost_detail.py
tests/apps/courses/test_templates_category_detail.py
tests/apps/courses/test_templates_course_detail_opengraph.py
tests/apps/courses/test_templates_organization_detail.py
tests/apps/courses/test_templates_person_detail.py
tests/apps/courses/test_templates_program_detail.py

Improve social sharing by specifying og:description meta for blogpost, category, person and program.
* if blog defaults to blog excerpt placeholder
* if category defaults to description placeholder
* if person defaults to bio placeholder
* if program defaults to excerpt placeholder
* if organization defaults to organization description placeholder value

✨(social) improve social sharing with og:description

---

CHANGELOG.md
src/richie/apps/search/indexers/courses.py
tests/apps/search/test_query_courses_edge_cases.py

The score computation we made to sort courses within a "search bucket" could lead to a negative score. This causes a 500 error in Elasticsearch and should not happen. When a course has dates far in the future, taking
into account the relative dates is not really relevant anyway.

🐛(search) fix negative scores causing errors with far future courses

---

CHANGELOG.md
src/frontend/js/components/Modal/_styles.scss
src/frontend/js/components/Modal/index.spec.tsx
src/frontend/js/components/Modal/index.tsx
src/frontend/js/components/SearchFilterGroup/index.spec.tsx
src/frontend/js/components/SearchFilterGroupModal/_styles.scss
src/frontend/js/components/SearchFilterGroupModal/index.spec.tsx
src/frontend/js/components/SearchFilterGroupModal/index.tsx
src/frontend/js/utils/useIntersectionObserver.tsx
src/richie/apps/search/filter_definitions/__init__.py
src/richie/apps/search/filter_definitions/base.py
src/richie/apps/search/filter_definitions/courses.py
src/richie/apps/search/forms.py
tests/apps/search/test_forms_search_courses.py
tests/apps/search/test_query_courses_facets.py

It is often the case that facet categories in course search have a lot of possible filter values.
We initially built the `<SearchFilterGroupModal />` to enable users to search through those values. However, we did not set up pagination.
As it turns out, users want to be able to move down the list to get to the value they want.
Implement infinite scrolling in the modal using react-query and IntersectionObserver to make it as effortless as possible for users.

✨(search) Scroll search filters more options

---

CHANGELOG.md
src/frontend/js/data/useSession/index.tsx
src/frontend/js/data/useSession/no-authentication.spec.tsx

As we deployed the latest version of Richie, all frontend code failed to run because authentication via an LMS connection was assumed to be present.
However, LMS authentication is optional in Richie, and some deployed sites do not use it and break if an authentication backend is not provided.

🐛(frontend) LMS authentication is optional

---

CHANGELOG.md
UPGRADE.md
src/richie/apps/core/templates/richie/base.html

We want to be able to customize the link behind the logo at the left of the footer.

🎨(core) make brand link customizable & rename related template block

---

CHANGELOG.md
src/richie/plugins/lti_consumer/api.py
src/richie/plugins/lti_consumer/models.py
tests/plugins/lti_consumer/test_api.py
tests/plugins/lti_consumer/test_models.py

The LTI consumer was not transmitting the language when making an LTI launch request. As a result, marsha was serving the english language on our french sites.
Add missing language parameter in LTI requests and set it with the current language.

🐛(lti_consumer)  Add missing language parameter in LTI requests

---

CHANGELOG.md
src/frontend/js/components/CourseGlimpse/index.spec.tsx
src/frontend/js/components/CourseGlimpse/index.tsx
src/frontend/scss/objects/_course_glimpses.scss
src/richie/apps/courses/templates/courses/cms/fragment_blogpost_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_organization_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_program_glimpse.html
tests/apps/courses/test_cms_plugins_blogpost.py
tests/apps/courses/test_cms_plugins_course.py
tests/apps/courses/test_cms_plugins_organization.py
tests/apps/courses/test_cms_plugins_organizations_by_category.py
tests/apps/courses/test_cms_plugins_program.py
tests/apps/courses/test_templates_category_detail.py
tests/apps/courses/test_templates_course_detail_rendering.py
tests/apps/courses/test_templates_organization_detail.py
tests/apps/courses/test_templates_person_detail.py
tests/apps/courses/test_templates_program_detail.py

On course glimpse, course and organization titles was not truncated when they
were too long. So when these two contents were too long, they overlap. So we
decided to truncate course title if it exceeds 3 lines and organization title if
it exceeds 2 lines. Furthermore, we decrease font-size of organization title to
0.7rem to homogenize font size within course glimpse.
Fix #1560
_Note: If browser does not support `-webkit-line-clamp`, ellipsis will not appear._

💄(course-glimpse) fix layout issue with long organization and course titles

---

CHANGELOG.md
src/frontend/js/components/CourseGlimpse/index.spec.tsx
src/frontend/js/components/CourseGlimpse/index.tsx
src/frontend/scss/objects/_course_glimpses.scss
src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html
tests/apps/courses/test_cms_plugins_course.py

Within course glimpse, metadata was positioned absolutely, there are
better things to do.

💄(frontend) improve course glimpse layout

---

Dockerfile

[djangocms-admin-style 3.0.0](https://pypi.org/project/djangocms-admin-style/) has been released and includes fixes we need. So we are now able to remove the use of our forked version of this
package.

📌(backend) remove use of forked djangocms-admin-style

---

CHANGELOG.md
src/frontend/js/components/Banner/index.spec.tsx
src/frontend/js/components/Banner/index.tsx

Previously we created a styles for a banner block. In the react app context, it could be interesting to have a reusable `Banner` component base on these styles to easily display messages.

✨(frontend) Create a Banner React component

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/category_list.html
src/richie/apps/courses/templates/courses/cms/organization_list.html
src/richie/apps/courses/templates/courses/cms/person_list.html
src/richie/apps/courses/templates/courses/cms/program_list.html
tests/apps/courses/test_templates_category_list.py
tests/apps/courses/test_templates_person_list.py
tests/apps/courses/test_templates_program_list.py

On the category, program and person list views, unpublished objects are listed on the public site.
The template code was a bit too naïve. Exclude unpublished objects (as it was already done for blog posts and organizations) and add tests to secure it.

🐛(courses) hide unpublished objects from list views

---

CHANGELOG.md
src/frontend/js/components/PaginateCourseSearch/index.tsx
src/richie/apps/core/templates/richie/pagination.html
src/richie/apps/core/templates/richie/pagination_inner.html
src/richie/apps/courses/templates/courses/cms/blogpost_list.html
src/richie/apps/courses/templates/courses/cms/category_detail.html
src/richie/apps/courses/templates/courses/cms/category_list.html
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/organization_detail.html
src/richie/apps/courses/templates/courses/cms/organization_list.html
src/richie/apps/courses/templates/courses/cms/person_detail.html
src/richie/apps/courses/templates/courses/cms/person_list.html
src/richie/apps/courses/templates/courses/cms/program_list.html

Fix #1581
The idea here is to easily allow custom labels when using multiple pagination components on the same page. We do this by using a new pagination-specific django tag, currently named `richie_pagination`, **but I guess the naming is not that great**.
Allowing custom labels without this new tag was cumbersome because, the dj-pagination `{% paginate %}` tag doesn't accept any custom context (like an `{% include %}` tag). So it would require to create a specific template file for each label change. I figured having a new tag was better?
Because I'm still not sure how it is usually dealt with in this project, **translation strings are missing** in this PR.

♿️(pagination) improve a11y labels when using multiple paginations on same page

---

env.d/development/mysql

When Django runs tests, it creates a temporary database with the name "test_{database_name}". The problem is that our `fun` user does not have the right to create a new database.
We can safely run our tests with the mysql `root` user.
Fixes https://github.com/openfun/richie/issues/1594

👷(tests) fix tests for mysql

---

CHANGELOG.md
sandbox/settings.py
setup.cfg
src/richie/apps/courses/cms_plugins.py
src/richie/apps/courses/forms.py
src/richie/apps/courses/urls.py
src/richie/apps/courses/views.py
tests/apps/courses/test_cms_views_person.py

Some sites can have a huge list of objects where it is hard to search for a specific
object. The page selector from Person plugin is one of this case.
We implement usage of an autocomplete feature with Select2.js by the way of new
dependancy 'django-autocomplete-light' enabled and configured on the 'page' field
from Person plugin form.

🚸(course) add admin autocomplete feature on Page select in Person plugin

---

CHANGELOG.md
src/richie/apps/courses/cms_plugins.py
src/richie/apps/courses/forms.py
src/richie/apps/courses/urls.py
src/richie/apps/courses/views.py
tests/apps/courses/test_cms_views.py

In PR https://github.com/openfun/richie/pull/1590, @sveetch proposed to activate an autocomplete select field for page related plugins in the frontend admin view. This feature was urgently needed for the person object as we have a lot of instances of this type of page in https://www.fun-mooc.fr, but it is also very interesting for all other types of page related plugins: blog post, category, course, organization, organization by category and program.
This is a generalization of @sveetch's  work to all other page related plugins.
We generate tests programmatically, for each type of page related object, in order not to repeat the exact same code 6 times.

🚸(courses) add admin autocomplete for remaining page related plugins

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html
src/richie/apps/search/indexers/courses.py
tests/apps/courses/test_cms_plugins_course.py
tests/apps/search/test_indexers_courses.py

Shows the organization menu title in the course glimpse card, if defined.
It retains original functionality, only displaying this field if the organization wants to. 
Solves #1570

Show organization code in the course glimpse card

---

UPGRADE.md

Add missing upgrade instructions to upgrade richie from 2.12.x to 2.13.x

📝(doc) add missing upgrade instruction to 2.13

---

.circleci/config.yml
CHANGELOG.md
UPGRADE.md
src/frontend/webpack.config.js

Previously, the frontend overriding system was designed to override only
components modules. We should be able to override any modules.

🔧(frontend) allow overriding of any module

---

CHANGELOG.md
src/frontend/js/components/CourseGlimpse/CourseGlimpseFooter.tsx
src/frontend/js/components/CourseGlimpse/index.tsx
src/frontend/js/components/Icon/index.spec.tsx
src/frontend/js/components/Icon/index.tsx
src/frontend/js/components/Search/index.tsx
src/frontend/js/components/SearchFilterGroupModal/index.tsx
src/frontend/js/components/SearchInput/index.tsx
src/frontend/js/components/UserLogin/index.tsx
src/frontend/js/components/UserMenu/MobileUserMenu.tsx

Make using icons in react templates easier for developers, without them having to ask themselves about what attributes the SVG element needs depending on use cases.
Add an `Icon` react component that handles common use cases:
- rendering decorative icons
- rendering informative icons
- allowing custom css classes

✨(frontend) new Icon component

---

CHANGELOG.md
src/frontend/js/components/Icon/index.tsx

Fix my morning mistake :upside_down_face: 
Forgot that svg elements don't support `title` attributes but do have
`<title>` tags instead. Fix that.

🐛(icons) fix title tooltip not working

---

CHANGELOG.md
src/frontend/js/components/RootSearchSuggestField/index.spec.tsx
src/frontend/js/components/RootSearchSuggestField/index.tsx
src/frontend/js/components/SearchSuggestField/index.spec.tsx
src/frontend/js/components/SearchSuggestField/index.tsx

Be sure that screen reader users understand when they are on the search suggestion fields.
Add an `aria-label` attribute in addition to the already there `placeholder`. 
accessibility-wise, having only placeholders is not enough for full
screen reader support.
Depending on screen readers, screen reader versions, combination with
different browsers, or configurations, placeholders are not always
announced.
The aria-label attribute is an actual accessible name recognized by all
softwares.

♿️(search) add labels to search suggest fields for screen readers

---

CHANGELOG.md
src/frontend/js/components/Search/index.tsx

Make the navigation between the different sections of the search page less confusing for screen reader users.
In the headings hierarchy, it looked like course glimpse headings were
descendants of "Filter courses". This was pretty misleading for screen
reader users that can rely a lot on headings hierarchy to navigate a
page.
This adds a heading for the results block that is the same level as the
filters to prevent this confusion. We can argue the heading is maybe not
that necessary in the UI though, so we can just have it for screen
readers.
To better understand the problem, here are screenshots of NVDA before/after the change:
<details><summary>Screenshots</summary>
**Avant**
<a target="_blank" rel="noopener noreferrer" href="https://user-images.githubusercontent.com/221253/155706324-070f …

♿️(search) add a heading for the search results

---

CHANGELOG.md
src/richie/plugins/section/templates/richie/section/section_tiles.html
tests/plugins/section/test_templates_section_default.py

It is required to disable automatic escaping from Django template since title is a
richtext now and CKEditor already transforms special characters which can leads to
artificial double escaping.
Section tile template has been changed to add '|safe' filter on section title to fix
this issue.

🐛(layout) fix section tile title with richtext

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/blogpost_detail.html
tests/apps/courses/test_templates_blogpost_detail.py

The author person name was hidden in blogpost detail when viewed in published mode and only showed in draft mode. But alike categories, the author is required to be displayed in published mode also except if its placeholder is empty.
This commit fix template to use the right condition to display author and add some tests around this behavior.

🐛(layout) display author name in blogpost detail in published mode also

---

CHANGELOG.md
src/frontend/scss/objects/_organization_glimpses.scss
src/richie/apps/courses/settings/__init__.py
src/richie/apps/courses/templates/courses/cms/fragment_organization_glimpse.html
src/richie/apps/courses/templates/courses/cms/organization_detail.html
tests/apps/courses/test_templates_organization_detail.py

Organization plugin 'row' variant has been reported to have broken layout in some situation.
This is due to two things, firstly the CSS was not made for the link wrapper around content, secondly Organization description can include links which break HTML since it is already included in a link wrapper, this is not valid and leads to CSS issues.
Note than the reported bug was when the Org description included a link but in fact there was other issues without any included links, this is because of invalid HTML that leads to erroneous behavior that depended from browser resolution with invalid HTML.
Below you can see a sample of render with the two possibilities (without or with included links in description):
Note than when row is hovered, everything adopt the "hover link" CSS behaviors with …

✨(courses) add 'excerpt' placeholder to Organization detail template

---

CHANGELOG.md
src/frontend/scss/components/templates/courses/cms/_organization_detail.scss
src/frontend/scss/components/templates/courses/cms/_person_detail.scss
src/frontend/scss/components/templates/courses/cms/_program_detail.scss

Some text contents from some detail pages have been reported to be too small:
- 'excerpt' placeholder content from Organization detail;
- 'body' placeholder content from Program detail;
- Main content from Person detail.
They are missing font size rule and so inherit it from the <body> base size which is too small for these kind of content.
This commit just set these content to 1rem alike other detail contents.

💄(layout) set font size to 1rem on some detail pages body contents

---

CHANGELOG.md
src/frontend/js/components/PaymentButton/_styles.scss
src/frontend/js/components/PaymentButton/index.spec.tsx
src/frontend/js/components/PaymentButton/index.tsx
src/frontend/js/components/PaymentInterfaces/Dummy.tsx
src/frontend/js/components/PaymentInterfaces/PayplugLightbox.tsx
src/frontend/js/components/PaymentInterfaces/__mocks__/index.tsx
src/frontend/js/components/PaymentInterfaces/index.spec.tsx
src/frontend/js/components/PaymentInterfaces/index.tsx
src/frontend/js/hooks/useOrders.ts
src/frontend/js/settings.ts
src/frontend/js/types/Joanie.ts
src/frontend/js/types/payments/payplug.d.ts
src/frontend/js/utils/test/factories.ts
src/frontend/scss/_main.scss

Add a payment button component which is in charge to create an order from Joanie then launch the right payment interface according to the payment provider used. Currently it supports Payplug and a dummy payment provider for development  purpose only.

✨(frontend) add a PaymentButton

---

CHANGELOG.md
src/richie/apps/courses/models/course.py
tests/apps/courses/test_models_course_run.py

It has been reported than trying to delete a course run fails to an error when a course run translation have an empty title.
This changes the `__str__` from CourseRunTranslation model to a fallback title "Empty title" when its title is empty. CourseRun deletion won't fail again because of empty translation title.

🐛(course) fix course run deletion when translation title is empty

---

CHANGELOG.md
src/frontend/js/components/PaginateCourseSearch/index.spec.tsx
src/frontend/js/components/PaginateCourseSearch/index.tsx

Pagination buttons behave like links: they update the url and make a new request. So we could use actual links instead of buttons.
This now allows users to open search pages in new tabs from the pagination links.

🚸(search) transform pagination buttons in pagination anchors

---

CHANGELOG.md
src/richie/apps/core/templates/richie/base.html
tests/apps/courses/test_templates_blogpost_detail.py
tests/apps/courses/test_templates_category_detail.py
tests/apps/courses/test_templates_course_detail_rendering.py
tests/apps/courses/test_templates_organization_detail.py
tests/apps/courses/test_templates_person_detail.py
tests/apps/courses/test_templates_program_detail.py

Improve a11y (and seo) by always having the website's name in the page `<title>`.
By default for now, the `<title>` only tells us about the current page; it does
not tell us about what website we are on.
Adding the site name after the page name mostly improves two things:
- accessibility. Knowing what is the current site is a great
improvement. Without it, if I have multiple tabs opened, all related to
learning stuff, and a few tabs don't have their website name in the
title, it can be cumbersome to navigate with a screen-reader and
remember what tab is what website.
- SEO
Stuff done to implement this:

✨(core) add site name in <title> everywhere

---

CHANGELOG.md
src/frontend/js/components/CourseGlimpse/index.tsx
src/richie/apps/core/templates/richie/base.html
src/richie/apps/core/templates/social-networks/blogpost-badges.html
src/richie/apps/core/templates/social-networks/course-badges.html
src/richie/apps/core/templates/social-networks/footer-badges.html
src/richie/apps/courses/templates/courses/cms/fragment_category_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_error_detail_template_banner.html
src/richie/plugins/glimpse/templates/richie/glimpse/glimpse_quote.html
tests/apps/courses/test_cms_plugins_course.py
tests/apps/courses/test_templates_category_detail.py
tests/apps/courses/test_templates_course_detail_rendering.py
tests/apps/courses/test_templates_organization_detail.py
tests/apps/courses/test_templates_person_detail.py
tests/apps/courses/test_templates_program_detail.py

This is a follow-up to https://github.com/openfun/richie/pull/1611 because @sandroscosta didn't have the time to finish.
@sandroscosta please note that I removed a few stuff that I didn't quite understand why they were in your PR (I left comments in your PR). I'll let you continue this on your own when you get the time.
Here are just the changes on:
- icon/img labels
- redundant `title` attributes on a few headings

♿️(templates) improve template rendering

---

CHANGELOG.md
src/frontend/scss/generic/_accessibility.scss
src/richie/apps/core/templates/richie/base.html

Change the implementation of the offscreen class to match the one from bootstrap that is battle-tested.
The main idea is to stop using `left: -100000px` that can cause scrolling "flicker" or weird focus styles when using a screen reader, as that can be annoying for sighted people that use a screen reader.

♿️(styles) improve the offscreen class

---

CHANGELOG.md
src/frontend/js/components/CourseGlimpse/CourseGlimpseFooter.tsx
src/frontend/js/components/CourseGlimpse/index.spec.tsx
src/frontend/js/components/CourseGlimpse/index.tsx
src/frontend/scss/objects/_course_glimpses.scss
src/richie/apps/courses/templates/courses/cms/fragment_category_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_course_glimpse.html
tests/apps/courses/test_cms_plugins_course.py
tests/apps/courses/test_templates_category_detail.py
tests/apps/courses/test_templates_course_detail_rendering.py
tests/apps/courses/test_templates_organization_detail.py
tests/apps/courses/test_templates_person_detail.py
tests/apps/courses/test_templates_program_detail.py

Make a course glimpse more understandable when using a screen reader.
A few stuff can be done:
Note: some improvements are already added via https://github.com/openfun/richie/pull/1611 (most notably, the removal of redundant `title` attributes)

♿️(course glimpse) improve global accessibility of a course glimpse

---

CHANGELOG.md
src/frontend/js/data/useCourseSearch/index.spec.tsx
src/frontend/js/data/useCourseSearch/index.ts

The `useCourseSearch` is using `useQuery` under the hood but its query key was
not localized so if user changes the language, search results was not refreshed
until current data are stale.
Fixes https://github.com/openfun/richie/issues/1661

🚑(frontend) make useCourseSearch hook locale sensible

---

CHANGELOG.md
src/frontend/scss/objects/_course_glimpses.scss

Fix course glimpse layout when organization logo is too narrow
Closes #1654

💄(course_glimpse) fix style with narrow org logo

---

CHANGELOG.md
UPGRADE.md
src/frontend/scss/components/templates/courses/cms/_course_detail.scss
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templatetags/extra_tags.py
tests/apps/courses/test_templates_course_detail_rendering.py

Move enroll button for the first open course run below the contact block. 
Closes #1612
Same implementation that fun-mooc has on the its site.
Normally every one has a single open course run for each course.
This could be kind of strange if the richie installation has multiple open course runs for the same course.
We on NAU don't have this problem.
Alternatively, I could change the PR and show the single open run bellow, the contact button, if there are exactly one open course. If there are 2 open runs, we could give the current output - show all the open courses near the other runs.
Screenshoot:

✨(course_detail) more emphasis on enroll button

---

CHANGELOG.md
src/frontend/js/data/SessionProvider/BaseSessionProvider.tsx
src/frontend/js/data/SessionProvider/JoanieSessionProvider.spec.tsx
src/frontend/js/data/SessionProvider/JoanieSessionProvider.tsx
src/frontend/js/data/SessionProvider/index.spec.tsx

The BaseSessionProvider did not clear session storage before redirect to login
or register page as JoanieSessionProvider do.

🐛(frontend) clear session on login and register

---

CHANGELOG.md
src/frontend/scss/objects/_course_glimpses.scss

When a course glimpse is used within a section using a variant, the course
glimpse title color is set with the section title color scheme property. This
commit fix this issue.

💄(frontend) prevent course glimpse title color override

---

CHANGELOG.md
src/frontend/js/components/SearchFilterGroupModal/index.spec.tsx
src/frontend/js/data/getResourceList/index.ts

The search filter query string was not formatted properly so when a user wanted to filter results with several languages the search request returned a 400 Bad Request error.
Resolve #1673

🚑(frontend) fix search query string formatting

---

CHANGELOG.md
src/frontend/js/components/LanguageSelector/index.spec.tsx
src/frontend/js/components/LanguageSelector/index.tsx

When user switches to another language we want to preserve the query string.

🚑(frontend) preserve query string on language change

---

docs/cookiecutter.md

We have published a new Docker image for Cookiecutter: https://hub.docker.com/repository/docker/fundocker/cookiecutter
With this version of Cookiecutter (1.7.3) we can specify a directory inside the repository. It can then be used to generate a richie site factory from the Cookiecutter template in richie's repository: https://github.com/openfun/richie/tree/master/cookiecutter
Add instructions to documentation to run Cookiecutter with Docker.

📝(website) add option to run Cookiecutter from Docker

---

website/core/Footer.js

Urls pointing to pages in the `\docs` folder are broken.
The documentation pages in `/docs` are not internationalized (yet?). We should not include the language when computing their urls.

📝(website) fix doc urls in footer by removing language from url

---

CHANGELOG.md
UPGRADE.md
src/frontend/scss/components/_header.scss
src/richie/apps/core/templates/richie/base.html

Make sure screen reader users and keyboard users get a good experience when navigating in the header, nav and footer of richie.
- fix how the `<header>` and `<nav>` tags are used. For best screen reader user experience, the `<nav>` shouldn't be in the `<header>` because some screen readers (NVDA, for example) will not recognize region tags that are wrapped in other region tags
- fix tabulation order, especially on mobile with the hamburger menu, but also on the footer

Improve accessibility of header and footer

---

CHANGELOG.md
src/frontend/scss/settings/_variables.scss
src/frontend/scss/tools/_rem.scss

Make the website clear to use visually when using text-only zoom.
As of now, a high lvl of text-only zoom breaks the websites on multiple occasions, because the website layout doesn't shift at all when zooming in text-only mode.
For example, a list of glimpses displayed with rows of 4 elements in "desktop mode", still displays with rows of 4 elements at 200% text-only zoom. But since the text is huge in this case, it's barely impossible to read the content of each element, they all render with 2 or 3 words max per-line.
*Note: I specifically talk about 200% text zoom because it's the goal in [WCAG/RGAA](https://www.w3.org/TR/WCAG21/#resize-text).*
The proposal to fix this easily is to go from `px` based media queries to `em` based media queries. This basically makes the text-only zoom …

Make text-only zoom follow responsive breakpoints

---

CHANGELOG.md
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/backend/{{cookiecutter.site}}/settings.py
sandbox/settings.py
src/richie/apps/search/__init__.py
tests/apps/search/test_elasticsearch_compat_layer.py

Allow to configure multiple elasticsearch hosts.
On sandbox we can try it like:
```
RICHIE_ES_HOST=elasticsearch_unexistence:9200,elasticsearch:9200
```

🐛(elasticsearch) multiple elasticsearch hosts

---

src/frontend/js/components/LtiConsumer/index.tsx

In the iframce LTI we must allow display-capture and autoply to all
orogin. Without it, the webinat launch with marsha will not be able to
autoplay the stream or to share the screen with jitsi.

✨(front) allow display-capture and autoplay in iframe LTI

---

CHANGELOG.md
src/frontend/scss/components/_index.scss

The stylesheet of the AddressesManagement component was not imported, so the
layout of this component was broken.

🐛(frontend) import a missing stylesheet

---

setup.cfg

In one week, Richie master branch has been corrupted twice due to unpinned dependency updates (easy thumbnails 2.8.2 then django-cms 3.11). This is unlucky but we should take action to prevent this happen again.
Currently, python dependencies was not pinned so the main branch could be corrupted if a package update introduces a breaking change. This behaviour is weird. Renovate is in charge to update those packages each week, so we are able to upgrade those package securely and regularly.

📌(backend) pin all python dependencies

---

src/frontend/js/utils/api/lms/dummy.ts

The access token to authenticate on Joanie must now contain a language field
within its claim. So in order to use Richie in dev mode without having to start
an authentication server, we have to regenerate the fake jwt token.

👽(frontend) add language field into the claim of fake jwt token

---

CHANGELOG.md
src/frontend/js/components/Search/FiltersPaneCloseButton.tsx
src/frontend/js/components/Search/index.spec.tsx
src/frontend/js/components/Search/index.tsx
src/frontend/js/components/SearchFiltersPane/index.tsx
src/frontend/scss/components/templates/search/_search.scss

Make sure navigating inside the search page is OK when using a mobile phone/small screen + screen reader/keyboard only navigation.
Everything is precisely described in the commit.
*Note: instead of doing multiple very small commits, I did one big commit concerning everything, let me know if you'd rather have everything split up.*
Todo:

Improve accessibility on filters pane when using a small screen

---

CHANGELOG.md
src/richie/apps/courses/settings/__init__.py

CKEditor basic configuration should allow to include target on anchors for course fields: assessment, format and prerequisites.
Resolves #1764
The business problem is that we need to include an anchor on the prerequisites, for an external stuff, but it should open it as a new tab (`target=_blank`), so the user doesn't simply leave the Richie site.
Screen capture:

🐛(course) allow to include anchor target

---

src/frontend/js/components/SaleTunnelStepPayment/index.spec.tsx
src/frontend/js/components/SaleTunnelStepValidation/index.spec.tsx

Some components display prices, and we need to test price currencies are well displayed to the user. To empower our tests, price currency is randomly picked so each tests can display a different content. Thus ensure that content exists in document we try to find an element containing the formatted price using Intl.NumberFormat, but spaces seems not rendered in the same way between this method and the render method of testing-library/react. As a workaround, we replace non-breakable space by a "normal" space through `replace` method but we didn't think about currency containing several spaces. In order to fix that, we have to use `replaceAll` method instead of `replace`.

🐛(frontend) fix flaky tests using random currencies

---

setup.cfg

We previously pinned all python dependencies to prevent some uncontrolled issues due to transparent upgrades. Unfortunately this workflow does not comply with library projects like Richie as user of this library should be able to install another version of a richie dependency and pinning all richie dependencies does not allow that that's why we have to roll back this change.

📌(backend) unpin python dependencies

---

CHANGELOG.md
src/frontend/.storybook/preview.tsx
src/frontend/js/components/Modal/_styles.scss
src/frontend/js/components/Modal/index.spec.tsx
src/frontend/js/components/Modal/index.stories.tsx
src/frontend/js/components/Modal/index.tsx
src/frontend/js/components/SaleTunnel/index.spec.tsx
src/frontend/js/components/SaleTunnel/index.tsx
src/frontend/js/components/SearchFilterGroupModal/_styles.scss
src/frontend/js/components/SearchFilterGroupModal/index.spec.tsx
src/frontend/js/components/SearchFilterGroupModal/index.tsx
src/frontend/js/utils/StringHelper/index.spec.tsx
src/frontend/js/utils/StringHelper/index.ts

The modal close button wasn't included in the modal component, therefore it was required to define it each time when using the modal. So let's define a generic approach to modal close button for homogeneous UI.
Moreover, we decided to make homogeneous the behavior of the modal component, in terms in scroll and with a sticky header.

♻️(frontend) refactor modal component ( UX / DX ) 

---

CHANGELOG.md
UPGRADE.md
docs/cookiecutter.md
docs/filters-customization.md
src/frontend/js/components/SearchFiltersPane/index.spec.tsx
src/frontend/js/components/SearchFiltersPane/index.tsx
src/richie/apps/search/defaults.py
src/richie/apps/search/filter_definitions/__init__.py
src/richie/apps/search/filter_definitions/base.py
src/richie/apps/search/filter_definitions/courses.py
src/richie/apps/search/views.py
src/richie/apps/search/viewsets/courses.py
tests/apps/search/test_query_courses.py
tests/apps/search/test_query_courses_facets.py
tests/apps/search/test_views_filter_definitions.py
tests/apps/search/test_viewsets_courses.py
website/sidebars.json

It was not easy to define the list of filters to display and their order.
PR https://github.com/openfun/richie/pull/1765 addressed this issue by introducing new settings, one per filter. 
This PR is an attempt to further simplify filters configuration and avoid adding too many settings, the existence of which is tied to what is defined in `FILTERS_CONFIGURATION`.
Introduce a new setting `FILTERS_PRESENTATION` and simplify the format of the existing `FILTERS_CONFIGURATION` setting.
With this new setting, it is easier to define which filters are displayed and their order.
Filter definitions became a dictionary which also makes it easier than previous list of tuples.
This requires upgrade attention only for sites that have customized their filters.
Now that filters configuration is easier, I …

♻️(search) refactor the way filters are being configured

---

CHANGELOG.md
src/richie/apps/courses/admin.py
tests/apps/courses/test_admin_form_course_run.py

Languages choices should be ordered alphabetically in admin forms.
Ordering depends on the active language and only works if it is done directly in the form instance.
Add a test to secure the behavior.

🐛(admin) order languages choices in course run admin form

---

CHANGELOG.md
src/richie/apps/core/templates/djangocms_video/default/video_player.html
tests/apps/courses/test_templates_course_detail_rendering.py

The main goal of the PR is to be a tiny more explicit about what the `iframe` elements on the website are about. This is mostly for screen reader users.
The added bonus of this PR is that it makes the website pass the RGAA test n° 2.1.
Add a `title` attribute on a video player `iframe` block.

♿️(templates) add label on external video players

---

.circleci/config.yml

Currently, `cookiecutter-bootstrap` job runs on every branch and currently this job failed when PRs are created from forks.
Furthermore it appears this is relevant to run `cookiecutter-bootstrap` job only on release branch, so we add a step to this job which is in charge to check if the workflow concerned this kind of branch. If this is not the case, the job is exited gracefully.

💚(cookiecutter) exec cookiecutter-bootstrap job only on release branch

---

CHANGELOG.md
src/richie/apps/courses/admin.py
src/richie/apps/courses/api.py
src/richie/apps/courses/lms/edx.py
src/richie/apps/courses/models/course.py
tests/apps/courses/test_admin_course_run.py
tests/apps/courses/test_admin_form_course_run.py
tests/apps/courses/test_api_course_run_sync_edx.py

We were having course run synchronization issues on our sites since version 2.15.0.
After investigation, it appeared that the synchronization hook was misbehaving since PR https://github.com/openfun/richie/pull/1549. Indeed the no-update fields were removed from the payload for create as well as update queries which lead to 400 errors because the fields removed are required to create a course run.
Split "field conversion" and "removing no-update fields" in 2 separated actions to play them only when they are respectively required.

Fix synchronization with openedx

---

src/frontend/js/components/DashboardCreditCardsManagement/index.spec.tsx

The DashboardCreditCardsManagement test suite was flaky. In some case the test in charge to check if the right class is displayed when a credit card soon expire could generate an expiration date in the wrong interval.

✅(frontend) fix flaky tests

---

CHANGELOG.md
src/frontend/scss/objects/_course_glimpses.scss

This bug was revealed by the 0bb70196c7c42bb3bceab4e06d60baadff8dc207 commit, by transforming all buttons to flex containers some css line that were not getting took into account before went to life resulting in this bug. So that means the existing code worked but ... by chance.

🐛(frontend) fix courses badges css

---

CHANGELOG.md
src/richie/apps/courses/api.py
src/richie/apps/courses/exceptions.py
src/richie/apps/courses/urls.py
tests/apps/courses/test_api_course_run_sync.py

When a course run is updated in Joanie, it may trigger the re-synchronization of many course runs in Richie (corresponding to a Joanie product). We don't want to have to call the synchronization hook too many times in a synchronous request.
Add bulk course synchronization to the existing API hook.
Single course run synchronization still works exactly the same as the existing tests can confirm.

✨(api) allow bulk course run synchronization

---

CHANGELOG.md
src/frontend/scss/components/templates/courses/cms/_course_detail.scss

Fix style in edit mode on courses with catalog visibility with `course_only` or `course_and_search`.
A course run without title and a course visibility of `course_only` or `course_and_search` didn't display the small image svg near the run. So the course editor don't know that the course run isn't going to be displayed on the course page or the course run won't be included on the search.
Before:
After:

🐛(courses) fix course page style in edit mode

---

cookiecutter/{{cookiecutter.organization}}-richie-site-factory/.circleci/src/commands/generate-version-file.yml
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/Dockerfile
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/Makefile
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/bin/_config.sh
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/bin/activate
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/bin/add-site
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/docker-compose.yml
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/docker/files/usr/local/bin/entrypoint
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/docs/aws.md
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/backend/base/tests/test_cache.py
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/backend/{{cookiecutter.site}}/wsgi.py

The developper experience was not good as we had to run `bin/activate` and then export a variable. Many users forgot to export the variable expecting the activate script to do what it claims to do...
We now use the `.env` file to record the active site (similar to what is done for workspaces in Terraform). This allows a much better DX as running `bin/activate` now effectively activates the site.
We further improved DX by automatically activating the site without any prompt when there is only one site.

🔨(bin) stop using env variable to activate sites

---

.circleci/config.yml

The condition statement to determine if the job should run contained a wrong operator. There was only one `&` but to create an and operator we must use `&&` operator.

💚(ci) fix cookiecutter-bootstrap job

---

src/frontend/scss/components/templates/courses/cms/_course_detail.scss

Recently [we fixed an issue about icon visibility state](#1832) of course detail page. It was not display when the course run had no title. As a workaround we positioned icon through `position: absolute`. But we forgot to add a `position: relative` attribute to the course run row element so all visibility icon stick to the top of the course run list element instead to stick to the top of the course run row.

💄(course-detail) fix course run visibility state icon position

---

CHANGELOG.md
src/frontend/js/components/DashboardAddressesManagement/DashboardEditAddressLoader.tsx
src/frontend/js/components/DashboardCreditCardsManagement/DashboardEditCreditCard.spec.tsx
src/frontend/js/components/DashboardCreditCardsManagement/DashboardEditCreditCardLoader.tsx
src/frontend/js/components/DashboardCreditCardsManagement/index.spec.tsx
src/frontend/js/components/PaymentButton/index.tsx
src/frontend/js/hooks/useAddresses.ts
src/frontend/js/hooks/useAddressesManagement.tsx
src/frontend/js/hooks/useCreditCards/index.spec.tsx
src/frontend/js/hooks/useCreditCards/index.ts
src/frontend/js/hooks/useCreditCardsManagement.tsx
src/frontend/js/hooks/useOrders.ts
src/frontend/js/hooks/useResources/index.spec.tsx
src/frontend/js/hooks/useResources/index.tsx
src/frontend/js/hooks/useResources/useResourcesOmniscient.ts
src/frontend/js/hooks/useResources/useResourcesRoot.ts
src/frontend/js/types/Joanie.ts
src/frontend/js/types/utils.ts
src/frontend/js/utils/api/joanie.ts
src/frontend/js/utils/react-query/useSessionQuery/index.ts

Refactor resources to make use of a new useResources hook

---

gitlint/gitlint_emoji.py

The repostiory containing the list of valid emojis just got transformed into a monorepo causing the old url to be obsolete.

👷(ci) update gitmojis json url

---

CHANGELOG.md
src/frontend/js/components/CourseProductCourseRuns/EnrollableCourseRunList.tsx
src/frontend/js/components/CourseProductCourseRuns/EnrolledCourseRun.tsx
src/frontend/js/components/CourseProductCourseRuns/_styles.scss
src/frontend/js/components/CourseProductCourseRuns/index.spec.tsx
src/frontend/js/components/PaymentButton/_styles.scss

On the CourseProductItem, when user tries to enroll or unenroll to a course run, if the request fails, the user has no feedback the action is failing that is weird.
An error message should be display to explicitly show to the user that its action has failed.

🐛(frontend) Bug/error message course run item

---

CHANGELOG.md
src/frontend/js/components/CourseProductItem/_styles.scss
src/frontend/js/components/SaleTunnel/index.spec.tsx
src/frontend/js/components/SaleTunnel/index.tsx

A user is able today to buy a product with no open course runs.

🐛(frontend) show message when a product without any course run

---

Makefile

Add `frontend-test` script that allows the developer to run a specific frontend test more easy.

🔨(test) add script to run specific frontend test

---

CHANGELOG.md
src/frontend/scss/colors/_theme.scss

When no opened course runs are available, a label is displayed to explain that to the user but currently the shade difference between the color label and its background does not comply with RGAA. A good takeoff seems to use the "dark-grey" color which is not the best contrast but good enough for RGAA and light enough to understand that something is "disabled".

♿(frontend) use darker color for empty course detail

---

src/frontend/js/hooks/useResources/useResourcesOmniscient.ts

When leaving a tab opened for at least 20min ( which is the stale time delay ), the first refresh was giving empty react-query results even if the HTTP request was appearing in the network. It was only affecting omniscient resources, it was due to that the fact that stale queries are the only one that, in the first render, will have at the same time fetching===true and datas fullfilled. This fix allows the useEffect that applies the filter to be called when fetching turns false.

🐛(frontend) fix omniscient stale query that stay empty

---

CHANGELOG.md
src/richie/apps/courses/api.py
tests/apps/courses/test_api_course_run_sync.py

Currently, the `sync_course_run` method raises a `MultipleReturnedObject` exception when trying to retrieve a Course which has snaphots.

🐛(courses) fix course runs sync api when course has a snapshot

---

CHANGELOG.md
src/frontend/js/components/CourseRunEnrollment/_styles.scss
src/frontend/js/components/CourseRunEnrollment/index.joanie.spec.tsx
src/frontend/js/components/CourseRunEnrollment/index.openedx.spec.tsx
src/frontend/js/components/CourseRunEnrollment/index.tsx
src/frontend/js/data/useCourseEnrollment/index.ts
src/frontend/js/types/api.ts
src/frontend/js/utils/api/configuration.ts
src/frontend/js/utils/api/enrollment.ts
src/frontend/js/utils/api/joanie.ts
src/frontend/js/utils/api/lms/index.ts
src/frontend/js/utils/api/lms/joanie.ts
src/frontend/js/utils/api/lms/openedx-hawthorn.ts

Since #1815, Richie is able to match course runs and products managed by Joanie. But in the case of a Joanie Course Run is matched, the EnrollmentAPI interface is not able to return an interface to enroll user through the Joanie API.
EnrollmentAPI should be able to match joanie course run resource_link then returns to the right api to manage enrollment on Joanie.

✨(frontend) CourseRunEnrollment - CourseRun managed by Joanie 

---

CHANGELOG.md
env.d/development/dev-ssl.dist
env.d/development/dev.dist
sandbox/settings.py
src/richie/apps/core/templatetags/feature_flags.py
tests/apps/core/test_templatetags_feature_flags.py

We need to activate / disable some features during development.
This will let us push partial features (only front,only back for example).
* configure feature flag in .env files with the prefix: "FEATURE_".
* add this flag in settings.py
* either use `settings.get('FEATURE_{MY_FEATURE}')` in python or use `{ feature_flags.feature 'MY_FEATURE' }` in jinja templates
I tried like to use a dict in .env file but i didn't find how to do it.
The idea is to set `settings.FEATURES` only once instead of editing `settings.py` each time we wanna add/remove a flag.

✨(backend) implement feature flags from .env

---

src/frontend/js/components/CourseProductCourseRuns/index.spec.tsx

The test passes randomly because of the random generation of the course_run

🐛(frontend) fix enrollment not started test for CourseProductCourseRuns

---

CHANGELOG.md
src/frontend/scss/objects/_course_glimpses.scss

In some cases, section variant can enforce the svg fill color of its children. That leads to a conflict with the course glimpses when they are used within this kind of section as organization and reference icons fill color are overriden.
<p>
</p>

💄(frontend) fix style bug on course glimpse when used in a section

---

CHANGELOG.md
src/frontend/js/components/AddressesManagement/AddressForm.tsx
src/frontend/js/components/DashboardCreditCardsManagement/DashboardEditCreditCard.tsx
src/frontend/js/components/Form/Field.stories.tsx
src/frontend/js/components/Form/Inputs.tsx
src/frontend/js/hooks/useDashboardAddressForm.tsx
src/frontend/scss/objects/_form.scss

Currently, checkbox and select labels are not suffixed by an asterisk when they are required.

💄(form) add * on select, checkbox and radio inputs when required

---

CHANGELOG.md
UPGRADE.md
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/backend/{{cookiecutter.site}}/settings.py
docs/web-analytics.md
sandbox/settings.py
src/frontend/js/types/WebAnalytics.ts
src/frontend/js/types/commonDataProps.ts
src/frontend/js/utils/api/web-analytics/base.ts
src/frontend/js/utils/api/web-analytics/google_tag.spec.ts
src/frontend/js/utils/api/web-analytics/google_tag.ts
src/frontend/js/utils/api/web-analytics/google_universal_analytics.spec.ts
src/frontend/js/utils/api/web-analytics/google_universal_analytics.ts
src/frontend/js/utils/api/web-analytics/google_universal_analytics_and_tag_manager.spec.ts
src/frontend/js/utils/api/web-analytics/index.ts
src/frontend/js/utils/api/web-analytics/unknown_provider.spec.ts
src/frontend/js/utils/test/factories.ts
src/richie/apps/core/context_processors.py
src/richie/apps/core/templates/richie/base.html
src/richie/apps/core/templates/richie/web_analytics.html
src/richie/apps/core/templates/richie/web_analytics_body_begin.html
tests/apps/core/test_pages.py
tests/apps/core/test_web_analytics.py

Allow multiple web analytics providers at the same time. 
Rename web analytics providers, from `google_analytics` to `google_universal_analytics`. The `google_tag_manager` now uses the correct `gtm.js` and the `google_tag` uses the `gtag.js`. Replace the multiple web analytics settings with a single `WEB_ANALYTICS` dict setting.
The location logic of web analytics js code has been moved to be inside the `web_analytics.html` template.

✨(web_analytics) allow multiple providers

---

src/frontend/.storybook/preview.tsx

The frontend architecture rework missed the rewrite of the Storybook preview file useAsyncEffect import causing Storybook to crash.

🐛(frontend) fix Storybook preview file import

---

cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/frontend/package.json
src/frontend/js/widgets/CourseProductItem/components/CourseProductCourseRuns/index.spec.tsx
src/frontend/js/widgets/CourseProductItem/index.spec.tsx

Currently, the nightly round job is failing because the cookiecutter fails to install frontend deps. Indeed, previously, webpack & webpack-cli were installed implicitly by `richie-education` package all was working fine. But now, it appears we have to installed explicitly those dependencies.
https://app.circleci.com/pipelines/github/openfun/richie/6136/workflows/33dcf424-4b4b-477d-93ab-735adee1d093/jobs/171755

🔧(cookiecutter) fix frontend build

---

CHANGELOG.md
src/richie/apps/courses/api.py
tests/apps/courses/test_api_course_run_sync.py

Fix error `MultipleObjectsReturned` when synchronize course runs, when using MySQL as Richie database.
fixes #1956

🚑️(api) fix sync error using MySQL

---

CHANGELOG.md
src/frontend/js/pages/DashboardCourses/index.spec.tsx
src/frontend/js/pages/DashboardOrderLayout/index.spec.tsx
src/frontend/js/pages/DashboardOrderLayout/index.tsx
src/frontend/js/types/Joanie.ts
src/frontend/js/utils/test/factories/joanie.ts
src/frontend/js/utils/test/mockProductWithOrder.ts
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.tsx
src/frontend/js/widgets/Dashboard/components/DashboardOrderLoader/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardSidebar/_styles.scss
src/frontend/js/widgets/Dashboard/components/DashboardSidebar/index.tsx
src/frontend/js/widgets/Dashboard/components/LearnerDashboardSidebar/index.tsx
src/frontend/js/widgets/Dashboard/utils/learnerRouteMessages.tsx
src/frontend/js/widgets/Dashboard/utils/learnerRoutes.tsx

~~- [ ] Update to DashboardLayoutRoute to render only Outlet~~

✨(front) rework order layout and add new pages

---

src/frontend/js/utils/test/factories/joanie.ts

The given type as factory type parameter does not
work as expected.
In order to force the return type of factories's builder function, it need's to be directly define as the builder return type.

🐛(frontend) fix factories initialization

---

src/frontend/js/pages/DashboardCourses/constants.ts
src/frontend/js/pages/DashboardCourses/index.spec.tsx
src/frontend/js/pages/DashboardCourses/useOrdersEnrollments.tsx

DashboardCourses take 150s to run.
Test pages of 4 elements instead of 50 for a run time of 8 seconds

⚡️(frontend) improve DashboardCourses test performance

---

CHANGELOG.md
UPGRADE.md
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/backend/setup.cfg
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/backend/{{cookiecutter.site}}/urls.py
sandbox/urls.py
setup.cfg
src/richie/apps/courses/urls.py
src/richie/apps/courses/views.py
tests/apps/courses/test_views_course_code_redirect.py

Within react component, we want to be able to create a link to course's syllabus . We get data from Joanie API so we cannot pass this link through component data-props. As a workaround, we decide to add a redirect route `/redirects/courses/<course_code>` which redirects the user to the course page through its course code.

✨(backend) add a route to redirect to course page through a course code

---

CHANGELOG.md
src/frontend/js/api/joanie.ts
src/frontend/js/components/TeacherDashboardCourseList/index.tsx
src/frontend/js/hooks/useCourseProductUnion/index.spec.tsx
src/frontend/js/hooks/useCourseProductUnion/index.ts
src/frontend/js/pages/TeacherOrganizationCourseDashboardLoader/index.tsx
src/frontend/js/types/Joanie.ts
src/frontend/js/widgets/Dashboard/_styles.scss
src/frontend/js/widgets/Dashboard/components/DashboardAvatar/_styles.scss
src/frontend/js/widgets/Dashboard/components/DashboardAvatar/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardAvatar/index.stories.tsx
src/frontend/js/widgets/Dashboard/components/DashboardAvatar/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardSidebar/_styles.scss
src/frontend/js/widgets/Dashboard/components/DashboardSidebar/index.tsx
src/frontend/js/widgets/Dashboard/components/TeacherOrganizationDashboardSidebar/index.tsx
src/frontend/scss/components/_index.scss

note: rebased on #1997 and #1990
On the teacher dashboard, teacher needs to access the list for they organizations courses.
Everything is configured and tested as if our backend returned the right `Courses` and `CourseProductRelations` listing for :
* `organizations/{organizationId}/courses`
* `organizations/{organizationId}/course-product-relations`

✨(frontend) Teacher dashboard: list organization courses

---

CHANGELOG.md
src/richie/apps/core/templates/menu/language_menu.html
src/richie/apps/core/templatetags/language_name.py
tests/apps/core/test_language_chooser.py

Show original language name on the menu instead of translating it on the current language.
Screenshots with this PR:
If user is authenticated in English:
If user is authenticated in French:

🚸(language) use original language name on menu

---

CHANGELOG.md
src/frontend/js/pages/TeacherCourseDashboardLoader/CourseRunList/utils.tsx
src/frontend/js/types/index.ts
src/frontend/js/utils/test/factories/joanie.ts
src/frontend/js/utils/test/factories/richie.ts
src/richie/apps/courses/models/course.py
tests/apps/courses/test_models_course_run.py
tests/apps/search/test_query_courses.py

This commit change text and remove datetime on glimpse footer.
Change text and remove datime on glimpse footer when state is ONGOING_OPEN 
This commit resolve the issue https://github.com/openfun/richie/issues/1970
- Changes was made on course models
- Existent tests was refactored.

✨(backend) change course glimpse footer state

---

src/frontend/js/types/Joanie.ts
src/frontend/js/widgets/CourseProductItem/components/PurchaseButton/index.spec.tsx
src/frontend/js/widgets/CourseProductItem/components/PurchaseButton/index.tsx

Currently, Joanie product endpoint does not return the `remaining_order_count`. In order to prevent to break the CourseProductItemWidget, we make this property optional.

🐛(frontend) make remaining_order_count optional

---

.circleci/config.yml
docker-compose.yml

Currently, the job to upload translations to crowdin fails. Actually, Crowdin API seems have breaking change that does not comply with current version of crowdin we are using. Upgrade to the latest version of crowdin fixes the issue.

💚(crowdin) upgrade crowdin to version 3.13.0

---

src/frontend/js/pages/TeacherOrganizationCourseDashboardLoader/index.tsx

We have an error when organization is not in ReactQuery cache.

🐛(frontend) fix organization breadcrumb

---

cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/frontend/package.json

Cookiecutter package name has been renamed by mistake. We fix it...

🔧(cookiecutter) fix frontend package name

---

CHANGELOG.md
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/.circleci/src/jobs/@project.yml

Missing `requests` pip package when running `gitlint`, like the same have been done on: https://github.com/openfun/richie/blob/2e3d0f4078071243a026c51ffa57b27c975ac707/.circleci/config.yml#L65

⬆️(cookiecutter) fix cookiecutter circleci gitlint

---

CHANGELOG.md
src/frontend/js/utils/CourseRuns/index.spec.tsx
src/frontend/js/utils/CourseRuns/index.ts

A miss in the code caused courses runs without enrollment end date or without end date to be considered as archived, where they are in reality ongoing.
Based on #2063

🐛(frontend) fix course run that should not be archived

---

CHANGELOG.md
src/frontend/js/widgets/LtiConsumer/index.spec.tsx
src/frontend/js/widgets/LtiConsumer/index.tsx

Currently, the query in charge to retrieve the LTIConsumer context relies on the
session state. So each time, the user is updated (e.g: when access token is
refreshed), the LTI context is refetched so the LTI Iframe is rerendered. This
is weird as it can reset the iframe state when user is interacting with. In
order to prevent this drawback, we decide to not reprocess the LTI Context each
time the user changes.
When user session is stale, it is refetched automatically in the background. Once the new state has been retrieved, the LTIConsumer component is rerendered. In the following case study, if the session state is updated while user is watching a teaser, the video player is reset ...
https://github.com/openfun/richie/assets/9265241/cc860c85-1a41-4da8-8876-4f01991a1c21

🐛(frontend) prevent LTIConsumer context to be refreshed on user update

---

src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderStateMessage/index.tsx

The OrderStateMessage does not handle validated state properly. Indeed this component does not have message to display for this state and it handles an error like this state was unknown. Of course, we only want to handle error in case an unknown state is provided but not when the provided state does not have message to display.

🐛(frontend) OrderStateMessage handle error on "validated" state

---

CHANGELOG.md
src/frontend/js/pages/TeacherDashboardContractsLoader/TeacherDashboardContracts/index.spec.tsx
src/frontend/js/pages/TeacherDashboardContractsLoader/TeacherDashboardContracts/index.tsx
src/frontend/js/types/Joanie.ts
src/frontend/js/utils/test/factories/joanie.ts
src/frontend/js/utils/test/mockCourseProductWithOrder.ts
src/frontend/js/widgets/Dashboard/components/DashboardItem/DashboardItemCourseEnrolling.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderStateMessage/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderStateMessage/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/_styles.scss
src/frontend/js/widgets/Dashboard/components/DashboardOrderLoader/_styles.scss
src/frontend/js/widgets/Dashboard/components/DashboardOrderLoader/index.tsx
src/frontend/scss/components/_index.scss

When a product with contract_definition is purchased,
The learner have to sign the order.contract before
enrolling to training's courses.
If the contract have been signed, the learner can
download it.
There a new section in order details page that
handle these actions.

✨(frontend) order details: add contract

---

src/frontend/js/components/Modal/index.tsx
src/frontend/js/components/SaleTunnel/components/SaleTunnelStepPayment/index.spec.tsx
src/frontend/js/components/SaleTunnel/components/SaleTunnelStepValidation/index.spec.tsx

:skull: The payment step of the sale tunnel is not accessible
Quickfix: 
Sale tunnel modal is render in a portal.
All our route are render inside a `<CunninghamProvider/>` but the modal's portal wasn't.

🐛(frontend) Fix sale tunnel

---

CHANGELOG.md
src/frontend/js/components/PaymentButton/index.spec.tsx
src/frontend/js/components/PaymentButton/index.tsx
src/frontend/js/components/PurchaseButton/index.tsx
src/frontend/js/components/SaleTunnel/context.tsx
src/frontend/js/components/SaleTunnel/index.tsx
src/frontend/js/types/Joanie.ts
src/frontend/js/utils/ProductHelper/index.ts
src/frontend/js/utils/test/factories/joanie.ts
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/_styles.scss
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.spec.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.tsx

We need to disable purchasing a product when all order groups are full, and also display multiple purchase button when there are multiple with seats available.

✨(frontend) handle OrderGroup on product purchase

---

CHANGELOG.md
src/frontend/js/hooks/useUnionResource/utils/fetchEntity.ts
src/frontend/js/pages/DashboardCourses/useOrdersEnrollments.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrderContract.spec.tsx

We had a bug where the cache invalidation triggered when a contract is signed was not impacting useOrdersEnrollments. This was causing the "Sign" button to be still displayed. A related bug where after buying a product from the syllabus page, the newly created order was not shown was also fixed by theses changes.

🐛(frontend) fix various cache order issues

---

src/frontend/js/hooks/useBreadcrumbsPlaceholders.tsx

We had multiple trigger of a useEffect that was enoying to test pages that use breadcrumb's placeholders.

🐛(frontend) multiple calls of pushBreadcrumbsPlaceholders

---

src/frontend/js/widgets/Dashboard/components/TeacherDashboardProfileSidebar/components/OrganizationLinks/_styles.scss
src/frontend/js/widgets/Dashboard/components/TeacherDashboardProfileSidebar/components/OrganizationLinks/index.tsx

Currently, the organization logo could be truncated if its dimensions does not match the aspect-ratio defined in style. E.g a 1/1 logo was truncated as the aspect ratio is 2/1.
Furthermore, joanie is returning a srcset property into its file detail, so we can take benefit of this attribute to properly set organization logo size in responsive context.
|<img width="292" alt="Capture d’écran 2023-12-12 à 11 36 31" src="https://github.com/openfun/richie/assets/9265241/dbbca011-6a81-4f7e-8fe1-b60e5f351231">|<img width="289" alt="Capture d’écran 2023-12-12 à 11 51 51" src="https://github.com/openfun/richie/assets/9265241/5ca2f77c-07b0-44b9-a2cd-f8decf56acbe">|

💄(frontend) fix organization logo link size issue

---

sandbox/settings.py

Now that we have a learner and teacher dashboard, we want to replace the lms dashboard route by the richie dashboard routes when Joanie is enabled and the feature flag REACT_DASHBOARD is set to True. Unfortunately, currently, the current logic is not working as it needs some information set during configuration post_setup.

🩹(backend) properly set AUTHENTICATION_DELEGATION.PROFILE_URLS

---

src/frontend/js/pages/DashboardOrderLayout/_styles.scss
src/frontend/js/pages/DashboardOrderLayout/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardLayout/_styles.scss
src/frontend/js/widgets/Dashboard/components/DashboardLayout/index.tsx
src/frontend/scss/components/_index.scss

We decided to simply hide the sidebar inside the order details because it was empty, and in the future we will just have to remove the display none clause to show it again. Also remove the empty space caused by the filters container, now we only show it if there are filters.

💄(frontend) hide order sidebar, hide filters space

---

CHANGELOG.md
src/frontend/js/api/lms/dummy.ts
src/frontend/js/components/SaleTunnel/components/SaleTunnelStepPayment/index.spec.tsx
src/frontend/js/components/SaleTunnel/components/SaleTunnelStepPayment/index.tsx
src/frontend/js/types/User.ts
src/frontend/js/utils/UserHelper/index.spec.ts
src/frontend/js/utils/UserHelper/index.ts
src/frontend/js/utils/test/factories/richie.ts
src/frontend/js/widgets/Dashboard/components/LearnerDashboardSidebar/index.tsx
src/frontend/js/widgets/Dashboard/components/TeacherDashboardProfileSidebar/index.tsx
src/frontend/js/widgets/Dashboard/index.spec.tsx
src/frontend/js/widgets/UserLogin/components/UserMenu/DesktopUserMenu.tsx
src/frontend/js/widgets/UserLogin/components/UserMenu/MobileUserMenu.tsx
src/frontend/js/widgets/UserLogin/index.not.isJoanieEnabled.spec.tsx
src/frontend/js/widgets/UserLogin/index.spec.tsx
src/frontend/js/widgets/UserLogin/index.tsx

Since fonzie 0.5.0, authentication server can now return user full name. So in this case, this property is defined, we should display it instead of username.
With PR openfun/joanie#489, Joanie create dev demo script now generate several users which stick to realistic use cases. Learner, teacher, organization owner are created so on Richie, in order to improve DX, we should be able to switch easily between those profiles. That's why we update the dummy api interface. We hardcode all existing users created by dev demo joanie script then we implement a method `getUserInfo` to return the right payload just by providing a username.

Frontend - Use full_name if it exists

---

CHANGELOG.md
src/frontend/js/types/index.ts
src/frontend/js/utils/test/factories/richie.ts
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunEnrollment/_styles.scss
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunEnrollment/index.openedx.spec.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunEnrollment/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/index.tsx

This attribute is no longer given by django since the migration
of the enrollment to full react. Now we need to compute it on the
front-end side to avoid any caching lags.
---
Some buttons were still using the legacy style, which was rendering
different style of buttons next to each other, it was a bit odd.

🐛(frontend) delete courseRun.starts_in_message

---

src/frontend/js/api/joanie.spec.ts
src/frontend/js/api/joanie.ts
src/frontend/js/hooks/useCourseProductRelation/index.ts
src/frontend/js/hooks/useCourseProductUnion/index.spec.tsx
src/frontend/js/hooks/useCourseProducts.ts
src/frontend/js/hooks/useCourses/index.ts
src/frontend/js/hooks/useOrganizations/index.ts
src/frontend/js/pages/DashboardCourses/index.spec.tsx
src/frontend/js/pages/DashboardOrderLayout/index.tsx
src/frontend/js/pages/TeacherDashboardCourseLoader/index.tsx
src/frontend/js/pages/TeacherDashboardTraining/TeacherDashboardTrainingLoader.tsx
src/frontend/js/pages/TeacherDashboardTraining/index.spec.tsx
src/frontend/js/types/Joanie.ts
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrderContract.useUnionResource.cache.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardOrderLoader/index.tsx
src/frontend/js/widgets/Dashboard/components/TeacherDashboardCourseSidebar/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.tsx

Currently an error can occured when a user can access to a course from its organization access but it does not course/training accesses on this course. Indeed, the user will be able to access to the course/training detail page but the api will return a 404... 
To work properly, in the context of an organization, course/training information should be fetched from the nested organization endpoints.
|<img width="1100" alt="Capture d’écran 2023-12-14 à 16 23 19" src="https://github.com/openfun/richie/assets/9265241/1f70165a-abbd-4642-ac3b-9711c6ec2844">|<img width="1100" alt="Capture d’écran 2023-12-14 à 16 22 51" src="https://github.com/openfun/richie/assets/9265241/72152ed5-a941-4cd2-8b53-ccddd8737c7c">|
|<img width="1100" alt="Capture d’écran …

♻️(frontend) refactor joanie api endpoints

---

src/frontend/js/components/PurchaseButton/index.spec.tsx

Wrong usage of act can hide real bug. Most of the time RTL handle needed act and we just have to await a element on the page.
```
$ yarn test js/components/PurchaseButton/index.spec.tsx
yarn run v1.22.19
$ jest js/components/PurchaseButton/index.spec.tsx
PASS  js/components/PurchaseButton/index.spec.tsx (5.387 s)
PurchaseButton
✓ shows a login button if user is not authenticated (107 ms)
✓ shows cta to open sale tunnel when user is authenticated (112 ms)
✓ shows cta to open sale tunnel when remaining orders is null (76 ms)
✓ shows cta to open sale tunnel when remaining orders is undefined (61 ms)
✓ renders a disabled CTA if the product have no remaining orders (24 ms)
✓ renders a disabled CTA if one target course has no course runs. Case "Product credential" (27 ms)
✓ renders a disabled …
```

✅(frontend) act clean in PurchaseButton test

---

src/frontend/js/widgets/Dashboard/components/DashboardItem/Certificate/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Certificate/index.tsx

resolve issue #2188
We've two way to retrieve course code depending on the certificate. If it's link to a credential order, then we look for certificate.order.course;
And when it's link to a certificate order, then we look for certificate.order.enrollment.

🐛(frontend) display course code on Certificate

---

src/frontend/js/components/ContractStatus/index.tsx
src/frontend/js/types/Joanie.ts
src/frontend/js/utils/ContractHelper/index.spec.ts
src/frontend/js/utils/ContractHelper/index.ts

A contract expects to be signed by both learner and organization, in some of our
views we need to get the signature state. That's the purpose of this
ContractHelper util. It is able to return the raw state or a human readable
label. Furthermore, according to point of view of the user (learner or
organization), label should be adapted.

✨(frontend) add ContractHelper to compute state

---

src/frontend/js/hooks/useUnionResource/index.spec.tsx
src/frontend/js/hooks/useUnionResource/index.ts
src/frontend/js/pages/DashboardCourses/index.spec.tsx

issue: [#2168](https://github.com/openfun/richie/issues/2168)
In the orders and enrollments listing page where we use this useUnionResources, we had a "Load more" button on the first render, when data where loading.
hasLoadMore must be false until we retrieve data for the first time.

🐛(frontend) Fix useUnionResource hasLoadMore

---

src/frontend/js/components/PaymentButton/index.spec.tsx
src/frontend/js/components/PaymentButton/index.tsx
src/frontend/js/utils/ObjectHelper/index.spec.ts
src/frontend/js/utils/ObjectHelper/index.ts

It appears there was a typing issue that lead to pass a wrong payload. This could break payment logic when working the dummy payment backend. Indeed, the billing address should not contain id and is_main fields but currently the address was not cleaned up before putting it in the payload. We now use the new `ObjectHelper.omit` utils to remove id and is_main fields from the selected address.

🩹(frontend) clean billing address before order submit

---

src/frontend/js/components/ContractStatus/index.spec.tsx
src/frontend/js/components/ContractStatus/index.tsx
src/frontend/js/components/SignContractButton/index.omniscientOrders.spec.tsx
src/frontend/js/components/SignContractButton/index.spec.tsx
src/frontend/js/components/SignContractButton/index.tsx
src/frontend/js/pages/DashboardContracts/index.spec.tsx
src/frontend/js/utils/ContractHelper/index.spec.ts
src/frontend/js/utils/ContractHelper/index.ts
src/frontend/js/widgets/Dashboard/components/DashboardItem/Contract/_styles.scss
src/frontend/js/widgets/Dashboard/components/DashboardItem/Contract/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Contract/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrderContract.spec.tsx

Learner's training contract can have a new status where it's signed by the
learner but waiting the organization to counter-sign it.
There a small adaptation of our ContractStatus and
DashboardItemContract components
New state "waiting for organization to sign"
Modified state "Download your training contract"

✨(frontend) adapt contract status with organization_signed_on

---

src/frontend/js/components/Banner/index.tsx
src/frontend/js/pages/DashboardCourses/index.spec.tsx
src/frontend/js/pages/DashboardCourses/index.tsx
src/frontend/js/utils/test/expectBanner.ts

issue: [#2187](https://github.com/openfun/richie/issues/2187)
Use a banner component to display the "empty list" message in the orders and enrollments listing page.
Before: 
After:

💄(frontend) Banner on dashboard/courses

---

cookiecutter/{{cookiecutter.organization}}-richie-site-factory/.circleci/src/jobs/@frontend.yml
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/Dockerfile
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/docker-compose.yml
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/frontend/package.json

Some frontend dependencies now requires node >= 18, we recently update node images of the repository but forgot cookiecutter ones.

⬆️(cookiecutter) migrate to node 18

---

src/frontend/js/widgets/Dashboard/components/DashboardItem/utils/order.ts
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.spec.tsx

Learner must sign there contract after they purchase a product with a
contract_definition attach.
There for it we should not show him any sign button before he complete
his purchase. It must be limited to VALIDATED orders.

🐛(frontend) fix sale tunnel order stats

---

src/frontend/js/widgets/Dashboard/components/DashboardSidebar/_styles.scss

On mobile, the dashboard sidebar is displayed at the top of the page. But currently its z-index is less than the content so when user open the select menu
to navigate this one appears below the content.

🩹(frontend) fix dashboard sidebar zindex issue

---

src/frontend/js/widgets/Dashboard/components/DashboardItem/DashboardItemCourseEnrolling.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderStateMessage/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardSidebar/_styles.scss
src/frontend/js/widgets/Dashboard/hooks/useEnroll/index.ts

Currently, the content of the dashboard sidebar header was not align to center so with long content, this one was left aligned that was weird.
| Before | After |
|<img width="325" alt="Capture d’écran 2024-01-04 à 13 36 05" src="https://github.com/openfun/richie/assets/9265241/22516e1b-a382-4c7c-9a70-7ea39a453560">|<img width="325" alt="image" src="https://github.com/openfun/richie/assets/9265241/878930fa-8fe3-43b9-8a07-fe875474126a">|
Furthermore, some messages have been declared without using the react-intl defineMessages
method so those messages have not been uploaded to crowdin.

🩹(frontend) minor fixes

---

CHANGELOG.md
src/frontend/js/widgets/Dashboard/components/LearnerDashboardSidebar/index.tsx

The order of learner dashboard link weren't perfect.
It's prettier like this, everyone whould agree.

💄(frontend) reorder learner dashbaord menu link

---

CHANGELOG.md
src/frontend/js/contexts/SessionContext/BaseSessionProvider.tsx
src/frontend/js/contexts/SessionContext/JoanieSessionProvider.tsx

The authentication logout is async but we do not wait the promise resolve when the user triggers logout method. But in some case it could lead to bug. Indeed, if the user query invalidation trigger a redirect, not await the promise resolve, lead to refetch user data before the authentication server has really logout the user so the session is populated with outdated user information...

🩹(frontend) await logout request

---

CHANGELOG.md
src/frontend/js/components/SaleTunnel/components/SaleTunnelStepResume/index.spec.tsx
src/frontend/js/components/SaleTunnel/components/SaleTunnelStepResume/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/components/ProductSignatureHeader/index.tsx

After a user purchased a training, if this one has a contract to sign, the UI invites the user to go to its dashboard to sign this one. But currently, the URL
is malformed according to the current locale. Indeed, dashboard urls are
localized so if the current locale is something else than english the link will
be wrong.

🐛(frontend) fix routes to redirect user to its dashboard

---

CHANGELOG.md
src/frontend/js/widgets/Dashboard/components/DashboardItem/DashboardItemCourseEnrolling.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/DashboardItemEnrollment.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/_styles.scss

Currently, in the order detail view, if a user is enrolled to a course run we
only display a labelled to tell it, it is enrolled but there is no link to
access to the course that is weird. So we revamp this UI to add this link and
keep information that the user is enrolled.
|<img width="800" alt="image" src="https://github.com/openfun/richie/assets/9265241/da601e9d-7c0f-408b-b21b-a0758d13103f">|<img width="800" alt="image" src="https://github.com/openfun/richie/assets/9265241/3050cca1-c788-4748-aac2-924ac3c5cf6c">|

Fix issue #2232

---

src/frontend/js/api/joanie.ts
src/frontend/js/components/ContractFrame/OrganizationContractFrame.tsx
src/frontend/js/hooks/useContracts/index.tsx
src/frontend/js/hooks/useTeacherPendingContractsCount/index.ts
src/frontend/js/pages/DashboardContracts/index.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/TeacherDashboardContracts/index.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useTeacherContractsToSign.tsx
src/frontend/js/types/Joanie.ts
src/frontend/js/widgets/Dashboard/components/TeacherDashboardOrganizationSidebar/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/TeacherDashboardOrganizationSidebar/index.tsx

We have three routes to interact with contracts:
* /contracts/id : return current user orders's contrats
* /organizations/id/contracts/id: return contract for a organization, check `OrganizationAccess`.
* /courses/id/contracts/id: return contract for a organization, check `CourseAccess`.
The current implementation of theses route use a unique hook that check filters to decide which route to use between contract and organizations/contracts. 
In order to implement courses's contract page and action, we need to interact with `courses/contracts` route and it's filters like : 
`courses/course_id/contracts/contract_id/?organization_id=organization_id`.
This isn't possible with the current implementation of contracts.get routes.
I decide here to split `useContract` hook in three to get one hook …

♻️(frontend) Split useContract into useContract and useOrganizationContract 

---

src/frontend/js/components/ContractFrame/OrganizationContractFrame.spec.tsx
src/frontend/js/components/ContractFrame/OrganizationContractFrame.tsx

Since useContract have been split into two (useUserContract and
useOrganizationContract), the list of contract on the teacher dashboard
wasn't refreshing after signing contracts.
It came from the query key that change after hook spliting.

🐛(frontend) Fix contract reload after signing

---

CHANGELOG.md
src/frontend/js/components/ContractFrame/AbstractContractFrame.spec.tsx
src/frontend/js/components/ContractFrame/AbstractContractFrame.tsx

We want to add a bit of explanations to the user becasue this step can take some time.
Closes #2243

✨(frontend) add signature polling description

---

CHANGELOG.md
src/frontend/js/hooks/useContracts/index.tsx
src/frontend/js/hooks/useTeacherPendingContractsCount/index.ts
src/frontend/js/pages/TeacherDashboardContractsLayout/TeacherDashboardContracts/index.spec.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/TeacherDashboardContracts/index.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/components/ContractActionsBar/index.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/components/ContractFiltersBar/index.spec.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/components/ContractFiltersBar/index.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useTeacherContractFilters.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useTeacherContractsToSign.tsx
src/frontend/js/types/Joanie.ts
src/frontend/js/widgets/Dashboard/components/TeacherDashboardOrganizationSidebar/index.tsx

blocked by ~[joanie issus 575](https://github.com/openfun/joanie/issues/575)~ (resolved)
We decide not to use the duo course_id and product_id anymore
but course_product_relation_id instead.
All our router's url have been migrate.
These contracts filters used the old way of filtering by product and
needed to be updated.

✨(frontend) update teacher contract filters

---

renovate.json

The manager declared in the renovate configuration is still setup-cfg but we change the manager used with pyproject. We have to change it in renovate with the pep621 manager:
https://docs.renovatebot.com/modules/manager/pep621/

 🔧(back) configure renovate with pyproject file

---

CHANGELOG.md
src/frontend/js/api/joanie.ts
src/frontend/js/hooks/useContractArchive/index.download.spec.tsx
src/frontend/js/hooks/useContractArchive/index.spec.tsx
src/frontend/js/hooks/useContractArchive/index.ts
src/frontend/js/pages/TeacherDashboardContractsLayout/components/BulkDownloadContractButton/index.spec.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/components/BulkDownloadContractButton/index.timer.spec.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/components/BulkDownloadContractButton/index.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/components/ContractActionsBar/index.spec.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/components/ContractActionsBar/index.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/components/SignOrganizationContractButton/index.spec.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useCheckContractArchiveExists/index.spec.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useCheckContractArchiveExists/index.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useDownloadContractArchive/contractArchiveLocalStorage.spec.ts
src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useDownloadContractArchive/contractArchiveLocalStorage.ts
src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useDownloadContractArchive/index.spec.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useDownloadContractArchive/index.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useHasContractToDownload/index.spec.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/hooks/useHasContractToDownload/index.tsx
src/frontend/js/settings.ts
src/frontend/js/types/Joanie.ts
src/frontend/js/utils/errors/HttpError.ts

Our organizations need to transfer signed contract to they administration.
We decide to let them download all fully signed contract from the
contracts page with this new "bulk download" feature.
Button label: 
* Download fully signed contracts
* Waiting zip archive generation...
* Request zip archive generation

✨(frontend) add contract bulk download 

---

CHANGELOG.md
src/frontend/js/api/lms/dummy.spec.ts
src/frontend/js/api/lms/dummy.ts
src/frontend/js/contexts/SessionContext/BaseSessionProvider.tsx
src/frontend/js/contexts/SessionContext/JoanieSessionProvider.tsx
src/frontend/js/contexts/SessionContext/index.spec.tsx

We realized that, on logout, setting react query ["user"] to null was taking too much time to be persisted in SessionStorage resulting in a redirection to the homepage before the data being flushed into the SessionStorage. (It is caused by throttleTime of the persister ) Sometimes the user was not able to logout due to this issue.

🐛(frontend) fix logout issue

---

CHANGELOG.md
src/frontend/js/components/PurchaseButton/index.tsx
src/frontend/js/components/SaleTunnel/index.tsx
src/frontend/js/components/TeacherDashboardCourseList/index.spec.tsx
src/frontend/js/hooks/useCourseProductUnion/index.ts
src/frontend/js/hooks/useQueryKeyInvalidateListener.tsx
src/frontend/js/hooks/useUnionResource/index.ts
src/frontend/js/pages/DashboardCourses/useOrdersEnrollments.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.tsx

The payment button was still shown after buying the associcated product certificate. So this refactor aims to do some optimistic UI updates in order to hide it after SaleTunnel payment.

fix cache enrollment product

---

src/frontend/js/components/Badge/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardSidebar/components/ContractNavLink/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardSidebar/components/ContractNavLink/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardSidebar/components/MenuNavLink/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardSidebar/components/MenuNavLink/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardSidebar/index.stories.tsx
src/frontend/js/widgets/Dashboard/components/DashboardSidebar/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardSidebar/utils.ts
src/frontend/js/widgets/Dashboard/components/TeacherDashboardOrganizationSidebar/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/TeacherDashboardOrganizationSidebar/index.tsx

:information_source: This new component will be used in the Course's contracts feature (see [related PR](https://github.com/openfun/richie/pull/2236))
:warning: ~block by #2229 ✨(frontend) update teacher contract filters~ (merged)
=== 
Contract navigation link have a specific behavior about they query params and a possible count badge.
This logic was part of the `OrganizationSidebar` component but need's to be implemented in the Course section.
To avoid duplicating code, we extract contract's dedicated code in a new `ContractNavLink` component.

♻️(frontend) add ContractNavLink

---

src/frontend/js/components/CourseGlimpse/index.spec.tsx
src/frontend/js/components/CourseGlimpse/index.tsx
src/frontend/js/components/CourseGlimpse/utils.ts

After some acceptance tests, it appears we should always display an organization
logo and the name of the main organization. In the case of Richie course run,
the `highlighted_organization` is the main ine. From Joanie, for now, we take the
first organization then later we add this notion of "main organization".
|Before|After|
|------|-----|
|<img width="300" alt="image" src="https://github.com/openfun/richie/assets/9265241/7865d0a1-1a4f-4c0f-a33d-372d9dae7177">|<img width="300" alt="image" src="https://github.com/openfun/richie/assets/9265241/fc425ada-181b-4b68-a1bb-41c6ddc54b24">|

🔥(frontend) remove nb_seller_organizations from course glimpse props

---

CHANGELOG.md
src/frontend/js/types/Joanie.ts
src/frontend/js/types/index.ts
src/frontend/js/utils/test/factories/joanie.ts
src/frontend/js/widgets/Dashboard/components/DashboardItem/stories.mock.ts
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunEnrollment/index.joanie.spec.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunEnrollment/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/hooks/useCourseEnrollment/index.ts

When a course run is managed by Joanie if the user is enrolled to a Course Run the link "Go to course" is not set properly. Indeed, the link targets the joanie course run endpoint instead of the lms course page.
resolve #2267

🐛(frontend) fix syllabus "Go to course" link

---

CHANGELOG.md
src/frontend/js/components/TeacherDashboardCourseList/index.tsx

We had a bug where the courses list scroll was reset at the top of the page.
`useUnionResource` `isLoading` is switching between `true` and `false` each time it load a new chunk of results.
As `isLoading` was used in `TeacherDashboardCourseList` to switch display between the spinner and the courses list, the page scroll was sometime reset when the list disappear.

🐛(frontend) fix teacher courses list scroll top

---

CHANGELOG.md
src/frontend/scss/objects/_organization_glimpses.scss
src/richie/apps/courses/settings/__init__.py
src/richie/apps/courses/templates/courses/cms/organization_detail.html
tests/apps/courses/test_templates_organization_detail.py

Actually, some organization can be a consortium of organizations. In this case, it can be interesting to list all organizations affiliated to this consortium. That's why we add a new placeholder `related_organizations` into organization_detail template.

✨(backend) allow to display related organizations on organization page

---

CHANGELOG.md
src/frontend/js/widgets/Dashboard/components/DashboardItem/DashboardItemCourseEnrolling.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/DashboardItemCourseEnrolling.tsx

We were displaying "enrollment starts on ..." on course run with wrong priorities which resulted in situation where it wasn't making any sense. Additionnally this commit fixes the existing tests that were not passing due to missing await clauses.
Fixes #2254

🐛(frontend) remove enrollment start on some course run

---

CHANGELOG.md
src/frontend/js/components/PaymentButton/hooks/useTerms.tsx
src/frontend/js/components/PaymentButton/index.spec.tsx
src/frontend/js/types/commonDataProps.ts
src/frontend/js/utils/test/factories/richie.ts
src/richie/apps/core/context_processors.py
tests/apps/core/test_pages.py
tests/apps/courses/test_templatetags_category_tags_get_related_categories.py
tests/apps/courses/test_templatetags_extra_tags_block_plugin.py

Currently, into the sale tunnel when there is a contract to sign, the user must accept our terms and conditions. We allow the user to download a preview of the contract which include those terms and conditions.
This is not a proper solution for ux. Instead we decide to create a dedicated page on our platform then we just have to link this page in the sale tunnel. Simpler, better.

✨(frontend) link to terms and conditions page

---

CHANGELOG.md
src/frontend/js/utils/CreditCardHelper/index.spec.tsx
src/frontend/js/utils/CreditCardHelper/index.tsx

`DashboardCreditCardsManagement` test about credit card expiration date use a date in less than 3 month in the future.
This date some time happen to be exactly 3 month, just a few hours before the treshold of 3 month.
As `CreditCardHelper.isExpiredSoon` only check year and month and not hours, the test failed.

✅(frontend) fix flaky test

---

CHANGELOG.md
src/frontend/js/api/lms/dummy.ts
src/frontend/js/settings.dev.dist.ts
src/frontend/js/widgets/Dashboard/utils/teacherRouteMessages.tsx

In teacher dashboard, the related sidebar menu entry to the root view of a 
training is labelled "Training". It should be labelled "General information" 
like free courses.

💬(frontend) update root menu entry label of training views

---

CHANGELOG.md
src/frontend/js/components/ContractFrame/OrganizationContractFrame.spec.tsx
src/frontend/js/components/ContractFrame/OrganizationContractFrame.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/TeacherDashboardContracts/index.spec.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/TeacherDashboardContracts/index.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/components/ContractActionsBar/index.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/components/SignOrganizationContractButton/index.spec.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/components/SignOrganizationContractButton/index.tsx
src/frontend/js/types/Joanie.ts
src/frontend/js/widgets/Dashboard/components/DashboardSidebar/components/ContractNavLink/index.tsx
src/frontend/js/widgets/Dashboard/components/TeacherDashboardCourseSidebar/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/TeacherDashboardCourseSidebar/index.tsx
src/frontend/js/widgets/Dashboard/components/TeacherDashboardCourseSidebar/utils.ts

blocked by ~[joanie issue: 575](https://github.com/openfun/joanie/issues/575) ✨(backend) filters organization get contract endpoint by course_product_relation_id~ (resolved)
blocked by ~[joanie issue: 576](https://github.com/openfun/joanie/issues/576) ✨(backend) make organization contract's getSignatureLinks usable with course & product~ (resolved)
blocked by PR #2228 ~♻️(frontend) Split useContract into useContract and useOrganizationContract~ (merged)
blocked by PR #2229 ~✨(frontend) update teacher contract filters~ (merged)
blocked by PR #2247 ~♻️(frontend) add ContractNavLink~ (merged)
blocked by PR #2265 ~🐛(frontend) fix useContractFilters~ (merged)
Organizations must to be able to sign all they pending contacts for a specific course.

✨(frontend) bulk sign contract on course

---

CHANGELOG.md
src/frontend/js/api/joanie.ts
src/frontend/js/components/PaymentButton/index.spec.tsx
src/frontend/js/components/PaymentButton/index.tsx
src/frontend/js/components/SaleTunnel/components/SaleTunnelStepResume/index.spec.tsx
src/frontend/js/components/SaleTunnel/context.tsx
src/frontend/js/components/SaleTunnel/index.tsx
src/frontend/js/hooks/useOrders.ts
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/CourseProductItemFooter/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.tsx

🐛(fix) SaleTunnel several cache issues
We encountered several issues in specific use cases with the SaleTunnel:
- Open and close the payment interface, when trying to open again the
frontend tries to create a new order, but there is already an existing
order: we should simply re-submit it. 
Fixed by: invalidate cache after aborting.
- Open and close payment interface and SaleTunnel, the PurchaseButton
is not displayed: it should because the order is pending.
Fixed by: invalidate cache after aborting.
- If we open a new tab and there is already an existing pending order,
the last step of the SaleTunnel (resume) crashes because the order
variable it uses is not defined.
Fixed by: Bring up useProductOrder to SaleTunnel in order to make the
existing order available accross the context.

SaleTunnel various cache issues

---

src/frontend/js/components/RegisteredAddress/index.tsx
src/frontend/js/components/SaleTunnel/components/SaleTunnelStepPayment/index.spec.tsx
src/frontend/js/components/SaleTunnel/components/SaleTunnelStepPayment/index.tsx

In the sale tunnel, currently the select is clearable but it does not unselect the address so the UX is weird. In order to improve that, we disable the clear feature of the select.
https://github.com/openfun/richie/assets/9265241/5306b81c-ccce-4929-abe9-8cbfa9e6c59d

🩹(frontend) prevent to clear address select field

---

CHANGELOG.md
src/frontend/js/components/TeacherDashboardCourseList/index.spec.tsx
src/frontend/js/components/TeacherDashboardCourseList/index.tsx
src/frontend/js/hooks/useCourseProductUnion/index.ts
src/frontend/js/pages/TeacherDashboardCoursesLoader/index.spec.tsx
src/frontend/js/types/Joanie.ts

⚠️ Awaiting `product_type` filter to be added on Joanie API side
We do not want to show certificate products inside the teacher dashboard, only credentials ones and plain courses.
Fixes #2253

🐛(frontend) Certicate products should not be listed

---

CHANGELOG.md
src/frontend/js/components/PaymentButton/index.spec.tsx
src/frontend/js/components/PaymentButton/index.tsx
src/frontend/js/types/Joanie.ts

Previously, only product having a contract definition link required to accept terms before pay. Since terms and conditions are available from a dedicated page
on our catalog, it seems relevant to require this consent on any kind of
product.
Related work : https://github.com/openfun/joanie/pull/617

✨(frontend) require terms consent on all purchase

---

CHANGELOG.md
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/_styles.scss
src/frontend/js/widgets/Dashboard/components/DashboardItem/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/index.stories.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/index.tsx

We need a generic "more" button to DashboardItem in order to display various advanced options.
We want to add a "Go to syllabus" button on orders in order to allow the users to go back to the course's main page directly from their dashboard.

✨(frontend) add more button to DashboardItem and Orders

---

src/frontend/jest/setup.ts
src/frontend/js/utils/test/render.tsx
src/frontend/js/utils/test/wrappers/IntlWrapper.tsx
src/frontend/js/utils/test/wrappers/JoanieAppWrapper.tsx
src/frontend/js/utils/test/wrappers/PresentationalAppWrapper.tsx
src/frontend/js/utils/test/wrappers/ReactQueryWrapper.tsx
src/frontend/js/utils/test/wrappers/RouterWrapper.tsx
src/frontend/js/utils/test/wrappers/types.ts
src/frontend/js/widgets/Dashboard/components/NavigateWithParams/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/TeacherDashboardProfileSidebar/components/OrganizationLinks/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/TeacherDashboardProfileSidebar/index.spec.tsx

We repeate application wrappers code in every single test. It's time to normalize theses usages.
A live review return about adding the modal div creation into jest/setup.ts have been made in it's own PR:
🧑‍💻[(frontend) jest/setup: create modal div](https://github.com/openfun/richie/pull/2296)

🧑‍💻(frontend) add test wrappers

---

src/frontend/js/settings/index.ts

> settings.dev should not be load outside of 'development environment.
Another mistake from previous settings merge

🐛(frontend) fix settings

---

CHANGELOG.md
UPGRADE.md
src/frontend/js/components/Address/index.tsx
src/frontend/js/components/SaleTunnel/components/SaleTunnelStepPayment/index.tsx
src/frontend/js/settings.dev.ts
src/frontend/js/types/Joanie.ts
src/frontend/js/utils/test/expectBanner.ts
src/frontend/js/utils/test/factories/joanie.ts
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/_styles.scss
src/frontend/js/widgets/Dashboard/components/DashboardOrderLoader/_styles.scss
src/frontend/js/widgets/Dashboard/components/DashboardOrderLoader/index.tsx
src/frontend/scss/colors/_theme.scss

We want to provide more infos about the organization as well as revamping a bit the UI to avoid the "blocky" effect on this page.

✨(frontend) add Organization details in Order details view + some ui revamp

---

src/frontend/js/pages/DashboardCreditCardsManagement/index.spec.tsx

The past date generated was sometimes not within the previous month, which was making the test to fail.

🧪(frontend) fix credit card flacky test

---

src/frontend/js/hooks/useDefaultOrganizationId/index.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/TeacherDashboardContracts/index.spec.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/TeacherDashboardContracts/index.tsx
src/frontend/js/pages/TeacherDashboardContractsLayout/components/ContractFiltersBar/index.tsx
src/frontend/js/widgets/Dashboard/components/TeacherDashboardCourseSidebar/index.spec.tsx

If a course_product_relation_id is found in the route,
organization filter's options in contract listing page should only
contain organization that sell the current training.

✨(frontend) improve contrat's organization filter

---

src/frontend/js/components/PaymentButton/index.spec.tsx
src/frontend/js/components/SaleTunnel/index.tsx
src/frontend/js/hooks/useOrders.ts

Currently, when we submit an order, related queries are not invalidated so
the query client is not update and could not know the order. But in the last
step of the SaleTunnel we need to get the order id but sometimes order
is not defined so an error is raised...

🚑 (frontend) invalidate order queries on submit call

---

.circleci/config.yml

Docker versions have been removed from circle-ci. We can use the default tags to replace them.
Furthermore, the cimg/base image has a current tag we can use to avoid to have to
update them when circle will decide to remove old tags.

💚(circle) update removed docker versions

---

src/frontend/js/hooks/useUnionResource/index.spec.tsx
src/frontend/js/hooks/useUnionResource/index.ts
src/frontend/js/pages/DashboardCourses/index.spec.tsx
src/frontend/js/utils/test/wrappers/BaseAppWrapper.tsx
src/frontend/js/utils/test/wrappers/BaseJoanieAppWrapper.tsx
src/frontend/js/utils/test/wrappers/JoanieAppWrapper.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrderContract.useUnionResource.cache.spec.tsx

`useUnionResource` should fetch new data when queries's filters change.

🐛(frontend) useUnionResource refetch on filter change

---

CHANGELOG.md
src/frontend/js/pages/TeacherDashboardCourseLearnersLayout/components/CourseLearnerDataGrid/index.spec.tsx
src/frontend/js/pages/TeacherDashboardCourseLearnersLayout/components/CourseLearnerDataGrid/index.tsx
src/frontend/js/utils/OrderHelper/index.ts
src/frontend/js/utils/test/factories/joanie.ts
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderStateLearnerMessage/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderStateLearnerMessage/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderStateMessage/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderStateTeacherMessage/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderStateTeacherMessage/index.tsx

Order state can be display either in the learner dashbaord or the teacher dashbaord.
For now, states message are made to be read by a learner. We introduce here a component that give dedicated message for the teacher dashboard.
Messages that's needs to be changed:
```ts
{
statusDraft:  'Draft',
statusSubmitted:  'Submitted',
statusPending:  'Pending',
statusOnGoing:  'On going',
statusCompleted:  'Completed',
statusWaitingSignature:  "Learner's signature required",
statusWaitingCounterSignature:  "Organization 'signature required",
statusCanceled:  'Canceled',
statusOther:  '{state}',
}
```

💬(frontend) add OrderStateTeacherMessage

---

src/frontend/js/api/lms/dummy.ts
src/frontend/js/api/lms/openedx-hawthorn.ts
src/frontend/js/types/api.ts
src/frontend/js/types/index.ts
src/frontend/js/utils/test/factories/richie.ts

richie's `Enrollment` was wrongly name.
As it's always undefined, we renamed it `UnknownEnrollment`, this make it usage more readable.

♻️(frontend) rename types/Enrollment

---

src/frontend/js/pages/DashboardCourses/index.spec.tsx
src/frontend/js/utils/test/expectBanner.ts

our expectBanner's helpers weren't properly async.
by returning waitFor, these functions can now be await.

✅(frontend) async expectBanner helpers

---

CHANGELOG.md
src/frontend/js/hooks/useLearnerCoursesSearch/index.tsx
src/frontend/js/hooks/useOrders.ts
src/frontend/js/pages/DashboardCourses/_styles.scss
src/frontend/js/pages/DashboardCourses/index.spec.tsx
src/frontend/js/pages/DashboardCourses/index.tsx
src/frontend/js/pages/DashboardCourses/useOrdersEnrollments.tsx
src/frontend/js/pages/TeacherDashboardCoursesLoader/index.tsx
src/frontend/js/types/Joanie.ts
src/frontend/js/widgets/Dashboard/components/SearchBar/_styles.scss
src/frontend/js/widgets/Dashboard/components/SearchBar/index.tsx

Note: rebased on ✨[(frontend) teacher courses search with query](https://github.com/openfun/richie/pull/2304)
on learner courses listing page, we can now perform textual research.
update:

✨(frontend) learner courses search with query

---

src/frontend/js/widgets/Dashboard/components/DashboardBreadcrumbs/index.tsx

the wrong button design were used when switching from richie buttons to cunningham buttons
BEFORE:
AFTER:

💄(frontend) update breadcumb button link style

---

src/frontend/js/hooks/useUnionResource/index.spec.tsx
src/frontend/js/hooks/useUnionResource/index.ts
src/frontend/js/hooks/useUnionResource/utils/fetchEntity.ts
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrderContract.useUnionResource.cache.spec.tsx

Because our Eof wasn't reset correctly, useUnionResource would never fetch the seconds pages and always return loadMore flag as true.
resolve #2317

🐛(frontend) fix useUnionResource loadMore

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templates/courses/cms/fragment_category_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_organization_glimpse.html
src/richie/apps/courses/templates/courses/cms/fragment_person_glimpse.html
src/richie/apps/courses/templates/courses/plugins/licence_plugin.html
src/richie/plugins/nesteditem/templates/richie/nesteditem/nesteditem.html
tests/apps/courses/test_cms_plugins_organization.py
tests/apps/courses/test_cms_plugins_person.py
tests/apps/courses/test_licence_plugin.py
tests/apps/courses/test_templates_course_detail_rdfa.py
tests/apps/courses/test_templates_course_detail_rendering.py
tests/apps/courses/test_templates_person_detail.py

The course detail page RDFa markup can be completed to fully describe the syllabus content.
The vocab used is (https://schema.org/Course).
_Note : I update existing markup logic to reverse contributor and author resources. Indeed, I decide to declare as authors the organization declared on the page and as contributor, person declared on the page. IMO, it's fit better our course architecture and it complies with the RDFa vocab used._

🔍️(backend) complete course detail RDFa markups

---

.circleci/config.yml
CHANGELOG.md
Dockerfile
Makefile
bin/_config.sh
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/Makefile
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/README.md
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/bin/manage
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/bin/pytest
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/bin/state
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/bin/terraform
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/docker-compose.yml
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/docker/files/usr/local/bin/entrypoint
docker-compose.yml
docker/files/usr/local/bin/entrypoint
docs/contributing.md
docs/docker-development.md
docs/installation.md
docs/lms-connection.md
docs/tls-connection.md

docker-compose command doesn't work anymore.
we need to switch to docker compose
```sh
git grep -rl docker-compose . | xargs sed -i 's/docker-compose/docker compose/g'
git grep -rl "docker compose file" . | xargs sed -i 's/docker compose file/docker-compose file/g'
git grep -rl "../docker compose.yml" . | xargs sed -i 's/docker compose.yml/docker-compose.yml/g'
```
migration: 
```sh
$ make down
$ docker-compose down
$ make boostrap
$ make stop && make run # postgresql seems to take time to initialize and need a reboot
$ make migrate
$ make demo-site
```

🔨(backend) migration docker compose

---

src/frontend/js/components/PurchaseButton/index.spec.tsx

An await before an asynchrone assertion was missing. After adding this missing `await` it appears the assertion was failing.

✅ (frontend) fix false positive test

---

src/frontend/js/components/PurchaseButton/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/CourseProductItemFooter/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/_styles.scss

Currently, the order group message in CourseProductItem has no color set. That mean we are not able to customize it from our factory that is weird. We decide to use the base color of the CourseProductItem. Furthermore, the spacing around the message is pretty weird so we propose an improvement of margin.
|<img width="350" alt="image" src="https://github.com/openfun/richie/assets/9265241/366c31b8-1233-4f69-9c49-06af62d02560">|<img width="350" alt="image" src="https://github.com/openfun/richie/assets/9265241/b00027c1-e5b0-49e5-83ce-79d3679d72ab">|

💄(frontend) improve order group message color and layout

---

CHANGELOG.md
src/frontend/js/hooks/useCourseOrders/index.ts
src/frontend/js/pages/TeacherDashboardCourseLearnersLayout/hooks/useCourseLearnersFilters/index.spec.tsx
src/frontend/js/pages/TeacherDashboardCourseLearnersLayout/hooks/useCourseLearnersFilters/index.ts
src/frontend/js/pages/TeacherDashboardCourseLearnersLayout/index.spec.tsx

Users mustn't see learner for organization they don't have access to. This will be handle by joanie's backend but for now, we need to add a filter on all available organization id for the logged user
FIXME:
Joanie don't have needed filter on organization_ids ([see filters on joanie](https://github.com/openfun/joanie/blob/main/src/backend/joanie/core/filters/client.py#L197-L229))

🐛(frontend) filter learner list by organization

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/course_detail.html

During the last update of the course detail template a typo has been added and it causes to display twice a the `course_format` placeholder ...

🚑(template) fix duplicated placeholder in course detail template

---

CHANGELOG.md
src/frontend/js/components/DownloadContractButton/index.spec.tsx
src/frontend/js/utils/download.ts

On the learner dashboard contract page, we had a alert "an error append" after a successfull download.
resolve #2369

🐛(frontend) fix alert error on success download

---

CHANGELOG.md
src/frontend/js/hooks/useCourseRunOrder/index.spec.tsx
src/frontend/js/hooks/useCourseRunOrder/index.tsx
src/frontend/js/types/Joanie.ts
src/frontend/js/utils/CertificateHelper/index.spec.ts
src/frontend/js/utils/test/factories/joanie.ts
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.stories.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunItemWithEnrollment/index.product.spec.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunItemWithEnrollment/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/hooks/useCourseEnrollment/index.spec.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/hooks/useCourseEnrollment/index.ts

"Go to course" link displayed under enrollment when a user have purchased it were targeting the resource link that is an api endpoint. Here we replace the target by the learner dashboard order details page.

🐛(frontend) fix "Go to course" link in syllabus

---

CHANGELOG.md
src/frontend/js/components/ProtectedRoute/index.spec.tsx
src/frontend/js/components/ProtectedRoute/index.tsx
src/frontend/js/hooks/useJoanieUserAbilities/index.spec.tsx
src/frontend/js/utils/test/createTestQueryClient.ts
src/frontend/js/widgets/Dashboard/utils/dashboardRoutes.tsx
src/frontend/js/widgets/UserLogin/index.spec.tsx

Teacher dashboard route should redirect to learner dashbaord route when
the user isn't authorized.

🐛(frontend) redirect on unauthorized pages

---

CHANGELOG.md
src/frontend/js/pages/DashboardPageNotFound/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardLayout/index.tsx
src/frontend/js/widgets/Dashboard/index.spec.tsx
src/frontend/js/widgets/Dashboard/utils/dashboardRoutes.tsx

We're currently using react router default 404 page. Let's design our own.

✨(frontend) add page 404 not found

---

.circleci/config.yml
CHANGELOG.md
Makefile
UPGRADE.md
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/.circleci/src/jobs/@backend.yml
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/docker-compose.yml
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/backend/{{cookiecutter.site}}/settings.py
docker-compose.yml
pyproject.toml
sandbox/settings.py
src/richie/apps/core/templates/richie/pagination_inner.html
src/richie/apps/courses/factories.py
src/richie/apps/courses/models/course.py
tests/apps/courses/test_admin_course_run.py
tests/apps/courses/test_admin_form_course_run.py
tests/apps/courses/test_api_course_run_sync.py
tests/apps/courses/test_api_course_run_sync_edx.py
tests/apps/courses/test_api_course_run_sync_joanie.py
tests/apps/courses/test_models_course_run.py
tests/apps/courses/test_templates_course_detail_rendering.py
tests/apps/search/test_index_manager.py
tests/apps/search/test_indexers_courses.py
tests/apps/search/test_signals.py
tests/apps/search/test_viewsets_courses.py

**From Django version 3.2.25 to 4.0 :**
The project was using **Django 3.2.25**, it now uses **Django 4.0**, this involved : 
- upgrading postgres image to version 12 (drop support for postgres < 12)
- shift from `pytz` library to `datetime.timezone` instead.
- updated the template tags `{% ifequal %}` in favor of `{% if %}`.
- `USE_L1ON` is deprecated in settings if value is `True`
**From Django 4.0 to 4.1 :**
- Update project.toml file to pin version to 4.1 of Django.
- Adjust admin view tests 
**From Django 4.1 to 4.2:**
- Update project.toml file to pin version Django <5
- Change staticfile settings constant in configuration file.
- Dropped support for mysql < 8
- Dropped circleci test-back-msql-5
- resources : 
1. https://docs.djangoproject.com/en/5.0/releases/4.0/
2. …

⬆️(backend) upgrade to Django 4.x (4.0, 4.1, <5)

---

cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/backend/{{cookiecutter.site}}/settings.py
sandbox/settings.py

In order to use django 4.2 we have to fully define the settings
STORAGES. We can't simply override the default or the static key. By
fully defining it, the deprecated settings DEFAULT_FILE_STORAGE and
STATICFILES_STORAGE are defined by django once setup by using the one
defined in STORAGES. And the django filer correctly use them.

🐛(back) fully define STORAGES settings

---

.circleci/config.yml
CHANGELOG.md
Dockerfile
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/.circleci/src/jobs/@backend.yml
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/.circleci/src/jobs/@project.yml
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/Dockerfile
pyproject.toml
tests/apps/search/test_indexers_courses.py

The application was running in python 3.10, it was about time to upgrade it into python 3.11. 
In this upgrade, we have upgraded  the cookiecutter folder with the version of python to 3.11.
Upgrading the application to python 3.11
Make bootstrap works. When using the slim version of `python:3.11-slim-bookworm`, the command who failed saying that there is an issue with the package :  `setuptools-scm>=8.0`. I've tried to take the heavier version, and make bootstrap works like a charm.
Must wait for this [PR](https://github.com/openfun/richie/pull/2399) to be merged before merging this one.
Version of Docker image for python 3.11 : 
- **python:3.11-bookworm** :  `make bootstrap`  works (will use this one because 3.11.9 has the same hash with 3.11)
- **python:3.11.9-bookworm** :  `make …

⬆️(backend) upgrade to python 3.11

---

CHANGELOG.md
src/frontend/cunningham.cjs
src/frontend/js/components/Tabs/_styles.scss
src/frontend/js/components/Tabs/index.stories.tsx
src/frontend/js/components/Tabs/index.tsx
src/frontend/js/hooks/useCertificates/index.tsx
src/frontend/js/pages/DashboardCertificates/_styles.scss
src/frontend/js/pages/DashboardCertificates/components/CertificateList/index.tsx
src/frontend/js/pages/DashboardCertificates/index.spec.tsx
src/frontend/js/pages/DashboardCertificates/index.tsx
src/frontend/js/types/Joanie.ts
src/frontend/js/utils/cunningham-tokens.ts
src/frontend/js/widgets/Dashboard/components/DashboardSidebar/components/MenuNavLink/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardSidebar/index.tsx
src/frontend/js/widgets/Dashboard/components/LearnerDashboardSidebar/index.tsx
src/frontend/js/widgets/Dashboard/utils/learnerRoutes.tsx
src/frontend/js/widgets/Dashboard/utils/learnerRoutesPaths.tsx
src/frontend/scss/components/_index.scss
src/frontend/scss/vendors/cunningham-tokens.scss

joanie's certificate endpoint now return only order's certificate by
default.
to retrive enrollments certificate we need a second request with the
right filter.
Here we add tab in learner dashboard certificate page to render both
list: order and enrollments certificates
[Capture vidéo du 25-04-2024 16:39:29.webm](https://github.com/openfun/richie/assets/139848/de8bb7d2-a448-465e-a70c-5886ff0b000b)

✨(frontend) split dashboard certifiate page

---

CHANGELOG.md
src/frontend/js/pages/DashboardAddressesManagement/DashboardCreateAddress.spec.tsx
src/frontend/js/pages/DashboardAddressesManagement/DashboardEditAddress.spec.tsx
src/frontend/js/pages/DashboardAddressesManagement/index.spec.tsx
src/frontend/js/pages/DashboardCreditCardsManagement/DashboardEditCreditCard.spec.tsx
src/frontend/js/pages/DashboardCreditCardsManagement/index.spec.tsx
src/frontend/js/pages/DashboardOpenEdxProfile/index.spec.tsx
src/frontend/js/pages/DashboardOpenEdxProfile/index.tsx
src/frontend/js/widgets/Dashboard/index.spec.tsx

On click on modify profile, we open a new window in OpenEdx profile page.
When modification are done, we would like to refresh informations display on this page.
This onWindowFocus event will be trigger the first time the user came back from OpenEdx profile page to refresh the informations. /!\ It's not perfect as it'll not work it he go and back from one tab to the other.

✨(frontend) refetch user profile after edition

---

CHANGELOG.md
src/frontend/js/hooks/useUnionResource/index.spec.tsx
src/frontend/js/hooks/useUnionResource/index.ts
src/frontend/js/hooks/useUnionResource/utils/fetchEntity.ts

eof must be reset on each reset (aka filters changes or query invalidation).
If it's not, we can arrive to a point where queries are set to eof === 0 (aka maximum page).
Also, on useUnionResource's fetchEntity function, we can have a case where we're retrieving data from react query cache, juste after a reset().
In that case, we must set eof with the right value, otherwise useUnionResource can try to fetch a page that does't exists and it will blow a error.

🐛(frontend) useUnionResource refetch

---

CHANGELOG.md
src/frontend/js/widgets/Dashboard/components/DashboardItem/_styles.scss

Within DashboardItem component, if the training title is too long, it is not truncated so the component overflows. The best option seems to use a line clamp to allow the title to go on two lines but truncate it if it exceeds this limit.
|<img width="800" alt="image" src="https://github.com/openfun/richie/assets/9265241/43a937af-d38c-4fe3-afb5-540e5d4b977f">|<img width="800" alt="image" src="https://github.com/openfun/richie/assets/9265241/62e74d47-9e29-4d44-96af-f21d14fd9428">|
_P.S: Even if the `-webkit` prefix let's believe that related CSS property are only supported by webkit browsers, line clamp is currently working with this prefix on Firefox, Safari, Chromium._
https://caniuse.com/css-line-clamp

💄(frontend) fix layout issue on DashboardItem

---

CHANGELOG.md
src/frontend/js/pages/DashboardCreditCardsManagement/CreditCardBrandLogo.spec.tsx
src/frontend/js/pages/DashboardCreditCardsManagement/CreditCardBrandLogo.tsx
src/frontend/js/types/Joanie.ts

Currently, if the credit card brand does not exist in CreditCardBrand enum a broken image is displayed. As a workaround, we decide to use the CB logo as a fallback when the brand is unknown.
|<img width="600" alt="image" src="https://github.com/openfun/richie/assets/9265241/11b5c736-6efd-47c5-9441-5537b03bdc9f">|<img width="600" alt="image" src="https://github.com/openfun/richie/assets/9265241/9b2f7746-f585-4545-84bb-08f34a033d88">|

🐛(frontend) use CB logo as fallback if credit card is unknown

---

CHANGELOG.md
src/frontend/js/components/PaymentButton/_styles.scss
src/frontend/js/components/PaymentInterfaces/LyraPopIn.tsx
src/frontend/js/components/PaymentInterfaces/types.ts
src/frontend/js/components/SaleTunnel/GenericPaymentButton/index.tsx
src/frontend/js/components/SaleTunnel/index.spec.tsx

Unlike Payplug, with Lyra, until the user has submit its payment, nothing will
happend on the backend side to notify that a payment has expired or has failed.
So we have to manage all those aspects on the frontend side.

🐛(frontend) reset payment state on payment failure

---

CHANGELOG.md
src/frontend/js/components/EnrollmentDate/index.spec.tsx
src/frontend/js/components/EnrollmentDate/index.tsx
src/frontend/js/components/SaleTunnel/ProductPath/CourseRunsList.tsx
src/frontend/js/hooks/useDateFormat/index.spec.tsx
src/frontend/js/hooks/useDateFormat/index.tsx
src/frontend/js/pages/TeacherDashboardCourseLoader/CourseRunList/utils.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/CourseEnrolling/hooks/useCourseRunPeriodMessage.ts
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/components/CourseProductCourseRuns/EnrollableCourseRunList.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunItem/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/SyllabusCourseRun/index.tsx

When a course run resource link does not match configured LMS Backend, we simply render a link to go follow the resource link. This link is currently a simple anchor tag but it's weird as it does not match the look'n feel of other course run blocks. So we decide to use a Cunningham Button component instead.
|<img width="400" alt="image" src="https://github.com/openfun/richie/assets/9265241/83f9fece-0a90-4570-a1ec-9a3ee9a56282">|<img width="400" alt="image" src="https://github.com/openfun/richie/assets/9265241/c992d0ea-16c9-4b6e-b660-d68cfc3f93ec">|
|<img width="450" alt="Capture d’écran 2024-05-30 à 16 35 10" src="https://github.com/openfun/richie/assets/9265241/a9979cb9-05f2-4d3d-bccd-4b7f38c1a18b">|<img …

💄(frontend) display course run link as button

---

CHANGELOG.md
src/richie/apps/core/templates/richie/base.html
src/richie/apps/search/templates/search/search.html
tests/apps/core/test_templates_cdn.py

If Richie site is configured to use a CDN_DOMAIN then the React JS Bundle should be downloaded from CDN instead of Richie site domain.
resolves #2423

⚡️(cdn) load react JS bundle from CDN

---

CHANGELOG.md
src/richie/apps/courses/models/category.py
tests/apps/courses/test_models_category.py

Currently, calling `get_children_categories` for a published category return all category children even draft ones. In order to prevent that, if the category is not in draft, we explicitly exclude unpublished categories.

🐛(backend) fix Category.get_children_categories in public mode

---

CHANGELOG.md
src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.tsx

Currently, if the learner has a submitted or pending order, the label displayed is the one as it has a validated order. Instead for submitted order, we want to prevent that the user tries to purchase again the product and with pending order
the learner should be able to retry to purchase the certificate.

🐛(frontend) fix ProductCertificateFooter state issue

---

CHANGELOG.md
src/frontend/js/api/joanie.ts
src/frontend/js/components/PaymentScheduleGrid/_styles.scss
src/frontend/js/components/PaymentScheduleGrid/index.tsx
src/frontend/js/components/PurchaseButton/index.spec.tsx
src/frontend/js/components/SaleTunnel/GenericPaymentButton/index.tsx
src/frontend/js/components/SaleTunnel/GenericSaleTunnel.tsx
src/frontend/js/components/SaleTunnel/SaleTunnelInformation/index.tsx
src/frontend/js/components/SaleTunnel/Sponsors/SaleTunnelSponsors.scss
src/frontend/js/components/SaleTunnel/Sponsors/SaleTunnelSponsors.tsx
src/frontend/js/components/SaleTunnel/_styles.scss
src/frontend/js/components/SaleTunnel/index.credential.spec.tsx
src/frontend/js/components/SaleTunnel/index.full-process.spec.tsx
src/frontend/js/components/SaleTunnel/index.spec.tsx
src/frontend/js/hooks/useCourseProducts.ts
src/frontend/js/hooks/usePaymentSchedule.tsx
src/frontend/js/hooks/useResources/useResourcesRoot.ts
src/frontend/js/index.tsx
src/frontend/js/types/Joanie.ts
src/frontend/js/utils/OrderHelper/index.ts
src/frontend/js/utils/test/factories/joanie.ts
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderPaymentDetailsModal/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderPaymentRetryModal/index.tsx
src/frontend/package.json
src/frontend/yarn.lock

In further development, we will stop to sell training with one shot payment. Instead we will schedule payments. From frontend, that means, before the user purchase a training, it should be able to know what is the planned schedule. A first step is to retrieve the estimated payment schedule and display it in the sale tunnel.

✨(frontend) retrieve estimated payment schedule in sale tunnel

---

CHANGELOG.md
src/richie/apps/courses/models/course.py
src/richie/apps/courses/templates/courses/cms/course_detail.html
tests/apps/courses/test_models_course.py
tests/apps/courses/test_templates_course_detail_rdfa.py

Google Search Console requires more information for the RDFa information.
Fixes 2 of 3 problems identified by #2444:
----
To validate copy paste a course page html code to the Google Search Console validator:
https://search.google.com/test/rich-results/result

🐛(rdfa) fix errors on Google Search Console

---

CHANGELOG.md
src/frontend/js/components/PaymentInterfaces/LyraPopIn.tsx
src/frontend/js/components/PaymentInterfaces/types.ts
src/frontend/js/components/SaleTunnel/GenericPaymentButton/index.tsx
src/frontend/js/components/SaleTunnel/hooks/useTerms.tsx

Currently, when an error occurred during a payment using lyra pop-in, a generic error message is displayed. This is weird as the message is not explicit and user does not understand if the problem comes from the application from its bank.

🥅(frontend) improve lyra error catching

---

Makefile
bin/_config.sh
docker-compose-mysql.yml
docker-compose-postgresql.yml
docker-compose-sqlite.yml
docker-compose.yml
env.d/development/sqlite

Fix error `dockerflow.health.E001` with the message of `Could not connect to database`.
This only occurs from a fresh installation or on the first boot of the database.
Probably this only occurs when the dev machine has a slower IO.
Split docker compose file, per supported database
and add a dependency of the app to db, if it's healthy, directly on docker compose level.
fixes #2455

🔨(docker) fix first bootstrap can't connect to DB

---

CHANGELOG.md
src/frontend/js/types/commonDataProps.ts
src/frontend/js/utils/test/factories/richie.ts
src/richie/apps/core/context_processors.py

The csrftoken present in frontend context processor is not used anymore by the front application. Still using it can lead to increase the django cms cache because lot of csrftoken can be issued and lead to increase significantly the cache.

🔥(core) remove csrftoken in frontend context processor

---

CHANGELOG.md
src/frontend/js/components/PurchaseButton/index.spec.tsx
src/frontend/js/components/PurchaseButton/index.tsx
src/frontend/js/components/SaleTunnel/index.credential.spec.tsx
src/frontend/js/components/SaleTunnel/index.full-process.spec.tsx
src/frontend/js/components/SaleTunnel/index.spec.tsx
src/frontend/js/components/SaleTunnel/index.stories.tsx
src/frontend/js/components/SaleTunnel/index.tsx
src/frontend/js/types/index.ts
src/frontend/js/utils/CourseRunHelper/index.spec.ts
src/frontend/js/utils/CourseRunHelper/index.ts
src/frontend/js/utils/test/factories/richie.ts
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/CourseProductItemFooter/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.spec.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.stories.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseWishButton/index.login.spec.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseWishButton/index.logout.spec.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseWishButton/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/SyllabusAsideList/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/SyllabusCourseRunCompacted/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/index.spec.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/index.tsx
src/richie/apps/courses/templatetags/extra_tags.py
tests/apps/courses/test_templatetags_extra_tags_course_runs_list_widget_props.py

1. If all runs of an opened course have the same languages, we hide the languages on the course run card, because those languages are shown after the course description.
2. On self-paced courses with single opened run, display a simplified version of the syllabus.
fix #1969
Change the message of the enrollment period for a course with single opened run when it is self-paced, and
hide the languages of a course when every run of that course has the same languages as all the others.
This PR shows a compacted version of the information.
Before:
After:
As all runs for the course as the same languages, showing the same exact information multiple times is unnecessary, so this PR removes that languages on each run syllabus.
This behavior is the same for both self-paced and instructor-paced …

✨(frontend) compact syllabus for self-paced

---

bin/compose

We recently split our docker-compose configuration in several files to handle properly the use of several database technology in our repository. There is one drawback to this; we cannot use simply docker compose command, we have to target right docker compose files to use according to the active database we want to use.

🔧(docker) add compose command

---

cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/backend/base/storage.py

The custom storage class currently ignores js files from its process as those files are already containing a hash during its generation. But the regex was not
improperly configured so those files were matched and their process recently
leads to issue.

🔧(cookiecutter) fix ignore static process regex

---

src/frontend/js/components/SaleTunnel/AddressSelector/index.spec.tsx
src/frontend/js/components/SaleTunnel/GenericSaleTunnel.tsx
src/frontend/js/components/SaleTunnel/index.spec.tsx
src/frontend/js/utils/OrderHelper/index.ts
src/frontend/js/utils/test/factories/joanie.ts
src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/index.tsx

Currently, when a user purchase a certificate, the enrollment was not refreshed so the purchase button is not hide.

✨(frontend) add OrderHelper.isPurchasable method

---

src/frontend/js/components/CreditCardSelector/index.tsx
src/frontend/js/components/SaleTunnel/SaleTunnelSavePaymentMethod/index.tsx
src/frontend/js/components/SaleTunnel/index.full-process.spec.tsx
src/frontend/js/settings/settings.prod.ts
src/frontend/js/settings/settings.test.ts

Currently, when the user add a new credit card, the related query is not refetched so the new credit card does not appear on the list and credit card information displayed are staled.

👔(frontend) refresh credit cards query on payment method definition

---

src/frontend/js/api/joanie.ts
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.spec.tsx

The endpoint to pay a failed installment has been renamed, so we have to update our joanie api routes to match the new endpoint.

👽(frontend) update joanie endpoint

---

CHANGELOG.md
src/frontend/js/components/ContractStatus/index.spec.tsx
src/frontend/js/components/ContractStatus/index.tsx
src/frontend/js/components/PurchaseButton/index.tsx
src/frontend/js/components/SaleTunnel/index.tsx
src/frontend/js/pages/DashboardOrderLayout/index.spec.tsx
src/frontend/js/utils/ProductHelper/index.spec.ts
src/frontend/js/utils/ProductHelper/index.ts
src/frontend/js/widgets/Dashboard/components/DashboardItem/Contract/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/CertificateItem/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/ContractItem/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemNotResumable.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrderContract.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrderContract.useUnionResource.cache.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemSavePaymentMethod.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/Installment/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderPaymentDetailsModal/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrganizationBlock/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardOrderLoader/index.tsx
src/frontend/package.json
src/frontend/yarn.lock

With the new workflow, a learner can quit the subscription process then it should be able to resume it later. Currently this is only possible on the course syllabus that is weird. In its dashboard, it is able to sign its training contract but not to define a payment method. So the UI should be updated to allow that.
https://github.com/user-attachments/assets/bb987914-159c-4e0f-bd43-5f24fe469734
Furthermore if a user has not finalized a subscription process, it should not be able to resume it if the related product is no more purchasable (no remaining seats, some target courses don't have opened course runs).

Dev - Learner Dashboard - Allow to resume subscription process

---

CHANGELOG.md
src/frontend/js/types/Joanie.ts
src/frontend/js/utils/OrderHelper/index.ts
src/frontend/js/utils/PaymentScheduleHelper/index.spec.tsx
src/frontend/js/utils/PaymentScheduleHelper/index.ts
src/frontend/js/utils/test/factories/joanie.ts
src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/DashboardItemEnrollment.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/DashboardItemEnrollment.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Enrollment/ProductCertificateFooter/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/DashboardItemOrder.spec.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/Installment/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderPaymentDetailsModal/index.tsx
src/frontend/js/widgets/Dashboard/components/DashboardItem/Order/OrderPaymentRetryModal/index.tsx

With the new workflow, the learner must be able to see installment information
for its certificate order. If one installment has failed, it should be able to
pay it manually.

✨(frontend) allow to manage installments for certificate order

---

CHANGELOG.md
src/frontend/js/types/openEdx.ts

The "other" value of the OpenEdxLevelOfEducation was wrong ("o"). It appears the right value is "other".

🏷️(frontend) fix OpenEdX level education "other" value

---

CHANGELOG.md
src/richie/apps/courses/templates/courses/cms/blogpost_detail.html

On blogpost detail page, there is currently a SEO major issue. Indeed, there are
two H1 on the same page. The first is the news label on the subheader and the
second is the blogpost title itself. The post title is the most relevant one
and the subheader "News" is not really relevant that's why we decide to fix
this issue to simply remove the subheader on the blogpost detail template.
|<img width="800" alt="image" src="https://github.com/user-attachments/assets/7890d950-4b7b-4951-a4f9-e2300cb3ec4b">|<img width="800" alt="image" src="https://github.com/user-attachments/assets/89b5e78a-95ca-4e0f-8fe4-5eb9f679fd7e">|

🔍(backend) fix duplicated h1 in blogpost detail page

---

CHANGELOG.md
src/frontend/js/hooks/useCourseRunOrder/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunItemWithEnrollment/index.product.spec.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseRunItemWithEnrollment/index.tsx

The logic to know if a user is enrolled to an ongoing product was wrong and it could lead to display that the user is enrolled when not...

🐛(frontend) fix logic to know if user has purchased an ongoing product

---

CHANGELOG.md
src/frontend/js/widgets/SyllabusCourseRunsList/components/SyllabusCourseRunCompacted/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/index.tsx

Detected the following two bugs on the course detail page:
To allows the user to enroll a course, the conditions need to validate if the course is opened, and then show it as available. The `Priority` enum value `ARCHIVED_OPEN` does not correspond to this condition.
The enroll action is being treated as link which does not seem correct in terms of accessibility and from the perspective of call to action concept.

🐛(frontend) fix enroll action validation

---

CHANGELOG.md
src/frontend/js/components/PaymentInterfaces/types.ts
src/frontend/js/components/SaleTunnel/AddressSelector/index.spec.tsx
src/frontend/js/components/SaleTunnel/GenericSaleTunnel.tsx
src/frontend/js/components/SaleTunnel/SaleTunnelInformation/index.tsx
src/frontend/js/components/SaleTunnel/SubscriptionButton/_styles.scss
src/frontend/js/components/SaleTunnel/SubscriptionButton/index.tsx
src/frontend/js/components/SaleTunnel/WithdrawRightCheckbox/index.tsx
src/frontend/js/components/SaleTunnel/index.full-process.spec.tsx
src/frontend/js/components/SaleTunnel/index.spec.tsx
src/frontend/js/types/Joanie.ts
src/frontend/js/utils/test/factories/joanie.ts

We want to prevent a user to subscribe to a training without waiving withdrawal right if the training will start before the end of the withdrawal period. So according the property `has_withdrawal_period` of a product, we ask to user to check a box to explicitly waive its withdrawal right.

✨(frontend) display checkbox to waive withdrawal right if needed

---

CHANGELOG.md
src/frontend/scss/components/templates/richie/_multiple-columns.scss

Currently only the section content included in multiple columns nicely fit into multiple column templates because they already include their own spacing. But everything else look almost sticked each other because content like plain text or image does not have any spacing.
This adds horizontal and vertical padding on all sizes columns from the `.multiple-columns` CSS component to improve layout with all plugins. The section contents still look nice, especially the section grids because they have been done to properly fit anywhere.
Only the CSS component for `.multiple-columns` has been changed and it don't need any change to work.
Topography to help to see spacing between element.

💄(frontend) add padding on columns from 'multiple-columns' component

---

CHANGELOG.md
src/frontend/js/components/AddressesManagement/AddressForm/index.spec.tsx
src/frontend/js/components/AddressesManagement/index.spec.tsx
src/frontend/js/components/ContractFrame/AbstractContractFrame.spec.tsx
src/frontend/js/components/SaleTunnel/AddressSelector/index.spec.tsx
src/frontend/js/components/SaleTunnel/index.full-process.spec.tsx
src/frontend/js/hooks/useCourseProductUnion/index.spec.tsx
src/frontend/js/pages/DashboardAddressesManagement/DashboardCreateAddress.spec.tsx
src/frontend/js/pages/DashboardCourses/index.spec.tsx
src/richie/apps/courses/settings/__init__.py
src/richie/apps/courses/templates/courses/cms/category_detail.html
src/richie/apps/courses/templates/courses/cms/course_detail.html
src/richie/apps/courses/templatetags/extra_tags.py
tests/apps/courses/test_templates_category_detail.py
tests/apps/courses/test_templatetags_extra_tags_get_categories_pages_additional_information.py

We at [NAU](https://www.nau.edu.pt/pt/) identified the need to provide more information according to the characteriscts of a course.
In quick words this PR includes:
- add `additional_information` placeholder to category detail page
- `additional_information` is a `Section` with `NestedItemPlugin` as children
- get the `additional_information` placeholder from the course detail page using the category **id** page
This PR is related to  [Contextual Course FAQ by Category #2506](https://github.com/openfun/richie/issues/2506).
Dynamically provide information according to a category business logic.
Through additional information content the organizations using the `Richie` can provide more specific information according to a category. For exemple, using the category **Available on edX.org** …

✨(frontend) add faqs to a category and get them from a course

---

CHANGELOG.md
src/frontend/js/widgets/SyllabusCourseRunsList/components/SyllabusCourseRun/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/SyllabusCourseRunCompacted/index.tsx

When using an external LMS, the CTA Enroll now on course runs isn't being translated.
Replace https://github.com/openfun/richie/pull/2246
Screenshot on French, is still showing the `Enroll now` on English.
Fixed version:
The course run needs to have something completely different URL that don't match the course regex configured.
Ex: https://lms.nau.edu.pt/course_modes/choose/course-v1:NOVA+FEEF+2023_T2/
To test locally, it requires to add to the file `src/frontend/i18n/locales/fr-FR.json`
```json
"components.SyllabusCourseRun.enrollNow": {
"description": "CTA for users to enroll on ongoing of future open course.",
"message": "S'inscrire maintenant"
},
"components.SyllabusCourseRunCompacted.enrollNow": {
"description": "CTA for users to enroll on ongoing of future open course.",
"message": …
```

🐛(frontend) fix Enroll now translation

---

CHANGELOG.md
UPGRADE.md
src/richie/apps/core/templates/richie/base.html

The current implementation of `base.html` template doesn't allow us to customize the link on the `branding_topbar`, only the logo.
We received information form our accessibility regulation national agency that our site was not compliant. One of the things they highlighted is that the homepage `h1` does not have enough context and that It would be more relevant to have it associated with the page branding (the top logo).
The suggestion is to only have a "Go back to main page" link if you're not on the main page. Also, if you're on the main page, you should see the `h1` around the image.
```html
<h1>                   
</h1>
```
If you want to, you can use a different strategy:
```html
<h1>     
<span class="offscreen">Richie website</span>
</h1>
```
The `<a>` should only be present when …

Add branding_topbar_logo

---

src/richie/apps/core/templates/menu/header_menu.html
src/richie/apps/core/templates/richie/base.html

The active menu entry selected class was not applied due to a typo
into the html template. Furthermore, when the dropdown was opened
the first item was focused. It is relevant when user is using keyboard but not
when it is using its mouse so we update the code to only focus first item when
user is using its keyboard.

🐛(frontend) fix little issues about dropdown menu

---

CHANGELOG.md
src/frontend/scss/settings/_variables.scss
src/richie/plugins/section/defaults.py

Introduce two new grid options for better layout distribution when using course cards or program cards. 
- 35x65 
- 65x35 
**Issue**
https://github.com/openfun/richie/issues/2570

✨(section) add new section grid distributions

---

src/frontend/scss/components/_header.scss
src/richie/apps/core/templates/richie/base.html

In some case, the dropdown menu does not need to be full width
but it has not enough remaining space on its right to be displayed
properly. So we manage this case and align the menu on left in those case.
https://github.com/user-attachments/assets/e6884e15-afab-4c26-8a2b-58a4564da8a8

🐛(frontend) fix edge case with topbar dropdown menu

---

CHANGELOG.md
src/richie/apps/core/templates/richie/base.html

With the proposed changes to the NAU site, there's a need to create a new, above the header, company wide bar that should contain a link to the brand site.
Add a new `above_header` block for better header customization.

Add above_header block

---

Makefile

Add settings.dev.ts to the bootstrap process and create a target to copy its content from settings.dev.dist.ts, ensuring proper setup for development environments.

🔧 (makefile) copy settings.dev.ts at bootstrap

---

src/frontend/scss/objects/_course_glimpses.scss

We recently revamp the HTML structure of the course glimpse but we forgot to remove the background color applied to the `.course-glimpse` element. This was invisible until the course glimpse was displayed on a background other than white...
|<img width="260" alt="Capture d’écran 2025-03-27 à 16 00 19" src="https://github.com/user-attachments/assets/b5cd78cb-c7d6-41ea-927e-0a72591c3c2f" />|<img width="260" alt="Capture d’écran 2025-03-27 à 16 00 00" src="https://github.com/user-attachments/assets/6eb55c5a-87cf-467e-b3aa-5d1404c2d6c9" />|

💄(frontend) remove course-glimpse background color

---

src/frontend/scss/objects/_course_glimpses.scss

Currently, if a course glimpse with a long title that goes on 3 lines the glimpse height is higher than other glimpse.
|<img width="800" alt="Capture d’écran 2025-04-02 à 08 37 40" src="https://github.com/user-attachments/assets/24b9a083-4a98-4598-860b-b8d7b96f4b63" />|<img width="800" alt="Capture d’écran 2025-04-02 à 08 37 16" src="https://github.com/user-attachments/assets/d1e6cd07-a11a-4168-8ce3-05180524bec8" />|

💄(frontend) fix variable course glimpse height

---

CHANGELOG.md
src/richie/apps/core/templates/djangocms_video/default/video_player.html
tests/apps/core/test_videoplayer.py

When showing a video player on programs with the
`RICHIE_VIDEO_PLUGIN_LAZY_LOADING` setting enabled it was raising a Javascript error.
This change makes the element swap more resilient for the both cases courses and programs page.

🐛(video_player) fix lazy load video player for programs

---

.gitlint
CHANGELOG.md

This commit re-configures the gitlint so it no longer outputs a warning.
```
WARNING: I1 - ignore-by-title: gitlint will be switching from using Python regex 'match' (match beginning) to 'search' (match anywhere) semantics. Please review your ignore-by-title.regex option accordingly. To remove this warning, set general.regex-style-search=True. More details:
https://jorisroovers.github.io/gitlint/configuration/#regex-style-search
```
To test it run the `gitlint` command.
Before:
```bash
$ gitlint
WARNING: I1 - ignore-by-title: gitlint will be switching from using Python regex 'match' (match beginning) to 'search' (match anywhere) semantics. Please review your ignore-by-title.regex option accordingly. To remove this warning, set general.regex-style-search=True. More details: …
```

👷(gitlint) fix gitlint warning

---

CHANGELOG.md
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/template/{{cookiecutter.site}}/src/backend/{{cookiecutter.site}}/settings.py
src/richie/apps/courses/models/category.py
src/richie/apps/courses/models/course.py
src/richie/apps/courses/models/organization.py
src/richie/apps/courses/models/person.py
src/richie/apps/courses/models/program.py
src/richie/apps/courses/templates/courses/cms/program_detail.html
tests/apps/courses/test_models_category.py
tests/apps/courses/test_models_organization.py
tests/apps/courses/test_models_person.py
tests/apps/courses/test_templates_program_detail.py

When a course is hidden from the search results, it should also be hidden from lists.
Fixes #2630
Add a filter `is_listed=True` to the models get_courses queries.

✨(backend) exclude non listed courses from list

---

CHANGELOG.md
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/docker-compose.yml

This PR has the only intention to complete [my previous PR](https://github.com/openfun/richie/pull/2564/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed) that was missing to provide postgres as default value for `ACTIVATED_DB` environment variable.

♻️(backend) adjusted ACTIVATED_DB variable

---

CHANGELOG.md
cookiecutter/{{cookiecutter.organization}}-richie-site-factory/docker-compose.yml

In [this](https://github.com/openfun/richie/pull/2652#event-18276910430) PR was merged a wrong information, which was attributing `postgres` as default value for `ACTIVATED_DB`, while the file is named as `postgresql`.  
- Corrected `postgresql` as default value for `ACTIVATED_DB` instead of only `postgres`.
It must to match the file name, such as `docker-compose-postgresql.yml`
and then, in the `docker-compose.yml` it includes the corresponding service.
```
include:
- docker-compose-${ACTIVATED_DB:-postgresql}.yml
```

🐛(backend) corrected ACTIVATED_DB default value

---

CHANGELOG.md
docker-compose.yml
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/_styles.scss
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/components/CourseProductCourseRuns/CourseRunList.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/components/CourseProductCourseRuns/_styles.scss

With the recent addition of discount, we need to adapt the styling on course detail pages. However, other few elements are modified to make the component looking better.
Fixes #2649
This PR changes the following elements:
-  Center the product title
- Highlight the registration deadline using bold text and color #03317f
- Display language(s) available in bold
- Make the price display larger and more prominent for all products
- If the product is already purchased, the "Purchased" label should be the same size as the price
If the product is discounted:
- The discounted price should be displayed in large red text, using the same font size as the standard price
- The original price should appear smaller and strikethrough, as currently implemented
New design :

Improve product display styling on course detail pages

---

CHANGELOG.md
src/frontend/.storybook/__mocks__/utils/context.ts
src/frontend/js/components/SaleTunnel/GenericSaleTunnel.tsx
src/frontend/js/components/SaleTunnel/SaleTunnelInformation/index.tsx
src/frontend/js/components/SaleTunnel/index.spec.tsx
src/frontend/js/components/SaleTunnel/index.stories.tsx

When we open the sales tunnel from the student's dashboard to purchase a certificate in a course that we have enrolled, when a discount is present we would not see the discounted price. Now the sales tunnel information has the data if there is a discounted price on the product certificate. Otherwise, it works has usual.
There is actually two entry points to see the salesTunnel, and we don't use the same endpoints in both.
So my certificate costs normally **600.00.**
Consider that we have applied an OfferRule that takes 10% off the price, we should have **540.00** as last price.
Shot before :
Shot after : 
Fixes #2645

🐛(frontend) discounted price in sales tunnel for certificate product

---

CHANGELOG.md
src/frontend/js/components/CourseGlimpse/CourseGlimpseFooter.tsx
src/frontend/js/components/CourseGlimpse/index.spec.tsx
src/frontend/js/components/CourseGlimpse/index.stories.tsx
src/frontend/js/components/CourseGlimpse/index.tsx
src/frontend/js/components/CourseGlimpse/utils.ts
src/frontend/js/types/Course.ts
src/frontend/js/types/Joanie.ts
src/frontend/js/types/index.ts
src/frontend/js/utils/test/factories/joanie.ts
src/frontend/js/utils/test/factories/richie.ts
src/frontend/js/widgets/SyllabusCourseRunsList/components/SyllabusCourseRun/index.stories.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/SyllabusCourseRun/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/components/SyllabusCourseRunCompacted/index.tsx
src/frontend/js/widgets/SyllabusCourseRunsList/index.spec.tsx
src/frontend/scss/objects/_course_glimpses.scss

With the addition of discount pricing, we need to add the discount informations to the CourseGlimpse. The price and certificate_price also needs to be nullable since the free courses have a null price now.
Fixes #2650 
We need to synchronize the discounted price from Joanie to Richie and display it in the following locations:
- In the course glimpse footer in the catalog (for credential-type products)
- In the course run section of course detail pages (for certificate-type products)
This is the new design implemented in this feature

Display the discounts

---

src/frontend/js/widgets/SyllabusCourseRunsList/components/CourseProductItem/_styles.scss
src/frontend/scss/objects/_course_glimpses.scss

The title of course product item was not centered on small devices.
Since it's because a breakpoint add a flex property on small devices, we now center the title with `margin: 0 auto; width: max-content;` to not create a flex issue.

Fix the center of course product item title on small devices and align prices on course glimpse

---

CHANGELOG.md
src/richie/apps/courses/api.py
tests/apps/courses/test_api_course_run_sync.py

Added cache clearing for public course pages and search cache upon publishing or modifying course runs and courses to ensure consistency.

🐛(backend) clear cache on course run and course publication

---

cookiecutter/{{cookiecutter.organization}}-richie-site-factory/docker-compose.yml

Unexisting .env file declaration causes ci job to fail.

🐛(docker) remove unused .env reference in docker-compose configuration

---

cookiecutter/{{cookiecutter.organization}}-richie-site-factory/docker-compose.yml

Include missing `.env` file reference in docker-compose to ensure proper environment variable loading.

🔧(docker) add `.env` file reference to docker-compose configuration
